-- This file is generated by ConstMaker, DON'T MODIFY.

/**
  Sample Database
  */
PRAGMA foreign_keys = ON;

PRAGMA journal_mode = WAL;

ATTACH DATABASE ':memory:' AS demo_db;

DETACH DATABASE demo_db;

BEGIN TRANSACTION;

SAVEPOINT sp1;

RELEASE sp1;

COMMIT;

BEGIN TRANSACTION;

ROLLBACK;

CREATE TABLE sd4pl(
    o2wii INTEGER PRIMARY KEY,
    q4zwa TEXT UNIQUE NOT NULL,
    hiwii TEXT CHECK(hiwii LIKE '%@%'),
    rffeing DATETIME DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE jvlcdrc(
    zmrqwnyi INTEGER PRIMARY KEY,
    o2wii INTEGER REFERENCES sd4pl(o2wii),
    ze9h9oh TEXT,
    ry1pdq TEXT,
    pq0vufg INTEGER DEFAULT 0);

CREATE INDEX xdxdu ON sd4pl(q4zwa);

CREATE INDEX oddeib46 ON jvlcdrc(pq0vufg DESC);

ANALYZE;

REINDEX xdxdu;

CREATE VIEW oiiqnv5h AS SELECT p.zmrqwnyi,u.q4zwa,p.ze9h9oh,p.pq0vufg FROM jvlcdrc p JOIN sd4pl u ON p.o2wii = u.o2wii WHERE p.pq0vufg > 100 ORDERBYp.viewsDESC;

SELECT p.zmrqwnyi,u.q4zwa,p.ze9h9oh,p.pq0vufg FROM jvlcdrc p JOIN sd4pl u ON p.o2wii = u.o2wii WHERE p.pq0vufg > 100 ORDERBYp.viewsDESC;

CREATE TRIGGER wyx4vf AFTER INSERT ON jvlcdrc FOR EACH ROW BEGIN UPDATE sd4pl SET qbdjz2hb = COALESCE(qbdjz2hb,'0') + '1' WHERE o2wii = NEW.o2wii;END;

UPDATE sd4pl SET qbdjz2hb = COALESCE(qbdjz2hb,0) + 1 WHERE o2wii = NEW.o2wii;

CREATE VIRTUAL TABLE cez0 USING fts5(ze9h9oh,ry1pdq,ry1pdq = 'jvlcdrc',m716md = 'zmrqwnyi',sngohw = 'porter unicode61');

INSERT INTO sd4pl(q4zwa,hiwii)VALUES('alice','alice@example.com'),('bob','bob@example.com');

INSERT INTO jvlcdrc(o2wii,ze9h9oh,ry1pdq)VALUES(1,'First Post','Hello world!'),(2,'SQLite Guide','Complete SQLite tutorial');

SELECT u.q4zwa,COUNT(p.zmrqwnyi) as qbdjz2hb FROM sd4pl u LEFT JOIN jvlcdrc p ON u.o2wii = p.o2wii GROUP BY u.o2wii HAVING qbdjz2hb > 0;

SELECT * FROM sd4pl WHERE q4zwa LIKE 'a%';

UPDATE sd4pl SET hiwii = 'alice.new@example.com' WHERE o2wii = 1;

DELETE FROM jvlcdrc WHERE zmrqwnyi = 2;

-- 11. Limited update/delete operations ---
UPDATE jvlcdrc SET pq0vufg = pq0vufg + 1 WHERE zmrqwnyi = 1 LIMIT1;

DELETE FROM jvlcdrc WHERE pq0vufg < 5 LIMIT10;

ALTER TABLE sd4pl ADD COLUMN 
    zwmwy0 TEXT DEFAULT '';

ALTER TABLE jvlcdrc RENAME COLUMN ry1pdq TO w3l7;

VACUUM;

PRAGMA optimize;

DROP TRIGGER wyx4vf;

DROP VIEW oiiqnv5h;

DROP INDEX xdxdu;

DROP TABLE jvlcdrc;

DROP TABLE sd4pl;
