// This file is generated by ConstMaker, DON'T MODIFY.

// Consts
pub const bio: &str = "g747b";
pub const body: &str = "rw9aorl";
pub const content: &str = "nvqzh";
pub const content_rowid: &str = "u0pi4";
pub const created_at: &str = "sgba";
pub const email: &str = "mmdwrgv";
pub const idx_post_views: &str = "v30c";
pub const idx_username: &str = "o1gk6f";
pub const popular_posts: &str = "kjpk6";
pub const post_count: &str = "sqf3fa";
pub const post_id: &str = "s4xp8";
pub const posts: &str = "y3n31";
pub const posts_search: &str = "knvbfa";
pub const title: &str = "otwnm2d";
pub const tokenize: &str = "ndvtzv";
pub const update_post_count: &str = "g1tg";
pub const user_id: &str = "ds6t3";
pub const username: &str = "k1hp5";
pub const users: &str = "sth5";
pub const views: &str = "cfb0kc4";

pub const pragma_foreign_keys_0115: &str = "PRAGMA foreign_keys = ON;";

pub const pragma_journal_mode_0116: &str = "PRAGMA journal_mode = WAL;";

pub const attach_demo_db_0117: &str = "ATTACH DATABASE ':memory:' AS demo_db;";

pub const detach_demo_db_0118: &str = "DETACH DATABASE demo_db;";

pub const begin__0119: &str = "BEGIN TRANSACTION;";

pub const savepoint__0120: &str = "SAVEPOINT sp1;";

pub const release__0121: &str = "RELEASE sp1;";

pub const commit__0122: &str = "COMMIT;";

pub const begin__0123: &str = "BEGIN TRANSACTION;";

pub const rollback__0124: &str = "ROLLBACK;";

pub const create_table_users_0125: &str = "CREATE TABLE sth5(
    ds6t3 INTEGER PRIMARY KEY,
    k1hp5 TEXT UNIQUE NOT NULL,
    mmdwrgv TEXT CHECK(mmdwrgv LIKE '%@%'),
    sgba DATETIME DEFAULT CURRENT_TIMESTAMP);";

pub const create_table_posts_0126: &str = "CREATE TABLE y3n31(
    s4xp8 INTEGER PRIMARY KEY,
    ds6t3 INTEGER REFERENCES sth5(ds6t3),
    otwnm2d TEXT,
    nvqzh TEXT,
    cfb0kc4 INTEGER DEFAULT 0);";

pub const create_index_idx_username_0127: &str = "CREATE INDEX o1gk6f ON sth5(k1hp5);";

pub const create_index_idx_post_views_0128: &str = "CREATE INDEX v30c ON y3n31(cfb0kc4 DESC);";

pub const analyze__0129: &str = "ANALYZE;";

pub const reindex_idx_username_0130: &str = "REINDEX o1gk6f;";

pub const create_view_popular_posts_0131: &str = "CREATE VIEW kjpk6 AS SELECT p.s4xp8,u.k1hp5,p.otwnm2d,p.cfb0kc4 FROM y3n31 p JOIN sth5 u ON p.ds6t3 = u.ds6t3 WHERE p.cfb0kc4 > 100 ORDERBYp.viewsDESC;";

pub const select_posts_users_0132: &str = "SELECT p.s4xp8,u.k1hp5,p.otwnm2d,p.cfb0kc4 FROM y3n31 p JOIN sth5 u ON p.ds6t3 = u.ds6t3 WHERE p.cfb0kc4 > 100 ORDERBYp.viewsDESC;";

pub const create_trigger_update_post_count_0133: &str = "CREATE TRIGGER g1tg AFTER INSERT ON y3n31 FOR EACH ROW BEGIN UPDATE sth5 SET sqf3fa = COALESCE(sqf3fa,'0') + '1' WHERE ds6t3 = NEW.ds6t3;END;";

pub const update_users_0134: &str = "UPDATE sth5 SET sqf3fa = COALESCE(sqf3fa,0) + 1 WHERE ds6t3 = NEW.ds6t3;";

pub const create_virtual_table_posts_search_0135: &str = "CREATE VIRTUAL TABLE knvbfa USING fts5(otwnm2d,nvqzh,nvqzh = 'y3n31',u0pi4 = 's4xp8',ndvtzv = 'porter unicode61');";

pub const insert_users_0136: &str = "INSERT INTO sth5(k1hp5,mmdwrgv)VALUES('alice','alice@example.com'),('bob','bob@example.com');";

pub const insert_posts_0137: &str = "INSERT INTO y3n31(ds6t3,otwnm2d,nvqzh)VALUES(1,'First Post','Hello world!'),(2,'SQLite Guide','Complete SQLite tutorial');";

pub const select_users_posts_0138: &str = "SELECT u.k1hp5,COUNT(p.s4xp8) as sqf3fa FROM sth5 u LEFT JOIN y3n31 p ON u.ds6t3 = p.ds6t3 GROUP BY u.ds6t3 HAVING sqf3fa > 0;";

pub const select_users_0139: &str = "SELECT * FROM sth5 WHERE k1hp5 LIKE 'a%';";

pub const update_users_0140: &str = "UPDATE sth5 SET mmdwrgv = 'alice.new@example.com' WHERE ds6t3 = 1;";

pub const delete_posts_0141: &str = "DELETE FROM y3n31 WHERE s4xp8 = 2;";

pub const update_limited_posts_0142: &str = "UPDATE y3n31 SET cfb0kc4 = cfb0kc4 + 1 WHERE s4xp8 = 1 LIMIT 1;";

pub const delete_limited_posts_0143: &str = "DELETE FROM y3n31 WHERE cfb0kc4 < 5 LIMIT 10;";

pub const alter_users_0144: &str = "ALTER TABLE sth5 ADD COLUMN 
    g747b TEXT DEFAULT '';";

pub const alter_posts_0145: &str = "ALTER TABLE y3n31 RENAME COLUMN nvqzh TO rw9aorl;";

pub const vacuum__0146: &str = "VACUUM;";

pub const pragma_optimize_0147: &str = "PRAGMA optimize;";

pub const drop_update_post_count_0148: &str = "DROP TRIGGER g1tg;";

pub const drop_popular_posts_0149: &str = "DROP VIEW kjpk6;";

pub const drop_idx_username_0150: &str = "DROP INDEX o1gk6f;";

pub const drop_posts_0151: &str = "DROP TABLE y3n31;";

pub const drop_users_0152: &str = "DROP TABLE sth5;";
