// This file is generated by ConstMaker, DON'T MODIFY.

#ifndef CONSTMAKER_GENERATED_TEST2_H
#define CONSTMAKER_GENERATED_TEST2_H

// Consts
const char* bio = "g747b";
const char* body = "rw9aorl";
const char* content = "nvqzh";
const char* content_rowid = "u0pi4";
const char* created_at = "sgba";
const char* email = "mmdwrgv";
const char* idx_post_views = "v30c";
const char* idx_username = "o1gk6f";
const char* popular_posts = "kjpk6";
const char* post_count = "sqf3fa";
const char* post_id = "s4xp8";
const char* posts = "y3n31";
const char* posts_search = "knvbfa";
const char* title = "otwnm2d";
const char* tokenize = "ndvtzv";
const char* update_post_count = "g1tg";
const char* user_id = "ds6t3";
const char* username = "k1hp5";
const char* users = "sth5";
const char* views = "cfb0kc4";

const char* pragma_foreign_keys_0001 = "PRAGMA foreign_keys = ON;";

const char* pragma_journal_mode_0002 = "PRAGMA journal_mode = WAL;";

const char* attach_demo_db_0003 = "ATTACH DATABASE ':memory:' AS demo_db;";

const char* detach_demo_db_0004 = "DETACH DATABASE demo_db;";

const char* begin__0005 = "BEGIN TRANSACTION;";

const char* savepoint__0006 = "SAVEPOINT sp1;";

const char* release__0007 = "RELEASE sp1;";

const char* commit__0008 = "COMMIT;";

const char* begin__0009 = "BEGIN TRANSACTION;";

const char* rollback__0010 = "ROLLBACK;";

const char* create_table_users_0011 = "CREATE TABLE sth5(
    ds6t3 INTEGER PRIMARY KEY,
    k1hp5 TEXT UNIQUE NOT NULL,
    mmdwrgv TEXT CHECK(mmdwrgv LIKE '%@%'),
    sgba DATETIME DEFAULT CURRENT_TIMESTAMP);";

const char* create_table_posts_0012 = "CREATE TABLE y3n31(
    s4xp8 INTEGER PRIMARY KEY,
    ds6t3 INTEGER REFERENCES sth5(ds6t3),
    otwnm2d TEXT,
    nvqzh TEXT,
    cfb0kc4 INTEGER DEFAULT 0);";

const char* create_index_idx_username_0013 = "CREATE INDEX o1gk6f ON sth5(k1hp5);";

const char* create_index_idx_post_views_0014 = "CREATE INDEX v30c ON y3n31(cfb0kc4 DESC);";

const char* analyze__0015 = "ANALYZE;";

const char* reindex_idx_username_0016 = "REINDEX o1gk6f;";

const char* create_view_popular_posts_0017 = "CREATE VIEW kjpk6 AS SELECT p.s4xp8,u.k1hp5,p.otwnm2d,p.cfb0kc4 FROM y3n31 p JOIN sth5 u ON p.ds6t3 = u.ds6t3 WHERE p.cfb0kc4 > 100 ORDERBYp.viewsDESC;";

const char* select_posts_users_0018 = "SELECT p.s4xp8,u.k1hp5,p.otwnm2d,p.cfb0kc4 FROM y3n31 p JOIN sth5 u ON p.ds6t3 = u.ds6t3 WHERE p.cfb0kc4 > 100 ORDERBYp.viewsDESC;";

const char* create_trigger_update_post_count_0019 = "CREATE TRIGGER g1tg AFTER INSERT ON y3n31 FOR EACH ROW BEGIN UPDATE sth5 SET sqf3fa = COALESCE(sqf3fa,'0') + '1' WHERE ds6t3 = NEW.ds6t3;END;";

const char* update_users_0020 = "UPDATE sth5 SET sqf3fa = COALESCE(sqf3fa,0) + 1 WHERE ds6t3 = NEW.ds6t3;";

const char* create_virtual_table_posts_search_0021 = "CREATE VIRTUAL TABLE knvbfa USING fts5(otwnm2d,nvqzh,nvqzh = 'y3n31',u0pi4 = 's4xp8',ndvtzv = 'porter unicode61');";

const char* insert_users_0022 = "INSERT INTO sth5(k1hp5,mmdwrgv)VALUES('alice','alice@example.com'),('bob','bob@example.com');";

const char* insert_posts_0023 = "INSERT INTO y3n31(ds6t3,otwnm2d,nvqzh)VALUES(1,'First Post','Hello world!'),(2,'SQLite Guide','Complete SQLite tutorial');";

const char* select_users_posts_0024 = "SELECT u.k1hp5,COUNT(p.s4xp8) as sqf3fa FROM sth5 u LEFT JOIN y3n31 p ON u.ds6t3 = p.ds6t3 GROUP BY u.ds6t3 HAVING sqf3fa > 0;";

const char* select_users_0025 = "SELECT * FROM sth5 WHERE k1hp5 LIKE 'a%';";

const char* update_users_0026 = "UPDATE sth5 SET mmdwrgv = 'alice.new@example.com' WHERE ds6t3 = 1;";

const char* delete_posts_0027 = "DELETE FROM y3n31 WHERE s4xp8 = 2;";

const char* update_limited_posts_0028 = "UPDATE y3n31 SET cfb0kc4 = cfb0kc4 + 1 WHERE s4xp8 = 1 LIMIT 1;";

const char* delete_limited_posts_0029 = "DELETE FROM y3n31 WHERE cfb0kc4 < 5 LIMIT 10;";

const char* alter_users_0030 = "ALTER TABLE sth5 ADD COLUMN 
    g747b TEXT DEFAULT '';";

const char* alter_posts_0031 = "ALTER TABLE y3n31 RENAME COLUMN nvqzh TO rw9aorl;";

const char* vacuum__0032 = "VACUUM;";

const char* pragma_optimize_0033 = "PRAGMA optimize;";

const char* drop_update_post_count_0034 = "DROP TRIGGER g1tg;";

const char* drop_popular_posts_0035 = "DROP VIEW kjpk6;";

const char* drop_idx_username_0036 = "DROP INDEX o1gk6f;";

const char* drop_posts_0037 = "DROP TABLE y3n31;";

const char* drop_users_0038 = "DROP TABLE sth5;";


#endif // CONSTMAKER_GENERATED_TEST2_H
