// This file is generated by ConstMaker, DON'T MODIFY.

package sqlite

const (
    // Consts
    bio string = "zheft";
    body string = "hmwlp";
    content string = "oob3324g";
    content_rowid string = "fx07rot2";
    created_at string = "nwkn5sg";
    email string = "u800s";
    idx_post_views string = "er8s";
    idx_username string = "f2skf";
    popular_posts string = "ltk7";
    post_count string = "vnml";
    post_id string = "sll5";
    posts string = "axlfobu9";
    posts_search string = "hxfhj";
    title string = "ydzgp";
    tokenize string = "antk2";
    update_post_count string = "py6v1";
    user_id string = "mfxt";
    username string = "v9wgrr";
    users string = "q7nguy48";
    views string = "qmjlk5s";
)

const (
    /**
      Sample Database
      */
    pragma_foreign_keys_0075 string = "PRAGMA foreign_keys = ON;"

    pragma_journal_mode_0076 string = "PRAGMA journal_mode = WAL;"

    attach_demo_db_0077 string = "ATTACH DATABASE ':memory:' AS demo_db;"

    detach_demo_db_0078 string = "DETACH DATABASE demo_db;"

    begin__0079 string = "BEGIN TRANSACTION;"

    savepoint__0080 string = "SAVEPOINT sp1;"

    release__0081 string = "RELEASE sp1;"

    commit__0082 string = "COMMIT;"

    begin__0083 string = "BEGIN TRANSACTION;"

    rollback__0084 string = "ROLLBACK;"

    create_table_users_0085 string = `CREATE TABLE q7nguy48(
        [id] INTEGER PRIMARY KEY AUTOINCREMENT,
        mfxt INTEGER PRIMARY KEY,
        v9wgrr TEXT UNIQUE NOT NULL,
        u800s TEXT CHECK(u800s LIKE '%@%'),
        nwkn5sg DATETIME DEFAULT CURRENT_TIMESTAMP);`

    select_users_0086 string = "SELECT * FROM q7nguy48 ORDER BY nwkn5sg DESC LIMIT 1024;"

    create_table_posts_0087 string = `CREATE TABLE axlfobu9(
        sll5 INTEGER PRIMARY KEY,
        mfxt INTEGER REFERENCES q7nguy48(mfxt),
        ydzgp TEXT,
        oob3324g TEXT,
        qmjlk5s INTEGER DEFAULT 0);`

    create_index_idx_username_0088 string = "CREATE INDEX f2skf ON q7nguy48(v9wgrr);"

    create_index_idx_post_views_0089 string = "CREATE INDEX er8s ON axlfobu9(qmjlk5s DESC);"

    analyze__0090 string = "ANALYZE;"

    reindex_idx_username_0091 string = "REINDEX f2skf;"

    create_view_popular_posts_0092 string = "CREATE VIEW ltk7 AS SELECT p.sll5,u.v9wgrr,p.ydzgp,p.qmjlk5s FROM axlfobu9 p JOIN q7nguy48 u ON p.mfxt = u.mfxt WHERE p.qmjlk5s > 100 ORDER BY p.qmjlk5s DESC;"

    select_posts_users_0093 string = "SELECT p.sll5,u.v9wgrr,p.ydzgp,p.qmjlk5s FROM axlfobu9 p JOIN q7nguy48 u ON p.mfxt = u.mfxt WHERE p.qmjlk5s > 100 ORDER BY p.qmjlk5s DESC;"

    create_trigger_update_post_count_0094 string = "CREATE TRIGGER py6v1 AFTER INSERT ON axlfobu9 FOR EACH ROW BEGIN UPDATE q7nguy48 SET vnml = COALESCE(vnml,'0') + '1' WHERE mfxt = NEW.mfxt;END;"

    update_users_0095 string = "UPDATE q7nguy48 SET vnml = COALESCE(vnml,0) + 1 WHERE mfxt = NEW.mfxt;"

    create_virtual_table_posts_search_0096 string = "CREATE VIRTUAL TABLE hxfhj USING fts5(ydzgp,oob3324g,oob3324g = 'axlfobu9',fx07rot2 = 'sll5',antk2 = 'porter unicode61');"

    insert_users_0097 string = "INSERT INTO q7nguy48(v9wgrr,u800s)VALUES('alice','alice@example.com'),('bob','bob@example.com');"

    insert_posts_0098 string = "INSERT INTO axlfobu9(mfxt,ydzgp,oob3324g)VALUES(1,'First Post','Hello world!'),(2,'SQLite Guide','Complete SQLite tutorial');"

    select_users_posts_0099 string = "SELECT u.v9wgrr,COUNT(p.sll5) as vnml FROM q7nguy48 u LEFT JOIN axlfobu9 p ON u.mfxt = p.mfxt GROUP BY u.mfxt HAVING vnml > 0;"

    select_users_0100 string = "SELECT * FROM q7nguy48 WHERE v9wgrr LIKE 'a%';"

    update_users_0101 string = "UPDATE q7nguy48 SET u800s = 'alice.new@example.com' WHERE mfxt = 1;"

    delete_posts_0102 string = "DELETE FROM axlfobu9 WHERE sll5 = 2;"

    // 11. Limited update/delete operations ---
    update_limited_posts_post_id string = "UPDATE axlfobu9 SET qmjlk5s = qmjlk5s + 1 WHERE sll5 = 1 LIMIT 1;"

    delete_limited_posts_0103 string = "DELETE FROM axlfobu9 WHERE qmjlk5s < 5 LIMIT 10;"

    alter_user_bio string = `ALTER TABLE q7nguy48 ADD COLUMN 
        zheft TEXT DEFAULT '';`

    alter_posts_0104 string = "ALTER TABLE axlfobu9 RENAME COLUMN oob3324g TO hmwlp;"

    vacuum__0105 string = "VACUUM;"

    pragma_optimize_0106 string = "PRAGMA optimize;"

    drop_update_post_count_0107 string = "DROP TRIGGER py6v1;"

    drop_popular_posts_0108 string = "DROP VIEW ltk7;"

    drop_idx_username_0109 string = "DROP INDEX f2skf;"

    drop_posts_0110 string = "DROP TABLE axlfobu9;"

    drop_users_0111 string = "DROP TABLE q7nguy48;"
)
