// This file is generated by ConstMaker, DON'T MODIFY.

// Consts
const String bio = "zheft";
const String body = "hmwlp";
const String content = "oob3324g";
const String content_rowid = "fx07rot2";
const String created_at = "nwkn5sg";
const String email = "u800s";
const String idx_post_views = "er8s";
const String idx_username = "f2skf";
const String popular_posts = "ltk7";
const String post_count = "vnml";
const String post_id = "sll5";
const String posts = "axlfobu9";
const String posts_search = "hxfhj";
const String title = "ydzgp";
const String tokenize = "antk2";
const String update_post_count = "py6v1";
const String user_id = "mfxt";
const String username = "v9wgrr";
const String users = "q7nguy48";
const String views = "qmjlk5s";

/**
  Sample Database
  */
const String pragma_foreign_keys_0038 = "PRAGMA foreign_keys = ON;";

const String pragma_journal_mode_0039 = "PRAGMA journal_mode = WAL;";

const String attach_demo_db_0040 = "ATTACH DATABASE ':memory:' AS demo_db;";

const String detach_demo_db_0041 = "DETACH DATABASE demo_db;";

const String begin__0042 = "BEGIN TRANSACTION;";

const String savepoint__0043 = "SAVEPOINT sp1;";

const String release__0044 = "RELEASE sp1;";

const String commit__0045 = "COMMIT;";

const String begin__0046 = "BEGIN TRANSACTION;";

const String rollback__0047 = "ROLLBACK;";

const String create_table_users_0048 = """CREATE TABLE q7nguy48(
    [id] INTEGER PRIMARY KEY AUTOINCREMENT,
    mfxt INTEGER PRIMARY KEY,
    v9wgrr TEXT UNIQUE NOT NULL,
    u800s TEXT CHECK(u800s LIKE '%@%'),
    nwkn5sg DATETIME DEFAULT CURRENT_TIMESTAMP);""";

const String select_users_0049 = "SELECT * FROM q7nguy48 ORDER BY nwkn5sg DESC LIMIT 1024;";

const String create_table_posts_0050 = """CREATE TABLE axlfobu9(
    sll5 INTEGER PRIMARY KEY,
    mfxt INTEGER REFERENCES q7nguy48(mfxt),
    ydzgp TEXT,
    oob3324g TEXT,
    qmjlk5s INTEGER DEFAULT 0);""";

const String create_index_idx_username_0051 = "CREATE INDEX f2skf ON q7nguy48(v9wgrr);";

const String create_index_idx_post_views_0052 = "CREATE INDEX er8s ON axlfobu9(qmjlk5s DESC);";

const String analyze__0053 = "ANALYZE;";

const String reindex_idx_username_0054 = "REINDEX f2skf;";

const String create_view_popular_posts_0055 = "CREATE VIEW ltk7 AS SELECT p.sll5,u.v9wgrr,p.ydzgp,p.qmjlk5s FROM axlfobu9 p JOIN q7nguy48 u ON p.mfxt = u.mfxt WHERE p.qmjlk5s > 100 ORDER BY p.qmjlk5s DESC;";

const String select_posts_users_0056 = "SELECT p.sll5,u.v9wgrr,p.ydzgp,p.qmjlk5s FROM axlfobu9 p JOIN q7nguy48 u ON p.mfxt = u.mfxt WHERE p.qmjlk5s > 100 ORDER BY p.qmjlk5s DESC;";

const String create_trigger_update_post_count_0057 = "CREATE TRIGGER py6v1 AFTER INSERT ON axlfobu9 FOR EACH ROW BEGIN UPDATE q7nguy48 SET vnml = COALESCE(vnml,'0') + '1' WHERE mfxt = NEW.mfxt;END;";

const String update_users_0058 = "UPDATE q7nguy48 SET vnml = COALESCE(vnml,0) + 1 WHERE mfxt = NEW.mfxt;";

const String create_virtual_table_posts_search_0059 = "CREATE VIRTUAL TABLE hxfhj USING fts5(ydzgp,oob3324g,oob3324g = 'axlfobu9',fx07rot2 = 'sll5',antk2 = 'porter unicode61');";

const String insert_users_0060 = "INSERT INTO q7nguy48(v9wgrr,u800s)VALUES('alice','alice@example.com'),('bob','bob@example.com');";

const String insert_posts_0061 = "INSERT INTO axlfobu9(mfxt,ydzgp,oob3324g)VALUES(1,'First Post','Hello world!'),(2,'SQLite Guide','Complete SQLite tutorial');";

const String select_users_posts_0062 = "SELECT u.v9wgrr,COUNT(p.sll5) as vnml FROM q7nguy48 u LEFT JOIN axlfobu9 p ON u.mfxt = p.mfxt GROUP BY u.mfxt HAVING vnml > 0;";

const String select_users_0063 = "SELECT * FROM q7nguy48 WHERE v9wgrr LIKE 'a%';";

const String update_users_0064 = "UPDATE q7nguy48 SET u800s = 'alice.new@example.com' WHERE mfxt = 1;";

const String delete_posts_0065 = "DELETE FROM axlfobu9 WHERE sll5 = 2;";

// 11. Limited update/delete operations ---
const String update_limited_posts_post_id = "UPDATE axlfobu9 SET qmjlk5s = qmjlk5s + 1 WHERE sll5 = 1 LIMIT 1;";

const String delete_limited_posts_0066 = "DELETE FROM axlfobu9 WHERE qmjlk5s < 5 LIMIT 10;";

const String alter_user_bio = """ALTER TABLE q7nguy48 ADD COLUMN 
    zheft TEXT DEFAULT '';""";

const String alter_posts_0067 = "ALTER TABLE axlfobu9 RENAME COLUMN oob3324g TO hmwlp;";

const String vacuum__0068 = "VACUUM;";

const String pragma_optimize_0069 = "PRAGMA optimize;";

const String drop_update_post_count_0070 = "DROP TRIGGER py6v1;";

const String drop_popular_posts_0071 = "DROP VIEW ltk7;";

const String drop_idx_username_0072 = "DROP INDEX f2skf;";

const String drop_posts_0073 = "DROP TABLE axlfobu9;";

const String drop_users_0074 = "DROP TABLE q7nguy48;";
