// This file is generated by ConstMaker, DON'T MODIFY.

/**
 *this is a test
 */
const Table = "table"; // hello word
const AllowTest = "at";
const Percent = 100;

/** pi */
const Pi = 3.14159;

/**
 * colors
 */
enum Colors: int {
    case KNoneDef = 0;
    case KBlueDef = (1 << 0);
    case KGreenDef = (1 << 1);
    case KRedDef = (1 << 2);
    case KAllDef = 0x7;
}
const ColorsKNoneDefStr = "KNoneDef";
const ColorsKBlueDefStr = "KBlueDef";
const ColorsKGreenDefStr = "KGreenDef";
const ColorsKRedDefStr = "KRedDef";
const ColorsKAllDefStr = "KAllDef";

namespace Node {
    const HtmlBlockId = "Block";
    const HtmlTableId = "Table";
}

namespace Item {
    const AllowTest = "at";
    const Pi = 3.14159;
    const Table = "table";
    const Percent = 100;
    const NoneId = 0;
    const AllowTestId = (1 << 0);
    const PiId = (1 << 1);
    const TableId = (1 << 2);
    const PercentId = (1 << 3);
    const AllId = 0xf;

    enum Colors: int {
        case Blue;
        case Green; // green
        case Red;
    }
}

namespace ItemNode {
    const Border = "border";

    enum Colors: int {
        case Red;
        case Green; // green
        case Blue;
    }
    const ColorsRedStr = "Red";
    const ColorsGreenStr = "Green";
    const ColorsBlueStr = "Blue";
}

namespace ItemNodeQuick {
    const Item = "item";
}

namespace ItemNodeQuickNode {
}

namespace Css3 {
    const XWebkitAirplay = "x-webkit-airplay";
    const WebkitTextZoom = "-webkit-text-zoom";
    const WebkitBackdropFilter = "-webkit-backdrop-filter";
    const WebkitBorderHorizontalSpacing = "-webkit-border-horizontal-spacing";
    const WebkitBorderVerticalSpacing = "-webkit-border-vertical-spacing";
    const WebkitBoxAlign = "-webkit-box-align";
    const NoneId = 0;
    const XWebkitAirplayId = (1 << 0);
    const WebkitTextZoomId = (1 << 1);
    const WebkitBackdropFilterId = (1 << 2);
    const WebkitBorderHorizontalSpacingId = (1 << 3);
    const WebkitBorderVerticalSpacingId = (1 << 4);
    const WebkitBoxAlignId = (1 << 5);
    const AllId = 0x3f;
}