// This file is generated by ConstMaker, DON'T MODIFY.

public static class Test1 {
    /**
     *this is a test
     */
    public const string Table = "table"; // hello word
    public const string AllowTest = "at";
    public const sbyte Percent = -100;

    /** pi */
    public const float Pi = 3.14159f;

    /**
     * colors
     */
    public enum Colors {
        KNoneDef = 0,
        KBlueDef = (1 << 0),
        KGreenDef = (1 << 1),
        KRedDef = (1 << 2),
        KAllDef = 0x7,
    }
    public const string ColorsKNoneDefStr = "KNoneDef";
    public const string ColorsKBlueDefStr = "KBlueDef";
    public const string ColorsKGreenDefStr = "KGreenDef";
    public const string ColorsKRedDefStr = "KRedDef";
    public const string ColorsKAllDefStr = "KAllDef";
}

public static class Node {
    public const string HtmlBlockId = "Block";
    public const string HtmlTableId = "Table";
}

public static class Item {
    public const string AllowTest = "at";
    public const float Pi = 3.14159f;
    public const string Table = "table";
    public const sbyte Percent = 100;
    public const byte NoneId = 0;
    public const byte AllowTestId = (1 << 0);
    public const byte PiId = (1 << 1);
    public const byte TableId = (1 << 2);
    public const byte PercentId = (1 << 3);
    public const byte AllId = 0xf;

    public enum Colors {
        Blue,
        Green, // green
        Red,
    }
}

public static class Node {
    public const string Border = "border";

    public enum Colors {
        Red,
        Green, // green
        Blue,
    }
    public const string ColorsRedStr = "Red";
    public const string ColorsGreenStr = "Green";
    public const string ColorsBlueStr = "Blue";
}

public static class Quick {
    public const string Item = "item";
}

public static class Node {
}

public static class Css3 {
    public const string XWebkitAirplay = "x-webkit-airplay";
    public const string WebkitTextZoom = "-webkit-text-zoom";
    public const string WebkitBackdropFilter = "-webkit-backdrop-filter";
    public const string WebkitBorderHorizontalSpacing = "-webkit-border-horizontal-spacing";
    public const string WebkitBorderVerticalSpacing = "-webkit-border-vertical-spacing";
    public const string WebkitBoxAlign = "-webkit-box-align";
    public const byte NoneId = 0;
    public const byte XWebkitAirplayId = (1 << 0);
    public const byte WebkitTextZoomId = (1 << 1);
    public const byte WebkitBackdropFilterId = (1 << 2);
    public const byte WebkitBorderHorizontalSpacingId = (1 << 3);
    public const byte WebkitBorderVerticalSpacingId = (1 << 4);
    public const byte WebkitBoxAlignId = (1 << 5);
    public const byte AllId = 0x3f;
}