// This file is generated by ConstMaker, DON'T MODIFY.

/**
 *this is a test
 */
pub const Table: &str = "table"; // hello word
pub const AllowTest: &str = "at";
pub const Percent: i8 = -100;

/** pi */
pub const Pi: f32 = 3.14159;

/**
 * colors
 */
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug, Hash)]
pub enum Colors {
    KNoneDef = 0,
    KBlueDef = (1 << 0),
    KGreenDef = (1 << 1),
    KRedDef = (1 << 2),
    KAllDef = 0x7,
}
pub const ColorsKNoneDefStr: &str = "KNoneDef";
pub const ColorsKBlueDefStr: &str = "KBlueDef";
pub const ColorsKGreenDefStr: &str = "KGreenDef";
pub const ColorsKRedDefStr: &str = "KRedDef";
pub const ColorsKAllDefStr: &str = "KAllDef";

// namespace Node
pub const NodeHtmlBlockId: &str = "Block";
pub const NodeHtmlTableId: &str = "Table";

// namespace Item
pub const ItemAllowTest: &str = "at";
pub const ItemPi: f32 = 3.14159;
pub const ItemTable: &str = "table";
pub const ItemPercent: i8 = 100;
pub const ItemNoneId : u8 = 0;
pub const ItemAllowTestId : u8 = (1 << 0);
pub const ItemPiId : u8 = (1 << 1);
pub const ItemTableId : u8 = (1 << 2);
pub const ItemPercentId : u8 = (1 << 3);
pub const ItemAllId : u8 = 0xf;

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug, Hash)]
pub enum ItemColors {
    Blue,
    Green, // green
    Red,
}

// namespace ItemNode
pub const ItemNodeBorder: &str = "border";

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug, Hash)]
pub enum ItemNodeColors {
    Red,
    Green, // green
    Blue,
}
pub const ItemNodeColorsRedStr: &str = "Red";
pub const ItemNodeColorsGreenStr: &str = "Green";
pub const ItemNodeColorsBlueStr: &str = "Blue";

// namespace ItemNodeQuick
pub const ItemNodeQuickItem: &str = "item";

// namespace ItemNodeQuickNode

// namespace Css3
pub const Css3XWebkitAirplay: &str = "x-webkit-airplay";
pub const Css3WebkitTextZoom: &str = "-webkit-text-zoom";
pub const Css3WebkitBackdropFilter: &str = "-webkit-backdrop-filter";
pub const Css3WebkitBorderHorizontalSpacing: &str = "-webkit-border-horizontal-spacing";
pub const Css3WebkitBorderVerticalSpacing: &str = "-webkit-border-vertical-spacing";
pub const Css3WebkitBoxAlign: &str = "-webkit-box-align";
pub const Css3NoneId : u8 = 0;
pub const Css3XWebkitAirplayId : u8 = (1 << 0);
pub const Css3WebkitTextZoomId : u8 = (1 << 1);
pub const Css3WebkitBackdropFilterId : u8 = (1 << 2);
pub const Css3WebkitBorderHorizontalSpacingId : u8 = (1 << 3);
pub const Css3WebkitBorderVerticalSpacingId : u8 = (1 << 4);
pub const Css3WebkitBoxAlignId : u8 = (1 << 5);
pub const Css3AllId : u8 = 0x3f;