// This file is generated by ConstMaker, DON'T MODIFY.

#ifndef CONSTMAKER_GENERATED_TEST1_H
#define CONSTMAKER_GENERATED_TEST1_H

#include <stdint.h>

/**
 *this is a test
 */
const char* Table = "table"; // hello word
const char* AllowTest = "at";
const uint8_t Percent = 100;

/** pi */
const float Pi = 3.14159;

/**
 * colors
 */
enum class Colors : uint16_t {
    KNoneDef = 0,
    KBlueDef = (1 << 0),
    KGreenDef = (1 << 1),
    KRedDef = (1 << 2),
    KAllDef = 0x7,
};
const char* ColorsKNoneDefStr = "KNoneDef";
const char* ColorsKBlueDefStr = "KBlueDef";
const char* ColorsKGreenDefStr = "KGreenDef";
const char* ColorsKRedDefStr = "KRedDef";
const char* ColorsKAllDefStr = "KAllDef";

namespace Node {
    const char* HtmlBlockId = "Block";
    const char* HtmlTableId = "Table";
};

namespace Item {
    const char* AllowTest = "at";
    const float Pi = 3.14159;
    const char* Table = "table";
    const int8_t Percent = 100;
    const uint8_t NoneId = 0;
    const uint8_t AllowTestId = (1 << 0);
    const uint8_t PiId = (1 << 1);
    const uint8_t TableId = (1 << 2);
    const uint8_t PercentId = (1 << 3);
    const uint8_t AllId = 0xf;

    enum class Colors : uint8_t {
        Blue,
        Green, // green
        Red,
    };
};

namespace ItemNode {
    const char* Border = "border";

    enum class Colors : uint8_t {
        Red,
        Green, // green
        Blue,
    };
    const char* ColorsRedStr = "Red";
    const char* ColorsGreenStr = "Green";
    const char* ColorsBlueStr = "Blue";
};

namespace ItemNodeQuick {
    const char* Item = "item";
};

namespace ItemNodeQuickNode {
};

namespace Css3 {
    const char* XWebkitAirplay = "x-webkit-airplay";
    const char* WebkitTextZoom = "-webkit-text-zoom";
    const char* WebkitBackdropFilter = "-webkit-backdrop-filter";
    const char* WebkitBorderHorizontalSpacing = "-webkit-border-horizontal-spacing";
    const char* WebkitBorderVerticalSpacing = "-webkit-border-vertical-spacing";
    const char* WebkitBoxAlign = "-webkit-box-align";
    const uint8_t NoneId = 0;
    const uint8_t XWebkitAirplayId = (1 << 0);
    const uint8_t WebkitTextZoomId = (1 << 1);
    const uint8_t WebkitBackdropFilterId = (1 << 2);
    const uint8_t WebkitBorderHorizontalSpacingId = (1 << 3);
    const uint8_t WebkitBorderVerticalSpacingId = (1 << 4);
    const uint8_t WebkitBoxAlignId = (1 << 5);
    const uint8_t AllId = 0x3f;
};

#endif // CONSTMAKER_GENERATED_TEST1_H
