// This file is generated by ConstMaker, DON'T MODIFY.

/**
 *this is a test
 */
const Table = "table"; // hello word
const AllowTest = "at";
const Percent = -100;

/** pi */
const Pi = 3.14159;

/**
 * colors
 */
const Colors = {
    KNoneDef: 0,
    KBlueDef: (1 << 0),
    KGreenDef: (1 << 1),
    KRedDef: (1 << 2),
    KAllDef: 0x7,
};
const ColorsKNoneDefStr = "KNoneDef";
const ColorsKBlueDefStr = "KBlueDef";
const ColorsKGreenDefStr = "KGreenDef";
const ColorsKRedDefStr = "KRedDef";
const ColorsKAllDefStr = "KAllDef";

const Node = {
    Constants: Object.freeze({
        HtmlBlockId: "Block",
        HtmlTableId: "Table",
    })
};

const Item = {
    Constants: Object.freeze({
        AllowTest: "at",
        Pi: 3.14159,
        Table: "table",
        Percent: 100,
        NoneId: 0,
        AllowTestId: (1 << 0),
        PiId: (1 << 1),
        TableId: (1 << 2),
        PercentId: (1 << 3),
        AllId: 0xf,

        Colors: Object.freeze({
            Blue: 0,
            Green: 1, // green
            Red: 2,
        }),
    })
};

const ItemNode = {
    Constants: Object.freeze({
        Border: "border",

        Colors: Object.freeze({
            Red: 0,
            Green: 1, // green
            Blue: 2,
        }),
        ColorsRedStr: "Red",
        ColorsGreenStr: "Green",
        ColorsBlueStr: "Blue",
    })
};

const ItemNodeQuick = {
    Constants: Object.freeze({
        Item: "item",
    })
};

const ItemNodeQuickNode = {
    Constants: Object.freeze({
    })
};

const Css3 = {
    Constants: Object.freeze({
        XWebkitAirplay: "x-webkit-airplay",
        WebkitTextZoom: "-webkit-text-zoom",
        WebkitBackdropFilter: "-webkit-backdrop-filter",
        WebkitBorderHorizontalSpacing: "-webkit-border-horizontal-spacing",
        WebkitBorderVerticalSpacing: "-webkit-border-vertical-spacing",
        WebkitBoxAlign: "-webkit-box-align",
        NoneId: 0,
        XWebkitAirplayId: (1 << 0),
        WebkitTextZoomId: (1 << 1),
        WebkitBackdropFilterId: (1 << 2),
        WebkitBorderHorizontalSpacingId: (1 << 3),
        WebkitBorderVerticalSpacingId: (1 << 4),
        WebkitBoxAlignId: (1 << 5),
        AllId: 0x3f,
    })
};