// This file is generated by ConstMaker, DON'T MODIFY.

package tests;

interface test1 {
    /**
     *this is a test
     */
    public static final String Table = "table"; // hello word
    public static final String AllowTest = "at";
    public static final byte Percent = -100;

    /** pi */
    public static final float Pi = 3.14159f;

    /**
     * colors
     */
    enum Colors {
        KNoneDef(0),
        KBlueDef((1 << 0)),
        KGreenDef((1 << 1)),
        KRedDef((1 << 2)),
        KAllDef(0x7);

        public static final String KNoneDefStr = "KNoneDef";
        public static final String KBlueDefStr = "KBlueDef";
        public static final String KGreenDefStr = "KGreenDef";
        public static final String KRedDefStr = "KRedDef";
        public static final String KAllDefStr = "KAllDef";

        final int value;
        Colors(int value) { this.value = value; }
    }

    interface Node {
        public static final String HtmlBlockId = "Block";
        public static final String HtmlTableId = "Table";
    }

    interface Item {
        public static final String AllowTest = "at";
        public static final float Pi = 3.14159f;
        public static final String Table = "table";
        public static final byte Percent = 100;
        public static final byte NoneId = 0;
        public static final byte AllowTestId = (1 << 0);
        public static final byte PiId = (1 << 1);
        public static final byte TableId = (1 << 2);
        public static final byte PercentId = (1 << 3);
        public static final byte AllId = 0xf;

        enum Colors {
            Blue,
            Green, // green
            Red
        }

        interface Node {
            public static final String Border = "border";

            enum Colors {
                Red,
                Green, // green
                Blue
            }
            public static final String ColorsRedStr = "Red";
            public static final String ColorsGreenStr = "Green";
            public static final String ColorsBlueStr = "Blue";

            interface Quick {
                public static final String Item = "item";

                // namespace Node
            }
        }
    }

    interface Css3 {
        public static final String XWebkitAirplay = "x-webkit-airplay";
        public static final String WebkitTextZoom = "-webkit-text-zoom";
        public static final String WebkitBackdropFilter = "-webkit-backdrop-filter";
        public static final String WebkitBorderHorizontalSpacing = "-webkit-border-horizontal-spacing";
        public static final String WebkitBorderVerticalSpacing = "-webkit-border-vertical-spacing";
        public static final String WebkitBoxAlign = "-webkit-box-align";
        public static final byte NoneId = 0;
        public static final byte XWebkitAirplayId = (1 << 0);
        public static final byte WebkitTextZoomId = (1 << 1);
        public static final byte WebkitBackdropFilterId = (1 << 2);
        public static final byte WebkitBorderHorizontalSpacingId = (1 << 3);
        public static final byte WebkitBorderVerticalSpacingId = (1 << 4);
        public static final byte WebkitBoxAlignId = (1 << 5);
        public static final byte AllId = 0x3f;
    }
}