// This file is generated by ConstMaker, DON'T MODIFY.

/**
 *this is a test
 */
const Table = "table"; // hello word
const AllowTest = "at";
const Percent = 100;

/** pi */
const Pi = 3.14159;

/**
 * colors
 */
export enum Colors {
    KNoneDef = 0,
    KBlueDef = (1 << 0),
    KGreenDef = (1 << 1),
    KRedDef = (1 << 2),
    KAllDef = 0x7,

    KNoneDefStr = "KNoneDef",
    KBlueDefStr = "KBlueDef",
    KGreenDefStr = "KGreenDef",
    KRedDefStr = "KRedDef",
    KAllDefStr = "KAllDef",
}

export namespace Node {
    const HtmlBlockId = "Block";
    const HtmlTableId = "Table";
}

export namespace Item {
    const AllowTest = "at";
    const Pi = 3.14159;
    const Table = "table";
    const Percent = 100;
    const NoneId = 0;
    const AllowTestId = (1 << 0);
    const PiId = (1 << 1);
    const TableId = (1 << 2);
    const PercentId = (1 << 3);
    const AllId = 0xf;

    export enum Colors {
        Blue,
        Green, // green
        Red,
    }
}

export namespace ItemNode {
    const Border = "border";

    export enum Colors {
        Red,
        Green, // green
        Blue,

        RedStr = "Red",
        GreenStr = "Green",
        BlueStr = "Blue",
    }
}

export namespace ItemNodeQuick {
    const Item = "item";
}

export namespace ItemNodeQuickNode {
}

export namespace Css3 {
    const XWebkitAirplay = "x-webkit-airplay";
    const WebkitTextZoom = "-webkit-text-zoom";
    const WebkitBackdropFilter = "-webkit-backdrop-filter";
    const WebkitBorderHorizontalSpacing = "-webkit-border-horizontal-spacing";
    const WebkitBorderVerticalSpacing = "-webkit-border-vertical-spacing";
    const WebkitBoxAlign = "-webkit-box-align";
    const NoneId = 0;
    const XWebkitAirplayId = (1 << 0);
    const WebkitTextZoomId = (1 << 1);
    const WebkitBackdropFilterId = (1 << 2);
    const WebkitBorderHorizontalSpacingId = (1 << 3);
    const WebkitBorderVerticalSpacingId = (1 << 4);
    const WebkitBoxAlignId = (1 << 5);
    const AllId = 0x3f;
}