// This file is generated by ConstMaker, DON'T MODIFY.

/**
 *this is a test
 */
static let Table: String = "table" // hello word
static let AllowTest: String = "at"
static let Percent: UInt8 = 100

/** pi */
static let Pi: Float = 3.14159

/**
 * colors
 */
enum Colors: UInt16 {
    case KNoneDef = 0
    case KBlueDef = (1 << 0)
    case KGreenDef = (1 << 1)
    case KRedDef = (1 << 2)
    case KAllDef = 0x7
}
static let ColorsKNoneDefStr: String = "KNoneDef"
static let ColorsKBlueDefStr: String = "KBlueDef"
static let ColorsKGreenDefStr: String = "KGreenDef"
static let ColorsKRedDefStr: String = "KRedDef"
static let ColorsKAllDefStr: String = "KAllDef"

struct Node {
    static let HtmlBlockId: String = "Block"
    static let HtmlTableId: String = "Table"
}

struct Item {
    static let AllowTest: String = "at"
    static let Pi: Float = 3.14159
    static let Table: String = "table"
    static let Percent: Int8 = 100
    static let NoneId: UInt8 = 0
    static let AllowTestId: UInt8 = (1 << 0)
    static let PiId: UInt8 = (1 << 1)
    static let TableId: UInt8 = (1 << 2)
    static let PercentId: UInt8 = (1 << 3)
    static let AllId: UInt8 = 0xf

    enum Colors: UInt8 {
        case Blue
        case Green // green
        case Red
    }
}

struct ItemNode {
    static let Border: String = "border"

    enum Colors: UInt8 {
        case Red
        case Green // green
        case Blue
    }
    static let ColorsRedStr: String = "Red"
    static let ColorsGreenStr: String = "Green"
    static let ColorsBlueStr: String = "Blue"
}

struct ItemNodeQuick {
    static let Item: String = "item"
}

struct ItemNodeQuickNode {
}

struct Css3 {
    static let XWebkitAirplay: String = "x-webkit-airplay"
    static let WebkitTextZoom: String = "-webkit-text-zoom"
    static let WebkitBackdropFilter: String = "-webkit-backdrop-filter"
    static let WebkitBorderHorizontalSpacing: String = "-webkit-border-horizontal-spacing"
    static let WebkitBorderVerticalSpacing: String = "-webkit-border-vertical-spacing"
    static let WebkitBoxAlign: String = "-webkit-box-align"
    static let NoneId: UInt8 = 0
    static let XWebkitAirplayId: UInt8 = (1 << 0)
    static let WebkitTextZoomId: UInt8 = (1 << 1)
    static let WebkitBackdropFilterId: UInt8 = (1 << 2)
    static let WebkitBorderHorizontalSpacingId: UInt8 = (1 << 3)
    static let WebkitBorderVerticalSpacingId: UInt8 = (1 << 4)
    static let WebkitBoxAlignId: UInt8 = (1 << 5)
    static let AllId: UInt8 = 0x3f
}