// This file is generated by ConstMaker, DON'T MODIFY.

QtObject {
    id: test1

    /**
     *this is a test
     */
    property string Table: "table" // hello word
    property string AllowTest: "at"
    property int Percent: 100

    /** pi */
    property real Pi: 3.14159

    /**
     * colors
     */
    enum Colors {
        KNoneDef = 0,
        KBlueDef = (1 << 0),
        KGreenDef = (1 << 1),
        KRedDef = (1 << 2),
        KAllDef = 0x7
    }
    property string ColorsKNoneDefStr: "KNoneDef"
    property string ColorsKBlueDefStr: "KBlueDef"
    property string ColorsKGreenDefStr: "KGreenDef"
    property string ColorsKRedDefStr: "KRedDef"
    property string ColorsKAllDefStr: "KAllDef"

    QtObject {
        id: node

        property string HtmlBlockId: "Block"
        property string HtmlTableId: "Table"
    }

    QtObject {
        id: item

        property string AllowTest: "at"
        property real Pi: 3.14159
        property string Table: "table"
        property int Percent: 100
        property int NoneId: 0
        property int AllowTestId: (1 << 0)
        property int PiId: (1 << 1)
        property int TableId: (1 << 2)
        property int PercentId: (1 << 3)
        property int AllId: 0xf

        enum Colors {
            Blue,
            Green, // green
            Red
        }

        QtObject {
            id: node

            property string Border: "border"

            enum Colors {
                Red,
                Green, // green
                Blue
            }
            property string ColorsRedStr: "Red"
            property string ColorsGreenStr: "Green"
            property string ColorsBlueStr: "Blue"

            QtObject {
                id: quick

                property string Item: "item"

                QtObject {
                    id: node

                }
            }
        }
    }

    QtObject {
        id: css3

        property string XWebkitAirplay: "x-webkit-airplay"
        property string WebkitTextZoom: "-webkit-text-zoom"
        property string WebkitBackdropFilter: "-webkit-backdrop-filter"
        property string WebkitBorderHorizontalSpacing: "-webkit-border-horizontal-spacing"
        property string WebkitBorderVerticalSpacing: "-webkit-border-vertical-spacing"
        property string WebkitBoxAlign: "-webkit-box-align"
        property int NoneId: 0
        property int XWebkitAirplayId: (1 << 0)
        property int WebkitTextZoomId: (1 << 1)
        property int WebkitBackdropFilterId: (1 << 2)
        property int WebkitBorderHorizontalSpacingId: (1 << 3)
        property int WebkitBorderVerticalSpacingId: (1 << 4)
        property int WebkitBoxAlignId: (1 << 5)
        property int AllId: 0x3f
    }
}