// Copyright © 2025 cymlifework (cymlifework@163.com). All rights reserved.
// Licensed under the Apache License, Version 2.0 (see LICENSE file).

package sqlite

import (
	"fmt"
	"os"
	"strings"

	"github.com/antlr4-go/antlr/v4"
	parser "github.com/cymfarcat/constmaker/parser/sqlite"
	src "github.com/cymfarcat/constmaker/src"
)

type SQLiteParser struct {
	parser.BaseSQLiteParserListener

	option *src.Options

	consts        map[string]string
	objects       map[string]*SQLiteObject
	currentObject *SQLiteObject
}

func NewSQLiteParser(option *src.Options) *SQLiteParser {
	parser := &SQLiteParser{}
	parser.option = option

	parser.consts = make(map[string]string)
	parser.objects = make(map[string]*SQLiteObject)
	parser.currentObject = nil

	return parser
}

func (obj *SQLiteParser) ParseFile() int {
	content, err := os.ReadFile(obj.option.InputFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Can't read file: %s, error: %s\n", obj.option.InputFile, err)
		return -1
	}

	is := antlr.NewInputStream(string(content))
	lexer := parser.NewSQLiteLexer(is)
	stream := antlr.NewCommonTokenStream(lexer, 0)
	parser := parser.NewSQLiteParser(stream)
	tree := parser.Parse()

	if obj.option.Verbose {
		str := tree.ToStringTree([]string{}, parser)
		str = strings.ReplaceAll(str, "(sql_stmt", "\n(sql_stmt")
		fmt.Println(str)
	}

	antlr.ParseTreeWalkerDefault.Walk(obj, tree)

	// build const
	for _, object := range obj.objects {
		object.applyOption(obj.option, obj.consts)
	}

	// then write
	obj.GenFile(tree)

	return 0
}

func (obj *SQLiteParser) AltName(name string, item string) string {
	// check is multi names
	if strings.Contains(name, src.SeparatorChar) {
		parts := strings.Split(name, src.SeparatorChar)

		for _, part := range parts {
			part = src.UnwrapIdent(part)
			object, ok := obj.objects[part]
			if ok {
				alt, ok := object.altName(item, obj.consts)
				if ok {
					return alt
				}
			}
		}
	}

	name = src.UnwrapIdent(name)

	// first search in name's object
	object, ok := obj.objects[name]
	if ok {
		alt, ok := object.altName(item, obj.consts)
		if ok {
			return alt
		}
	}

	// then search in all object
	for _, object := range obj.objects {
		alt, ok := object.altName(item, obj.consts)
		if ok {
			return alt
		}
	}
	return item
}

func (obj *SQLiteParser) GenFile(tree parser.IParseContext) {
	if obj.option.GenAll || obj.option.GenCpp {
		writer := NewSQLWriterAny(obj, src.CPP)
		writer.GenCpp(tree)
	}

	if obj.option.GenAll || obj.option.GenDart {
		writer := NewSQLWriterAny(obj, src.Dart)
		writer.GenDart(tree)
	}

	if obj.option.GenAll || obj.option.GenGo {
		writer := NewSQLWriterAny(obj, src.Go)
		writer.GenGo(tree)
	}

	if obj.option.GenAll || obj.option.GenRust {
		writer := NewSQLWriterAny(obj, src.Rust)
		writer.GenRust(tree)
	}
}

func (obj *SQLiteParser) writeFile(path string, data string, headComment bool, startComment string, endComment string) {
	file, err := os.Create(path)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Can't create file: %s, error: %s\n", path, err)
		return
	}
	defer file.Close()

	if headComment {
		if len(startComment) == 0 && len(endComment) == 0 {
			startComment = "// "
		}

		_, err = file.WriteString(startComment + "This file is generated by ConstMaker, DON'T MODIFY." + endComment + "\n")
		if err != nil {
			fmt.Fprintf(os.Stderr, "Can't write file: %s, error: %s\n", path, err)
		}
	}

	_, err = file.WriteString(data)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Can't write file: %s, error: %s\n", path, err)
	}
}

func (obj *SQLiteParser) checkObjName(name string, create_action string, line int, column int) {
	_, ok := obj.objects[name]
	if ok {
		fmt.Fprintf(os.Stderr, "file: %s, %s duplicate name: %s, at %d : %d.\n", obj.option.InputFile, name, create_action, line, column)
		os.Exit(-1)
	}
}

// EnterParse is called when production parse is entered.
func (obj *SQLiteParser) EnterParse(ctx *parser.ParseContext) {}

// ExitParse is called when production parse is exited.
func (obj *SQLiteParser) ExitParse(ctx *parser.ParseContext) {}

// EnterSql_stmt_list is called when production sql_stmt_list is entered.
func (obj *SQLiteParser) EnterSql_stmt_list(ctx *parser.Sql_stmt_listContext) {}

// ExitSql_stmt_list is called when production sql_stmt_list is exited.
func (obj *SQLiteParser) ExitSql_stmt_list(ctx *parser.Sql_stmt_listContext) {}

// EnterSql_stmt is called when production sql_stmt is entered.
func (obj *SQLiteParser) EnterSql_stmt(ctx *parser.Sql_stmtContext) {}

// ExitSql_stmt is called when production sql_stmt is exited.
func (obj *SQLiteParser) ExitSql_stmt(ctx *parser.Sql_stmtContext) {}

// EnterAlter_table_stmt is called when production alter_table_stmt is entered.
func (obj *SQLiteParser) EnterAlter_table_stmt(ctx *parser.Alter_table_stmtContext) {
	name := ctx.Table_name(0).GetText()
	obj.currentObject = obj.objects[name]
}

// ExitAlter_table_stmt is called when production alter_table_stmt is exited.
func (obj *SQLiteParser) ExitAlter_table_stmt(ctx *parser.Alter_table_stmtContext) {
	// pop stack
	obj.currentObject = nil
}

// EnterAnalyze_stmt is called when production analyze_stmt is entered.
func (obj *SQLiteParser) EnterAnalyze_stmt(ctx *parser.Analyze_stmtContext) {}

// ExitAnalyze_stmt is called when production analyze_stmt is exited.
func (obj *SQLiteParser) ExitAnalyze_stmt(ctx *parser.Analyze_stmtContext) {}

// EnterAttach_stmt is called when production attach_stmt is entered.
func (obj *SQLiteParser) EnterAttach_stmt(ctx *parser.Attach_stmtContext) {}

// ExitAttach_stmt is called when production attach_stmt is exited.
func (obj *SQLiteParser) ExitAttach_stmt(ctx *parser.Attach_stmtContext) {}

// EnterBegin_stmt is called when production begin_stmt is entered.
func (obj *SQLiteParser) EnterBegin_stmt(ctx *parser.Begin_stmtContext) {}

// ExitBegin_stmt is called when production begin_stmt is exited.
func (obj *SQLiteParser) ExitBegin_stmt(ctx *parser.Begin_stmtContext) {}

// EnterCommit_stmt is called when production commit_stmt is entered.
func (obj *SQLiteParser) EnterCommit_stmt(ctx *parser.Commit_stmtContext) {}

// ExitCommit_stmt is called when production commit_stmt is exited.
func (obj *SQLiteParser) ExitCommit_stmt(ctx *parser.Commit_stmtContext) {}

// EnterRollback_stmt is called when production rollback_stmt is entered.
func (obj *SQLiteParser) EnterRollback_stmt(ctx *parser.Rollback_stmtContext) {}

// ExitRollback_stmt is called when production rollback_stmt is exited.
func (obj *SQLiteParser) ExitRollback_stmt(ctx *parser.Rollback_stmtContext) {}

// EnterSavepoint_stmt is called when production savepoint_stmt is entered.
func (obj *SQLiteParser) EnterSavepoint_stmt(ctx *parser.Savepoint_stmtContext) {}

// ExitSavepoint_stmt is called when production savepoint_stmt is exited.
func (obj *SQLiteParser) ExitSavepoint_stmt(ctx *parser.Savepoint_stmtContext) {}

// EnterRelease_stmt is called when production release_stmt is entered.
func (obj *SQLiteParser) EnterRelease_stmt(ctx *parser.Release_stmtContext) {}

// ExitRelease_stmt is called when production release_stmt is exited.
func (obj *SQLiteParser) ExitRelease_stmt(ctx *parser.Release_stmtContext) {}

// EnterCreate_index_stmt is called when production create_index_stmt is entered.
func (obj *SQLiteParser) EnterCreate_index_stmt(ctx *parser.Create_index_stmtContext) {
	name := src.UnwrapIdent(ctx.Index_name().GetText())

	obj.checkObjName(name, "create index", ctx.GetStart().GetLine(), ctx.GetStart().GetColumn())

	index := NewSQLiteObject(name, TypeIndex)

	obj.objects[name] = index

	// push stack
	obj.currentObject = index
}

// ExitCreate_index_stmt is called when production create_index_stmt is exited.
func (obj *SQLiteParser) ExitCreate_index_stmt(ctx *parser.Create_index_stmtContext) {
	// pop stack
	obj.currentObject = nil
}

// EnterIndexed_column is called when production indexed_column is entered.
func (obj *SQLiteParser) EnterIndexed_column(ctx *parser.Indexed_columnContext) {
}

// ExitIndexed_column is called when production indexed_column is exited.
func (obj *SQLiteParser) ExitIndexed_column(ctx *parser.Indexed_columnContext) {}

// EnterCreate_table_stmt is called when production create_table_stmt is entered.
func (obj *SQLiteParser) EnterCreate_table_stmt(ctx *parser.Create_table_stmtContext) {
	name := src.UnwrapIdent(ctx.Table_name().GetText())

	obj.checkObjName(name, "create table", ctx.GetStart().GetLine(), ctx.GetStart().GetColumn())

	table := NewSQLiteObject(name, TypeTable)

	obj.objects[name] = table

	// push stack
	obj.currentObject = table
}

// ExitCreate_table_stmt is called when production create_table_stmt is exited.
func (obj *SQLiteParser) ExitCreate_table_stmt(ctx *parser.Create_table_stmtContext) {
	// pop stack
	obj.currentObject = nil
}

// EnterColumn_def is called when production column_def is entered.
func (obj *SQLiteParser) EnterColumn_def(ctx *parser.Column_defContext) {}

// ExitColumn_def is called when production column_def is exited.
func (obj *SQLiteParser) ExitColumn_def(ctx *parser.Column_defContext) {}

// EnterType_name is called when production type_name is entered.
func (obj *SQLiteParser) EnterType_name(ctx *parser.Type_nameContext) {}

// ExitType_name is called when production type_name is exited.
func (obj *SQLiteParser) ExitType_name(ctx *parser.Type_nameContext) {}

// EnterColumn_constraint is called when production column_constraint is entered.
func (obj *SQLiteParser) EnterColumn_constraint(ctx *parser.Column_constraintContext) {}

// ExitColumn_constraint is called when production column_constraint is exited.
func (obj *SQLiteParser) ExitColumn_constraint(ctx *parser.Column_constraintContext) {}

// EnterSigned_number is called when production signed_number is entered.
func (obj *SQLiteParser) EnterSigned_number(ctx *parser.Signed_numberContext) {}

// ExitSigned_number is called when production signed_number is exited.
func (obj *SQLiteParser) ExitSigned_number(ctx *parser.Signed_numberContext) {}

// EnterTable_constraint is called when production table_constraint is entered.
func (obj *SQLiteParser) EnterTable_constraint(ctx *parser.Table_constraintContext) {}

// ExitTable_constraint is called when production table_constraint is exited.
func (obj *SQLiteParser) ExitTable_constraint(ctx *parser.Table_constraintContext) {}

// EnterForeign_key_clause is called when production foreign_key_clause is entered.
func (obj *SQLiteParser) EnterForeign_key_clause(ctx *parser.Foreign_key_clauseContext) {}

// ExitForeign_key_clause is called when production foreign_key_clause is exited.
func (obj *SQLiteParser) ExitForeign_key_clause(ctx *parser.Foreign_key_clauseContext) {}

// EnterConflict_clause is called when production conflict_clause is entered.
func (obj *SQLiteParser) EnterConflict_clause(ctx *parser.Conflict_clauseContext) {}

// ExitConflict_clause is called when production conflict_clause is exited.
func (obj *SQLiteParser) ExitConflict_clause(ctx *parser.Conflict_clauseContext) {}

// EnterCreate_trigger_stmt is called when production create_trigger_stmt is entered.
func (obj *SQLiteParser) EnterCreate_trigger_stmt(ctx *parser.Create_trigger_stmtContext) {
	name := src.UnwrapIdent(ctx.Trigger_name().GetText())

	obj.checkObjName(name, "create trigger", ctx.GetStart().GetLine(), ctx.GetStart().GetColumn())

	trigger := NewSQLiteObject(name, TypeTrigger)

	obj.objects[name] = trigger

	// push stack
	obj.currentObject = trigger
}

// ExitCreate_trigger_stmt is called when production create_trigger_stmt is exited.
func (obj *SQLiteParser) ExitCreate_trigger_stmt(ctx *parser.Create_trigger_stmtContext) {
	// pop stack
	obj.currentObject = nil
}

// EnterCreate_view_stmt is called when production create_view_stmt is entered.
func (obj *SQLiteParser) EnterCreate_view_stmt(ctx *parser.Create_view_stmtContext) {
	name := src.UnwrapIdent(ctx.View_name().GetText())

	obj.checkObjName(name, "create view", ctx.GetStart().GetLine(), ctx.GetStart().GetColumn())

	view := NewSQLiteObject(name, TypeView)

	obj.objects[name] = view

	// push stack
	obj.currentObject = view
}

// ExitCreate_view_stmt is called when production create_view_stmt is exited.
func (obj *SQLiteParser) ExitCreate_view_stmt(ctx *parser.Create_view_stmtContext) {
	// pop stack
	obj.currentObject = nil
}

// EnterCreate_virtual_table_stmt is called when production create_virtual_table_stmt is entered.
func (obj *SQLiteParser) EnterCreate_virtual_table_stmt(ctx *parser.Create_virtual_table_stmtContext) {
	name := src.UnwrapIdent(ctx.Table_name().GetText())

	obj.checkObjName(name, "create virtual table", ctx.GetStart().GetLine(), ctx.GetStart().GetColumn())

	virtualTable := NewSQLiteObject(name, TypeVirtualTable)

	obj.objects[name] = virtualTable

	// push stack
	obj.currentObject = virtualTable
}

// ExitCreate_virtual_table_stmt is called when production create_virtual_table_stmt is exited.
func (obj *SQLiteParser) ExitCreate_virtual_table_stmt(ctx *parser.Create_virtual_table_stmtContext) {
	// pop stack
	obj.currentObject = nil
}

// EnterWith_clause is called when production with_clause is entered.
func (obj *SQLiteParser) EnterWith_clause(ctx *parser.With_clauseContext) {}

// ExitWith_clause is called when production with_clause is exited.
func (obj *SQLiteParser) ExitWith_clause(ctx *parser.With_clauseContext) {}

// EnterCte_table_name is called when production cte_table_name is entered.
func (obj *SQLiteParser) EnterCte_table_name(ctx *parser.Cte_table_nameContext) {}

// ExitCte_table_name is called when production cte_table_name is exited.
func (obj *SQLiteParser) ExitCte_table_name(ctx *parser.Cte_table_nameContext) {}

// EnterRecursive_cte is called when production recursive_cte is entered.
func (obj *SQLiteParser) EnterRecursive_cte(ctx *parser.Recursive_cteContext) {}

// ExitRecursive_cte is called when production recursive_cte is exited.
func (obj *SQLiteParser) ExitRecursive_cte(ctx *parser.Recursive_cteContext) {}

// EnterCommon_table_expression is called when production common_table_expression is entered.
func (obj *SQLiteParser) EnterCommon_table_expression(ctx *parser.Common_table_expressionContext) {
}

// ExitCommon_table_expression is called when production common_table_expression is exited.
func (obj *SQLiteParser) ExitCommon_table_expression(ctx *parser.Common_table_expressionContext) {}

// EnterDelete_stmt is called when production delete_stmt is entered.
func (obj *SQLiteParser) EnterDelete_stmt(ctx *parser.Delete_stmtContext) {}

// ExitDelete_stmt is called when production delete_stmt is exited.
func (obj *SQLiteParser) ExitDelete_stmt(ctx *parser.Delete_stmtContext) {}

// EnterDelete_stmt_limited is called when production delete_stmt_limited is entered.
func (obj *SQLiteParser) EnterDelete_stmt_limited(ctx *parser.Delete_stmt_limitedContext) {}

// ExitDelete_stmt_limited is called when production delete_stmt_limited is exited.
func (obj *SQLiteParser) ExitDelete_stmt_limited(ctx *parser.Delete_stmt_limitedContext) {}

// EnterDetach_stmt is called when production detach_stmt is entered.
func (obj *SQLiteParser) EnterDetach_stmt(ctx *parser.Detach_stmtContext) {}

// ExitDetach_stmt is called when production detach_stmt is exited.
func (obj *SQLiteParser) ExitDetach_stmt(ctx *parser.Detach_stmtContext) {}

// EnterDrop_stmt is called when production drop_stmt is entered.
func (obj *SQLiteParser) EnterDrop_stmt(ctx *parser.Drop_stmtContext) {}

// ExitDrop_stmt is called when production drop_stmt is exited.
func (obj *SQLiteParser) ExitDrop_stmt(ctx *parser.Drop_stmtContext) {}

// EnterExpr is called when production expr is entered.
func (obj *SQLiteParser) EnterExpr(ctx *parser.ExprContext) {}

// ExitExpr is called when production expr is exited.
func (obj *SQLiteParser) ExitExpr(ctx *parser.ExprContext) {}

// EnterRaise_function is called when production raise_function is entered.
func (obj *SQLiteParser) EnterRaise_function(ctx *parser.Raise_functionContext) {}

// ExitRaise_function is called when production raise_function is exited.
func (obj *SQLiteParser) ExitRaise_function(ctx *parser.Raise_functionContext) {}

// EnterLiteral_value is called when production literal_value is entered.
func (obj *SQLiteParser) EnterLiteral_value(ctx *parser.Literal_valueContext) {}

// ExitLiteral_value is called when production literal_value is exited.
func (obj *SQLiteParser) ExitLiteral_value(ctx *parser.Literal_valueContext) {}

// EnterValue_row is called when production value_row is entered.
func (obj *SQLiteParser) EnterValue_row(ctx *parser.Value_rowContext) {}

// ExitValue_row is called when production value_row is exited.
func (obj *SQLiteParser) ExitValue_row(ctx *parser.Value_rowContext) {}

// EnterValues_clause is called when production values_clause is entered.
func (obj *SQLiteParser) EnterValues_clause(ctx *parser.Values_clauseContext) {}

// ExitValues_clause is called when production values_clause is exited.
func (obj *SQLiteParser) ExitValues_clause(ctx *parser.Values_clauseContext) {}

// EnterInsert_stmt is called when production insert_stmt is entered.
func (obj *SQLiteParser) EnterInsert_stmt(ctx *parser.Insert_stmtContext) {}

// ExitInsert_stmt is called when production insert_stmt is exited.
func (obj *SQLiteParser) ExitInsert_stmt(ctx *parser.Insert_stmtContext) {}

// EnterReturning_clause is called when production returning_clause is entered.
func (obj *SQLiteParser) EnterReturning_clause(ctx *parser.Returning_clauseContext) {}

// ExitReturning_clause is called when production returning_clause is exited.
func (obj *SQLiteParser) ExitReturning_clause(ctx *parser.Returning_clauseContext) {}

// EnterUpsert_clause is called when production upsert_clause is entered.
func (obj *SQLiteParser) EnterUpsert_clause(ctx *parser.Upsert_clauseContext) {}

// ExitUpsert_clause is called when production upsert_clause is exited.
func (obj *SQLiteParser) ExitUpsert_clause(ctx *parser.Upsert_clauseContext) {}

// EnterPragma_stmt is called when production pragma_stmt is entered.
func (obj *SQLiteParser) EnterPragma_stmt(ctx *parser.Pragma_stmtContext) {}

// ExitPragma_stmt is called when production pragma_stmt is exited.
func (obj *SQLiteParser) ExitPragma_stmt(ctx *parser.Pragma_stmtContext) {}

// EnterPragma_value is called when production pragma_value is entered.
func (obj *SQLiteParser) EnterPragma_value(ctx *parser.Pragma_valueContext) {}

// ExitPragma_value is called when production pragma_value is exited.
func (obj *SQLiteParser) ExitPragma_value(ctx *parser.Pragma_valueContext) {}

// EnterReindex_stmt is called when production reindex_stmt is entered.
func (obj *SQLiteParser) EnterReindex_stmt(ctx *parser.Reindex_stmtContext) {}

// ExitReindex_stmt is called when production reindex_stmt is exited.
func (obj *SQLiteParser) ExitReindex_stmt(ctx *parser.Reindex_stmtContext) {}

// EnterSelect_stmt is called when production select_stmt is entered.
func (obj *SQLiteParser) EnterSelect_stmt(ctx *parser.Select_stmtContext) {}

// ExitSelect_stmt is called when production select_stmt is exited.
func (obj *SQLiteParser) ExitSelect_stmt(ctx *parser.Select_stmtContext) {}

// EnterJoin_clause is called when production join_clause is entered.
func (obj *SQLiteParser) EnterJoin_clause(ctx *parser.Join_clauseContext) {}

// ExitJoin_clause is called when production join_clause is exited.
func (obj *SQLiteParser) ExitJoin_clause(ctx *parser.Join_clauseContext) {}

// EnterSelect_core is called when production select_core is entered.
func (obj *SQLiteParser) EnterSelect_core(ctx *parser.Select_coreContext) {}

// ExitSelect_core is called when production select_core is exited.
func (obj *SQLiteParser) ExitSelect_core(ctx *parser.Select_coreContext) {}

// EnterFactored_select_stmt is called when production factored_select_stmt is entered.
func (obj *SQLiteParser) EnterFactored_select_stmt(ctx *parser.Factored_select_stmtContext) {}

// ExitFactored_select_stmt is called when production factored_select_stmt is exited.
func (obj *SQLiteParser) ExitFactored_select_stmt(ctx *parser.Factored_select_stmtContext) {}

// EnterSimple_select_stmt is called when production simple_select_stmt is entered.
func (obj *SQLiteParser) EnterSimple_select_stmt(ctx *parser.Simple_select_stmtContext) {}

// ExitSimple_select_stmt is called when production simple_select_stmt is exited.
func (obj *SQLiteParser) ExitSimple_select_stmt(ctx *parser.Simple_select_stmtContext) {}

// EnterCompound_select_stmt is called when production compound_select_stmt is entered.
func (obj *SQLiteParser) EnterCompound_select_stmt(ctx *parser.Compound_select_stmtContext) {}

// ExitCompound_select_stmt is called when production compound_select_stmt is exited.
func (obj *SQLiteParser) ExitCompound_select_stmt(ctx *parser.Compound_select_stmtContext) {}

// EnterTable_or_subquery is called when production table_or_subquery is entered.
func (obj *SQLiteParser) EnterTable_or_subquery(ctx *parser.Table_or_subqueryContext) {}

// ExitTable_or_subquery is called when production table_or_subquery is exited.
func (obj *SQLiteParser) ExitTable_or_subquery(ctx *parser.Table_or_subqueryContext) {}

// EnterResult_column is called when production result_column is entered.
func (obj *SQLiteParser) EnterResult_column(ctx *parser.Result_columnContext) {}

// ExitResult_column is called when production result_column is exited.
func (obj *SQLiteParser) ExitResult_column(ctx *parser.Result_columnContext) {}

// EnterJoin_operator is called when production join_operator is entered.
func (obj *SQLiteParser) EnterJoin_operator(ctx *parser.Join_operatorContext) {}

// ExitJoin_operator is called when production join_operator is exited.
func (obj *SQLiteParser) ExitJoin_operator(ctx *parser.Join_operatorContext) {}

// EnterJoin_constraint is called when production join_constraint is entered.
func (obj *SQLiteParser) EnterJoin_constraint(ctx *parser.Join_constraintContext) {}

// ExitJoin_constraint is called when production join_constraint is exited.
func (obj *SQLiteParser) ExitJoin_constraint(ctx *parser.Join_constraintContext) {}

// EnterCompound_operator is called when production compound_operator is entered.
func (obj *SQLiteParser) EnterCompound_operator(ctx *parser.Compound_operatorContext) {}

// ExitCompound_operator is called when production compound_operator is exited.
func (obj *SQLiteParser) ExitCompound_operator(ctx *parser.Compound_operatorContext) {}

// EnterUpdate_stmt is called when production update_stmt is entered.
func (obj *SQLiteParser) EnterUpdate_stmt(ctx *parser.Update_stmtContext) {}

// ExitUpdate_stmt is called when production update_stmt is exited.
func (obj *SQLiteParser) ExitUpdate_stmt(ctx *parser.Update_stmtContext) {}

// EnterColumn_name_list is called when production column_name_list is entered.
func (obj *SQLiteParser) EnterColumn_name_list(ctx *parser.Column_name_listContext) {}

// ExitColumn_name_list is called when production column_name_list is exited.
func (obj *SQLiteParser) ExitColumn_name_list(ctx *parser.Column_name_listContext) {}

// EnterUpdate_stmt_limited is called when production update_stmt_limited is entered.
func (obj *SQLiteParser) EnterUpdate_stmt_limited(ctx *parser.Update_stmt_limitedContext) {}

// ExitUpdate_stmt_limited is called when production update_stmt_limited is exited.
func (obj *SQLiteParser) ExitUpdate_stmt_limited(ctx *parser.Update_stmt_limitedContext) {}

// EnterQualified_table_name is called when production qualified_table_name is entered.
func (obj *SQLiteParser) EnterQualified_table_name(ctx *parser.Qualified_table_nameContext) {}

// ExitQualified_table_name is called when production qualified_table_name is exited.
func (obj *SQLiteParser) ExitQualified_table_name(ctx *parser.Qualified_table_nameContext) {}

// EnterVacuum_stmt is called when production vacuum_stmt is entered.
func (obj *SQLiteParser) EnterVacuum_stmt(ctx *parser.Vacuum_stmtContext) {}

// ExitVacuum_stmt is called when production vacuum_stmt is exited.
func (obj *SQLiteParser) ExitVacuum_stmt(ctx *parser.Vacuum_stmtContext) {}

// EnterFilter_clause is called when production filter_clause is entered.
func (obj *SQLiteParser) EnterFilter_clause(ctx *parser.Filter_clauseContext) {}

// ExitFilter_clause is called when production filter_clause is exited.
func (obj *SQLiteParser) ExitFilter_clause(ctx *parser.Filter_clauseContext) {}

// EnterWindow_defn is called when production window_defn is entered.
func (obj *SQLiteParser) EnterWindow_defn(ctx *parser.Window_defnContext) {}

// ExitWindow_defn is called when production window_defn is exited.
func (obj *SQLiteParser) ExitWindow_defn(ctx *parser.Window_defnContext) {}

// EnterOver_clause is called when production over_clause is entered.
func (obj *SQLiteParser) EnterOver_clause(ctx *parser.Over_clauseContext) {}

// ExitOver_clause is called when production over_clause is exited.
func (obj *SQLiteParser) ExitOver_clause(ctx *parser.Over_clauseContext) {}

// EnterFrame_spec is called when production frame_spec is entered.
func (obj *SQLiteParser) EnterFrame_spec(ctx *parser.Frame_specContext) {}

// ExitFrame_spec is called when production frame_spec is exited.
func (obj *SQLiteParser) ExitFrame_spec(ctx *parser.Frame_specContext) {}

// EnterFrame_clause is called when production frame_clause is entered.
func (obj *SQLiteParser) EnterFrame_clause(ctx *parser.Frame_clauseContext) {}

// ExitFrame_clause is called when production frame_clause is exited.
func (obj *SQLiteParser) ExitFrame_clause(ctx *parser.Frame_clauseContext) {}

// EnterSimple_function_invocation is called when production simple_function_invocation is entered.
func (obj *SQLiteParser) EnterSimple_function_invocation(ctx *parser.Simple_function_invocationContext) {
}

// ExitSimple_function_invocation is called when production simple_function_invocation is exited.
func (obj *SQLiteParser) ExitSimple_function_invocation(ctx *parser.Simple_function_invocationContext) {
}

// EnterAggregate_function_invocation is called when production aggregate_function_invocation is entered.
func (obj *SQLiteParser) EnterAggregate_function_invocation(ctx *parser.Aggregate_function_invocationContext) {
}

// ExitAggregate_function_invocation is called when production aggregate_function_invocation is exited.
func (obj *SQLiteParser) ExitAggregate_function_invocation(ctx *parser.Aggregate_function_invocationContext) {
}

// EnterWindow_function_invocation is called when production window_function_invocation is entered.
func (obj *SQLiteParser) EnterWindow_function_invocation(ctx *parser.Window_function_invocationContext) {
}

// ExitWindow_function_invocation is called when production window_function_invocation is exited.
func (obj *SQLiteParser) ExitWindow_function_invocation(ctx *parser.Window_function_invocationContext) {
}

// EnterCommon_table_stmt is called when production common_table_stmt is entered.
func (obj *SQLiteParser) EnterCommon_table_stmt(ctx *parser.Common_table_stmtContext) {}

// ExitCommon_table_stmt is called when production common_table_stmt is exited.
func (obj *SQLiteParser) ExitCommon_table_stmt(ctx *parser.Common_table_stmtContext) {}

// EnterOrder_by_stmt is called when production order_by_stmt is entered.
func (obj *SQLiteParser) EnterOrder_by_stmt(ctx *parser.Order_by_stmtContext) {}

// ExitOrder_by_stmt is called when production order_by_stmt is exited.
func (obj *SQLiteParser) ExitOrder_by_stmt(ctx *parser.Order_by_stmtContext) {}

// EnterLimit_stmt is called when production limit_stmt is entered.
func (obj *SQLiteParser) EnterLimit_stmt(ctx *parser.Limit_stmtContext) {}

// ExitLimit_stmt is called when production limit_stmt is exited.
func (obj *SQLiteParser) ExitLimit_stmt(ctx *parser.Limit_stmtContext) {}

// EnterOrdering_term is called when production ordering_term is entered.
func (obj *SQLiteParser) EnterOrdering_term(ctx *parser.Ordering_termContext) {}

// ExitOrdering_term is called when production ordering_term is exited.
func (obj *SQLiteParser) ExitOrdering_term(ctx *parser.Ordering_termContext) {}

// EnterAsc_desc is called when production asc_desc is entered.
func (obj *SQLiteParser) EnterAsc_desc(ctx *parser.Asc_descContext) {}

// ExitAsc_desc is called when production asc_desc is exited.
func (obj *SQLiteParser) ExitAsc_desc(ctx *parser.Asc_descContext) {}

// EnterFrame_left is called when production frame_left is entered.
func (obj *SQLiteParser) EnterFrame_left(ctx *parser.Frame_leftContext) {}

// ExitFrame_left is called when production frame_left is exited.
func (obj *SQLiteParser) ExitFrame_left(ctx *parser.Frame_leftContext) {}

// EnterFrame_right is called when production frame_right is entered.
func (obj *SQLiteParser) EnterFrame_right(ctx *parser.Frame_rightContext) {}

// ExitFrame_right is called when production frame_right is exited.
func (obj *SQLiteParser) ExitFrame_right(ctx *parser.Frame_rightContext) {}

// EnterFrame_single is called when production frame_single is entered.
func (obj *SQLiteParser) EnterFrame_single(ctx *parser.Frame_singleContext) {}

// ExitFrame_single is called when production frame_single is exited.
func (obj *SQLiteParser) ExitFrame_single(ctx *parser.Frame_singleContext) {}

// EnterWindow_function is called when production window_function is entered.
func (obj *SQLiteParser) EnterWindow_function(ctx *parser.Window_functionContext) {}

// ExitWindow_function is called when production window_function is exited.
func (obj *SQLiteParser) ExitWindow_function(ctx *parser.Window_functionContext) {}

// EnterOffset is called when production offset is entered.
func (obj *SQLiteParser) EnterOffset(ctx *parser.OffsetContext) {}

// ExitOffset is called when production offset is exited.
func (obj *SQLiteParser) ExitOffset(ctx *parser.OffsetContext) {}

// EnterDefault_value is called when production default_value is entered.
func (obj *SQLiteParser) EnterDefault_value(ctx *parser.Default_valueContext) {}

// ExitDefault_value is called when production default_value is exited.
func (obj *SQLiteParser) ExitDefault_value(ctx *parser.Default_valueContext) {}

// EnterPartition_by is called when production partition_by is entered.
func (obj *SQLiteParser) EnterPartition_by(ctx *parser.Partition_byContext) {}

// ExitPartition_by is called when production partition_by is exited.
func (obj *SQLiteParser) ExitPartition_by(ctx *parser.Partition_byContext) {}

// EnterOrder_by_expr is called when production order_by_expr is entered.
func (obj *SQLiteParser) EnterOrder_by_expr(ctx *parser.Order_by_exprContext) {}

// ExitOrder_by_expr is called when production order_by_expr is exited.
func (obj *SQLiteParser) ExitOrder_by_expr(ctx *parser.Order_by_exprContext) {}

// EnterOrder_by_expr_asc_desc is called when production order_by_expr_asc_desc is entered.
func (obj *SQLiteParser) EnterOrder_by_expr_asc_desc(ctx *parser.Order_by_expr_asc_descContext) {}

// ExitOrder_by_expr_asc_desc is called when production order_by_expr_asc_desc is exited.
func (obj *SQLiteParser) ExitOrder_by_expr_asc_desc(ctx *parser.Order_by_expr_asc_descContext) {}

// EnterExpr_asc_desc is called when production expr_asc_desc is entered.
func (obj *SQLiteParser) EnterExpr_asc_desc(ctx *parser.Expr_asc_descContext) {}

// ExitExpr_asc_desc is called when production expr_asc_desc is exited.
func (obj *SQLiteParser) ExitExpr_asc_desc(ctx *parser.Expr_asc_descContext) {}

// EnterInitial_select is called when production initial_select is entered.
func (obj *SQLiteParser) EnterInitial_select(ctx *parser.Initial_selectContext) {}

// ExitInitial_select is called when production initial_select is exited.
func (obj *SQLiteParser) ExitInitial_select(ctx *parser.Initial_selectContext) {}

// EnterRecursive_select is called when production recursive_select is entered.
func (obj *SQLiteParser) EnterRecursive_select(ctx *parser.Recursive_selectContext) {}

// ExitRecursive_select is called when production recursive_select is exited.
func (obj *SQLiteParser) ExitRecursive_select(ctx *parser.Recursive_selectContext) {}

// EnterUnary_operator is called when production unary_operator is entered.
func (obj *SQLiteParser) EnterUnary_operator(ctx *parser.Unary_operatorContext) {}

// ExitUnary_operator is called when production unary_operator is exited.
func (obj *SQLiteParser) ExitUnary_operator(ctx *parser.Unary_operatorContext) {}

// EnterError_message is called when production error_message is entered.
func (obj *SQLiteParser) EnterError_message(ctx *parser.Error_messageContext) {}

// ExitError_message is called when production error_message is exited.
func (obj *SQLiteParser) ExitError_message(ctx *parser.Error_messageContext) {}

// EnterModule_argument is called when production module_argument is entered.
func (obj *SQLiteParser) EnterModule_argument(ctx *parser.Module_argumentContext) {}

// ExitModule_argument is called when production module_argument is exited.
func (obj *SQLiteParser) ExitModule_argument(ctx *parser.Module_argumentContext) {}

// EnterColumn_alias is called when production column_alias is entered.
func (obj *SQLiteParser) EnterColumn_alias(ctx *parser.Column_aliasContext) {}

// ExitColumn_alias is called when production column_alias is exited.
func (obj *SQLiteParser) ExitColumn_alias(ctx *parser.Column_aliasContext) {}

// EnterKeyword is called when production keyword is entered.
func (obj *SQLiteParser) EnterKeyword(ctx *parser.KeywordContext) {}

// ExitKeyword is called when production keyword is exited.
func (obj *SQLiteParser) ExitKeyword(ctx *parser.KeywordContext) {}

// EnterName is called when production name is entered.
func (obj *SQLiteParser) EnterName(ctx *parser.NameContext) {}

// ExitName is called when production name is exited.
func (obj *SQLiteParser) ExitName(ctx *parser.NameContext) {}

// EnterFunction_name is called when production function_name is entered.
func (obj *SQLiteParser) EnterFunction_name(ctx *parser.Function_nameContext) {}

// ExitFunction_name is called when production function_name is exited.
func (obj *SQLiteParser) ExitFunction_name(ctx *parser.Function_nameContext) {}

// EnterSchema_name is called when production schema_name is entered.
func (obj *SQLiteParser) EnterSchema_name(ctx *parser.Schema_nameContext) {}

// ExitSchema_name is called when production schema_name is exited.
func (obj *SQLiteParser) ExitSchema_name(ctx *parser.Schema_nameContext) {}

// EnterTable_name is called when production table_name is entered.
func (obj *SQLiteParser) EnterTable_name(ctx *parser.Table_nameContext) {}

// ExitTable_name is called when production table_name is exited.
func (obj *SQLiteParser) ExitTable_name(ctx *parser.Table_nameContext) {}

// EnterTable_or_index_name is called when production table_or_index_name is entered.
func (obj *SQLiteParser) EnterTable_or_index_name(ctx *parser.Table_or_index_nameContext) {}

// ExitTable_or_index_name is called when production table_or_index_name is exited.
func (obj *SQLiteParser) ExitTable_or_index_name(ctx *parser.Table_or_index_nameContext) {}

// EnterColumn_name is called when production column_name is entered.
func (obj *SQLiteParser) EnterColumn_name(ctx *parser.Column_nameContext) {
	if obj.currentObject != nil && ctx.Any_name() != nil {
		field := ctx.Any_name().GetText()
		obj.currentObject.addField(obj.option, field /*, obj.option.InputFile, "", ctx.GetStart().GetLine(), ctx.GetStart().GetColumn()*/)
	}
}

// ExitColumn_name is called when production column_name is exited.
func (obj *SQLiteParser) ExitColumn_name(ctx *parser.Column_nameContext) {}

// EnterCollation_name is called when production collation_name is entered.
func (obj *SQLiteParser) EnterCollation_name(ctx *parser.Collation_nameContext) {}

// ExitCollation_name is called when production collation_name is exited.
func (obj *SQLiteParser) ExitCollation_name(ctx *parser.Collation_nameContext) {}

// EnterForeign_table is called when production foreign_table is entered.
func (obj *SQLiteParser) EnterForeign_table(ctx *parser.Foreign_tableContext) {}

// ExitForeign_table is called when production foreign_table is exited.
func (obj *SQLiteParser) ExitForeign_table(ctx *parser.Foreign_tableContext) {}

// EnterIndex_name is called when production index_name is entered.
func (obj *SQLiteParser) EnterIndex_name(ctx *parser.Index_nameContext) {}

// ExitIndex_name is called when production index_name is exited.
func (obj *SQLiteParser) ExitIndex_name(ctx *parser.Index_nameContext) {}

// EnterTrigger_name is called when production trigger_name is entered.
func (obj *SQLiteParser) EnterTrigger_name(ctx *parser.Trigger_nameContext) {}

// ExitTrigger_name is called when production trigger_name is exited.
func (obj *SQLiteParser) ExitTrigger_name(ctx *parser.Trigger_nameContext) {}

// EnterView_name is called when production view_name is entered.
func (obj *SQLiteParser) EnterView_name(ctx *parser.View_nameContext) {}

// ExitView_name is called when production view_name is exited.
func (obj *SQLiteParser) ExitView_name(ctx *parser.View_nameContext) {}

// EnterModule_name is called when production module_name is entered.
func (obj *SQLiteParser) EnterModule_name(ctx *parser.Module_nameContext) {}

// ExitModule_name is called when production module_name is exited.
func (obj *SQLiteParser) ExitModule_name(ctx *parser.Module_nameContext) {}

// EnterPragma_name is called when production pragma_name is entered.
func (obj *SQLiteParser) EnterPragma_name(ctx *parser.Pragma_nameContext) {}

// ExitPragma_name is called when production pragma_name is exited.
func (obj *SQLiteParser) ExitPragma_name(ctx *parser.Pragma_nameContext) {}

// EnterSavepoint_name is called when production savepoint_name is entered.
func (obj *SQLiteParser) EnterSavepoint_name(ctx *parser.Savepoint_nameContext) {}

// ExitSavepoint_name is called when production savepoint_name is exited.
func (obj *SQLiteParser) ExitSavepoint_name(ctx *parser.Savepoint_nameContext) {}

// EnterTable_alias is called when production table_alias is entered.
func (obj *SQLiteParser) EnterTable_alias(ctx *parser.Table_aliasContext) {}

// ExitTable_alias is called when production table_alias is exited.
func (obj *SQLiteParser) ExitTable_alias(ctx *parser.Table_aliasContext) {}

// EnterTransaction_name is called when production transaction_name is entered.
func (obj *SQLiteParser) EnterTransaction_name(ctx *parser.Transaction_nameContext) {}

// ExitTransaction_name is called when production transaction_name is exited.
func (obj *SQLiteParser) ExitTransaction_name(ctx *parser.Transaction_nameContext) {}

// EnterWindow_name is called when production window_name is entered.
func (obj *SQLiteParser) EnterWindow_name(ctx *parser.Window_nameContext) {}

// ExitWindow_name is called when production window_name is exited.
func (obj *SQLiteParser) ExitWindow_name(ctx *parser.Window_nameContext) {}

// EnterAlias is called when production alias is entered.
func (obj *SQLiteParser) EnterAlias(ctx *parser.AliasContext) {}

// ExitAlias is called when production alias is exited.
func (obj *SQLiteParser) ExitAlias(ctx *parser.AliasContext) {}

// EnterFilename is called when production filename is entered.
func (obj *SQLiteParser) EnterFilename(ctx *parser.FilenameContext) {}

// ExitFilename is called when production filename is exited.
func (obj *SQLiteParser) ExitFilename(ctx *parser.FilenameContext) {}

// EnterBase_window_name is called when production base_window_name is entered.
func (obj *SQLiteParser) EnterBase_window_name(ctx *parser.Base_window_nameContext) {}

// ExitBase_window_name is called when production base_window_name is exited.
func (obj *SQLiteParser) ExitBase_window_name(ctx *parser.Base_window_nameContext) {}

// EnterSimple_func is called when production simple_func is entered.
func (obj *SQLiteParser) EnterSimple_func(ctx *parser.Simple_funcContext) {}

// ExitSimple_func is called when production simple_func is exited.
func (obj *SQLiteParser) ExitSimple_func(ctx *parser.Simple_funcContext) {}

// EnterAggregate_func is called when production aggregate_func is entered.
func (obj *SQLiteParser) EnterAggregate_func(ctx *parser.Aggregate_funcContext) {}

// ExitAggregate_func is called when production aggregate_func is exited.
func (obj *SQLiteParser) ExitAggregate_func(ctx *parser.Aggregate_funcContext) {}

// EnterTable_function_name is called when production table_function_name is entered.
func (obj *SQLiteParser) EnterTable_function_name(ctx *parser.Table_function_nameContext) {}

// ExitTable_function_name is called when production table_function_name is exited.
func (obj *SQLiteParser) ExitTable_function_name(ctx *parser.Table_function_nameContext) {}

// EnterAny_name is called when production any_name is entered.
func (obj *SQLiteParser) EnterAny_name(ctx *parser.Any_nameContext) {}

// ExitAny_name is called when production any_name is exited.
func (obj *SQLiteParser) ExitAny_name(ctx *parser.Any_nameContext) {
	//fmt.Println("any_name=" + ctx.GetText())
}
