// This file is generated by ConstMaker, DON'T MODIFY.

/**
 *this is a test
 */
static let table: String = "table" // hello word
static let allowTest: String = "at"
static let percent: Int8 = -100

/** pi */
static let pi: Float = 3.14159

/**
 * colors
 */
enum mColors: UInt8 {
    case kBlueDef
    case kGreenDef
    case kRedDef
}
static let mColorsKBlueStr: String = "blue"
static let mColorsKGreenStr: String = "green"
static let mColorsKRedStr: String = "red"

struct node {
    static let htmlBlockId: String = "Block"
    static let htmlTableId: String = "Table"
}

struct item {
    static let allowTest: String = "at"
    static let pi: Float = 3.14159
    static let table: String = "table"
    static let Percent: Int8 = 100
    static let noneId: UInt8 = 0
    static let allowTestId: UInt8 = 1 << 0
    static let piId: UInt8 = 1 << 1
    static let tableId: UInt8 = 1 << 2
    static let PercentId: UInt8 = 1 << 3
    static let allId: UInt8 = 0xf

    enum colors: UInt8 {
        case blue
        case green // green
        case red
    }
}

struct itemNode {
    static let border: String = "border"

    enum colors: UInt8 {
        case red
        case green // green
        case blue
    }
    static let colorsRedStr: String = "RED"
    static let colorsGreenStr: String = "GREEN"
    static let colorsBlueStr: String = "BLUE"
}

struct itemNodeQuick {
    static let item: String = "item"
}

struct itemNodeQuickNode {
}

struct css3 {
    static let xWebkitAirplay: String = "x-webkit-airplay"
    static let WebkitTextZoom: String = "-webkit-text-zoom"
    static let WebkitBackdropFilter: String = "-webkit-backdrop-filter"
    static let WebkitBorderHorizontalSpacing: String = "-webkit-border-horizontal-spacing"
    static let WebkitBorderVerticalSpacing: String = "-webkit-border-vertical-spacing"
    static let WebkitBoxAlign: String = "-webkit-box-align"
    static let noneId: UInt8 = 0
    static let xWebkitAirplayId: UInt8 = 1 << 0
    static let WebkitTextZoomId: UInt8 = 1 << 1
    static let WebkitBackdropFilterId: UInt8 = 1 << 2
    static let WebkitBorderHorizontalSpacingId: UInt8 = 1 << 3
    static let WebkitBorderVerticalSpacingId: UInt8 = 1 << 4
    static let WebkitBoxAlignId: UInt8 = 1 << 5
    static let allId: UInt8 = 0x3f
}