# This file is generated by ConstMaker, DON'T MODIFY.

from enum import Enum

# 
# this is a test
# 
table: str = "table" # hello word
allowTest: str = "at"
percent: int = -100
# pi 
pi: float = 3.14159

# 
# colors
# 
class mColors(Enum):
    kBlueDef
    kGreenDef
    kRedDef

    kBlueStr: str = "blue"
    kGreenStr: str = "green"
    kRedStr: str = "red"

class node:
    htmlBlockId: str = "Block"
    htmlTableId: str = "Table"


class item:
    allowTest: str = "at"
    pi: float = 3.14159
    table: str = "table"
    Percent: int = 100
    noneId: int = 0
    allowTestId: int = 1 << 0
    piId: int = 1 << 1
    tableId: int = 1 << 2
    PercentId: int = 1 << 3
    allId: int = 0xf

    class colors(Enum):
        blue
        green # green
        red


class itemNode:
    border: str = "border"

    class colors(Enum):
        red
        green # green
        blue

        redStr: str = "RED"
        greenStr: str = "GREEN"
        blueStr: str = "BLUE"


class itemNodeQuick:
    item: str = "item"


# namespace ITEM_NODE_Quick_NODE

class itemCss3:
    xWebkitAirplay: str = "x-webkit-airplay"
    WebkitTextZoom: str = "-webkit-text-zoom"
    WebkitBackdropFilter: str = "-webkit-backdrop-filter"
    WebkitBorderHorizontalSpacing: str = "-webkit-border-horizontal-spacing"
    WebkitBorderVerticalSpacing: str = "-webkit-border-vertical-spacing"
    WebkitBoxAlign: str = "-webkit-box-align"
    noneId: int = 0
    xWebkitAirplayId: int = 1 << 0
    WebkitTextZoomId: int = 1 << 1
    WebkitBackdropFilterId: int = 1 << 2
    WebkitBorderHorizontalSpacingId: int = 1 << 3
    WebkitBorderVerticalSpacingId: int = 1 << 4
    WebkitBoxAlignId: int = 1 << 5
    allId: int = 0x3f
