// This file is generated by ConstMaker, DON'T MODIFY.

public static class TEST1 {
    /**
     *this is a test
     */
    public const string TABLE = "table"; // hello word
    public const string ALLOW_TEST = "at";
    public const sbyte PERCENT = -100;

    /** pi */
    public const float PI = 3.14159f;

    /**
     * colors
     */
    public enum COLORS {
        K_NONE_DEF = 0,
        K_BLUE_DEF = 1 << 0,
        K_GREEN_DEF = 1 << 1,
        K_RED_DEF = 1 << 2,
        K_ALL_DEF = 0x7,
    }
    public const string COLORS_K_NONE_DEF_STR = "NONE";
    public const string COLORS_K_BLUE_DEF_STR = "blue";
    public const string COLORS_K_GREEN_DEF_STR = "green";
    public const string COLORS_K_RED_DEF_STR = "red";
    public const string COLORS_K_ALL_DEF_STR = "ALL";
}

public static class NODE {
    public const string HTML_BLOCK_ID = "Block";
    public const string HTML_TABLE_ID = "Table";
}

public static class ITEM {
    public const string ALLOW_TEST = "at";
    public const float PI = 3.14159f;
    public const string TABLE = "table";
    public const sbyte _PERCENT = 100;
    public const byte NONE_ID = 0;
    public const byte ALLOW_TEST_ID = 1 << 0;
    public const byte PI_ID = 1 << 1;
    public const byte TABLE_ID = 1 << 2;
    public const byte _PERCENT_ID = 1 << 3;
    public const byte ALL_ID = 0xf;

    public enum COLORS {
        BLUE,
        GREEN, // green
        RED,
    }
}

public static class NODE {
    public const string BORDER = "border";

    public enum COLORS {
        RED,
        GREEN, // green
        BLUE,
    }
    public const string COLORS_RED_STR = "RED";
    public const string COLORS_GREEN_STR = "GREEN";
    public const string COLORS_BLUE_STR = "BLUE";
}

public static class QUICK {
    public const string ITEM = "item";
}

public static class NODE {
}

public static class CSS3 {
    public const string X_WEBKIT_AIRPLAY = "x-webkit-airplay";
    public const string _WEBKIT_TEXT_ZOOM = "-webkit-text-zoom";
    public const string _WEBKIT_BACKDROP_FILTER = "-webkit-backdrop-filter";
    public const string _WEBKIT_BORDER_HORIZONTAL_SPACING = "-webkit-border-horizontal-spacing";
    public const string _WEBKIT_BORDER_VERTICAL_SPACING = "-webkit-border-vertical-spacing";
    public const string _WEBKIT_BOX_ALIGN = "-webkit-box-align";
    public const byte NONE_ID = 0;
    public const byte X_WEBKIT_AIRPLAY_ID = 1 << 0;
    public const byte _WEBKIT_TEXT_ZOOM_ID = 1 << 1;
    public const byte _WEBKIT_BACKDROP_FILTER_ID = 1 << 2;
    public const byte _WEBKIT_BORDER_HORIZONTAL_SPACING_ID = 1 << 3;
    public const byte _WEBKIT_BORDER_VERTICAL_SPACING_ID = 1 << 4;
    public const byte _WEBKIT_BOX_ALIGN_ID = 1 << 5;
    public const byte ALL_ID = 0x3f;
}