// This file is generated by ConstMaker, DON'T MODIFY.

/**
 *this is a test
 */
const String table = "table"; // hello word
const String allowTest = "at";
const int percent = -100;

/** pi */
const double pi = 3.14159;

/**
 * colors
 */
enum mColors {
    kBlueDef,
    kGreenDef,
    kRedDef,
}

const String mColorsKBlueStr = "blue";
const String mColorsKGreenStr = "green";
const String mColorsKRedStr = "red";

//*********************************************
final Map<String, mColors> gStrMapMColors = {
    mColorsKBlueStr: mColors.kBlueDef,
    mColorsKGreenStr: mColors.kGreenDef,
    mColorsKRedStr: mColors.kRedDef,
};

mColors? mColorsFromString(String str) {
    return gStrMapMColors[str];
}

//*********************************************
final Map<mColors, String> gMColorsMapStr = {
    mColors.kBlueDef: mColorsKBlueStr,
    mColors.kGreenDef: mColorsKGreenStr,
    mColors.kRedDef: mColorsKRedStr,
};

String? stringFromMColors(mColors name) {
    return gMColorsMapStr[name];
}

class node {
    static const String htmlBlockId = "Block";
    static const String htmlTableId = "Table";
}

class item {
    static const String allowTest = "at";
    static const double pi = 3.14159;
    static const String table = "table";
    static const int Percent = 100;
    static const int noneId = 0;
    static const int allowTestId = 1 << 0;
    static const int piId = 1 << 1;
    static const int tableId = 1 << 2;
    static const int PercentId = 1 << 3;
    static const int allId = 0xf;
}

enum itemColors {
    blue,
    green, // green
    red,
}

class itemNode {
    static const String border = "border";
}

enum itemNodeColors {
    red,
    green, // green
    blue,
}

const String itemNodeColorsRedStr = "RED";
const String itemNodeColorsGreenStr = "GREEN";
const String itemNodeColorsBlueStr = "BLUE";

class itemNodeQuick {
    static const String item = "item";
}

class itemNodeQuickNode {
}

class css3 {
    static const String xWebkitAirplay = "x-webkit-airplay";
    static const String WebkitTextZoom = "-webkit-text-zoom";
    static const String WebkitBackdropFilter = "-webkit-backdrop-filter";
    static const String WebkitBorderHorizontalSpacing = "-webkit-border-horizontal-spacing";
    static const String WebkitBorderVerticalSpacing = "-webkit-border-vertical-spacing";
    static const String WebkitBoxAlign = "-webkit-box-align";
    static const int noneId = 0;
    static const int xWebkitAirplayId = 1 << 0;
    static const int WebkitTextZoomId = 1 << 1;
    static const int WebkitBackdropFilterId = 1 << 2;
    static const int WebkitBorderHorizontalSpacingId = 1 << 3;
    static const int WebkitBorderVerticalSpacingId = 1 << 4;
    static const int WebkitBoxAlignId = 1 << 5;
    static const int allId = 0x3f;
}