// This file is generated by ConstMaker, DON'T MODIFY.

#ifndef CONSTMAKER_GENERATED_TEST1_H
#define CONSTMAKER_GENERATED_TEST1_H

#include <stdint.h>

/**
 *this is a test
 */
NSString *const TABLE = @"table"; // hello word
NSString *const ALLOW_TEST = @"at";
const int8_t PERCENT = -100;

/** pi */
const float PI = 3.14159;

/**
 * colors
 */
typedef NS_ENUM(uint16_t, COLORS) {
    K_NONE_DEF = 0,
    K_BLUE_DEF = 1 << 0,
    K_GREEN_DEF = 1 << 1,
    K_RED_DEF = 1 << 2,
    K_ALL_DEF = 0x7
};
NSString *const COLORS_K_NONE_DEF_STR = @"NONE";
NSString *const COLORS_K_BLUE_DEF_STR = @"blue";
NSString *const COLORS_K_GREEN_DEF_STR = @"green";
NSString *const COLORS_K_RED_DEF_STR = @"red";
NSString *const COLORS_K_ALL_DEF_STR = @"ALL";

// namespace NODE
NSString *const NODE_HTML_BLOCK_ID = @"Block";
NSString *const NODE_HTML_TABLE_ID = @"Table";

// namespace ITEM
NSString *const ITEM_ALLOW_TEST = @"at";
const float ITEM_PI = 3.14159;
NSString *const ITEM_TABLE = @"table";
const int8_t ITEM__PERCENT = 100;
const uint8_t ITEM_NONE_ID_ID = 0;
const uint8_t ITEM_ALLOW_TEST_ID_ID = 1 << 0;
const uint8_t ITEM_PI_ID_ID = 1 << 1;
const uint8_t ITEM_TABLE_ID_ID = 1 << 2;
const uint8_t ITEM__PERCENT_ID_ID = 1 << 3;
const uint8_t ITEM_ALL_ID_ID = 0xf;

typedef NS_ENUM(uint8_t, ITEM_COLORS) {
    BLUE,
    GREEN, // green
    RED
};

// namespace ITEM_NODE
NSString *const ITEM_NODE_BORDER = @"border";

typedef NS_ENUM(uint8_t, ITEM_NODE_COLORS) {
    RED,
    GREEN, // green
    BLUE
};
NSString *const ITEM_NODE_COLORS_RED_STR = @"RED";
NSString *const ITEM_NODE_COLORS_GREEN_STR = @"GREEN";
NSString *const ITEM_NODE_COLORS_BLUE_STR = @"BLUE";

// namespace ITEM_NODE_QUICK
NSString *const ITEM_NODE_QUICK_ITEM = @"item";

// namespace ITEM_NODE_QUICK_NODE

// namespace CSS3
NSString *const CSS3_X_WEBKIT_AIRPLAY = @"x-webkit-airplay";
NSString *const CSS3__WEBKIT_TEXT_ZOOM = @"-webkit-text-zoom";
NSString *const CSS3__WEBKIT_BACKDROP_FILTER = @"-webkit-backdrop-filter";
NSString *const CSS3__WEBKIT_BORDER_HORIZONTAL_SPACING = @"-webkit-border-horizontal-spacing";
NSString *const CSS3__WEBKIT_BORDER_VERTICAL_SPACING = @"-webkit-border-vertical-spacing";
NSString *const CSS3__WEBKIT_BOX_ALIGN = @"-webkit-box-align";
const uint8_t CSS3_NONE_ID_ID = 0;
const uint8_t CSS3_X_WEBKIT_AIRPLAY_ID_ID = 1 << 0;
const uint8_t CSS3__WEBKIT_TEXT_ZOOM_ID_ID = 1 << 1;
const uint8_t CSS3__WEBKIT_BACKDROP_FILTER_ID_ID = 1 << 2;
const uint8_t CSS3__WEBKIT_BORDER_HORIZONTAL_SPACING_ID_ID = 1 << 3;
const uint8_t CSS3__WEBKIT_BORDER_VERTICAL_SPACING_ID_ID = 1 << 4;
const uint8_t CSS3__WEBKIT_BOX_ALIGN_ID_ID = 1 << 5;
const uint8_t CSS3_ALL_ID_ID = 0x3f;

#endif // CONSTMAKER_GENERATED_TEST1_H
