// This file is generated by ConstMaker, DON'T MODIFY.

/**
 *this is a test
 */
const table = "table"; // hello word
const allowTest = "at";
const percent = -100;

/** pi */
const pi = 3.14159;

/**
 * colors
 */
enum mColors: int {
    case kBlueDef;
    case kGreenDef;
    case kRedDef;
}
const mColorsKBlueStr = "blue";
const mColorsKGreenStr = "green";
const mColorsKRedStr = "red";

namespace node {
    const htmlBlockId = "Block";
    const htmlTableId = "Table";
}

namespace item {
    const allowTest = "at";
    const pi = 3.14159;
    const table = "table";
    const Percent = 100;
    const noneId = 0;
    const allowTestId = 1 << 0;
    const piId = 1 << 1;
    const tableId = 1 << 2;
    const PercentId = 1 << 3;
    const allId = 0xf;

    enum colors: int {
        case blue;
        case green; // green
        case red;
    }
}

namespace itemNode {
    const border = "border";

    enum colors: int {
        case red;
        case green; // green
        case blue;
    }
    const colorsRedStr = "RED";
    const colorsGreenStr = "GREEN";
    const colorsBlueStr = "BLUE";
}

namespace itemNodeQuick {
    const item = "item";
}

namespace itemNodeQuickNode {
}

namespace css3 {
    const xWebkitAirplay = "x-webkit-airplay";
    const WebkitTextZoom = "-webkit-text-zoom";
    const WebkitBackdropFilter = "-webkit-backdrop-filter";
    const WebkitBorderHorizontalSpacing = "-webkit-border-horizontal-spacing";
    const WebkitBorderVerticalSpacing = "-webkit-border-vertical-spacing";
    const WebkitBoxAlign = "-webkit-box-align";
    const noneId = 0;
    const xWebkitAirplayId = 1 << 0;
    const WebkitTextZoomId = 1 << 1;
    const WebkitBackdropFilterId = 1 << 2;
    const WebkitBorderHorizontalSpacingId = 1 << 3;
    const WebkitBorderVerticalSpacingId = 1 << 4;
    const WebkitBoxAlignId = 1 << 5;
    const allId = 0x3f;
}