(* This file is generated by ConstMaker, DON'T MODIFY. *)

(* 
 this is a test
 *)
const TABLE: String = "table"; (* hello word *)
const ALLOW_TEST: String = "at";
const PERCENT: Shortint = -100;
(* pi *)
const PI: Real = 3.14159;

(* 
 colors
 *)
type COLORS = (
    K_NONE_DEF,
    K_BLUE_DEF,
    K_GREEN_DEF,
    K_RED_DEF,
    K_ALL_DEF
);
const COLORS_K_NONE_DEF_STR: String = "NONE";
const COLORS_K_BLUE_DEF_STR: String = "blue";
const COLORS_K_GREEN_DEF_STR: String = "green";
const COLORS_K_RED_DEF_STR: String = "red";
const COLORS_K_ALL_DEF_STR: String = "ALL";

type
    NODE = class
        const HTML_BLOCK_ID: String = "Block";
        const HTML_TABLE_ID: String = "Table";
    end;

type
    ITEM = class
        const ALLOW_TEST: String = "at";
        const PI: Real = 3.14159;
        const TABLE: String = "table";
        const _PERCENT: Shortint = 100;
        const NONE_ID: Byte = 0;
        const ALLOW_TEST_ID: Byte = 1 << 0;
        const PI_ID: Byte = 1 << 1;
        const TABLE_ID: Byte = 1 << 2;
        const _PERCENT_ID: Byte = 1 << 3;
        const ALL_ID: Byte = 0xf;

        type COLORS = (
            BLUE,
            GREEN, (* green *)
            RED
        );

        type
            NODE = class
                const BORDER: String = "border";

                type COLORS = (
                    RED,
                    GREEN, (* green *)
                    BLUE
                );
                const COLORS_RED_STR: String = "RED";
                const COLORS_GREEN_STR: String = "GREEN";
                const COLORS_BLUE_STR: String = "BLUE";

                type
                    QUICK = class
                        const ITEM: String = "item";

                        type
                            NODE = class
                            end;
                    end;
            end;
    end;

type
    CSS3 = class
        const X_WEBKIT_AIRPLAY: String = "x-webkit-airplay";
        const _WEBKIT_TEXT_ZOOM: String = "-webkit-text-zoom";
        const _WEBKIT_BACKDROP_FILTER: String = "-webkit-backdrop-filter";
        const _WEBKIT_BORDER_HORIZONTAL_SPACING: String = "-webkit-border-horizontal-spacing";
        const _WEBKIT_BORDER_VERTICAL_SPACING: String = "-webkit-border-vertical-spacing";
        const _WEBKIT_BOX_ALIGN: String = "-webkit-box-align";
        const NONE_ID: Byte = 0;
        const X_WEBKIT_AIRPLAY_ID: Byte = 1 << 0;
        const _WEBKIT_TEXT_ZOOM_ID: Byte = 1 << 1;
        const _WEBKIT_BACKDROP_FILTER_ID: Byte = 1 << 2;
        const _WEBKIT_BORDER_HORIZONTAL_SPACING_ID: Byte = 1 << 3;
        const _WEBKIT_BORDER_VERTICAL_SPACING_ID: Byte = 1 << 4;
        const _WEBKIT_BOX_ALIGN_ID: Byte = 1 << 5;
        const ALL_ID: Byte = 0x3f;
    end;