# This file is generated by ConstMaker, DON'T MODIFY.

# 
# this is a test
# 
table = "table" # hello word
allowTest = "at"
percent = -100
# pi 
pi = 3.14159

# 
# colors
# 
module mColors
    kBlueDef = 0
    kGreenDef = 1
    kRedDef = 2
    mColorsKBlueStr = "blue"
    mColorsKGreenStr = "green"
    mColorsKRedStr = "red"
end

module node
    htmlBlockId = "Block"
    htmlTableId = "Table"
end

module item
    allowTest = "at"
    pi = 3.14159
    table = "table"
    Percent = 100
    noneId = 0
    allowTestId = 1 << 0
    piId = 1 << 1
    tableId = 1 << 2
    PercentId = 1 << 3
    allId = 0xf

    module colors
        blue = 0
        green = 1 # green
        red = 2
    end
end

module itemNode
    border = "border"

    module colors
        red = 0
        green = 1 # green
        blue = 2
        colorsRedStr = "RED"
        colorsGreenStr = "GREEN"
        colorsBlueStr = "BLUE"
    end
end

module itemNodeQuick
    item = "item"
end

module itemNodeQuickNode
end

module css3
    xWebkitAirplay = "x-webkit-airplay"
    WebkitTextZoom = "-webkit-text-zoom"
    WebkitBackdropFilter = "-webkit-backdrop-filter"
    WebkitBorderHorizontalSpacing = "-webkit-border-horizontal-spacing"
    WebkitBorderVerticalSpacing = "-webkit-border-vertical-spacing"
    WebkitBoxAlign = "-webkit-box-align"
    noneId = 0
    xWebkitAirplayId = 1 << 0
    WebkitTextZoomId = 1 << 1
    WebkitBackdropFilterId = 1 << 2
    WebkitBorderHorizontalSpacingId = 1 << 3
    WebkitBorderVerticalSpacingId = 1 << 4
    WebkitBoxAlignId = 1 << 5
    allId = 0x3f
end