// This file is generated by ConstMaker, DON'T MODIFY.

public static class test1 {
    /**
     *this is a test
     */
    public const string table = "table"; // hello word
    public const string allowTest = "at";
    public const sbyte percent = -100;

    /** pi */
    public const float pi = 3.14159f;

    /**
     * colors
     */
    public enum mColors {
        kBlueDef,
        kGreenDef,
        kRedDef,
    }
    public const string mColorsKBlueStr = "blue";
    public const string mColorsKGreenStr = "green";
    public const string mColorsKRedStr = "red";
}

public static class node {
    public const string htmlBlockId = "Block";
    public const string htmlTableId = "Table";
}

public static class item {
    public const string allowTest = "at";
    public const float pi = 3.14159f;
    public const string table = "table";
    public const sbyte Percent = 100;
    public const byte noneId = 0;
    public const byte allowTestId = 1 << 0;
    public const byte piId = 1 << 1;
    public const byte tableId = 1 << 2;
    public const byte PercentId = 1 << 3;
    public const byte allId = 0xf;

    public enum colors {
        blue,
        green, // green
        red,
    }
}

public static class node {
    public const string border = "border";

    public enum colors {
        red,
        green, // green
        blue,
    }
    public const string colorsRedStr = "RED";
    public const string colorsGreenStr = "GREEN";
    public const string colorsBlueStr = "BLUE";
}

public static class quick {
    public const string item = "item";
}

public static class node {
}

public static class css3 {
    public const string xWebkitAirplay = "x-webkit-airplay";
    public const string WebkitTextZoom = "-webkit-text-zoom";
    public const string WebkitBackdropFilter = "-webkit-backdrop-filter";
    public const string WebkitBorderHorizontalSpacing = "-webkit-border-horizontal-spacing";
    public const string WebkitBorderVerticalSpacing = "-webkit-border-vertical-spacing";
    public const string WebkitBoxAlign = "-webkit-box-align";
    public const byte noneId = 0;
    public const byte xWebkitAirplayId = 1 << 0;
    public const byte WebkitTextZoomId = 1 << 1;
    public const byte WebkitBackdropFilterId = 1 << 2;
    public const byte WebkitBorderHorizontalSpacingId = 1 << 3;
    public const byte WebkitBorderVerticalSpacingId = 1 << 4;
    public const byte WebkitBoxAlignId = 1 << 5;
    public const byte allId = 0x3f;
}