// This file is generated by ConstMaker, DON'T MODIFY.

#ifndef CONSTMAKER_GENERATED_TEST1_H
#define CONSTMAKER_GENERATED_TEST1_H

#include <stdint.h>

/**
 *this is a test
 */
const char* TABLE = "table"; // hello word
const char* ALLOW_TEST = "at";
const int8_t PERCENT = -100;

/** pi */
const float PI = 3.14159;

/**
 * colors
 */
enum class COLORS : uint16_t {
    K_NONE_DEF = 0,
    K_BLUE_DEF = 1 << 0,
    K_GREEN_DEF = 1 << 1,
    K_RED_DEF = 1 << 2,
    K_ALL_DEF = 0x7,
};
const char* COLORS_K_NONE_DEF_STR = "NONE";
const char* COLORS_K_BLUE_DEF_STR = "blue";
const char* COLORS_K_GREEN_DEF_STR = "green";
const char* COLORS_K_RED_DEF_STR = "red";
const char* COLORS_K_ALL_DEF_STR = "ALL";

namespace NODE {
    const char* HTML_BLOCK_ID = "Block";
    const char* HTML_TABLE_ID = "Table";
};

namespace ITEM {
    const char* ALLOW_TEST = "at";
    const float PI = 3.14159;
    const char* TABLE = "table";
    const int8_t _PERCENT = 100;
    const uint8_t NONE_ID = 0;
    const uint8_t ALLOW_TEST_ID = 1 << 0;
    const uint8_t PI_ID = 1 << 1;
    const uint8_t TABLE_ID = 1 << 2;
    const uint8_t _PERCENT_ID = 1 << 3;
    const uint8_t ALL_ID = 0xf;

    enum class COLORS : uint8_t {
        BLUE,
        GREEN, // green
        RED,
    };
};

namespace ITEM_NODE {
    const char* BORDER = "border";

    enum class COLORS : uint8_t {
        RED,
        GREEN, // green
        BLUE,
    };
    const char* COLORS_RED_STR = "RED";
    const char* COLORS_GREEN_STR = "GREEN";
    const char* COLORS_BLUE_STR = "BLUE";
};

namespace ITEM_NODE_QUICK {
    const char* ITEM = "item";
};

namespace ITEM_NODE_QUICK_NODE {
};

namespace CSS3 {
    const char* X_WEBKIT_AIRPLAY = "x-webkit-airplay";
    const char* _WEBKIT_TEXT_ZOOM = "-webkit-text-zoom";
    const char* _WEBKIT_BACKDROP_FILTER = "-webkit-backdrop-filter";
    const char* _WEBKIT_BORDER_HORIZONTAL_SPACING = "-webkit-border-horizontal-spacing";
    const char* _WEBKIT_BORDER_VERTICAL_SPACING = "-webkit-border-vertical-spacing";
    const char* _WEBKIT_BOX_ALIGN = "-webkit-box-align";
    const uint8_t NONE_ID = 0;
    const uint8_t X_WEBKIT_AIRPLAY_ID = 1 << 0;
    const uint8_t _WEBKIT_TEXT_ZOOM_ID = 1 << 1;
    const uint8_t _WEBKIT_BACKDROP_FILTER_ID = 1 << 2;
    const uint8_t _WEBKIT_BORDER_HORIZONTAL_SPACING_ID = 1 << 3;
    const uint8_t _WEBKIT_BORDER_VERTICAL_SPACING_ID = 1 << 4;
    const uint8_t _WEBKIT_BOX_ALIGN_ID = 1 << 5;
    const uint8_t ALL_ID = 0x3f;
};

#endif // CONSTMAKER_GENERATED_TEST1_H
