// This file is generated by ConstMaker, DON'T MODIFY.

package consts

const (
    /**
     *this is a test
     */
    TABLE string = "table" // hello word
    ALLOW_TEST string = "at"
    PERCENT int8 = -100

    /** pi */
    PI float32 = 3.14159
)

/**
 * colors
 */
// enum COLORS
const (
    COLORS_K_NONE_DEF uint16 = 0
    COLORS_K_BLUE_DEF uint16 = 1 << 0
    COLORS_K_GREEN_DEF uint16 = 1 << 1
    COLORS_K_RED_DEF uint16 = 1 << 2
    COLORS_K_ALL_DEF uint16 = 0x7
    COLORS_K_NONE_DEF_STR string = "NONE";
    COLORS_K_BLUE_DEF_STR string = "blue";
    COLORS_K_GREEN_DEF_STR string = "green";
    COLORS_K_RED_DEF_STR string = "red";
    COLORS_K_ALL_DEF_STR string = "ALL";
)

// namespace NODE
const (
    NODE_HTML_BLOCK_ID string = "Block"
    NODE_HTML_TABLE_ID string = "Table"
)

// namespace ITEM
const (
    ITEM_ALLOW_TEST string = "at"
    ITEM_PI float32 = 3.14159
    ITEM_TABLE string = "table"
    ITEM__PERCENT int8 = 100
    ITEM_NONE_ID uint8 = 0;
    ITEM_ALLOW_TEST_ID uint8 = 1 << 0;
    ITEM_PI_ID uint8 = 1 << 1;
    ITEM_TABLE_ID uint8 = 1 << 2;
    ITEM__PERCENT_ID uint8 = 1 << 3;
    ITEM_ALL_ID uint8 = 0xf;
)

// enum ITEM_COLORS
const (
    ITEM_COLORS_BLUE uint8 = 0
    ITEM_COLORS_GREEN uint8 = 1 // green
    ITEM_COLORS_RED uint8 = 2
)

// namespace ITEM_NODE
const (
    ITEM_NODE_BORDER string = "border"
)

// enum ITEM_NODE_COLORS
const (
    ITEM_NODE_COLORS_RED uint8 = 0
    ITEM_NODE_COLORS_GREEN uint8 = 1 // green
    ITEM_NODE_COLORS_BLUE uint8 = 2
    ITEM_NODE_COLORS_RED_STR string = "RED";
    ITEM_NODE_COLORS_GREEN_STR string = "GREEN";
    ITEM_NODE_COLORS_BLUE_STR string = "BLUE";
)

// namespace ITEM_NODE_QUICK
const (
    ITEM_NODE_QUICK_ITEM string = "item"
)

// namespace ITEM_NODE_QUICK_NODE

// namespace CSS3
const (
    CSS3_X_WEBKIT_AIRPLAY string = "x-webkit-airplay"
    CSS3__WEBKIT_TEXT_ZOOM string = "-webkit-text-zoom"
    CSS3__WEBKIT_BACKDROP_FILTER string = "-webkit-backdrop-filter"
    CSS3__WEBKIT_BORDER_HORIZONTAL_SPACING string = "-webkit-border-horizontal-spacing"
    CSS3__WEBKIT_BORDER_VERTICAL_SPACING string = "-webkit-border-vertical-spacing"
    CSS3__WEBKIT_BOX_ALIGN string = "-webkit-box-align"
    CSS3_NONE_ID uint8 = 0;
    CSS3_X_WEBKIT_AIRPLAY_ID uint8 = 1 << 0;
    CSS3__WEBKIT_TEXT_ZOOM_ID uint8 = 1 << 1;
    CSS3__WEBKIT_BACKDROP_FILTER_ID uint8 = 1 << 2;
    CSS3__WEBKIT_BORDER_HORIZONTAL_SPACING_ID uint8 = 1 << 3;
    CSS3__WEBKIT_BORDER_VERTICAL_SPACING_ID uint8 = 1 << 4;
    CSS3__WEBKIT_BOX_ALIGN_ID uint8 = 1 << 5;
    CSS3_ALL_ID uint8 = 0x3f;
)