// This file is generated by ConstMaker, DON'T MODIFY.

#ifndef CONSTMAKER_GENERATED_TEST1_H
#define CONSTMAKER_GENERATED_TEST1_H

#include <stdint.h>

/**
 *this is a test
 */
NSString *const Table = @"table"; // hello word
NSString *const AllowTest = @"at";
const int8_t Percent = -100;

/** pi */
const float Pi = 3.14159;

/**
 * colors
 */
typedef NS_ENUM(uint16_t, Colors) {
    KNoneDef = 0,
    KBlueDef = (1 << 0),
    KGreenDef = (1 << 1),
    KRedDef = (1 << 2),
    KAllDef = 0x7
};
NSString *const ColorsKNoneDefStr = @"KNoneDef";
NSString *const ColorsKBlueDefStr = @"KBlueDef";
NSString *const ColorsKGreenDefStr = @"KGreenDef";
NSString *const ColorsKRedDefStr = @"KRedDef";
NSString *const ColorsKAllDefStr = @"KAllDef";

// namespace Node
NSString *const NodeHtmlBlockId = @"Block";
NSString *const NodeHtmlTableId = @"Table";

// namespace Item
NSString *const ItemAllowTest = @"at";
const float ItemPi = 3.14159;
NSString *const ItemTable = @"table";
const int8_t ItemPercent = 100;
const uint8_t ItemNoneId_ID = 0;
const uint8_t ItemAllowTestId_ID = (1 << 0);
const uint8_t ItemPiId_ID = (1 << 1);
const uint8_t ItemTableId_ID = (1 << 2);
const uint8_t ItemPercentId_ID = (1 << 3);
const uint8_t ItemAllId_ID = 0xf;

typedef NS_ENUM(uint8_t, ItemColors) {
    Blue,
    Green, // green
    Red
};

// namespace ItemNode
NSString *const ItemNodeBorder = @"border";

typedef NS_ENUM(uint8_t, ItemNodeColors) {
    Red,
    Green, // green
    Blue
};
NSString *const ItemNodeColorsRedStr = @"Red";
NSString *const ItemNodeColorsGreenStr = @"Green";
NSString *const ItemNodeColorsBlueStr = @"Blue";

// namespace ItemNodeQuick
NSString *const ItemNodeQuickItem = @"item";

// namespace ItemNodeQuickNode

// namespace Css3
NSString *const Css3XWebkitAirplay = @"x-webkit-airplay";
NSString *const Css3WebkitTextZoom = @"-webkit-text-zoom";
NSString *const Css3WebkitBackdropFilter = @"-webkit-backdrop-filter";
NSString *const Css3WebkitBorderHorizontalSpacing = @"-webkit-border-horizontal-spacing";
NSString *const Css3WebkitBorderVerticalSpacing = @"-webkit-border-vertical-spacing";
NSString *const Css3WebkitBoxAlign = @"-webkit-box-align";
const uint8_t Css3NoneId_ID = 0;
const uint8_t Css3XWebkitAirplayId_ID = (1 << 0);
const uint8_t Css3WebkitTextZoomId_ID = (1 << 1);
const uint8_t Css3WebkitBackdropFilterId_ID = (1 << 2);
const uint8_t Css3WebkitBorderHorizontalSpacingId_ID = (1 << 3);
const uint8_t Css3WebkitBorderVerticalSpacingId_ID = (1 << 4);
const uint8_t Css3WebkitBoxAlignId_ID = (1 << 5);
const uint8_t Css3AllId_ID = 0x3f;

#endif // CONSTMAKER_GENERATED_TEST1_H
