(* This file is generated by ConstMaker, DON'T MODIFY. *)

(* 
 this is a test
 *)
const table: String = "table"; (* hello word *)
const allowTest: String = "at";
const percent: Shortint = -100;
(* pi *)
const pi: Real = 3.14159;

(* 
 colors
 *)
type mColors = (
    kBlueDef,
    kGreenDef,
    kRedDef
);
const mColorsKBlueStr: String = "blue";
const mColorsKGreenStr: String = "green";
const mColorsKRedStr: String = "red";

type
    node = class
        const htmlBlockId: String = "Block";
        const htmlTableId: String = "Table";
    end;

type
    item = class
        const allowTest: String = "at";
        const pi: Real = 3.14159;
        const table: String = "table";
        const Percent: Shortint = 100;
        const noneId: Byte = 0;
        const allowTestId: Byte = 1 << 0;
        const piId: Byte = 1 << 1;
        const tableId: Byte = 1 << 2;
        const PercentId: Byte = 1 << 3;
        const allId: Byte = 0xf;

        type colors = (
            blue,
            green, (* green *)
            red
        );

        type
            node = class
                const border: String = "border";

                type colors = (
                    red,
                    green, (* green *)
                    blue
                );
                const colorsRedStr: String = "RED";
                const colorsGreenStr: String = "GREEN";
                const colorsBlueStr: String = "BLUE";

                type
                    quick = class
                        const item: String = "item";

                        type
                            node = class
                            end;
                    end;
            end;
    end;

type
    css3 = class
        const xWebkitAirplay: String = "x-webkit-airplay";
        const WebkitTextZoom: String = "-webkit-text-zoom";
        const WebkitBackdropFilter: String = "-webkit-backdrop-filter";
        const WebkitBorderHorizontalSpacing: String = "-webkit-border-horizontal-spacing";
        const WebkitBorderVerticalSpacing: String = "-webkit-border-vertical-spacing";
        const WebkitBoxAlign: String = "-webkit-box-align";
        const noneId: Byte = 0;
        const xWebkitAirplayId: Byte = 1 << 0;
        const WebkitTextZoomId: Byte = 1 << 1;
        const WebkitBackdropFilterId: Byte = 1 << 2;
        const WebkitBorderHorizontalSpacingId: Byte = 1 << 3;
        const WebkitBorderVerticalSpacingId: Byte = 1 << 4;
        const WebkitBoxAlignId: Byte = 1 << 5;
        const allId: Byte = 0x3f;
    end;