(* This file is generated by ConstMaker, DON'T MODIFY. *)

(* 
 this is a test
 *)
const Table: String = "table"; (* hello word *)
const AllowTest: String = "at";
const Percent: Shortint = -100;
(* pi *)
const Pi: Real = 3.14159;

(* 
 colors
 *)
type Colors = (
    KNoneDef,
    KBlueDef,
    KGreenDef,
    KRedDef,
    KAllDef
);
const ColorsKNoneDefStr: String = "KNoneDef";
const ColorsKBlueDefStr: String = "KBlueDef";
const ColorsKGreenDefStr: String = "KGreenDef";
const ColorsKRedDefStr: String = "KRedDef";
const ColorsKAllDefStr: String = "KAllDef";

type
    Node = class
        const HtmlBlockId: String = "Block";
        const HtmlTableId: String = "Table";
    end;

type
    Item = class
        const AllowTest: String = "at";
        const Pi: Real = 3.14159;
        const Table: String = "table";
        const Percent: Shortint = 100;
        const NoneId: Byte = 0;
        const AllowTestId: Byte = (1 << 0);
        const PiId: Byte = (1 << 1);
        const TableId: Byte = (1 << 2);
        const PercentId: Byte = (1 << 3);
        const AllId: Byte = 0xf;

        type Colors = (
            Blue,
            Green, (* green *)
            Red
        );

        type
            Node = class
                const Border: String = "border";

                type Colors = (
                    Red,
                    Green, (* green *)
                    Blue
                );
                const ColorsRedStr: String = "Red";
                const ColorsGreenStr: String = "Green";
                const ColorsBlueStr: String = "Blue";

                type
                    Quick = class
                        const Item: String = "item";

                        type
                            Node = class
                            end;
                    end;
            end;
    end;

type
    Css3 = class
        const XWebkitAirplay: String = "x-webkit-airplay";
        const WebkitTextZoom: String = "-webkit-text-zoom";
        const WebkitBackdropFilter: String = "-webkit-backdrop-filter";
        const WebkitBorderHorizontalSpacing: String = "-webkit-border-horizontal-spacing";
        const WebkitBorderVerticalSpacing: String = "-webkit-border-vertical-spacing";
        const WebkitBoxAlign: String = "-webkit-box-align";
        const NoneId: Byte = 0;
        const XWebkitAirplayId: Byte = (1 << 0);
        const WebkitTextZoomId: Byte = (1 << 1);
        const WebkitBackdropFilterId: Byte = (1 << 2);
        const WebkitBorderHorizontalSpacingId: Byte = (1 << 3);
        const WebkitBorderVerticalSpacingId: Byte = (1 << 4);
        const WebkitBoxAlignId: Byte = (1 << 5);
        const AllId: Byte = 0x3f;
    end;