// This file is generated by ConstMaker, DON'T MODIFY.

/**
 *this is a test
 */
const TABLE = "table"; // hello word
const ALLOW_TEST = "at";
const PERCENT = -100;

/** pi */
const PI = 3.14159;

/**
 * colors
 */
enum COLORS: int {
    case K_NONE_DEF = 0;
    case K_BLUE_DEF = 1 << 0;
    case K_GREEN_DEF = 1 << 1;
    case K_RED_DEF = 1 << 2;
    case K_ALL_DEF = 0x7;
}
const COLORS_K_NONE_DEF_STR = "NONE";
const COLORS_K_BLUE_DEF_STR = "blue";
const COLORS_K_GREEN_DEF_STR = "green";
const COLORS_K_RED_DEF_STR = "red";
const COLORS_K_ALL_DEF_STR = "ALL";

namespace NODE {
    const HTML_BLOCK_ID = "Block";
    const HTML_TABLE_ID = "Table";
}

namespace ITEM {
    const ALLOW_TEST = "at";
    const PI = 3.14159;
    const TABLE = "table";
    const _PERCENT = 100;
    const NONE_ID = 0;
    const ALLOW_TEST_ID = 1 << 0;
    const PI_ID = 1 << 1;
    const TABLE_ID = 1 << 2;
    const _PERCENT_ID = 1 << 3;
    const ALL_ID = 0xf;

    enum COLORS: int {
        case BLUE;
        case GREEN; // green
        case RED;
    }
}

namespace ITEM_NODE {
    const BORDER = "border";

    enum COLORS: int {
        case RED;
        case GREEN; // green
        case BLUE;
    }
    const COLORS_RED_STR = "RED";
    const COLORS_GREEN_STR = "GREEN";
    const COLORS_BLUE_STR = "BLUE";
}

namespace ITEM_NODE_QUICK {
    const ITEM = "item";
}

namespace ITEM_NODE_QUICK_NODE {
}

namespace CSS3 {
    const X_WEBKIT_AIRPLAY = "x-webkit-airplay";
    const _WEBKIT_TEXT_ZOOM = "-webkit-text-zoom";
    const _WEBKIT_BACKDROP_FILTER = "-webkit-backdrop-filter";
    const _WEBKIT_BORDER_HORIZONTAL_SPACING = "-webkit-border-horizontal-spacing";
    const _WEBKIT_BORDER_VERTICAL_SPACING = "-webkit-border-vertical-spacing";
    const _WEBKIT_BOX_ALIGN = "-webkit-box-align";
    const NONE_ID = 0;
    const X_WEBKIT_AIRPLAY_ID = 1 << 0;
    const _WEBKIT_TEXT_ZOOM_ID = 1 << 1;
    const _WEBKIT_BACKDROP_FILTER_ID = 1 << 2;
    const _WEBKIT_BORDER_HORIZONTAL_SPACING_ID = 1 << 3;
    const _WEBKIT_BORDER_VERTICAL_SPACING_ID = 1 << 4;
    const _WEBKIT_BOX_ALIGN_ID = 1 << 5;
    const ALL_ID = 0x3f;
}