// This file is generated by ConstMaker, DON'T MODIFY.

#ifndef CONSTMAKER_GENERATED_TEST1_H
#define CONSTMAKER_GENERATED_TEST1_H

#include <stdint.h>

/**
 *this is a test
 */
const char* table = "table"; // hello word
const char* allowTest = "at";
const int8_t percent = -100;

/** pi */
const float pi = 3.14159;

/**
 * colors
 */
enum class mColors : uint16_t {
    kBlueDef,
    kGreenDef,
    kRedDef,
};
const char* mColorsKBlueStr = "blue";
const char* mColorsKGreenStr = "green";
const char* mColorsKRedStr = "red";

namespace node {
    const char* htmlBlockId = "Block";
    const char* htmlTableId = "Table";
};

namespace item {
    const char* allowTest = "at";
    const float pi = 3.14159;
    const char* table = "table";
    const int8_t Percent = 100;
    const uint8_t noneId = 0;
    const uint8_t allowTestId = 1 << 0;
    const uint8_t piId = 1 << 1;
    const uint8_t tableId = 1 << 2;
    const uint8_t PercentId = 1 << 3;
    const uint8_t allId = 0xf;

    enum class colors : uint8_t {
        blue,
        green, // green
        red,
    };
};

namespace itemNode {
    const char* border = "border";

    enum class colors : uint8_t {
        red,
        green, // green
        blue,
    };
    const char* colorsRedStr = "RED";
    const char* colorsGreenStr = "GREEN";
    const char* colorsBlueStr = "BLUE";
};

namespace itemNodeQuick {
    const char* item = "item";
};

namespace itemNodeQuickNode {
};

namespace css3 {
    const char* xWebkitAirplay = "x-webkit-airplay";
    const char* WebkitTextZoom = "-webkit-text-zoom";
    const char* WebkitBackdropFilter = "-webkit-backdrop-filter";
    const char* WebkitBorderHorizontalSpacing = "-webkit-border-horizontal-spacing";
    const char* WebkitBorderVerticalSpacing = "-webkit-border-vertical-spacing";
    const char* WebkitBoxAlign = "-webkit-box-align";
    const uint8_t noneId = 0;
    const uint8_t xWebkitAirplayId = 1 << 0;
    const uint8_t WebkitTextZoomId = 1 << 1;
    const uint8_t WebkitBackdropFilterId = 1 << 2;
    const uint8_t WebkitBorderHorizontalSpacingId = 1 << 3;
    const uint8_t WebkitBorderVerticalSpacingId = 1 << 4;
    const uint8_t WebkitBoxAlignId = 1 << 5;
    const uint8_t allId = 0x3f;
};

#endif // CONSTMAKER_GENERATED_TEST1_H
