# This file is generated by ConstMaker, DON'T MODIFY.

from enum import Enum

# 
# this is a test
# 
TABLE: str = "table" # hello word
ALLOW_TEST: str = "at"
PERCENT: int = -100
# pi 
PI: float = 3.14159

# 
# colors
# 
class COLORS(Enum):
    K_NONE_DEF = 0
    K_BLUE_DEF = 1 << 0
    K_GREEN_DEF = 1 << 1
    K_RED_DEF = 1 << 2
    K_ALL_DEF = 0x7

    K_NONE_DEF_STR: str = "NONE"
    K_BLUE_DEF_STR: str = "blue"
    K_GREEN_DEF_STR: str = "green"
    K_RED_DEF_STR: str = "red"
    K_ALL_DEF_STR: str = "ALL"

class NODE:
    HTML_BLOCK_ID: str = "Block"
    HTML_TABLE_ID: str = "Table"


class ITEM:
    ALLOW_TEST: str = "at"
    PI: float = 3.14159
    TABLE: str = "table"
    _PERCENT: int = 100
    NONE_ID: int = 0
    ALLOW_TEST_ID: int = 1 << 0
    PI_ID: int = 1 << 1
    TABLE_ID: int = 1 << 2
    _PERCENT_ID: int = 1 << 3
    ALL_ID: int = 0xf

    class COLORS(Enum):
        BLUE
        GREEN # green
        RED


class ITEM_NODE:
    BORDER: str = "border"

    class COLORS(Enum):
        RED
        GREEN # green
        BLUE

        RED_STR: str = "RED"
        GREEN_STR: str = "GREEN"
        BLUE_STR: str = "BLUE"


class ITEM_NODE_QUICK:
    ITEM: str = "item"


# namespace ITEM_NODE_Quick_NODE

class ITEM_CSS3:
    X_WEBKIT_AIRPLAY: str = "x-webkit-airplay"
    _WEBKIT_TEXT_ZOOM: str = "-webkit-text-zoom"
    _WEBKIT_BACKDROP_FILTER: str = "-webkit-backdrop-filter"
    _WEBKIT_BORDER_HORIZONTAL_SPACING: str = "-webkit-border-horizontal-spacing"
    _WEBKIT_BORDER_VERTICAL_SPACING: str = "-webkit-border-vertical-spacing"
    _WEBKIT_BOX_ALIGN: str = "-webkit-box-align"
    NONE_ID: int = 0
    X_WEBKIT_AIRPLAY_ID: int = 1 << 0
    _WEBKIT_TEXT_ZOOM_ID: int = 1 << 1
    _WEBKIT_BACKDROP_FILTER_ID: int = 1 << 2
    _WEBKIT_BORDER_HORIZONTAL_SPACING_ID: int = 1 << 3
    _WEBKIT_BORDER_VERTICAL_SPACING_ID: int = 1 << 4
    _WEBKIT_BOX_ALIGN_ID: int = 1 << 5
    ALL_ID: int = 0x3f
