// This file is generated by ConstMaker, DON'T MODIFY.

/**
 *this is a test
 */
const table = "table"; // hello word
const allowTest = "at";
const percent = -100;

/** pi */
const pi = 3.14159;

/**
 * colors
 */
const mColors = {
    kBlueDef: 0,
    kGreenDef: 1,
    kRedDef: 2,
};
const mColorsKBlueStr = "blue";
const mColorsKGreenStr = "green";
const mColorsKRedStr = "red";

const node = {
    Constants: Object.freeze({
        htmlBlockId: "Block",
        htmlTableId: "Table",
    })
};

const item = {
    Constants: Object.freeze({
        allowTest: "at",
        pi: 3.14159,
        table: "table",
        Percent: 100,
        noneId: 0,
        allowTestId: 1 << 0,
        piId: 1 << 1,
        tableId: 1 << 2,
        PercentId: 1 << 3,
        allId: 0xf,

        colors: Object.freeze({
            blue: 0,
            green: 1, // green
            red: 2,
        }),
    })
};

const itemNode = {
    Constants: Object.freeze({
        border: "border",

        colors: Object.freeze({
            red: 0,
            green: 1, // green
            blue: 2,
        }),
        colorsRedStr: "RED",
        colorsGreenStr: "GREEN",
        colorsBlueStr: "BLUE",
    })
};

const itemNodeQuick = {
    Constants: Object.freeze({
        item: "item",
    })
};

const itemNodeQuickNode = {
    Constants: Object.freeze({
    })
};

const css3 = {
    Constants: Object.freeze({
        xWebkitAirplay: "x-webkit-airplay",
        WebkitTextZoom: "-webkit-text-zoom",
        WebkitBackdropFilter: "-webkit-backdrop-filter",
        WebkitBorderHorizontalSpacing: "-webkit-border-horizontal-spacing",
        WebkitBorderVerticalSpacing: "-webkit-border-vertical-spacing",
        WebkitBoxAlign: "-webkit-box-align",
        noneId: 0,
        xWebkitAirplayId: 1 << 0,
        WebkitTextZoomId: 1 << 1,
        WebkitBackdropFilterId: 1 << 2,
        WebkitBorderHorizontalSpacingId: 1 << 3,
        WebkitBorderVerticalSpacingId: 1 << 4,
        WebkitBoxAlignId: 1 << 5,
        allId: 0x3f,
    })
};