// This file is generated by ConstMaker, DON'T MODIFY.

package consts;

interface test1 {
    /**
     *this is a test
     */
    public static final String TABLE = "table"; // hello word
    public static final String ALLOW_TEST = "at";
    public static final byte PERCENT = -100;

    /** pi */
    public static final float PI = 3.14159f;

    /**
     * colors
     */
    enum COLORS {
        K_NONE_DEF(0),
        K_BLUE_DEF(1 << 0),
        K_GREEN_DEF(1 << 1),
        K_RED_DEF(1 << 2),
        K_ALL_DEF(0x7);

        public static final String K_NONE_DEF_STR = "NONE";
        public static final String K_BLUE_DEF_STR = "blue";
        public static final String K_GREEN_DEF_STR = "green";
        public static final String K_RED_DEF_STR = "red";
        public static final String K_ALL_DEF_STR = "ALL";

        final int value;
        COLORS(int value) { this.value = value; }
    }

    interface NODE {
        public static final String HTML_BLOCK_ID = "Block";
        public static final String HTML_TABLE_ID = "Table";
    }

    interface ITEM {
        public static final String ALLOW_TEST = "at";
        public static final float PI = 3.14159f;
        public static final String TABLE = "table";
        public static final byte _PERCENT = 100;
        public static final byte NONE_ID = 0;
        public static final byte ALLOW_TEST_ID = 1 << 0;
        public static final byte PI_ID = 1 << 1;
        public static final byte TABLE_ID = 1 << 2;
        public static final byte _PERCENT_ID = 1 << 3;
        public static final byte ALL_ID = 0xf;

        enum COLORS {
            BLUE,
            GREEN, // green
            RED
        }

        interface NODE {
            public static final String BORDER = "border";

            enum COLORS {
                RED,
                GREEN, // green
                BLUE
            }
            public static final String COLORS_RED_STR = "RED";
            public static final String COLORS_GREEN_STR = "GREEN";
            public static final String COLORS_BLUE_STR = "BLUE";

            interface QUICK {
                public static final String ITEM = "item";

                // namespace NODE
            }
        }
    }

    interface CSS3 {
        public static final String X_WEBKIT_AIRPLAY = "x-webkit-airplay";
        public static final String _WEBKIT_TEXT_ZOOM = "-webkit-text-zoom";
        public static final String _WEBKIT_BACKDROP_FILTER = "-webkit-backdrop-filter";
        public static final String _WEBKIT_BORDER_HORIZONTAL_SPACING = "-webkit-border-horizontal-spacing";
        public static final String _WEBKIT_BORDER_VERTICAL_SPACING = "-webkit-border-vertical-spacing";
        public static final String _WEBKIT_BOX_ALIGN = "-webkit-box-align";
        public static final byte NONE_ID = 0;
        public static final byte X_WEBKIT_AIRPLAY_ID = 1 << 0;
        public static final byte _WEBKIT_TEXT_ZOOM_ID = 1 << 1;
        public static final byte _WEBKIT_BACKDROP_FILTER_ID = 1 << 2;
        public static final byte _WEBKIT_BORDER_HORIZONTAL_SPACING_ID = 1 << 3;
        public static final byte _WEBKIT_BORDER_VERTICAL_SPACING_ID = 1 << 4;
        public static final byte _WEBKIT_BOX_ALIGN_ID = 1 << 5;
        public static final byte ALL_ID = 0x3f;
    }
}