// This file is generated by ConstMaker, DON'T MODIFY.

/**
 *this is a test
 */
const val table: String = "table" // hello word
const val allowTest: String = "at"
const val percent: Byte = -100

/** pi */
const val pi: Float = 3.14159f

/**
 * colors
 */
enum class mColors(val value: UByte) {
    kBlueDef,
    kGreenDef,
    kRedDef
}
const val mColorsKBlueStr: String = "blue"
const val mColorsKGreenStr: String = "green"
const val mColorsKRedStr: String = "red"

object node {
    const val htmlBlockId: String = "Block"
    const val htmlTableId: String = "Table"
}

object item {
    const val allowTest: String = "at"
    const val pi: Float = 3.14159f
    const val table: String = "table"
    const val Percent: Byte = 100
    const val noneId: UByte = 0
    const val allowTestId: UByte = 1 << 0
    const val piId: UByte = 1 << 1
    const val tableId: UByte = 1 << 2
    const val PercentId: UByte = 1 << 3
    const val allId: UByte = 0xf

    enum class colors(val value: UByte) {
        blue,
        green, // green
        red
    }
}

object itemNode {
    const val border: String = "border"

    enum class colors(val value: UByte) {
        red,
        green, // green
        blue
    }
    const val colorsRedStr: String = "RED"
    const val colorsGreenStr: String = "GREEN"
    const val colorsBlueStr: String = "BLUE"
}

object itemNodeQuick {
    const val item: String = "item"
}

object itemNodeQuickNode {
}

object css3 {
    const val xWebkitAirplay: String = "x-webkit-airplay"
    const val WebkitTextZoom: String = "-webkit-text-zoom"
    const val WebkitBackdropFilter: String = "-webkit-backdrop-filter"
    const val WebkitBorderHorizontalSpacing: String = "-webkit-border-horizontal-spacing"
    const val WebkitBorderVerticalSpacing: String = "-webkit-border-vertical-spacing"
    const val WebkitBoxAlign: String = "-webkit-box-align"
    const val noneId: UByte = 0
    const val xWebkitAirplayId: UByte = 1 << 0
    const val WebkitTextZoomId: UByte = 1 << 1
    const val WebkitBackdropFilterId: UByte = 1 << 2
    const val WebkitBorderHorizontalSpacingId: UByte = 1 << 3
    const val WebkitBorderVerticalSpacingId: UByte = 1 << 4
    const val WebkitBoxAlignId: UByte = 1 << 5
    const val allId: UByte = 0x3f
}