# This file is generated by ConstMaker, DON'T MODIFY.

# 
# this is a test
# 
use constant table => "table"; # hello word
use constant allowTest => "at";
use constant percent => -100;
# pi 
use constant pi => 3.14159;

# 
# colors
# 
use constant {
    mColorsKBlueDef => 0,
    mColorsKGreenDef => 1,
    mColorsKRedDef => 2,
    mColorsKBlueStr => "blue";
    mColorsKGreenStr => "green";
    mColorsKRedStr => "red";
};

# namespace node
use constant nodeHtmlBlockId => "Block";
use constant nodeHtmlTableId => "Table";

# namespace item
use constant itemAllowTest => "at";
use constant itemPi => 3.14159;
use constant itemTable => "table";
use constant itemPercent => 100;
use constant itemNoneId => 0;
use constant itemAllowTestId => 1 << 0;
use constant itemPiId => 1 << 1;
use constant itemTableId => 1 << 2;
use constant itemPercentId => 1 << 3;
use constant itemAllId => 0xf;

use constant {
    itemColorsBlue => 0,
    itemColorsGreen => 1, # green
    itemColorsRed => 2,
};

# namespace itemNode
use constant itemNodeBorder => "border";

use constant {
    itemNodeColorsRed => 0,
    itemNodeColorsGreen => 1, # green
    itemNodeColorsBlue => 2,
    itemNodeColorsRedStr => "RED";
    itemNodeColorsGreenStr => "GREEN";
    itemNodeColorsBlueStr => "BLUE";
};

# namespace itemNodeQuick
use constant itemNodeQuickItem => "item";

# namespace itemNodeQuickNode

# namespace css3
use constant css3XWebkitAirplay => "x-webkit-airplay";
use constant css3WebkitTextZoom => "-webkit-text-zoom";
use constant css3WebkitBackdropFilter => "-webkit-backdrop-filter";
use constant css3WebkitBorderHorizontalSpacing => "-webkit-border-horizontal-spacing";
use constant css3WebkitBorderVerticalSpacing => "-webkit-border-vertical-spacing";
use constant css3WebkitBoxAlign => "-webkit-box-align";
use constant css3NoneId => 0;
use constant css3XWebkitAirplayId => 1 << 0;
use constant css3WebkitTextZoomId => 1 << 1;
use constant css3WebkitBackdropFilterId => 1 << 2;
use constant css3WebkitBorderHorizontalSpacingId => 1 << 3;
use constant css3WebkitBorderVerticalSpacingId => 1 << 4;
use constant css3WebkitBoxAlignId => 1 << 5;
use constant css3AllId => 0x3f;