// This file is generated by ConstMaker, DON'T MODIFY.

QtObject {
    id: test1

    /**
     *this is a test
     */
    property string table: "table" // hello word
    property string allowTest: "at"
    property int percent: -100

    /** pi */
    property real pi: 3.14159

    /**
     * colors
     */
    enum mColors {
        kBlueDef,
        kGreenDef,
        kRedDef
    }
    property string mColorsKBlueStr: "blue"
    property string mColorsKGreenStr: "green"
    property string mColorsKRedStr: "red"

    QtObject {
        id: node

        property string htmlBlockId: "Block"
        property string htmlTableId: "Table"
    }

    QtObject {
        id: item

        property string allowTest: "at"
        property real pi: 3.14159
        property string table: "table"
        property int Percent: 100
        property int noneId: 0
        property int allowTestId: 1 << 0
        property int piId: 1 << 1
        property int tableId: 1 << 2
        property int PercentId: 1 << 3
        property int allId: 0xf

        enum colors {
            blue,
            green, // green
            red
        }

        QtObject {
            id: node

            property string border: "border"

            enum colors {
                red,
                green, // green
                blue
            }
            property string colorsRedStr: "RED"
            property string colorsGreenStr: "GREEN"
            property string colorsBlueStr: "BLUE"

            QtObject {
                id: quick

                property string item: "item"

                QtObject {
                    id: node

                }
            }
        }
    }

    QtObject {
        id: css3

        property string xWebkitAirplay: "x-webkit-airplay"
        property string WebkitTextZoom: "-webkit-text-zoom"
        property string WebkitBackdropFilter: "-webkit-backdrop-filter"
        property string WebkitBorderHorizontalSpacing: "-webkit-border-horizontal-spacing"
        property string WebkitBorderVerticalSpacing: "-webkit-border-vertical-spacing"
        property string WebkitBoxAlign: "-webkit-box-align"
        property int noneId: 0
        property int xWebkitAirplayId: 1 << 0
        property int WebkitTextZoomId: 1 << 1
        property int WebkitBackdropFilterId: 1 << 2
        property int WebkitBorderHorizontalSpacingId: 1 << 3
        property int WebkitBorderVerticalSpacingId: 1 << 4
        property int WebkitBoxAlignId: 1 << 5
        property int allId: 0x3f
    }
}