// This file is generated by ConstMaker, DON'T MODIFY.

package consts;

interface test1 {
    /**
     *this is a test
     */
    public static final String table = "table"; // hello word
    public static final String allowTest = "at";
    public static final byte percent = -100;

    /** pi */
    public static final float pi = 3.14159f;

    /**
     * colors
     */
    enum mColors {
        kBlueDef,
        kGreenDef,
        kRedDef
    }
    public static final String mColorsKBlueStr = "blue";
    public static final String mColorsKGreenStr = "green";
    public static final String mColorsKRedStr = "red";

    interface node {
        public static final String htmlBlockId = "Block";
        public static final String htmlTableId = "Table";
    }

    interface item {
        public static final String allowTest = "at";
        public static final float pi = 3.14159f;
        public static final String table = "table";
        public static final byte Percent = 100;
        public static final byte noneId = 0;
        public static final byte allowTestId = 1 << 0;
        public static final byte piId = 1 << 1;
        public static final byte tableId = 1 << 2;
        public static final byte PercentId = 1 << 3;
        public static final byte allId = 0xf;

        enum colors {
            blue,
            green, // green
            red
        }

        interface node {
            public static final String border = "border";

            enum colors {
                red,
                green, // green
                blue
            }
            public static final String colorsRedStr = "RED";
            public static final String colorsGreenStr = "GREEN";
            public static final String colorsBlueStr = "BLUE";

            interface quick {
                public static final String item = "item";

                // namespace node
            }
        }
    }

    interface css3 {
        public static final String xWebkitAirplay = "x-webkit-airplay";
        public static final String WebkitTextZoom = "-webkit-text-zoom";
        public static final String WebkitBackdropFilter = "-webkit-backdrop-filter";
        public static final String WebkitBorderHorizontalSpacing = "-webkit-border-horizontal-spacing";
        public static final String WebkitBorderVerticalSpacing = "-webkit-border-vertical-spacing";
        public static final String WebkitBoxAlign = "-webkit-box-align";
        public static final byte noneId = 0;
        public static final byte xWebkitAirplayId = 1 << 0;
        public static final byte WebkitTextZoomId = 1 << 1;
        public static final byte WebkitBackdropFilterId = 1 << 2;
        public static final byte WebkitBorderHorizontalSpacingId = 1 << 3;
        public static final byte WebkitBorderVerticalSpacingId = 1 << 4;
        public static final byte WebkitBoxAlignId = 1 << 5;
        public static final byte allId = 0x3f;
    }
}