// This file is generated by ConstMaker, DON'T MODIFY.


enum class ELEMENT(val value: UByte) {
    SVG_A_ID,
    SVG_ALTGLYPH_ID,
    SVG_ALTGLYPHDEF_ID,
    SVG_ALTGLYPHITEM_ID,
    SVG_ANIMATE_ID,
    SVG_ANIMATECOLOR_ID,
    SVG_ANIMATEMOTION_ID,
    SVG_ANIMATETRANSFORM_ID,
    SVG_CIRCLE_ID,
    SVG_CLIPPATH_ID,
    SVG_COLOR_PROFILE_ID,
    SVG_CURSOR_ID,
    SVG_DEFINITION_SRC_ID,
    SVG_DEFS_ID,
    SVG_DESC_ID,
    SVG_ELLIPSE_ID,
    SVG_FEBLEND_ID,
    SVG_FECOLORMATRIX_ID,
    SVG_FECOMPONENTTRANSFER_ID,
    SVG_FECOMPOSITE_ID,
    SVG_FECONVOLVEMATRIX_ID,
    SVG_FEDIFFUSELIGHTING_ID,
    SVG_FEDISPLACEMENTMAP_ID,
    SVG_FEDISTANTLIGHT_ID,
    SVG_FEFLOOD_ID,
    SVG_FEFUNCA_ID,
    SVG_FEFUNCB_ID,
    SVG_FEFUNCG_ID,
    SVG_FEFUNCR_ID,
    SVG_FEGAUSSIANBLUR_ID,
    SVG_FEIMAGE_ID,
    SVG_FEMERGE_ID,
    SVG_FEMERGENODE_ID,
    SVG_FEMORPHOLOGY_ID,
    SVG_FEOFFSET_ID,
    SVG_FEPOINTLIGHT_ID,
    SVG_FESPECULARLIGHTING_ID,
    SVG_FESPOTLIGHT_ID,
    SVG_FETILE_ID,
    SVG_FETURBULENCE_ID,
    SVG_FILTER_ID,
    SVG_FONT_ID,
    SVG_FONT_FACE_ID,
    SVG_FONT_FACE_FORMAT_ID,
    SVG_FONT_FACE_NAME_ID,
    SVG_FONT_FACE_SRC_ID,
    SVG_FONT_FACE_URI_ID,
    SVG_FOREIGNOBJECT_ID,
    SVG_G_ID,
    SVG_GLYPH_ID,
    SVG_GLYPHREF_ID,
    SVG_HKERN_ID,
    SVG_IMAGE_ID,
    SVG_LINE_ID,
    SVG_LINEARGRADIENT_ID,
    SVG_MARKER_ID,
    SVG_MASK_ID,
    SVG_METADATA_ID,
    SVG_MISSING_GLYPH_ID,
    SVG_MPATH_ID,
    SVG_PATH_ID,
    SVG_PATTERN_ID,
    SVG_POLYGON_ID,
    SVG_POLYLINE_ID,
    SVG_RADIALGRADIENT_ID,
    SVG_RECT_ID,
    SVG_SCRIPT_ID,
    SVG_SET_ID,
    SVG_STOP_ID,
    SVG_STYLE_ID,
    SVG_SVG_ID,
    SVG_SWITCH_ID,
    SVG_SYMBOL_ID,
    SVG_TEXT_ID,
    SVG_TEXTPATH_ID,
    SVG_TITLE_ID,
    SVG_TREF_ID,
    SVG_TSPAN_ID,
    SVG_USE_ID,
    SVG_VIEW_ID,
    SVG_VKERN_ID
}
const val ELEMENT_SVG_A_ID_STR: String = "a"
const val ELEMENT_SVG_ALTGLYPH_ID_STR: String = "altGlyph"
const val ELEMENT_SVG_ALTGLYPHDEF_ID_STR: String = "altGlyphDef"
const val ELEMENT_SVG_ALTGLYPHITEM_ID_STR: String = "altGlyphItem"
const val ELEMENT_SVG_ANIMATE_ID_STR: String = "animate"
const val ELEMENT_SVG_ANIMATECOLOR_ID_STR: String = "animateColor"
const val ELEMENT_SVG_ANIMATEMOTION_ID_STR: String = "animateMotion"
const val ELEMENT_SVG_ANIMATETRANSFORM_ID_STR: String = "animateTransform"
const val ELEMENT_SVG_CIRCLE_ID_STR: String = "circle"
const val ELEMENT_SVG_CLIPPATH_ID_STR: String = "clipPath"
const val ELEMENT_SVG_COLOR_PROFILE_ID_STR: String = "color_profile"
const val ELEMENT_SVG_CURSOR_ID_STR: String = "cursor"
const val ELEMENT_SVG_DEFINITION_SRC_ID_STR: String = "definition_src"
const val ELEMENT_SVG_DEFS_ID_STR: String = "defs"
const val ELEMENT_SVG_DESC_ID_STR: String = "desc"
const val ELEMENT_SVG_ELLIPSE_ID_STR: String = "ellipse"
const val ELEMENT_SVG_FEBLEND_ID_STR: String = "feBlend"
const val ELEMENT_SVG_FECOLORMATRIX_ID_STR: String = "feColorMatrix"
const val ELEMENT_SVG_FECOMPONENTTRANSFER_ID_STR: String = "feComponentTransfer"
const val ELEMENT_SVG_FECOMPOSITE_ID_STR: String = "feComposite"
const val ELEMENT_SVG_FECONVOLVEMATRIX_ID_STR: String = "feConvolveMatrix"
const val ELEMENT_SVG_FEDIFFUSELIGHTING_ID_STR: String = "feDiffuseLighting"
const val ELEMENT_SVG_FEDISPLACEMENTMAP_ID_STR: String = "feDisplacementMap"
const val ELEMENT_SVG_FEDISTANTLIGHT_ID_STR: String = "feDistantLight"
const val ELEMENT_SVG_FEFLOOD_ID_STR: String = "feFlood"
const val ELEMENT_SVG_FEFUNCA_ID_STR: String = "feFuncA"
const val ELEMENT_SVG_FEFUNCB_ID_STR: String = "feFuncB"
const val ELEMENT_SVG_FEFUNCG_ID_STR: String = "feFuncG"
const val ELEMENT_SVG_FEFUNCR_ID_STR: String = "feFuncR"
const val ELEMENT_SVG_FEGAUSSIANBLUR_ID_STR: String = "feGaussianBlur"
const val ELEMENT_SVG_FEIMAGE_ID_STR: String = "feImage"
const val ELEMENT_SVG_FEMERGE_ID_STR: String = "feMerge"
const val ELEMENT_SVG_FEMERGENODE_ID_STR: String = "feMergeNode"
const val ELEMENT_SVG_FEMORPHOLOGY_ID_STR: String = "feMorphology"
const val ELEMENT_SVG_FEOFFSET_ID_STR: String = "feOffset"
const val ELEMENT_SVG_FEPOINTLIGHT_ID_STR: String = "fePointLight"
const val ELEMENT_SVG_FESPECULARLIGHTING_ID_STR: String = "feSpecularLighting"
const val ELEMENT_SVG_FESPOTLIGHT_ID_STR: String = "feSpotLight"
const val ELEMENT_SVG_FETILE_ID_STR: String = "feTile"
const val ELEMENT_SVG_FETURBULENCE_ID_STR: String = "feTurbulence"
const val ELEMENT_SVG_FILTER_ID_STR: String = "filter"
const val ELEMENT_SVG_FONT_ID_STR: String = "font"
const val ELEMENT_SVG_FONT_FACE_ID_STR: String = "font_face"
const val ELEMENT_SVG_FONT_FACE_FORMAT_ID_STR: String = "font_face_format"
const val ELEMENT_SVG_FONT_FACE_NAME_ID_STR: String = "font_face_name"
const val ELEMENT_SVG_FONT_FACE_SRC_ID_STR: String = "font_face_src"
const val ELEMENT_SVG_FONT_FACE_URI_ID_STR: String = "font_face_uri"
const val ELEMENT_SVG_FOREIGNOBJECT_ID_STR: String = "foreignObject"
const val ELEMENT_SVG_G_ID_STR: String = "g"
const val ELEMENT_SVG_GLYPH_ID_STR: String = "glyph"
const val ELEMENT_SVG_GLYPHREF_ID_STR: String = "glyphRef"
const val ELEMENT_SVG_HKERN_ID_STR: String = "hkern"
const val ELEMENT_SVG_IMAGE_ID_STR: String = "image"
const val ELEMENT_SVG_LINE_ID_STR: String = "line"
const val ELEMENT_SVG_LINEARGRADIENT_ID_STR: String = "linearGradient"
const val ELEMENT_SVG_MARKER_ID_STR: String = "marker"
const val ELEMENT_SVG_MASK_ID_STR: String = "mask"
const val ELEMENT_SVG_METADATA_ID_STR: String = "metadata"
const val ELEMENT_SVG_MISSING_GLYPH_ID_STR: String = "missing_glyph"
const val ELEMENT_SVG_MPATH_ID_STR: String = "mpath"
const val ELEMENT_SVG_PATH_ID_STR: String = "path"
const val ELEMENT_SVG_PATTERN_ID_STR: String = "pattern"
const val ELEMENT_SVG_POLYGON_ID_STR: String = "polygon"
const val ELEMENT_SVG_POLYLINE_ID_STR: String = "polyline"
const val ELEMENT_SVG_RADIALGRADIENT_ID_STR: String = "radialGradient"
const val ELEMENT_SVG_RECT_ID_STR: String = "rect"
const val ELEMENT_SVG_SCRIPT_ID_STR: String = "script"
const val ELEMENT_SVG_SET_ID_STR: String = "set"
const val ELEMENT_SVG_STOP_ID_STR: String = "stop"
const val ELEMENT_SVG_STYLE_ID_STR: String = "style"
const val ELEMENT_SVG_SVG_ID_STR: String = "svg"
const val ELEMENT_SVG_SWITCH_ID_STR: String = "switch"
const val ELEMENT_SVG_SYMBOL_ID_STR: String = "symbol"
const val ELEMENT_SVG_TEXT_ID_STR: String = "text"
const val ELEMENT_SVG_TEXTPATH_ID_STR: String = "textPath"
const val ELEMENT_SVG_TITLE_ID_STR: String = "title"
const val ELEMENT_SVG_TREF_ID_STR: String = "tref"
const val ELEMENT_SVG_TSPAN_ID_STR: String = "tspan"
const val ELEMENT_SVG_USE_ID_STR: String = "use"
const val ELEMENT_SVG_VIEW_ID_STR: String = "view"
const val ELEMENT_SVG_VKERN_ID_STR: String = "vkern"

enum class ATTRIB(val value: UByte) {
    SVG_ACCENT_HEIGHT,
    SVG_ACCUMULATE,
    SVG_ADDITIVE,
    SVG_ALIGNMENT_BASELINE,
    SVG_ALPHABETIC,
    SVG_AMPLITUDE,
    SVG_ANIMATE,
    SVG_ARABIC_FORM,
    SVG_ASCENT,
    SVG_ATTRIBUTENAME,
    SVG_ATTRIBUTETYPE,
    SVG_AZIMUTH,
    SVG_BASEFREQUENCY,
    SVG_BASEPROFILE,
    SVG_BASELINE_SHIFT,
    SVG_BBOX,
    SVG_BEGIN,
    SVG_BIAS,
    SVG_BY,
    SVG_CALCMODE,
    SVG_CAP_HEIGHT,
    SVG_CLIP,
    SVG_CLIPPATHUNITS,
    SVG_CLIP_PATH,
    SVG_CLIP_RULE,
    SVG_COLOR,
    SVG_COLOR_INTERPOLATION,
    SVG_COLOR_INTERPOLATION_FILTERS,
    SVG_COLOR_PROFILE,
    SVG_COLOR_RENDERING,
    SVG_CONTENTSCRIPTTYPE,
    SVG_CONTENTSTYLETYPE,
    SVG_CURSOR,
    SVG_CX,
    SVG_CY,
    SVG_D,
    SVG_DESCENT,
    SVG_DIFFUSECONSTANT,
    SVG_DIRECTION,
    SVG_DISPLAY,
    SVG_DIVISOR,
    SVG_DOMINANT_BASELINE,
    SVG_DUR,
    SVG_DX,
    SVG_DY,
    SVG_EDGEMODE,
    SVG_ELEVATION,
    SVG_ENABLE_BACKGROUND,
    SVG_END,
    SVG_EXPONENT,
    SVG_EXTERNALRESOURCESREQUIRED,
    SVG_FECOLORMATRIX,
    SVG_FECOMPOSITE,
    SVG_FEGAUSSIANBLUR,
    SVG_FEMORPHOLOGY,
    SVG_FETILE,
    SVG_FILL,
    SVG_FILL_OPACITY,
    SVG_FILL_RULE,
    SVG_FILTER,
    SVG_FILTERRES,
    SVG_FILTERUNITS,
    SVG_FLOOD_COLOR,
    SVG_FLOOD_OPACITY,
    SVG_FONT_FAMILY,
    SVG_FONT_SIZE,
    SVG_FONT_SIZE_ADJUST,
    SVG_FONT_STRETCH,
    SVG_FONT_STYLE,
    SVG_FONT_VARIANT,
    SVG_FONT_WEIGHT,
    SVG_FORMAT,
    SVG_FROM,
    SVG_FX,
    SVG_FY,
    SVG_G1,
    SVG_G2,
    SVG_GLYPHREF,
    SVG_GLYPH_NAME,
    SVG_GLYPH_ORIENTATION_HORIZONTAL,
    SVG_GLYPH_ORIENTATION_VERTICAL,
    SVG_GRADIENTTRANSFORM,
    SVG_GRADIENTUNITS,
    SVG_HANGING,
    SVG_HEIGHT,
    SVG_HORIZ_ADV_X,
    SVG_HORIZ_ORIGIN_X,
    SVG_HORIZ_ORIGIN_Y,
    SVG_IDEOGRAPHIC,
    SVG_IMAGE_RENDERING,
    SVG_IN,
    SVG_IN2,
    SVG_INTERCEPT,
    SVG_K,
    SVG_K1,
    SVG_K2,
    SVG_K3,
    SVG_K4,
    SVG_KERNELMATRIX,
    SVG_KERNELUNITLENGTH,
    SVG_KERNING,
    SVG_KEYPOINTS,
    SVG_KEYSPLINES,
    SVG_KEYTIMES,
    SVG_LANG,
    SVG_LENGTHADJUST,
    SVG_LETTER_SPACING,
    SVG_LIGHTING_COLOR,
    SVG_LIMITINGCONEANGLE,
    SVG_LOCAL,
    SVG_MARKERHEIGHT,
    SVG_MARKERUNITS,
    SVG_MARKERWIDTH,
    SVG_MARKER_END,
    SVG_MARKER_MID,
    SVG_MARKER_START,
    SVG_MASK,
    SVG_MASKCONTENTUNITS,
    SVG_MASKUNITS,
    SVG_MATHEMATICAL,
    SVG_MAX,
    SVG_MEDIA,
    SVG_METHOD,
    SVG_MIN,
    SVG_MODE,
    SVG_NAME,
    SVG_NUMOCTAVES,
    SVG_OFFSET,
    SVG_ONACTIVATE,
    SVG_ONBEGIN,
    SVG_ONEND,
    SVG_ONFOCUSIN,
    SVG_ONFOCUSOUT,
    SVG_ONREPEAT,
    SVG_ONZOOM,
    SVG_OPACITY,
    SVG_OPERATOR,
    SVG_ORDER,
    SVG_ORIENT,
    SVG_ORIENTATION,
    SVG_ORIGIN,
    SVG_OVERFLOW,
    SVG_OVERLINE_POSITION,
    SVG_OVERLINE_THICKNESS,
    SVG_PANOSE_1,
    SVG_PATH,
    SVG_PATHLENGTH,
    SVG_PATTERNCONTENTUNITS,
    SVG_PATTERNTRANSFORM,
    SVG_PATTERNUNITS,
    SVG_POINTER_EVENTS,
    SVG_POINTS,
    SVG_POINTSATX,
    SVG_POINTSATY,
    SVG_POINTSATZ,
    SVG_PRESERVEALPHA,
    SVG_PRESERVEASPECTRATIO,
    SVG_PRIMITIVEUNITS,
    SVG_R,
    SVG_RADIUS,
    SVG_REFX,
    SVG_REFY,
    SVG_RENDERING_INTENT,
    SVG_REPEATCOUNT,
    SVG_REPEATDUR,
    SVG_REQUIREDEXTENSIONS,
    SVG_REQUIREDFEATURES,
    SVG_RESTART,
    SVG_RESULT,
    SVG_ROTATE,
    SVG_RX,
    SVG_RY,
    SVG_SCALE,
    SVG_SEED,
    SVG_SHAPE_RENDERING,
    SVG_SLOPE,
    SVG_SPACING,
    SVG_SPECULARCONSTANT,
    SVG_SPECULAREXPONENT,
    SVG_SPREADMETHOD,
    SVG_STARTOFFSET,
    SVG_STDDEVIATION,
    SVG_STEMH,
    SVG_STEMV,
    SVG_STITCHTILES,
    SVG_STOP_COLOR,
    SVG_STOP_OPACITY,
    SVG_STRIKETHROUGH_POSITION,
    SVG_STRIKETHROUGH_THICKNESS,
    SVG_STROKE,
    SVG_STROKE_DASHARRAY,
    SVG_STROKE_DASHOFFSET,
    SVG_STROKE_LINECAP,
    SVG_STROKE_LINEJOIN,
    SVG_STROKE_MITERLIMIT,
    SVG_STROKE_OPACITY,
    SVG_STROKE_WIDTH,
    SVG_STYLE,
    SVG_SURFACESCALE,
    SVG_SYSTEMLANGUAGE,
    SVG_TABLEVALUES,
    SVG_TARGET,
    SVG_TARGETX,
    SVG_TARGETY,
    SVG_TEXTLENGTH,
    SVG_TEXT_ANCHOR,
    SVG_TEXT_DECORATION,
    SVG_TEXT_RENDERING,
    SVG_TITLE,
    SVG_TO,
    SVG_TRANSFORM,
    SVG_TYPE,
    SVG_U1,
    SVG_U2,
    SVG_UNDERLINE_POSITION,
    SVG_UNDERLINE_THICKNESS,
    SVG_UNICODE,
    SVG_UNICODE_BIDI,
    SVG_UNICODE_RANGE,
    SVG_UNITS_PER_EM,
    SVG_V_ALPHABETIC,
    SVG_V_HANGING,
    SVG_V_IDEOGRAPHIC,
    SVG_V_MATHEMATICAL,
    SVG_VALUES,
    SVG_VERSION,
    SVG_VERT_ADV_Y,
    SVG_VERT_ORIGIN_X,
    SVG_VERT_ORIGIN_Y,
    SVG_VIEWBOX,
    SVG_VIEWTARGET,
    SVG_VISIBILITY,
    SVG_WIDTH,
    SVG_WIDTHS,
    SVG_WORD_SPACING,
    SVG_WRITING_MODE,
    SVG_X,
    SVG_X1,
    SVG_X2,
    SVG_XCHANNELSELECTOR,
    SVG_X_HEIGHT,
    SVG_Y,
    SVG_Y1,
    SVG_Y2,
    SVG_YCHANNELSELECTOR,
    SVG_Z,
    SVG_ZOOMANDPAN
}
const val ATTRIB_SVG_ACCENT_HEIGHT_STR: String = "accent_height"
const val ATTRIB_SVG_ACCUMULATE_STR: String = "accumulate"
const val ATTRIB_SVG_ADDITIVE_STR: String = "additive"
const val ATTRIB_SVG_ALIGNMENT_BASELINE_STR: String = "alignment_baseline"
const val ATTRIB_SVG_ALPHABETIC_STR: String = "alphabetic"
const val ATTRIB_SVG_AMPLITUDE_STR: String = "amplitude"
const val ATTRIB_SVG_ANIMATE_STR: String = "animate"
const val ATTRIB_SVG_ARABIC_FORM_STR: String = "arabic_form"
const val ATTRIB_SVG_ASCENT_STR: String = "ascent"
const val ATTRIB_SVG_ATTRIBUTENAME_STR: String = "attributeName"
const val ATTRIB_SVG_ATTRIBUTETYPE_STR: String = "attributeType"
const val ATTRIB_SVG_AZIMUTH_STR: String = "azimuth"
const val ATTRIB_SVG_BASEFREQUENCY_STR: String = "baseFrequency"
const val ATTRIB_SVG_BASEPROFILE_STR: String = "baseProfile"
const val ATTRIB_SVG_BASELINE_SHIFT_STR: String = "baseline_shift"
const val ATTRIB_SVG_BBOX_STR: String = "bbox"
const val ATTRIB_SVG_BEGIN_STR: String = "begin"
const val ATTRIB_SVG_BIAS_STR: String = "bias"
const val ATTRIB_SVG_BY_STR: String = "by"
const val ATTRIB_SVG_CALCMODE_STR: String = "calcMode"
const val ATTRIB_SVG_CAP_HEIGHT_STR: String = "cap_height"
const val ATTRIB_SVG_CLIP_STR: String = "clip"
const val ATTRIB_SVG_CLIPPATHUNITS_STR: String = "clipPathUnits"
const val ATTRIB_SVG_CLIP_PATH_STR: String = "clip_path"
const val ATTRIB_SVG_CLIP_RULE_STR: String = "clip_rule"
const val ATTRIB_SVG_COLOR_STR: String = "color"
const val ATTRIB_SVG_COLOR_INTERPOLATION_STR: String = "color_interpolation"
const val ATTRIB_SVG_COLOR_INTERPOLATION_FILTERS_STR: String = "color_interpolation_filters"
const val ATTRIB_SVG_COLOR_PROFILE_STR: String = "color_profile"
const val ATTRIB_SVG_COLOR_RENDERING_STR: String = "color_rendering"
const val ATTRIB_SVG_CONTENTSCRIPTTYPE_STR: String = "contentScriptType"
const val ATTRIB_SVG_CONTENTSTYLETYPE_STR: String = "contentStyleType"
const val ATTRIB_SVG_CURSOR_STR: String = "cursor"
const val ATTRIB_SVG_CX_STR: String = "cx"
const val ATTRIB_SVG_CY_STR: String = "cy"
const val ATTRIB_SVG_D_STR: String = "d"
const val ATTRIB_SVG_DESCENT_STR: String = "descent"
const val ATTRIB_SVG_DIFFUSECONSTANT_STR: String = "diffuseConstant"
const val ATTRIB_SVG_DIRECTION_STR: String = "direction"
const val ATTRIB_SVG_DISPLAY_STR: String = "display"
const val ATTRIB_SVG_DIVISOR_STR: String = "divisor"
const val ATTRIB_SVG_DOMINANT_BASELINE_STR: String = "dominant_baseline"
const val ATTRIB_SVG_DUR_STR: String = "dur"
const val ATTRIB_SVG_DX_STR: String = "dx"
const val ATTRIB_SVG_DY_STR: String = "dy"
const val ATTRIB_SVG_EDGEMODE_STR: String = "edgeMode"
const val ATTRIB_SVG_ELEVATION_STR: String = "elevation"
const val ATTRIB_SVG_ENABLE_BACKGROUND_STR: String = "enable_background"
const val ATTRIB_SVG_END_STR: String = "end"
const val ATTRIB_SVG_EXPONENT_STR: String = "exponent"
const val ATTRIB_SVG_EXTERNALRESOURCESREQUIRED_STR: String = "externalResourcesRequired"
const val ATTRIB_SVG_FECOLORMATRIX_STR: String = "feColorMatrix"
const val ATTRIB_SVG_FECOMPOSITE_STR: String = "feComposite"
const val ATTRIB_SVG_FEGAUSSIANBLUR_STR: String = "feGaussianBlur"
const val ATTRIB_SVG_FEMORPHOLOGY_STR: String = "feMorphology"
const val ATTRIB_SVG_FETILE_STR: String = "feTile"
const val ATTRIB_SVG_FILL_STR: String = "fill"
const val ATTRIB_SVG_FILL_OPACITY_STR: String = "fill_opacity"
const val ATTRIB_SVG_FILL_RULE_STR: String = "fill_rule"
const val ATTRIB_SVG_FILTER_STR: String = "filter"
const val ATTRIB_SVG_FILTERRES_STR: String = "filterRes"
const val ATTRIB_SVG_FILTERUNITS_STR: String = "filterUnits"
const val ATTRIB_SVG_FLOOD_COLOR_STR: String = "flood_color"
const val ATTRIB_SVG_FLOOD_OPACITY_STR: String = "flood_opacity"
const val ATTRIB_SVG_FONT_FAMILY_STR: String = "font_family"
const val ATTRIB_SVG_FONT_SIZE_STR: String = "font_size"
const val ATTRIB_SVG_FONT_SIZE_ADJUST_STR: String = "font_size_adjust"
const val ATTRIB_SVG_FONT_STRETCH_STR: String = "font_stretch"
const val ATTRIB_SVG_FONT_STYLE_STR: String = "font_style"
const val ATTRIB_SVG_FONT_VARIANT_STR: String = "font_variant"
const val ATTRIB_SVG_FONT_WEIGHT_STR: String = "font_weight"
const val ATTRIB_SVG_FORMAT_STR: String = "format"
const val ATTRIB_SVG_FROM_STR: String = "from"
const val ATTRIB_SVG_FX_STR: String = "fx"
const val ATTRIB_SVG_FY_STR: String = "fy"
const val ATTRIB_SVG_G1_STR: String = "g1"
const val ATTRIB_SVG_G2_STR: String = "g2"
const val ATTRIB_SVG_GLYPHREF_STR: String = "glyphRef"
const val ATTRIB_SVG_GLYPH_NAME_STR: String = "glyph_name"
const val ATTRIB_SVG_GLYPH_ORIENTATION_HORIZONTAL_STR: String = "glyph_orientation_horizontal"
const val ATTRIB_SVG_GLYPH_ORIENTATION_VERTICAL_STR: String = "glyph_orientation_vertical"
const val ATTRIB_SVG_GRADIENTTRANSFORM_STR: String = "gradientTransform"
const val ATTRIB_SVG_GRADIENTUNITS_STR: String = "gradientUnits"
const val ATTRIB_SVG_HANGING_STR: String = "hanging"
const val ATTRIB_SVG_HEIGHT_STR: String = "height"
const val ATTRIB_SVG_HORIZ_ADV_X_STR: String = "horiz_adv_x"
const val ATTRIB_SVG_HORIZ_ORIGIN_X_STR: String = "horiz_origin_x"
const val ATTRIB_SVG_HORIZ_ORIGIN_Y_STR: String = "horiz_origin_y"
const val ATTRIB_SVG_IDEOGRAPHIC_STR: String = "ideographic"
const val ATTRIB_SVG_IMAGE_RENDERING_STR: String = "image_rendering"
const val ATTRIB_SVG_IN_STR: String = "in"
const val ATTRIB_SVG_IN2_STR: String = "in2"
const val ATTRIB_SVG_INTERCEPT_STR: String = "intercept"
const val ATTRIB_SVG_K_STR: String = "k"
const val ATTRIB_SVG_K1_STR: String = "k1"
const val ATTRIB_SVG_K2_STR: String = "k2"
const val ATTRIB_SVG_K3_STR: String = "k3"
const val ATTRIB_SVG_K4_STR: String = "k4"
const val ATTRIB_SVG_KERNELMATRIX_STR: String = "kernelMatrix"
const val ATTRIB_SVG_KERNELUNITLENGTH_STR: String = "kernelUnitLength"
const val ATTRIB_SVG_KERNING_STR: String = "kerning"
const val ATTRIB_SVG_KEYPOINTS_STR: String = "keyPoints"
const val ATTRIB_SVG_KEYSPLINES_STR: String = "keySplines"
const val ATTRIB_SVG_KEYTIMES_STR: String = "keyTimes"
const val ATTRIB_SVG_LANG_STR: String = "lang"
const val ATTRIB_SVG_LENGTHADJUST_STR: String = "lengthAdjust"
const val ATTRIB_SVG_LETTER_SPACING_STR: String = "letter_spacing"
const val ATTRIB_SVG_LIGHTING_COLOR_STR: String = "lighting_color"
const val ATTRIB_SVG_LIMITINGCONEANGLE_STR: String = "limitingConeAngle"
const val ATTRIB_SVG_LOCAL_STR: String = "local"
const val ATTRIB_SVG_MARKERHEIGHT_STR: String = "markerHeight"
const val ATTRIB_SVG_MARKERUNITS_STR: String = "markerUnits"
const val ATTRIB_SVG_MARKERWIDTH_STR: String = "markerWidth"
const val ATTRIB_SVG_MARKER_END_STR: String = "marker_end"
const val ATTRIB_SVG_MARKER_MID_STR: String = "marker_mid"
const val ATTRIB_SVG_MARKER_START_STR: String = "marker_start"
const val ATTRIB_SVG_MASK_STR: String = "mask"
const val ATTRIB_SVG_MASKCONTENTUNITS_STR: String = "maskContentUnits"
const val ATTRIB_SVG_MASKUNITS_STR: String = "maskUnits"
const val ATTRIB_SVG_MATHEMATICAL_STR: String = "mathematical"
const val ATTRIB_SVG_MAX_STR: String = "max"
const val ATTRIB_SVG_MEDIA_STR: String = "media"
const val ATTRIB_SVG_METHOD_STR: String = "method"
const val ATTRIB_SVG_MIN_STR: String = "min"
const val ATTRIB_SVG_MODE_STR: String = "mode"
const val ATTRIB_SVG_NAME_STR: String = "name"
const val ATTRIB_SVG_NUMOCTAVES_STR: String = "numOctaves"
const val ATTRIB_SVG_OFFSET_STR: String = "offset"
const val ATTRIB_SVG_ONACTIVATE_STR: String = "onactivate"
const val ATTRIB_SVG_ONBEGIN_STR: String = "onbegin"
const val ATTRIB_SVG_ONEND_STR: String = "onend"
const val ATTRIB_SVG_ONFOCUSIN_STR: String = "onfocusin"
const val ATTRIB_SVG_ONFOCUSOUT_STR: String = "onfocusout"
const val ATTRIB_SVG_ONREPEAT_STR: String = "onrepeat"
const val ATTRIB_SVG_ONZOOM_STR: String = "onzoom"
const val ATTRIB_SVG_OPACITY_STR: String = "opacity"
const val ATTRIB_SVG_OPERATOR_STR: String = "operator"
const val ATTRIB_SVG_ORDER_STR: String = "order"
const val ATTRIB_SVG_ORIENT_STR: String = "orient"
const val ATTRIB_SVG_ORIENTATION_STR: String = "orientation"
const val ATTRIB_SVG_ORIGIN_STR: String = "origin"
const val ATTRIB_SVG_OVERFLOW_STR: String = "overflow"
const val ATTRIB_SVG_OVERLINE_POSITION_STR: String = "overline_position"
const val ATTRIB_SVG_OVERLINE_THICKNESS_STR: String = "overline_thickness"
const val ATTRIB_SVG_PANOSE_1_STR: String = "panose_1"
const val ATTRIB_SVG_PATH_STR: String = "path"
const val ATTRIB_SVG_PATHLENGTH_STR: String = "pathLength"
const val ATTRIB_SVG_PATTERNCONTENTUNITS_STR: String = "patternContentUnits"
const val ATTRIB_SVG_PATTERNTRANSFORM_STR: String = "patternTransform"
const val ATTRIB_SVG_PATTERNUNITS_STR: String = "patternUnits"
const val ATTRIB_SVG_POINTER_EVENTS_STR: String = "pointer_events"
const val ATTRIB_SVG_POINTS_STR: String = "points"
const val ATTRIB_SVG_POINTSATX_STR: String = "pointsAtX"
const val ATTRIB_SVG_POINTSATY_STR: String = "pointsAtY"
const val ATTRIB_SVG_POINTSATZ_STR: String = "pointsAtZ"
const val ATTRIB_SVG_PRESERVEALPHA_STR: String = "preserveAlpha"
const val ATTRIB_SVG_PRESERVEASPECTRATIO_STR: String = "preserveAspectRatio"
const val ATTRIB_SVG_PRIMITIVEUNITS_STR: String = "primitiveUnits"
const val ATTRIB_SVG_R_STR: String = "r"
const val ATTRIB_SVG_RADIUS_STR: String = "radius"
const val ATTRIB_SVG_REFX_STR: String = "refX"
const val ATTRIB_SVG_REFY_STR: String = "refY"
const val ATTRIB_SVG_RENDERING_INTENT_STR: String = "rendering_intent"
const val ATTRIB_SVG_REPEATCOUNT_STR: String = "repeatCount"
const val ATTRIB_SVG_REPEATDUR_STR: String = "repeatDur"
const val ATTRIB_SVG_REQUIREDEXTENSIONS_STR: String = "requiredExtensions"
const val ATTRIB_SVG_REQUIREDFEATURES_STR: String = "requiredFeatures"
const val ATTRIB_SVG_RESTART_STR: String = "restart"
const val ATTRIB_SVG_RESULT_STR: String = "result"
const val ATTRIB_SVG_ROTATE_STR: String = "rotate"
const val ATTRIB_SVG_RX_STR: String = "rx"
const val ATTRIB_SVG_RY_STR: String = "ry"
const val ATTRIB_SVG_SCALE_STR: String = "scale"
const val ATTRIB_SVG_SEED_STR: String = "seed"
const val ATTRIB_SVG_SHAPE_RENDERING_STR: String = "shape_rendering"
const val ATTRIB_SVG_SLOPE_STR: String = "slope"
const val ATTRIB_SVG_SPACING_STR: String = "spacing"
const val ATTRIB_SVG_SPECULARCONSTANT_STR: String = "specularConstant"
const val ATTRIB_SVG_SPECULAREXPONENT_STR: String = "specularExponent"
const val ATTRIB_SVG_SPREADMETHOD_STR: String = "spreadMethod"
const val ATTRIB_SVG_STARTOFFSET_STR: String = "startOffset"
const val ATTRIB_SVG_STDDEVIATION_STR: String = "stdDeviation"
const val ATTRIB_SVG_STEMH_STR: String = "stemh"
const val ATTRIB_SVG_STEMV_STR: String = "stemv"
const val ATTRIB_SVG_STITCHTILES_STR: String = "stitchTiles"
const val ATTRIB_SVG_STOP_COLOR_STR: String = "stop_color"
const val ATTRIB_SVG_STOP_OPACITY_STR: String = "stop_opacity"
const val ATTRIB_SVG_STRIKETHROUGH_POSITION_STR: String = "strikethrough_position"
const val ATTRIB_SVG_STRIKETHROUGH_THICKNESS_STR: String = "strikethrough_thickness"
const val ATTRIB_SVG_STROKE_STR: String = "stroke"
const val ATTRIB_SVG_STROKE_DASHARRAY_STR: String = "stroke_dasharray"
const val ATTRIB_SVG_STROKE_DASHOFFSET_STR: String = "stroke_dashoffset"
const val ATTRIB_SVG_STROKE_LINECAP_STR: String = "stroke_linecap"
const val ATTRIB_SVG_STROKE_LINEJOIN_STR: String = "stroke_linejoin"
const val ATTRIB_SVG_STROKE_MITERLIMIT_STR: String = "stroke_miterlimit"
const val ATTRIB_SVG_STROKE_OPACITY_STR: String = "stroke_opacity"
const val ATTRIB_SVG_STROKE_WIDTH_STR: String = "stroke_width"
const val ATTRIB_SVG_STYLE_STR: String = "style"
const val ATTRIB_SVG_SURFACESCALE_STR: String = "surfaceScale"
const val ATTRIB_SVG_SYSTEMLANGUAGE_STR: String = "systemLanguage"
const val ATTRIB_SVG_TABLEVALUES_STR: String = "tableValues"
const val ATTRIB_SVG_TARGET_STR: String = "target"
const val ATTRIB_SVG_TARGETX_STR: String = "targetX"
const val ATTRIB_SVG_TARGETY_STR: String = "targetY"
const val ATTRIB_SVG_TEXTLENGTH_STR: String = "textLength"
const val ATTRIB_SVG_TEXT_ANCHOR_STR: String = "text_anchor"
const val ATTRIB_SVG_TEXT_DECORATION_STR: String = "text_decoration"
const val ATTRIB_SVG_TEXT_RENDERING_STR: String = "text_rendering"
const val ATTRIB_SVG_TITLE_STR: String = "title"
const val ATTRIB_SVG_TO_STR: String = "to"
const val ATTRIB_SVG_TRANSFORM_STR: String = "transform"
const val ATTRIB_SVG_TYPE_STR: String = "type"
const val ATTRIB_SVG_U1_STR: String = "u1"
const val ATTRIB_SVG_U2_STR: String = "u2"
const val ATTRIB_SVG_UNDERLINE_POSITION_STR: String = "underline_position"
const val ATTRIB_SVG_UNDERLINE_THICKNESS_STR: String = "underline_thickness"
const val ATTRIB_SVG_UNICODE_STR: String = "unicode"
const val ATTRIB_SVG_UNICODE_BIDI_STR: String = "unicode_bidi"
const val ATTRIB_SVG_UNICODE_RANGE_STR: String = "unicode_range"
const val ATTRIB_SVG_UNITS_PER_EM_STR: String = "units_per_em"
const val ATTRIB_SVG_V_ALPHABETIC_STR: String = "v_alphabetic"
const val ATTRIB_SVG_V_HANGING_STR: String = "v_hanging"
const val ATTRIB_SVG_V_IDEOGRAPHIC_STR: String = "v_ideographic"
const val ATTRIB_SVG_V_MATHEMATICAL_STR: String = "v_mathematical"
const val ATTRIB_SVG_VALUES_STR: String = "values"
const val ATTRIB_SVG_VERSION_STR: String = "version"
const val ATTRIB_SVG_VERT_ADV_Y_STR: String = "vert_adv_y"
const val ATTRIB_SVG_VERT_ORIGIN_X_STR: String = "vert_origin_x"
const val ATTRIB_SVG_VERT_ORIGIN_Y_STR: String = "vert_origin_y"
const val ATTRIB_SVG_VIEWBOX_STR: String = "viewBox"
const val ATTRIB_SVG_VIEWTARGET_STR: String = "viewTarget"
const val ATTRIB_SVG_VISIBILITY_STR: String = "visibility"
const val ATTRIB_SVG_WIDTH_STR: String = "width"
const val ATTRIB_SVG_WIDTHS_STR: String = "widths"
const val ATTRIB_SVG_WORD_SPACING_STR: String = "word_spacing"
const val ATTRIB_SVG_WRITING_MODE_STR: String = "writing_mode"
const val ATTRIB_SVG_X_STR: String = "x"
const val ATTRIB_SVG_X1_STR: String = "x1"
const val ATTRIB_SVG_X2_STR: String = "x2"
const val ATTRIB_SVG_XCHANNELSELECTOR_STR: String = "xChannelSelector"
const val ATTRIB_SVG_X_HEIGHT_STR: String = "x_height"
const val ATTRIB_SVG_Y_STR: String = "y"
const val ATTRIB_SVG_Y1_STR: String = "y1"
const val ATTRIB_SVG_Y2_STR: String = "y2"
const val ATTRIB_SVG_YCHANNELSELECTOR_STR: String = "yChannelSelector"
const val ATTRIB_SVG_Z_STR: String = "z"
const val ATTRIB_SVG_ZOOMANDPAN_STR: String = "zoomAndPan"