// This file is generated by ConstMaker, DON'T MODIFY.

interface svg {

    enum ELEMENT {
        SVG_A_ID,
        SVG_ALTGLYPH_ID,
        SVG_ALTGLYPHDEF_ID,
        SVG_ALTGLYPHITEM_ID,
        SVG_ANIMATE_ID,
        SVG_ANIMATECOLOR_ID,
        SVG_ANIMATEMOTION_ID,
        SVG_ANIMATETRANSFORM_ID,
        SVG_CIRCLE_ID,
        SVG_CLIPPATH_ID,
        SVG_COLOR_PROFILE_ID,
        SVG_CURSOR_ID,
        SVG_DEFINITION_SRC_ID,
        SVG_DEFS_ID,
        SVG_DESC_ID,
        SVG_ELLIPSE_ID,
        SVG_FEBLEND_ID,
        SVG_FECOLORMATRIX_ID,
        SVG_FECOMPONENTTRANSFER_ID,
        SVG_FECOMPOSITE_ID,
        SVG_FECONVOLVEMATRIX_ID,
        SVG_FEDIFFUSELIGHTING_ID,
        SVG_FEDISPLACEMENTMAP_ID,
        SVG_FEDISTANTLIGHT_ID,
        SVG_FEFLOOD_ID,
        SVG_FEFUNCA_ID,
        SVG_FEFUNCB_ID,
        SVG_FEFUNCG_ID,
        SVG_FEFUNCR_ID,
        SVG_FEGAUSSIANBLUR_ID,
        SVG_FEIMAGE_ID,
        SVG_FEMERGE_ID,
        SVG_FEMERGENODE_ID,
        SVG_FEMORPHOLOGY_ID,
        SVG_FEOFFSET_ID,
        SVG_FEPOINTLIGHT_ID,
        SVG_FESPECULARLIGHTING_ID,
        SVG_FESPOTLIGHT_ID,
        SVG_FETILE_ID,
        SVG_FETURBULENCE_ID,
        SVG_FILTER_ID,
        SVG_FONT_ID,
        SVG_FONT_FACE_ID,
        SVG_FONT_FACE_FORMAT_ID,
        SVG_FONT_FACE_NAME_ID,
        SVG_FONT_FACE_SRC_ID,
        SVG_FONT_FACE_URI_ID,
        SVG_FOREIGNOBJECT_ID,
        SVG_G_ID,
        SVG_GLYPH_ID,
        SVG_GLYPHREF_ID,
        SVG_HKERN_ID,
        SVG_IMAGE_ID,
        SVG_LINE_ID,
        SVG_LINEARGRADIENT_ID,
        SVG_MARKER_ID,
        SVG_MASK_ID,
        SVG_METADATA_ID,
        SVG_MISSING_GLYPH_ID,
        SVG_MPATH_ID,
        SVG_PATH_ID,
        SVG_PATTERN_ID,
        SVG_POLYGON_ID,
        SVG_POLYLINE_ID,
        SVG_RADIALGRADIENT_ID,
        SVG_RECT_ID,
        SVG_SCRIPT_ID,
        SVG_SET_ID,
        SVG_STOP_ID,
        SVG_STYLE_ID,
        SVG_SVG_ID,
        SVG_SWITCH_ID,
        SVG_SYMBOL_ID,
        SVG_TEXT_ID,
        SVG_TEXTPATH_ID,
        SVG_TITLE_ID,
        SVG_TREF_ID,
        SVG_TSPAN_ID,
        SVG_USE_ID,
        SVG_VIEW_ID,
        SVG_VKERN_ID
    }
    public static final String ELEMENT_SVG_A_ID_STR = "SVG_A_ID";
    public static final String ELEMENT_SVG_ALTGLYPH_ID_STR = "SVG_ALTGLYPH_ID";
    public static final String ELEMENT_SVG_ALTGLYPHDEF_ID_STR = "SVG_ALTGLYPHDEF_ID";
    public static final String ELEMENT_SVG_ALTGLYPHITEM_ID_STR = "SVG_ALTGLYPHITEM_ID";
    public static final String ELEMENT_SVG_ANIMATE_ID_STR = "SVG_ANIMATE_ID";
    public static final String ELEMENT_SVG_ANIMATECOLOR_ID_STR = "SVG_ANIMATECOLOR_ID";
    public static final String ELEMENT_SVG_ANIMATEMOTION_ID_STR = "SVG_ANIMATEMOTION_ID";
    public static final String ELEMENT_SVG_ANIMATETRANSFORM_ID_STR = "SVG_ANIMATETRANSFORM_ID";
    public static final String ELEMENT_SVG_CIRCLE_ID_STR = "SVG_CIRCLE_ID";
    public static final String ELEMENT_SVG_CLIPPATH_ID_STR = "SVG_CLIPPATH_ID";
    public static final String ELEMENT_SVG_COLOR_PROFILE_ID_STR = "SVG_COLOR_PROFILE_ID";
    public static final String ELEMENT_SVG_CURSOR_ID_STR = "SVG_CURSOR_ID";
    public static final String ELEMENT_SVG_DEFINITION_SRC_ID_STR = "SVG_DEFINITION_SRC_ID";
    public static final String ELEMENT_SVG_DEFS_ID_STR = "SVG_DEFS_ID";
    public static final String ELEMENT_SVG_DESC_ID_STR = "SVG_DESC_ID";
    public static final String ELEMENT_SVG_ELLIPSE_ID_STR = "SVG_ELLIPSE_ID";
    public static final String ELEMENT_SVG_FEBLEND_ID_STR = "SVG_FEBLEND_ID";
    public static final String ELEMENT_SVG_FECOLORMATRIX_ID_STR = "SVG_FECOLORMATRIX_ID";
    public static final String ELEMENT_SVG_FECOMPONENTTRANSFER_ID_STR = "SVG_FECOMPONENTTRANSFER_ID";
    public static final String ELEMENT_SVG_FECOMPOSITE_ID_STR = "SVG_FECOMPOSITE_ID";
    public static final String ELEMENT_SVG_FECONVOLVEMATRIX_ID_STR = "SVG_FECONVOLVEMATRIX_ID";
    public static final String ELEMENT_SVG_FEDIFFUSELIGHTING_ID_STR = "SVG_FEDIFFUSELIGHTING_ID";
    public static final String ELEMENT_SVG_FEDISPLACEMENTMAP_ID_STR = "SVG_FEDISPLACEMENTMAP_ID";
    public static final String ELEMENT_SVG_FEDISTANTLIGHT_ID_STR = "SVG_FEDISTANTLIGHT_ID";
    public static final String ELEMENT_SVG_FEFLOOD_ID_STR = "SVG_FEFLOOD_ID";
    public static final String ELEMENT_SVG_FEFUNCA_ID_STR = "SVG_FEFUNCA_ID";
    public static final String ELEMENT_SVG_FEFUNCB_ID_STR = "SVG_FEFUNCB_ID";
    public static final String ELEMENT_SVG_FEFUNCG_ID_STR = "SVG_FEFUNCG_ID";
    public static final String ELEMENT_SVG_FEFUNCR_ID_STR = "SVG_FEFUNCR_ID";
    public static final String ELEMENT_SVG_FEGAUSSIANBLUR_ID_STR = "SVG_FEGAUSSIANBLUR_ID";
    public static final String ELEMENT_SVG_FEIMAGE_ID_STR = "SVG_FEIMAGE_ID";
    public static final String ELEMENT_SVG_FEMERGE_ID_STR = "SVG_FEMERGE_ID";
    public static final String ELEMENT_SVG_FEMERGENODE_ID_STR = "SVG_FEMERGENODE_ID";
    public static final String ELEMENT_SVG_FEMORPHOLOGY_ID_STR = "SVG_FEMORPHOLOGY_ID";
    public static final String ELEMENT_SVG_FEOFFSET_ID_STR = "SVG_FEOFFSET_ID";
    public static final String ELEMENT_SVG_FEPOINTLIGHT_ID_STR = "SVG_FEPOINTLIGHT_ID";
    public static final String ELEMENT_SVG_FESPECULARLIGHTING_ID_STR = "SVG_FESPECULARLIGHTING_ID";
    public static final String ELEMENT_SVG_FESPOTLIGHT_ID_STR = "SVG_FESPOTLIGHT_ID";
    public static final String ELEMENT_SVG_FETILE_ID_STR = "SVG_FETILE_ID";
    public static final String ELEMENT_SVG_FETURBULENCE_ID_STR = "SVG_FETURBULENCE_ID";
    public static final String ELEMENT_SVG_FILTER_ID_STR = "SVG_FILTER_ID";
    public static final String ELEMENT_SVG_FONT_ID_STR = "SVG_FONT_ID";
    public static final String ELEMENT_SVG_FONT_FACE_ID_STR = "SVG_FONT_FACE_ID";
    public static final String ELEMENT_SVG_FONT_FACE_FORMAT_ID_STR = "SVG_FONT_FACE_FORMAT_ID";
    public static final String ELEMENT_SVG_FONT_FACE_NAME_ID_STR = "SVG_FONT_FACE_NAME_ID";
    public static final String ELEMENT_SVG_FONT_FACE_SRC_ID_STR = "SVG_FONT_FACE_SRC_ID";
    public static final String ELEMENT_SVG_FONT_FACE_URI_ID_STR = "SVG_FONT_FACE_URI_ID";
    public static final String ELEMENT_SVG_FOREIGNOBJECT_ID_STR = "SVG_FOREIGNOBJECT_ID";
    public static final String ELEMENT_SVG_G_ID_STR = "SVG_G_ID";
    public static final String ELEMENT_SVG_GLYPH_ID_STR = "SVG_GLYPH_ID";
    public static final String ELEMENT_SVG_GLYPHREF_ID_STR = "SVG_GLYPHREF_ID";
    public static final String ELEMENT_SVG_HKERN_ID_STR = "SVG_HKERN_ID";
    public static final String ELEMENT_SVG_IMAGE_ID_STR = "SVG_IMAGE_ID";
    public static final String ELEMENT_SVG_LINE_ID_STR = "SVG_LINE_ID";
    public static final String ELEMENT_SVG_LINEARGRADIENT_ID_STR = "SVG_LINEARGRADIENT_ID";
    public static final String ELEMENT_SVG_MARKER_ID_STR = "SVG_MARKER_ID";
    public static final String ELEMENT_SVG_MASK_ID_STR = "SVG_MASK_ID";
    public static final String ELEMENT_SVG_METADATA_ID_STR = "SVG_METADATA_ID";
    public static final String ELEMENT_SVG_MISSING_GLYPH_ID_STR = "SVG_MISSING_GLYPH_ID";
    public static final String ELEMENT_SVG_MPATH_ID_STR = "SVG_MPATH_ID";
    public static final String ELEMENT_SVG_PATH_ID_STR = "SVG_PATH_ID";
    public static final String ELEMENT_SVG_PATTERN_ID_STR = "SVG_PATTERN_ID";
    public static final String ELEMENT_SVG_POLYGON_ID_STR = "SVG_POLYGON_ID";
    public static final String ELEMENT_SVG_POLYLINE_ID_STR = "SVG_POLYLINE_ID";
    public static final String ELEMENT_SVG_RADIALGRADIENT_ID_STR = "SVG_RADIALGRADIENT_ID";
    public static final String ELEMENT_SVG_RECT_ID_STR = "SVG_RECT_ID";
    public static final String ELEMENT_SVG_SCRIPT_ID_STR = "SVG_SCRIPT_ID";
    public static final String ELEMENT_SVG_SET_ID_STR = "SVG_SET_ID";
    public static final String ELEMENT_SVG_STOP_ID_STR = "SVG_STOP_ID";
    public static final String ELEMENT_SVG_STYLE_ID_STR = "SVG_STYLE_ID";
    public static final String ELEMENT_SVG_SVG_ID_STR = "SVG_SVG_ID";
    public static final String ELEMENT_SVG_SWITCH_ID_STR = "SVG_SWITCH_ID";
    public static final String ELEMENT_SVG_SYMBOL_ID_STR = "SVG_SYMBOL_ID";
    public static final String ELEMENT_SVG_TEXT_ID_STR = "SVG_TEXT_ID";
    public static final String ELEMENT_SVG_TEXTPATH_ID_STR = "SVG_TEXTPATH_ID";
    public static final String ELEMENT_SVG_TITLE_ID_STR = "SVG_TITLE_ID";
    public static final String ELEMENT_SVG_TREF_ID_STR = "SVG_TREF_ID";
    public static final String ELEMENT_SVG_TSPAN_ID_STR = "SVG_TSPAN_ID";
    public static final String ELEMENT_SVG_USE_ID_STR = "SVG_USE_ID";
    public static final String ELEMENT_SVG_VIEW_ID_STR = "SVG_VIEW_ID";
    public static final String ELEMENT_SVG_VKERN_ID_STR = "SVG_VKERN_ID";

    enum ATTRIB {
        SVG_ACCENT_HEIGHT,
        SVG_ACCUMULATE,
        SVG_ADDITIVE,
        SVG_ALIGNMENT_BASELINE,
        SVG_ALPHABETIC,
        SVG_AMPLITUDE,
        SVG_ANIMATE,
        SVG_ARABIC_FORM,
        SVG_ASCENT,
        SVG_ATTRIBUTENAME,
        SVG_ATTRIBUTETYPE,
        SVG_AZIMUTH,
        SVG_BASEFREQUENCY,
        SVG_BASEPROFILE,
        SVG_BASELINE_SHIFT,
        SVG_BBOX,
        SVG_BEGIN,
        SVG_BIAS,
        SVG_BY,
        SVG_CALCMODE,
        SVG_CAP_HEIGHT,
        SVG_CLIP,
        SVG_CLIPPATHUNITS,
        SVG_CLIP_PATH,
        SVG_CLIP_RULE,
        SVG_COLOR,
        SVG_COLOR_INTERPOLATION,
        SVG_COLOR_INTERPOLATION_FILTERS,
        SVG_COLOR_PROFILE,
        SVG_COLOR_RENDERING,
        SVG_CONTENTSCRIPTTYPE,
        SVG_CONTENTSTYLETYPE,
        SVG_CURSOR,
        SVG_CX,
        SVG_CY,
        SVG_D,
        SVG_DESCENT,
        SVG_DIFFUSECONSTANT,
        SVG_DIRECTION,
        SVG_DISPLAY,
        SVG_DIVISOR,
        SVG_DOMINANT_BASELINE,
        SVG_DUR,
        SVG_DX,
        SVG_DY,
        SVG_EDGEMODE,
        SVG_ELEVATION,
        SVG_ENABLE_BACKGROUND,
        SVG_END,
        SVG_EXPONENT,
        SVG_EXTERNALRESOURCESREQUIRED,
        SVG_FECOLORMATRIX,
        SVG_FECOMPOSITE,
        SVG_FEGAUSSIANBLUR,
        SVG_FEMORPHOLOGY,
        SVG_FETILE,
        SVG_FILL,
        SVG_FILL_OPACITY,
        SVG_FILL_RULE,
        SVG_FILTER,
        SVG_FILTERRES,
        SVG_FILTERUNITS,
        SVG_FLOOD_COLOR,
        SVG_FLOOD_OPACITY,
        SVG_FONT_FAMILY,
        SVG_FONT_SIZE,
        SVG_FONT_SIZE_ADJUST,
        SVG_FONT_STRETCH,
        SVG_FONT_STYLE,
        SVG_FONT_VARIANT,
        SVG_FONT_WEIGHT,
        SVG_FORMAT,
        SVG_FROM,
        SVG_FX,
        SVG_FY,
        SVG_G1,
        SVG_G2,
        SVG_GLYPHREF,
        SVG_GLYPH_NAME,
        SVG_GLYPH_ORIENTATION_HORIZONTAL,
        SVG_GLYPH_ORIENTATION_VERTICAL,
        SVG_GRADIENTTRANSFORM,
        SVG_GRADIENTUNITS,
        SVG_HANGING,
        SVG_HEIGHT,
        SVG_HORIZ_ADV_X,
        SVG_HORIZ_ORIGIN_X,
        SVG_HORIZ_ORIGIN_Y,
        SVG_IDEOGRAPHIC,
        SVG_IMAGE_RENDERING,
        SVG_IN,
        SVG_IN2,
        SVG_INTERCEPT,
        SVG_K,
        SVG_K1,
        SVG_K2,
        SVG_K3,
        SVG_K4,
        SVG_KERNELMATRIX,
        SVG_KERNELUNITLENGTH,
        SVG_KERNING,
        SVG_KEYPOINTS,
        SVG_KEYSPLINES,
        SVG_KEYTIMES,
        SVG_LANG,
        SVG_LENGTHADJUST,
        SVG_LETTER_SPACING,
        SVG_LIGHTING_COLOR,
        SVG_LIMITINGCONEANGLE,
        SVG_LOCAL,
        SVG_MARKERHEIGHT,
        SVG_MARKERUNITS,
        SVG_MARKERWIDTH,
        SVG_MARKER_END,
        SVG_MARKER_MID,
        SVG_MARKER_START,
        SVG_MASK,
        SVG_MASKCONTENTUNITS,
        SVG_MASKUNITS,
        SVG_MATHEMATICAL,
        SVG_MAX,
        SVG_MEDIA,
        SVG_METHOD,
        SVG_MIN,
        SVG_MODE,
        SVG_NAME,
        SVG_NUMOCTAVES,
        SVG_OFFSET,
        SVG_ONACTIVATE,
        SVG_ONBEGIN,
        SVG_ONEND,
        SVG_ONFOCUSIN,
        SVG_ONFOCUSOUT,
        SVG_ONREPEAT,
        SVG_ONZOOM,
        SVG_OPACITY,
        SVG_OPERATOR,
        SVG_ORDER,
        SVG_ORIENT,
        SVG_ORIENTATION,
        SVG_ORIGIN,
        SVG_OVERFLOW,
        SVG_OVERLINE_POSITION,
        SVG_OVERLINE_THICKNESS,
        SVG_PANOSE_1,
        SVG_PATH,
        SVG_PATHLENGTH,
        SVG_PATTERNCONTENTUNITS,
        SVG_PATTERNTRANSFORM,
        SVG_PATTERNUNITS,
        SVG_POINTER_EVENTS,
        SVG_POINTS,
        SVG_POINTSATX,
        SVG_POINTSATY,
        SVG_POINTSATZ,
        SVG_PRESERVEALPHA,
        SVG_PRESERVEASPECTRATIO,
        SVG_PRIMITIVEUNITS,
        SVG_R,
        SVG_RADIUS,
        SVG_REFX,
        SVG_REFY,
        SVG_RENDERING_INTENT,
        SVG_REPEATCOUNT,
        SVG_REPEATDUR,
        SVG_REQUIREDEXTENSIONS,
        SVG_REQUIREDFEATURES,
        SVG_RESTART,
        SVG_RESULT,
        SVG_ROTATE,
        SVG_RX,
        SVG_RY,
        SVG_SCALE,
        SVG_SEED,
        SVG_SHAPE_RENDERING,
        SVG_SLOPE,
        SVG_SPACING,
        SVG_SPECULARCONSTANT,
        SVG_SPECULAREXPONENT,
        SVG_SPREADMETHOD,
        SVG_STARTOFFSET,
        SVG_STDDEVIATION,
        SVG_STEMH,
        SVG_STEMV,
        SVG_STITCHTILES,
        SVG_STOP_COLOR,
        SVG_STOP_OPACITY,
        SVG_STRIKETHROUGH_POSITION,
        SVG_STRIKETHROUGH_THICKNESS,
        SVG_STROKE,
        SVG_STROKE_DASHARRAY,
        SVG_STROKE_DASHOFFSET,
        SVG_STROKE_LINECAP,
        SVG_STROKE_LINEJOIN,
        SVG_STROKE_MITERLIMIT,
        SVG_STROKE_OPACITY,
        SVG_STROKE_WIDTH,
        SVG_STYLE,
        SVG_SURFACESCALE,
        SVG_SYSTEMLANGUAGE,
        SVG_TABLEVALUES,
        SVG_TARGET,
        SVG_TARGETX,
        SVG_TARGETY,
        SVG_TEXTLENGTH,
        SVG_TEXT_ANCHOR,
        SVG_TEXT_DECORATION,
        SVG_TEXT_RENDERING,
        SVG_TITLE,
        SVG_TO,
        SVG_TRANSFORM,
        SVG_TYPE,
        SVG_U1,
        SVG_U2,
        SVG_UNDERLINE_POSITION,
        SVG_UNDERLINE_THICKNESS,
        SVG_UNICODE,
        SVG_UNICODE_BIDI,
        SVG_UNICODE_RANGE,
        SVG_UNITS_PER_EM,
        SVG_V_ALPHABETIC,
        SVG_V_HANGING,
        SVG_V_IDEOGRAPHIC,
        SVG_V_MATHEMATICAL,
        SVG_VALUES,
        SVG_VERSION,
        SVG_VERT_ADV_Y,
        SVG_VERT_ORIGIN_X,
        SVG_VERT_ORIGIN_Y,
        SVG_VIEWBOX,
        SVG_VIEWTARGET,
        SVG_VISIBILITY,
        SVG_WIDTH,
        SVG_WIDTHS,
        SVG_WORD_SPACING,
        SVG_WRITING_MODE,
        SVG_X,
        SVG_X1,
        SVG_X2,
        SVG_XCHANNELSELECTOR,
        SVG_X_HEIGHT,
        SVG_Y,
        SVG_Y1,
        SVG_Y2,
        SVG_YCHANNELSELECTOR,
        SVG_Z,
        SVG_ZOOMANDPAN
    }
    public static final String ATTRIB_SVG_ACCENT_HEIGHT_STR = "SVG_ACCENT_HEIGHT";
    public static final String ATTRIB_SVG_ACCUMULATE_STR = "SVG_ACCUMULATE";
    public static final String ATTRIB_SVG_ADDITIVE_STR = "SVG_ADDITIVE";
    public static final String ATTRIB_SVG_ALIGNMENT_BASELINE_STR = "SVG_ALIGNMENT_BASELINE";
    public static final String ATTRIB_SVG_ALPHABETIC_STR = "SVG_ALPHABETIC";
    public static final String ATTRIB_SVG_AMPLITUDE_STR = "SVG_AMPLITUDE";
    public static final String ATTRIB_SVG_ANIMATE_STR = "SVG_ANIMATE";
    public static final String ATTRIB_SVG_ARABIC_FORM_STR = "SVG_ARABIC_FORM";
    public static final String ATTRIB_SVG_ASCENT_STR = "SVG_ASCENT";
    public static final String ATTRIB_SVG_ATTRIBUTENAME_STR = "SVG_ATTRIBUTENAME";
    public static final String ATTRIB_SVG_ATTRIBUTETYPE_STR = "SVG_ATTRIBUTETYPE";
    public static final String ATTRIB_SVG_AZIMUTH_STR = "SVG_AZIMUTH";
    public static final String ATTRIB_SVG_BASEFREQUENCY_STR = "SVG_BASEFREQUENCY";
    public static final String ATTRIB_SVG_BASEPROFILE_STR = "SVG_BASEPROFILE";
    public static final String ATTRIB_SVG_BASELINE_SHIFT_STR = "SVG_BASELINE_SHIFT";
    public static final String ATTRIB_SVG_BBOX_STR = "SVG_BBOX";
    public static final String ATTRIB_SVG_BEGIN_STR = "SVG_BEGIN";
    public static final String ATTRIB_SVG_BIAS_STR = "SVG_BIAS";
    public static final String ATTRIB_SVG_BY_STR = "SVG_BY";
    public static final String ATTRIB_SVG_CALCMODE_STR = "SVG_CALCMODE";
    public static final String ATTRIB_SVG_CAP_HEIGHT_STR = "SVG_CAP_HEIGHT";
    public static final String ATTRIB_SVG_CLIP_STR = "SVG_CLIP";
    public static final String ATTRIB_SVG_CLIPPATHUNITS_STR = "SVG_CLIPPATHUNITS";
    public static final String ATTRIB_SVG_CLIP_PATH_STR = "SVG_CLIP_PATH";
    public static final String ATTRIB_SVG_CLIP_RULE_STR = "SVG_CLIP_RULE";
    public static final String ATTRIB_SVG_COLOR_STR = "SVG_COLOR";
    public static final String ATTRIB_SVG_COLOR_INTERPOLATION_STR = "SVG_COLOR_INTERPOLATION";
    public static final String ATTRIB_SVG_COLOR_INTERPOLATION_FILTERS_STR = "SVG_COLOR_INTERPOLATION_FILTERS";
    public static final String ATTRIB_SVG_COLOR_PROFILE_STR = "SVG_COLOR_PROFILE";
    public static final String ATTRIB_SVG_COLOR_RENDERING_STR = "SVG_COLOR_RENDERING";
    public static final String ATTRIB_SVG_CONTENTSCRIPTTYPE_STR = "SVG_CONTENTSCRIPTTYPE";
    public static final String ATTRIB_SVG_CONTENTSTYLETYPE_STR = "SVG_CONTENTSTYLETYPE";
    public static final String ATTRIB_SVG_CURSOR_STR = "SVG_CURSOR";
    public static final String ATTRIB_SVG_CX_STR = "SVG_CX";
    public static final String ATTRIB_SVG_CY_STR = "SVG_CY";
    public static final String ATTRIB_SVG_D_STR = "SVG_D";
    public static final String ATTRIB_SVG_DESCENT_STR = "SVG_DESCENT";
    public static final String ATTRIB_SVG_DIFFUSECONSTANT_STR = "SVG_DIFFUSECONSTANT";
    public static final String ATTRIB_SVG_DIRECTION_STR = "SVG_DIRECTION";
    public static final String ATTRIB_SVG_DISPLAY_STR = "SVG_DISPLAY";
    public static final String ATTRIB_SVG_DIVISOR_STR = "SVG_DIVISOR";
    public static final String ATTRIB_SVG_DOMINANT_BASELINE_STR = "SVG_DOMINANT_BASELINE";
    public static final String ATTRIB_SVG_DUR_STR = "SVG_DUR";
    public static final String ATTRIB_SVG_DX_STR = "SVG_DX";
    public static final String ATTRIB_SVG_DY_STR = "SVG_DY";
    public static final String ATTRIB_SVG_EDGEMODE_STR = "SVG_EDGEMODE";
    public static final String ATTRIB_SVG_ELEVATION_STR = "SVG_ELEVATION";
    public static final String ATTRIB_SVG_ENABLE_BACKGROUND_STR = "SVG_ENABLE_BACKGROUND";
    public static final String ATTRIB_SVG_END_STR = "SVG_END";
    public static final String ATTRIB_SVG_EXPONENT_STR = "SVG_EXPONENT";
    public static final String ATTRIB_SVG_EXTERNALRESOURCESREQUIRED_STR = "SVG_EXTERNALRESOURCESREQUIRED";
    public static final String ATTRIB_SVG_FECOLORMATRIX_STR = "SVG_FECOLORMATRIX";
    public static final String ATTRIB_SVG_FECOMPOSITE_STR = "SVG_FECOMPOSITE";
    public static final String ATTRIB_SVG_FEGAUSSIANBLUR_STR = "SVG_FEGAUSSIANBLUR";
    public static final String ATTRIB_SVG_FEMORPHOLOGY_STR = "SVG_FEMORPHOLOGY";
    public static final String ATTRIB_SVG_FETILE_STR = "SVG_FETILE";
    public static final String ATTRIB_SVG_FILL_STR = "SVG_FILL";
    public static final String ATTRIB_SVG_FILL_OPACITY_STR = "SVG_FILL_OPACITY";
    public static final String ATTRIB_SVG_FILL_RULE_STR = "SVG_FILL_RULE";
    public static final String ATTRIB_SVG_FILTER_STR = "SVG_FILTER";
    public static final String ATTRIB_SVG_FILTERRES_STR = "SVG_FILTERRES";
    public static final String ATTRIB_SVG_FILTERUNITS_STR = "SVG_FILTERUNITS";
    public static final String ATTRIB_SVG_FLOOD_COLOR_STR = "SVG_FLOOD_COLOR";
    public static final String ATTRIB_SVG_FLOOD_OPACITY_STR = "SVG_FLOOD_OPACITY";
    public static final String ATTRIB_SVG_FONT_FAMILY_STR = "SVG_FONT_FAMILY";
    public static final String ATTRIB_SVG_FONT_SIZE_STR = "SVG_FONT_SIZE";
    public static final String ATTRIB_SVG_FONT_SIZE_ADJUST_STR = "SVG_FONT_SIZE_ADJUST";
    public static final String ATTRIB_SVG_FONT_STRETCH_STR = "SVG_FONT_STRETCH";
    public static final String ATTRIB_SVG_FONT_STYLE_STR = "SVG_FONT_STYLE";
    public static final String ATTRIB_SVG_FONT_VARIANT_STR = "SVG_FONT_VARIANT";
    public static final String ATTRIB_SVG_FONT_WEIGHT_STR = "SVG_FONT_WEIGHT";
    public static final String ATTRIB_SVG_FORMAT_STR = "SVG_FORMAT";
    public static final String ATTRIB_SVG_FROM_STR = "SVG_FROM";
    public static final String ATTRIB_SVG_FX_STR = "SVG_FX";
    public static final String ATTRIB_SVG_FY_STR = "SVG_FY";
    public static final String ATTRIB_SVG_G1_STR = "SVG_G1";
    public static final String ATTRIB_SVG_G2_STR = "SVG_G2";
    public static final String ATTRIB_SVG_GLYPHREF_STR = "SVG_GLYPHREF";
    public static final String ATTRIB_SVG_GLYPH_NAME_STR = "SVG_GLYPH_NAME";
    public static final String ATTRIB_SVG_GLYPH_ORIENTATION_HORIZONTAL_STR = "SVG_GLYPH_ORIENTATION_HORIZONTAL";
    public static final String ATTRIB_SVG_GLYPH_ORIENTATION_VERTICAL_STR = "SVG_GLYPH_ORIENTATION_VERTICAL";
    public static final String ATTRIB_SVG_GRADIENTTRANSFORM_STR = "SVG_GRADIENTTRANSFORM";
    public static final String ATTRIB_SVG_GRADIENTUNITS_STR = "SVG_GRADIENTUNITS";
    public static final String ATTRIB_SVG_HANGING_STR = "SVG_HANGING";
    public static final String ATTRIB_SVG_HEIGHT_STR = "SVG_HEIGHT";
    public static final String ATTRIB_SVG_HORIZ_ADV_X_STR = "SVG_HORIZ_ADV_X";
    public static final String ATTRIB_SVG_HORIZ_ORIGIN_X_STR = "SVG_HORIZ_ORIGIN_X";
    public static final String ATTRIB_SVG_HORIZ_ORIGIN_Y_STR = "SVG_HORIZ_ORIGIN_Y";
    public static final String ATTRIB_SVG_IDEOGRAPHIC_STR = "SVG_IDEOGRAPHIC";
    public static final String ATTRIB_SVG_IMAGE_RENDERING_STR = "SVG_IMAGE_RENDERING";
    public static final String ATTRIB_SVG_IN_STR = "SVG_IN";
    public static final String ATTRIB_SVG_IN2_STR = "SVG_IN2";
    public static final String ATTRIB_SVG_INTERCEPT_STR = "SVG_INTERCEPT";
    public static final String ATTRIB_SVG_K_STR = "SVG_K";
    public static final String ATTRIB_SVG_K1_STR = "SVG_K1";
    public static final String ATTRIB_SVG_K2_STR = "SVG_K2";
    public static final String ATTRIB_SVG_K3_STR = "SVG_K3";
    public static final String ATTRIB_SVG_K4_STR = "SVG_K4";
    public static final String ATTRIB_SVG_KERNELMATRIX_STR = "SVG_KERNELMATRIX";
    public static final String ATTRIB_SVG_KERNELUNITLENGTH_STR = "SVG_KERNELUNITLENGTH";
    public static final String ATTRIB_SVG_KERNING_STR = "SVG_KERNING";
    public static final String ATTRIB_SVG_KEYPOINTS_STR = "SVG_KEYPOINTS";
    public static final String ATTRIB_SVG_KEYSPLINES_STR = "SVG_KEYSPLINES";
    public static final String ATTRIB_SVG_KEYTIMES_STR = "SVG_KEYTIMES";
    public static final String ATTRIB_SVG_LANG_STR = "SVG_LANG";
    public static final String ATTRIB_SVG_LENGTHADJUST_STR = "SVG_LENGTHADJUST";
    public static final String ATTRIB_SVG_LETTER_SPACING_STR = "SVG_LETTER_SPACING";
    public static final String ATTRIB_SVG_LIGHTING_COLOR_STR = "SVG_LIGHTING_COLOR";
    public static final String ATTRIB_SVG_LIMITINGCONEANGLE_STR = "SVG_LIMITINGCONEANGLE";
    public static final String ATTRIB_SVG_LOCAL_STR = "SVG_LOCAL";
    public static final String ATTRIB_SVG_MARKERHEIGHT_STR = "SVG_MARKERHEIGHT";
    public static final String ATTRIB_SVG_MARKERUNITS_STR = "SVG_MARKERUNITS";
    public static final String ATTRIB_SVG_MARKERWIDTH_STR = "SVG_MARKERWIDTH";
    public static final String ATTRIB_SVG_MARKER_END_STR = "SVG_MARKER_END";
    public static final String ATTRIB_SVG_MARKER_MID_STR = "SVG_MARKER_MID";
    public static final String ATTRIB_SVG_MARKER_START_STR = "SVG_MARKER_START";
    public static final String ATTRIB_SVG_MASK_STR = "SVG_MASK";
    public static final String ATTRIB_SVG_MASKCONTENTUNITS_STR = "SVG_MASKCONTENTUNITS";
    public static final String ATTRIB_SVG_MASKUNITS_STR = "SVG_MASKUNITS";
    public static final String ATTRIB_SVG_MATHEMATICAL_STR = "SVG_MATHEMATICAL";
    public static final String ATTRIB_SVG_MAX_STR = "SVG_MAX";
    public static final String ATTRIB_SVG_MEDIA_STR = "SVG_MEDIA";
    public static final String ATTRIB_SVG_METHOD_STR = "SVG_METHOD";
    public static final String ATTRIB_SVG_MIN_STR = "SVG_MIN";
    public static final String ATTRIB_SVG_MODE_STR = "SVG_MODE";
    public static final String ATTRIB_SVG_NAME_STR = "SVG_NAME";
    public static final String ATTRIB_SVG_NUMOCTAVES_STR = "SVG_NUMOCTAVES";
    public static final String ATTRIB_SVG_OFFSET_STR = "SVG_OFFSET";
    public static final String ATTRIB_SVG_ONACTIVATE_STR = "SVG_ONACTIVATE";
    public static final String ATTRIB_SVG_ONBEGIN_STR = "SVG_ONBEGIN";
    public static final String ATTRIB_SVG_ONEND_STR = "SVG_ONEND";
    public static final String ATTRIB_SVG_ONFOCUSIN_STR = "SVG_ONFOCUSIN";
    public static final String ATTRIB_SVG_ONFOCUSOUT_STR = "SVG_ONFOCUSOUT";
    public static final String ATTRIB_SVG_ONREPEAT_STR = "SVG_ONREPEAT";
    public static final String ATTRIB_SVG_ONZOOM_STR = "SVG_ONZOOM";
    public static final String ATTRIB_SVG_OPACITY_STR = "SVG_OPACITY";
    public static final String ATTRIB_SVG_OPERATOR_STR = "SVG_OPERATOR";
    public static final String ATTRIB_SVG_ORDER_STR = "SVG_ORDER";
    public static final String ATTRIB_SVG_ORIENT_STR = "SVG_ORIENT";
    public static final String ATTRIB_SVG_ORIENTATION_STR = "SVG_ORIENTATION";
    public static final String ATTRIB_SVG_ORIGIN_STR = "SVG_ORIGIN";
    public static final String ATTRIB_SVG_OVERFLOW_STR = "SVG_OVERFLOW";
    public static final String ATTRIB_SVG_OVERLINE_POSITION_STR = "SVG_OVERLINE_POSITION";
    public static final String ATTRIB_SVG_OVERLINE_THICKNESS_STR = "SVG_OVERLINE_THICKNESS";
    public static final String ATTRIB_SVG_PANOSE_1_STR = "SVG_PANOSE_1";
    public static final String ATTRIB_SVG_PATH_STR = "SVG_PATH";
    public static final String ATTRIB_SVG_PATHLENGTH_STR = "SVG_PATHLENGTH";
    public static final String ATTRIB_SVG_PATTERNCONTENTUNITS_STR = "SVG_PATTERNCONTENTUNITS";
    public static final String ATTRIB_SVG_PATTERNTRANSFORM_STR = "SVG_PATTERNTRANSFORM";
    public static final String ATTRIB_SVG_PATTERNUNITS_STR = "SVG_PATTERNUNITS";
    public static final String ATTRIB_SVG_POINTER_EVENTS_STR = "SVG_POINTER_EVENTS";
    public static final String ATTRIB_SVG_POINTS_STR = "SVG_POINTS";
    public static final String ATTRIB_SVG_POINTSATX_STR = "SVG_POINTSATX";
    public static final String ATTRIB_SVG_POINTSATY_STR = "SVG_POINTSATY";
    public static final String ATTRIB_SVG_POINTSATZ_STR = "SVG_POINTSATZ";
    public static final String ATTRIB_SVG_PRESERVEALPHA_STR = "SVG_PRESERVEALPHA";
    public static final String ATTRIB_SVG_PRESERVEASPECTRATIO_STR = "SVG_PRESERVEASPECTRATIO";
    public static final String ATTRIB_SVG_PRIMITIVEUNITS_STR = "SVG_PRIMITIVEUNITS";
    public static final String ATTRIB_SVG_R_STR = "SVG_R";
    public static final String ATTRIB_SVG_RADIUS_STR = "SVG_RADIUS";
    public static final String ATTRIB_SVG_REFX_STR = "SVG_REFX";
    public static final String ATTRIB_SVG_REFY_STR = "SVG_REFY";
    public static final String ATTRIB_SVG_RENDERING_INTENT_STR = "SVG_RENDERING_INTENT";
    public static final String ATTRIB_SVG_REPEATCOUNT_STR = "SVG_REPEATCOUNT";
    public static final String ATTRIB_SVG_REPEATDUR_STR = "SVG_REPEATDUR";
    public static final String ATTRIB_SVG_REQUIREDEXTENSIONS_STR = "SVG_REQUIREDEXTENSIONS";
    public static final String ATTRIB_SVG_REQUIREDFEATURES_STR = "SVG_REQUIREDFEATURES";
    public static final String ATTRIB_SVG_RESTART_STR = "SVG_RESTART";
    public static final String ATTRIB_SVG_RESULT_STR = "SVG_RESULT";
    public static final String ATTRIB_SVG_ROTATE_STR = "SVG_ROTATE";
    public static final String ATTRIB_SVG_RX_STR = "SVG_RX";
    public static final String ATTRIB_SVG_RY_STR = "SVG_RY";
    public static final String ATTRIB_SVG_SCALE_STR = "SVG_SCALE";
    public static final String ATTRIB_SVG_SEED_STR = "SVG_SEED";
    public static final String ATTRIB_SVG_SHAPE_RENDERING_STR = "SVG_SHAPE_RENDERING";
    public static final String ATTRIB_SVG_SLOPE_STR = "SVG_SLOPE";
    public static final String ATTRIB_SVG_SPACING_STR = "SVG_SPACING";
    public static final String ATTRIB_SVG_SPECULARCONSTANT_STR = "SVG_SPECULARCONSTANT";
    public static final String ATTRIB_SVG_SPECULAREXPONENT_STR = "SVG_SPECULAREXPONENT";
    public static final String ATTRIB_SVG_SPREADMETHOD_STR = "SVG_SPREADMETHOD";
    public static final String ATTRIB_SVG_STARTOFFSET_STR = "SVG_STARTOFFSET";
    public static final String ATTRIB_SVG_STDDEVIATION_STR = "SVG_STDDEVIATION";
    public static final String ATTRIB_SVG_STEMH_STR = "SVG_STEMH";
    public static final String ATTRIB_SVG_STEMV_STR = "SVG_STEMV";
    public static final String ATTRIB_SVG_STITCHTILES_STR = "SVG_STITCHTILES";
    public static final String ATTRIB_SVG_STOP_COLOR_STR = "SVG_STOP_COLOR";
    public static final String ATTRIB_SVG_STOP_OPACITY_STR = "SVG_STOP_OPACITY";
    public static final String ATTRIB_SVG_STRIKETHROUGH_POSITION_STR = "SVG_STRIKETHROUGH_POSITION";
    public static final String ATTRIB_SVG_STRIKETHROUGH_THICKNESS_STR = "SVG_STRIKETHROUGH_THICKNESS";
    public static final String ATTRIB_SVG_STROKE_STR = "SVG_STROKE";
    public static final String ATTRIB_SVG_STROKE_DASHARRAY_STR = "SVG_STROKE_DASHARRAY";
    public static final String ATTRIB_SVG_STROKE_DASHOFFSET_STR = "SVG_STROKE_DASHOFFSET";
    public static final String ATTRIB_SVG_STROKE_LINECAP_STR = "SVG_STROKE_LINECAP";
    public static final String ATTRIB_SVG_STROKE_LINEJOIN_STR = "SVG_STROKE_LINEJOIN";
    public static final String ATTRIB_SVG_STROKE_MITERLIMIT_STR = "SVG_STROKE_MITERLIMIT";
    public static final String ATTRIB_SVG_STROKE_OPACITY_STR = "SVG_STROKE_OPACITY";
    public static final String ATTRIB_SVG_STROKE_WIDTH_STR = "SVG_STROKE_WIDTH";
    public static final String ATTRIB_SVG_STYLE_STR = "SVG_STYLE";
    public static final String ATTRIB_SVG_SURFACESCALE_STR = "SVG_SURFACESCALE";
    public static final String ATTRIB_SVG_SYSTEMLANGUAGE_STR = "SVG_SYSTEMLANGUAGE";
    public static final String ATTRIB_SVG_TABLEVALUES_STR = "SVG_TABLEVALUES";
    public static final String ATTRIB_SVG_TARGET_STR = "SVG_TARGET";
    public static final String ATTRIB_SVG_TARGETX_STR = "SVG_TARGETX";
    public static final String ATTRIB_SVG_TARGETY_STR = "SVG_TARGETY";
    public static final String ATTRIB_SVG_TEXTLENGTH_STR = "SVG_TEXTLENGTH";
    public static final String ATTRIB_SVG_TEXT_ANCHOR_STR = "SVG_TEXT_ANCHOR";
    public static final String ATTRIB_SVG_TEXT_DECORATION_STR = "SVG_TEXT_DECORATION";
    public static final String ATTRIB_SVG_TEXT_RENDERING_STR = "SVG_TEXT_RENDERING";
    public static final String ATTRIB_SVG_TITLE_STR = "SVG_TITLE";
    public static final String ATTRIB_SVG_TO_STR = "SVG_TO";
    public static final String ATTRIB_SVG_TRANSFORM_STR = "SVG_TRANSFORM";
    public static final String ATTRIB_SVG_TYPE_STR = "SVG_TYPE";
    public static final String ATTRIB_SVG_U1_STR = "SVG_U1";
    public static final String ATTRIB_SVG_U2_STR = "SVG_U2";
    public static final String ATTRIB_SVG_UNDERLINE_POSITION_STR = "SVG_UNDERLINE_POSITION";
    public static final String ATTRIB_SVG_UNDERLINE_THICKNESS_STR = "SVG_UNDERLINE_THICKNESS";
    public static final String ATTRIB_SVG_UNICODE_STR = "SVG_UNICODE";
    public static final String ATTRIB_SVG_UNICODE_BIDI_STR = "SVG_UNICODE_BIDI";
    public static final String ATTRIB_SVG_UNICODE_RANGE_STR = "SVG_UNICODE_RANGE";
    public static final String ATTRIB_SVG_UNITS_PER_EM_STR = "SVG_UNITS_PER_EM";
    public static final String ATTRIB_SVG_V_ALPHABETIC_STR = "SVG_V_ALPHABETIC";
    public static final String ATTRIB_SVG_V_HANGING_STR = "SVG_V_HANGING";
    public static final String ATTRIB_SVG_V_IDEOGRAPHIC_STR = "SVG_V_IDEOGRAPHIC";
    public static final String ATTRIB_SVG_V_MATHEMATICAL_STR = "SVG_V_MATHEMATICAL";
    public static final String ATTRIB_SVG_VALUES_STR = "SVG_VALUES";
    public static final String ATTRIB_SVG_VERSION_STR = "SVG_VERSION";
    public static final String ATTRIB_SVG_VERT_ADV_Y_STR = "SVG_VERT_ADV_Y";
    public static final String ATTRIB_SVG_VERT_ORIGIN_X_STR = "SVG_VERT_ORIGIN_X";
    public static final String ATTRIB_SVG_VERT_ORIGIN_Y_STR = "SVG_VERT_ORIGIN_Y";
    public static final String ATTRIB_SVG_VIEWBOX_STR = "SVG_VIEWBOX";
    public static final String ATTRIB_SVG_VIEWTARGET_STR = "SVG_VIEWTARGET";
    public static final String ATTRIB_SVG_VISIBILITY_STR = "SVG_VISIBILITY";
    public static final String ATTRIB_SVG_WIDTH_STR = "SVG_WIDTH";
    public static final String ATTRIB_SVG_WIDTHS_STR = "SVG_WIDTHS";
    public static final String ATTRIB_SVG_WORD_SPACING_STR = "SVG_WORD_SPACING";
    public static final String ATTRIB_SVG_WRITING_MODE_STR = "SVG_WRITING_MODE";
    public static final String ATTRIB_SVG_X_STR = "SVG_X";
    public static final String ATTRIB_SVG_X1_STR = "SVG_X1";
    public static final String ATTRIB_SVG_X2_STR = "SVG_X2";
    public static final String ATTRIB_SVG_XCHANNELSELECTOR_STR = "SVG_XCHANNELSELECTOR";
    public static final String ATTRIB_SVG_X_HEIGHT_STR = "SVG_X_HEIGHT";
    public static final String ATTRIB_SVG_Y_STR = "SVG_Y";
    public static final String ATTRIB_SVG_Y1_STR = "SVG_Y1";
    public static final String ATTRIB_SVG_Y2_STR = "SVG_Y2";
    public static final String ATTRIB_SVG_YCHANNELSELECTOR_STR = "SVG_YCHANNELSELECTOR";
    public static final String ATTRIB_SVG_Z_STR = "SVG_Z";
    public static final String ATTRIB_SVG_ZOOMANDPAN_STR = "SVG_ZOOMANDPAN";
}