// This file is generated by ConstMaker, DON'T MODIFY.


#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug, Hash)]
pub enum ELEMENT {
    SVG_A_ID,
    SVG_ALTGLYPH_ID,
    SVG_ALTGLYPHDEF_ID,
    SVG_ALTGLYPHITEM_ID,
    SVG_ANIMATE_ID,
    SVG_ANIMATECOLOR_ID,
    SVG_ANIMATEMOTION_ID,
    SVG_ANIMATETRANSFORM_ID,
    SVG_CIRCLE_ID,
    SVG_CLIPPATH_ID,
    SVG_COLOR_PROFILE_ID,
    SVG_CURSOR_ID,
    SVG_DEFINITION_SRC_ID,
    SVG_DEFS_ID,
    SVG_DESC_ID,
    SVG_ELLIPSE_ID,
    SVG_FEBLEND_ID,
    SVG_FECOLORMATRIX_ID,
    SVG_FECOMPONENTTRANSFER_ID,
    SVG_FECOMPOSITE_ID,
    SVG_FECONVOLVEMATRIX_ID,
    SVG_FEDIFFUSELIGHTING_ID,
    SVG_FEDISPLACEMENTMAP_ID,
    SVG_FEDISTANTLIGHT_ID,
    SVG_FEFLOOD_ID,
    SVG_FEFUNCA_ID,
    SVG_FEFUNCB_ID,
    SVG_FEFUNCG_ID,
    SVG_FEFUNCR_ID,
    SVG_FEGAUSSIANBLUR_ID,
    SVG_FEIMAGE_ID,
    SVG_FEMERGE_ID,
    SVG_FEMERGENODE_ID,
    SVG_FEMORPHOLOGY_ID,
    SVG_FEOFFSET_ID,
    SVG_FEPOINTLIGHT_ID,
    SVG_FESPECULARLIGHTING_ID,
    SVG_FESPOTLIGHT_ID,
    SVG_FETILE_ID,
    SVG_FETURBULENCE_ID,
    SVG_FILTER_ID,
    SVG_FONT_ID,
    SVG_FONT_FACE_ID,
    SVG_FONT_FACE_FORMAT_ID,
    SVG_FONT_FACE_NAME_ID,
    SVG_FONT_FACE_SRC_ID,
    SVG_FONT_FACE_URI_ID,
    SVG_FOREIGNOBJECT_ID,
    SVG_G_ID,
    SVG_GLYPH_ID,
    SVG_GLYPHREF_ID,
    SVG_HKERN_ID,
    SVG_IMAGE_ID,
    SVG_LINE_ID,
    SVG_LINEARGRADIENT_ID,
    SVG_MARKER_ID,
    SVG_MASK_ID,
    SVG_METADATA_ID,
    SVG_MISSING_GLYPH_ID,
    SVG_MPATH_ID,
    SVG_PATH_ID,
    SVG_PATTERN_ID,
    SVG_POLYGON_ID,
    SVG_POLYLINE_ID,
    SVG_RADIALGRADIENT_ID,
    SVG_RECT_ID,
    SVG_SCRIPT_ID,
    SVG_SET_ID,
    SVG_STOP_ID,
    SVG_STYLE_ID,
    SVG_SVG_ID,
    SVG_SWITCH_ID,
    SVG_SYMBOL_ID,
    SVG_TEXT_ID,
    SVG_TEXTPATH_ID,
    SVG_TITLE_ID,
    SVG_TREF_ID,
    SVG_TSPAN_ID,
    SVG_USE_ID,
    SVG_VIEW_ID,
    SVG_VKERN_ID,
}
pub const ELEMENT_SVG_A_ID_STR: &str = "a";
pub const ELEMENT_SVG_ALTGLYPH_ID_STR: &str = "altGlyph";
pub const ELEMENT_SVG_ALTGLYPHDEF_ID_STR: &str = "altGlyphDef";
pub const ELEMENT_SVG_ALTGLYPHITEM_ID_STR: &str = "altGlyphItem";
pub const ELEMENT_SVG_ANIMATE_ID_STR: &str = "animate";
pub const ELEMENT_SVG_ANIMATECOLOR_ID_STR: &str = "animateColor";
pub const ELEMENT_SVG_ANIMATEMOTION_ID_STR: &str = "animateMotion";
pub const ELEMENT_SVG_ANIMATETRANSFORM_ID_STR: &str = "animateTransform";
pub const ELEMENT_SVG_CIRCLE_ID_STR: &str = "circle";
pub const ELEMENT_SVG_CLIPPATH_ID_STR: &str = "clipPath";
pub const ELEMENT_SVG_COLOR_PROFILE_ID_STR: &str = "color_profile";
pub const ELEMENT_SVG_CURSOR_ID_STR: &str = "cursor";
pub const ELEMENT_SVG_DEFINITION_SRC_ID_STR: &str = "definition_src";
pub const ELEMENT_SVG_DEFS_ID_STR: &str = "defs";
pub const ELEMENT_SVG_DESC_ID_STR: &str = "desc";
pub const ELEMENT_SVG_ELLIPSE_ID_STR: &str = "ellipse";
pub const ELEMENT_SVG_FEBLEND_ID_STR: &str = "feBlend";
pub const ELEMENT_SVG_FECOLORMATRIX_ID_STR: &str = "feColorMatrix";
pub const ELEMENT_SVG_FECOMPONENTTRANSFER_ID_STR: &str = "feComponentTransfer";
pub const ELEMENT_SVG_FECOMPOSITE_ID_STR: &str = "feComposite";
pub const ELEMENT_SVG_FECONVOLVEMATRIX_ID_STR: &str = "feConvolveMatrix";
pub const ELEMENT_SVG_FEDIFFUSELIGHTING_ID_STR: &str = "feDiffuseLighting";
pub const ELEMENT_SVG_FEDISPLACEMENTMAP_ID_STR: &str = "feDisplacementMap";
pub const ELEMENT_SVG_FEDISTANTLIGHT_ID_STR: &str = "feDistantLight";
pub const ELEMENT_SVG_FEFLOOD_ID_STR: &str = "feFlood";
pub const ELEMENT_SVG_FEFUNCA_ID_STR: &str = "feFuncA";
pub const ELEMENT_SVG_FEFUNCB_ID_STR: &str = "feFuncB";
pub const ELEMENT_SVG_FEFUNCG_ID_STR: &str = "feFuncG";
pub const ELEMENT_SVG_FEFUNCR_ID_STR: &str = "feFuncR";
pub const ELEMENT_SVG_FEGAUSSIANBLUR_ID_STR: &str = "feGaussianBlur";
pub const ELEMENT_SVG_FEIMAGE_ID_STR: &str = "feImage";
pub const ELEMENT_SVG_FEMERGE_ID_STR: &str = "feMerge";
pub const ELEMENT_SVG_FEMERGENODE_ID_STR: &str = "feMergeNode";
pub const ELEMENT_SVG_FEMORPHOLOGY_ID_STR: &str = "feMorphology";
pub const ELEMENT_SVG_FEOFFSET_ID_STR: &str = "feOffset";
pub const ELEMENT_SVG_FEPOINTLIGHT_ID_STR: &str = "fePointLight";
pub const ELEMENT_SVG_FESPECULARLIGHTING_ID_STR: &str = "feSpecularLighting";
pub const ELEMENT_SVG_FESPOTLIGHT_ID_STR: &str = "feSpotLight";
pub const ELEMENT_SVG_FETILE_ID_STR: &str = "feTile";
pub const ELEMENT_SVG_FETURBULENCE_ID_STR: &str = "feTurbulence";
pub const ELEMENT_SVG_FILTER_ID_STR: &str = "filter";
pub const ELEMENT_SVG_FONT_ID_STR: &str = "font";
pub const ELEMENT_SVG_FONT_FACE_ID_STR: &str = "font_face";
pub const ELEMENT_SVG_FONT_FACE_FORMAT_ID_STR: &str = "font_face_format";
pub const ELEMENT_SVG_FONT_FACE_NAME_ID_STR: &str = "font_face_name";
pub const ELEMENT_SVG_FONT_FACE_SRC_ID_STR: &str = "font_face_src";
pub const ELEMENT_SVG_FONT_FACE_URI_ID_STR: &str = "font_face_uri";
pub const ELEMENT_SVG_FOREIGNOBJECT_ID_STR: &str = "foreignObject";
pub const ELEMENT_SVG_G_ID_STR: &str = "g";
pub const ELEMENT_SVG_GLYPH_ID_STR: &str = "glyph";
pub const ELEMENT_SVG_GLYPHREF_ID_STR: &str = "glyphRef";
pub const ELEMENT_SVG_HKERN_ID_STR: &str = "hkern";
pub const ELEMENT_SVG_IMAGE_ID_STR: &str = "image";
pub const ELEMENT_SVG_LINE_ID_STR: &str = "line";
pub const ELEMENT_SVG_LINEARGRADIENT_ID_STR: &str = "linearGradient";
pub const ELEMENT_SVG_MARKER_ID_STR: &str = "marker";
pub const ELEMENT_SVG_MASK_ID_STR: &str = "mask";
pub const ELEMENT_SVG_METADATA_ID_STR: &str = "metadata";
pub const ELEMENT_SVG_MISSING_GLYPH_ID_STR: &str = "missing_glyph";
pub const ELEMENT_SVG_MPATH_ID_STR: &str = "mpath";
pub const ELEMENT_SVG_PATH_ID_STR: &str = "path";
pub const ELEMENT_SVG_PATTERN_ID_STR: &str = "pattern";
pub const ELEMENT_SVG_POLYGON_ID_STR: &str = "polygon";
pub const ELEMENT_SVG_POLYLINE_ID_STR: &str = "polyline";
pub const ELEMENT_SVG_RADIALGRADIENT_ID_STR: &str = "radialGradient";
pub const ELEMENT_SVG_RECT_ID_STR: &str = "rect";
pub const ELEMENT_SVG_SCRIPT_ID_STR: &str = "script";
pub const ELEMENT_SVG_SET_ID_STR: &str = "set";
pub const ELEMENT_SVG_STOP_ID_STR: &str = "stop";
pub const ELEMENT_SVG_STYLE_ID_STR: &str = "style";
pub const ELEMENT_SVG_SVG_ID_STR: &str = "svg";
pub const ELEMENT_SVG_SWITCH_ID_STR: &str = "switch";
pub const ELEMENT_SVG_SYMBOL_ID_STR: &str = "symbol";
pub const ELEMENT_SVG_TEXT_ID_STR: &str = "text";
pub const ELEMENT_SVG_TEXTPATH_ID_STR: &str = "textPath";
pub const ELEMENT_SVG_TITLE_ID_STR: &str = "title";
pub const ELEMENT_SVG_TREF_ID_STR: &str = "tref";
pub const ELEMENT_SVG_TSPAN_ID_STR: &str = "tspan";
pub const ELEMENT_SVG_USE_ID_STR: &str = "use";
pub const ELEMENT_SVG_VIEW_ID_STR: &str = "view";
pub const ELEMENT_SVG_VKERN_ID_STR: &str = "vkern";

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug, Hash)]
pub enum ATTRIB {
    SVG_ACCENT_HEIGHT,
    SVG_ACCUMULATE,
    SVG_ADDITIVE,
    SVG_ALIGNMENT_BASELINE,
    SVG_ALPHABETIC,
    SVG_AMPLITUDE,
    SVG_ANIMATE,
    SVG_ARABIC_FORM,
    SVG_ASCENT,
    SVG_ATTRIBUTENAME,
    SVG_ATTRIBUTETYPE,
    SVG_AZIMUTH,
    SVG_BASEFREQUENCY,
    SVG_BASEPROFILE,
    SVG_BASELINE_SHIFT,
    SVG_BBOX,
    SVG_BEGIN,
    SVG_BIAS,
    SVG_BY,
    SVG_CALCMODE,
    SVG_CAP_HEIGHT,
    SVG_CLIP,
    SVG_CLIPPATHUNITS,
    SVG_CLIP_PATH,
    SVG_CLIP_RULE,
    SVG_COLOR,
    SVG_COLOR_INTERPOLATION,
    SVG_COLOR_INTERPOLATION_FILTERS,
    SVG_COLOR_PROFILE,
    SVG_COLOR_RENDERING,
    SVG_CONTENTSCRIPTTYPE,
    SVG_CONTENTSTYLETYPE,
    SVG_CURSOR,
    SVG_CX,
    SVG_CY,
    SVG_D,
    SVG_DESCENT,
    SVG_DIFFUSECONSTANT,
    SVG_DIRECTION,
    SVG_DISPLAY,
    SVG_DIVISOR,
    SVG_DOMINANT_BASELINE,
    SVG_DUR,
    SVG_DX,
    SVG_DY,
    SVG_EDGEMODE,
    SVG_ELEVATION,
    SVG_ENABLE_BACKGROUND,
    SVG_END,
    SVG_EXPONENT,
    SVG_EXTERNALRESOURCESREQUIRED,
    SVG_FECOLORMATRIX,
    SVG_FECOMPOSITE,
    SVG_FEGAUSSIANBLUR,
    SVG_FEMORPHOLOGY,
    SVG_FETILE,
    SVG_FILL,
    SVG_FILL_OPACITY,
    SVG_FILL_RULE,
    SVG_FILTER,
    SVG_FILTERRES,
    SVG_FILTERUNITS,
    SVG_FLOOD_COLOR,
    SVG_FLOOD_OPACITY,
    SVG_FONT_FAMILY,
    SVG_FONT_SIZE,
    SVG_FONT_SIZE_ADJUST,
    SVG_FONT_STRETCH,
    SVG_FONT_STYLE,
    SVG_FONT_VARIANT,
    SVG_FONT_WEIGHT,
    SVG_FORMAT,
    SVG_FROM,
    SVG_FX,
    SVG_FY,
    SVG_G1,
    SVG_G2,
    SVG_GLYPHREF,
    SVG_GLYPH_NAME,
    SVG_GLYPH_ORIENTATION_HORIZONTAL,
    SVG_GLYPH_ORIENTATION_VERTICAL,
    SVG_GRADIENTTRANSFORM,
    SVG_GRADIENTUNITS,
    SVG_HANGING,
    SVG_HEIGHT,
    SVG_HORIZ_ADV_X,
    SVG_HORIZ_ORIGIN_X,
    SVG_HORIZ_ORIGIN_Y,
    SVG_IDEOGRAPHIC,
    SVG_IMAGE_RENDERING,
    SVG_IN,
    SVG_IN2,
    SVG_INTERCEPT,
    SVG_K,
    SVG_K1,
    SVG_K2,
    SVG_K3,
    SVG_K4,
    SVG_KERNELMATRIX,
    SVG_KERNELUNITLENGTH,
    SVG_KERNING,
    SVG_KEYPOINTS,
    SVG_KEYSPLINES,
    SVG_KEYTIMES,
    SVG_LANG,
    SVG_LENGTHADJUST,
    SVG_LETTER_SPACING,
    SVG_LIGHTING_COLOR,
    SVG_LIMITINGCONEANGLE,
    SVG_LOCAL,
    SVG_MARKERHEIGHT,
    SVG_MARKERUNITS,
    SVG_MARKERWIDTH,
    SVG_MARKER_END,
    SVG_MARKER_MID,
    SVG_MARKER_START,
    SVG_MASK,
    SVG_MASKCONTENTUNITS,
    SVG_MASKUNITS,
    SVG_MATHEMATICAL,
    SVG_MAX,
    SVG_MEDIA,
    SVG_METHOD,
    SVG_MIN,
    SVG_MODE,
    SVG_NAME,
    SVG_NUMOCTAVES,
    SVG_OFFSET,
    SVG_ONACTIVATE,
    SVG_ONBEGIN,
    SVG_ONEND,
    SVG_ONFOCUSIN,
    SVG_ONFOCUSOUT,
    SVG_ONREPEAT,
    SVG_ONZOOM,
    SVG_OPACITY,
    SVG_OPERATOR,
    SVG_ORDER,
    SVG_ORIENT,
    SVG_ORIENTATION,
    SVG_ORIGIN,
    SVG_OVERFLOW,
    SVG_OVERLINE_POSITION,
    SVG_OVERLINE_THICKNESS,
    SVG_PANOSE_1,
    SVG_PATH,
    SVG_PATHLENGTH,
    SVG_PATTERNCONTENTUNITS,
    SVG_PATTERNTRANSFORM,
    SVG_PATTERNUNITS,
    SVG_POINTER_EVENTS,
    SVG_POINTS,
    SVG_POINTSATX,
    SVG_POINTSATY,
    SVG_POINTSATZ,
    SVG_PRESERVEALPHA,
    SVG_PRESERVEASPECTRATIO,
    SVG_PRIMITIVEUNITS,
    SVG_R,
    SVG_RADIUS,
    SVG_REFX,
    SVG_REFY,
    SVG_RENDERING_INTENT,
    SVG_REPEATCOUNT,
    SVG_REPEATDUR,
    SVG_REQUIREDEXTENSIONS,
    SVG_REQUIREDFEATURES,
    SVG_RESTART,
    SVG_RESULT,
    SVG_ROTATE,
    SVG_RX,
    SVG_RY,
    SVG_SCALE,
    SVG_SEED,
    SVG_SHAPE_RENDERING,
    SVG_SLOPE,
    SVG_SPACING,
    SVG_SPECULARCONSTANT,
    SVG_SPECULAREXPONENT,
    SVG_SPREADMETHOD,
    SVG_STARTOFFSET,
    SVG_STDDEVIATION,
    SVG_STEMH,
    SVG_STEMV,
    SVG_STITCHTILES,
    SVG_STOP_COLOR,
    SVG_STOP_OPACITY,
    SVG_STRIKETHROUGH_POSITION,
    SVG_STRIKETHROUGH_THICKNESS,
    SVG_STROKE,
    SVG_STROKE_DASHARRAY,
    SVG_STROKE_DASHOFFSET,
    SVG_STROKE_LINECAP,
    SVG_STROKE_LINEJOIN,
    SVG_STROKE_MITERLIMIT,
    SVG_STROKE_OPACITY,
    SVG_STROKE_WIDTH,
    SVG_STYLE,
    SVG_SURFACESCALE,
    SVG_SYSTEMLANGUAGE,
    SVG_TABLEVALUES,
    SVG_TARGET,
    SVG_TARGETX,
    SVG_TARGETY,
    SVG_TEXTLENGTH,
    SVG_TEXT_ANCHOR,
    SVG_TEXT_DECORATION,
    SVG_TEXT_RENDERING,
    SVG_TITLE,
    SVG_TO,
    SVG_TRANSFORM,
    SVG_TYPE,
    SVG_U1,
    SVG_U2,
    SVG_UNDERLINE_POSITION,
    SVG_UNDERLINE_THICKNESS,
    SVG_UNICODE,
    SVG_UNICODE_BIDI,
    SVG_UNICODE_RANGE,
    SVG_UNITS_PER_EM,
    SVG_V_ALPHABETIC,
    SVG_V_HANGING,
    SVG_V_IDEOGRAPHIC,
    SVG_V_MATHEMATICAL,
    SVG_VALUES,
    SVG_VERSION,
    SVG_VERT_ADV_Y,
    SVG_VERT_ORIGIN_X,
    SVG_VERT_ORIGIN_Y,
    SVG_VIEWBOX,
    SVG_VIEWTARGET,
    SVG_VISIBILITY,
    SVG_WIDTH,
    SVG_WIDTHS,
    SVG_WORD_SPACING,
    SVG_WRITING_MODE,
    SVG_X,
    SVG_X1,
    SVG_X2,
    SVG_XCHANNELSELECTOR,
    SVG_X_HEIGHT,
    SVG_Y,
    SVG_Y1,
    SVG_Y2,
    SVG_YCHANNELSELECTOR,
    SVG_Z,
    SVG_ZOOMANDPAN,
}
pub const ATTRIB_SVG_ACCENT_HEIGHT_STR: &str = "accent_height";
pub const ATTRIB_SVG_ACCUMULATE_STR: &str = "accumulate";
pub const ATTRIB_SVG_ADDITIVE_STR: &str = "additive";
pub const ATTRIB_SVG_ALIGNMENT_BASELINE_STR: &str = "alignment_baseline";
pub const ATTRIB_SVG_ALPHABETIC_STR: &str = "alphabetic";
pub const ATTRIB_SVG_AMPLITUDE_STR: &str = "amplitude";
pub const ATTRIB_SVG_ANIMATE_STR: &str = "animate";
pub const ATTRIB_SVG_ARABIC_FORM_STR: &str = "arabic_form";
pub const ATTRIB_SVG_ASCENT_STR: &str = "ascent";
pub const ATTRIB_SVG_ATTRIBUTENAME_STR: &str = "attributeName";
pub const ATTRIB_SVG_ATTRIBUTETYPE_STR: &str = "attributeType";
pub const ATTRIB_SVG_AZIMUTH_STR: &str = "azimuth";
pub const ATTRIB_SVG_BASEFREQUENCY_STR: &str = "baseFrequency";
pub const ATTRIB_SVG_BASEPROFILE_STR: &str = "baseProfile";
pub const ATTRIB_SVG_BASELINE_SHIFT_STR: &str = "baseline_shift";
pub const ATTRIB_SVG_BBOX_STR: &str = "bbox";
pub const ATTRIB_SVG_BEGIN_STR: &str = "begin";
pub const ATTRIB_SVG_BIAS_STR: &str = "bias";
pub const ATTRIB_SVG_BY_STR: &str = "by";
pub const ATTRIB_SVG_CALCMODE_STR: &str = "calcMode";
pub const ATTRIB_SVG_CAP_HEIGHT_STR: &str = "cap_height";
pub const ATTRIB_SVG_CLIP_STR: &str = "clip";
pub const ATTRIB_SVG_CLIPPATHUNITS_STR: &str = "clipPathUnits";
pub const ATTRIB_SVG_CLIP_PATH_STR: &str = "clip_path";
pub const ATTRIB_SVG_CLIP_RULE_STR: &str = "clip_rule";
pub const ATTRIB_SVG_COLOR_STR: &str = "color";
pub const ATTRIB_SVG_COLOR_INTERPOLATION_STR: &str = "color_interpolation";
pub const ATTRIB_SVG_COLOR_INTERPOLATION_FILTERS_STR: &str = "color_interpolation_filters";
pub const ATTRIB_SVG_COLOR_PROFILE_STR: &str = "color_profile";
pub const ATTRIB_SVG_COLOR_RENDERING_STR: &str = "color_rendering";
pub const ATTRIB_SVG_CONTENTSCRIPTTYPE_STR: &str = "contentScriptType";
pub const ATTRIB_SVG_CONTENTSTYLETYPE_STR: &str = "contentStyleType";
pub const ATTRIB_SVG_CURSOR_STR: &str = "cursor";
pub const ATTRIB_SVG_CX_STR: &str = "cx";
pub const ATTRIB_SVG_CY_STR: &str = "cy";
pub const ATTRIB_SVG_D_STR: &str = "d";
pub const ATTRIB_SVG_DESCENT_STR: &str = "descent";
pub const ATTRIB_SVG_DIFFUSECONSTANT_STR: &str = "diffuseConstant";
pub const ATTRIB_SVG_DIRECTION_STR: &str = "direction";
pub const ATTRIB_SVG_DISPLAY_STR: &str = "display";
pub const ATTRIB_SVG_DIVISOR_STR: &str = "divisor";
pub const ATTRIB_SVG_DOMINANT_BASELINE_STR: &str = "dominant_baseline";
pub const ATTRIB_SVG_DUR_STR: &str = "dur";
pub const ATTRIB_SVG_DX_STR: &str = "dx";
pub const ATTRIB_SVG_DY_STR: &str = "dy";
pub const ATTRIB_SVG_EDGEMODE_STR: &str = "edgeMode";
pub const ATTRIB_SVG_ELEVATION_STR: &str = "elevation";
pub const ATTRIB_SVG_ENABLE_BACKGROUND_STR: &str = "enable_background";
pub const ATTRIB_SVG_END_STR: &str = "end";
pub const ATTRIB_SVG_EXPONENT_STR: &str = "exponent";
pub const ATTRIB_SVG_EXTERNALRESOURCESREQUIRED_STR: &str = "externalResourcesRequired";
pub const ATTRIB_SVG_FECOLORMATRIX_STR: &str = "feColorMatrix";
pub const ATTRIB_SVG_FECOMPOSITE_STR: &str = "feComposite";
pub const ATTRIB_SVG_FEGAUSSIANBLUR_STR: &str = "feGaussianBlur";
pub const ATTRIB_SVG_FEMORPHOLOGY_STR: &str = "feMorphology";
pub const ATTRIB_SVG_FETILE_STR: &str = "feTile";
pub const ATTRIB_SVG_FILL_STR: &str = "fill";
pub const ATTRIB_SVG_FILL_OPACITY_STR: &str = "fill_opacity";
pub const ATTRIB_SVG_FILL_RULE_STR: &str = "fill_rule";
pub const ATTRIB_SVG_FILTER_STR: &str = "filter";
pub const ATTRIB_SVG_FILTERRES_STR: &str = "filterRes";
pub const ATTRIB_SVG_FILTERUNITS_STR: &str = "filterUnits";
pub const ATTRIB_SVG_FLOOD_COLOR_STR: &str = "flood_color";
pub const ATTRIB_SVG_FLOOD_OPACITY_STR: &str = "flood_opacity";
pub const ATTRIB_SVG_FONT_FAMILY_STR: &str = "font_family";
pub const ATTRIB_SVG_FONT_SIZE_STR: &str = "font_size";
pub const ATTRIB_SVG_FONT_SIZE_ADJUST_STR: &str = "font_size_adjust";
pub const ATTRIB_SVG_FONT_STRETCH_STR: &str = "font_stretch";
pub const ATTRIB_SVG_FONT_STYLE_STR: &str = "font_style";
pub const ATTRIB_SVG_FONT_VARIANT_STR: &str = "font_variant";
pub const ATTRIB_SVG_FONT_WEIGHT_STR: &str = "font_weight";
pub const ATTRIB_SVG_FORMAT_STR: &str = "format";
pub const ATTRIB_SVG_FROM_STR: &str = "from";
pub const ATTRIB_SVG_FX_STR: &str = "fx";
pub const ATTRIB_SVG_FY_STR: &str = "fy";
pub const ATTRIB_SVG_G1_STR: &str = "g1";
pub const ATTRIB_SVG_G2_STR: &str = "g2";
pub const ATTRIB_SVG_GLYPHREF_STR: &str = "glyphRef";
pub const ATTRIB_SVG_GLYPH_NAME_STR: &str = "glyph_name";
pub const ATTRIB_SVG_GLYPH_ORIENTATION_HORIZONTAL_STR: &str = "glyph_orientation_horizontal";
pub const ATTRIB_SVG_GLYPH_ORIENTATION_VERTICAL_STR: &str = "glyph_orientation_vertical";
pub const ATTRIB_SVG_GRADIENTTRANSFORM_STR: &str = "gradientTransform";
pub const ATTRIB_SVG_GRADIENTUNITS_STR: &str = "gradientUnits";
pub const ATTRIB_SVG_HANGING_STR: &str = "hanging";
pub const ATTRIB_SVG_HEIGHT_STR: &str = "height";
pub const ATTRIB_SVG_HORIZ_ADV_X_STR: &str = "horiz_adv_x";
pub const ATTRIB_SVG_HORIZ_ORIGIN_X_STR: &str = "horiz_origin_x";
pub const ATTRIB_SVG_HORIZ_ORIGIN_Y_STR: &str = "horiz_origin_y";
pub const ATTRIB_SVG_IDEOGRAPHIC_STR: &str = "ideographic";
pub const ATTRIB_SVG_IMAGE_RENDERING_STR: &str = "image_rendering";
pub const ATTRIB_SVG_IN_STR: &str = "in";
pub const ATTRIB_SVG_IN2_STR: &str = "in2";
pub const ATTRIB_SVG_INTERCEPT_STR: &str = "intercept";
pub const ATTRIB_SVG_K_STR: &str = "k";
pub const ATTRIB_SVG_K1_STR: &str = "k1";
pub const ATTRIB_SVG_K2_STR: &str = "k2";
pub const ATTRIB_SVG_K3_STR: &str = "k3";
pub const ATTRIB_SVG_K4_STR: &str = "k4";
pub const ATTRIB_SVG_KERNELMATRIX_STR: &str = "kernelMatrix";
pub const ATTRIB_SVG_KERNELUNITLENGTH_STR: &str = "kernelUnitLength";
pub const ATTRIB_SVG_KERNING_STR: &str = "kerning";
pub const ATTRIB_SVG_KEYPOINTS_STR: &str = "keyPoints";
pub const ATTRIB_SVG_KEYSPLINES_STR: &str = "keySplines";
pub const ATTRIB_SVG_KEYTIMES_STR: &str = "keyTimes";
pub const ATTRIB_SVG_LANG_STR: &str = "lang";
pub const ATTRIB_SVG_LENGTHADJUST_STR: &str = "lengthAdjust";
pub const ATTRIB_SVG_LETTER_SPACING_STR: &str = "letter_spacing";
pub const ATTRIB_SVG_LIGHTING_COLOR_STR: &str = "lighting_color";
pub const ATTRIB_SVG_LIMITINGCONEANGLE_STR: &str = "limitingConeAngle";
pub const ATTRIB_SVG_LOCAL_STR: &str = "local";
pub const ATTRIB_SVG_MARKERHEIGHT_STR: &str = "markerHeight";
pub const ATTRIB_SVG_MARKERUNITS_STR: &str = "markerUnits";
pub const ATTRIB_SVG_MARKERWIDTH_STR: &str = "markerWidth";
pub const ATTRIB_SVG_MARKER_END_STR: &str = "marker_end";
pub const ATTRIB_SVG_MARKER_MID_STR: &str = "marker_mid";
pub const ATTRIB_SVG_MARKER_START_STR: &str = "marker_start";
pub const ATTRIB_SVG_MASK_STR: &str = "mask";
pub const ATTRIB_SVG_MASKCONTENTUNITS_STR: &str = "maskContentUnits";
pub const ATTRIB_SVG_MASKUNITS_STR: &str = "maskUnits";
pub const ATTRIB_SVG_MATHEMATICAL_STR: &str = "mathematical";
pub const ATTRIB_SVG_MAX_STR: &str = "max";
pub const ATTRIB_SVG_MEDIA_STR: &str = "media";
pub const ATTRIB_SVG_METHOD_STR: &str = "method";
pub const ATTRIB_SVG_MIN_STR: &str = "min";
pub const ATTRIB_SVG_MODE_STR: &str = "mode";
pub const ATTRIB_SVG_NAME_STR: &str = "name";
pub const ATTRIB_SVG_NUMOCTAVES_STR: &str = "numOctaves";
pub const ATTRIB_SVG_OFFSET_STR: &str = "offset";
pub const ATTRIB_SVG_ONACTIVATE_STR: &str = "onactivate";
pub const ATTRIB_SVG_ONBEGIN_STR: &str = "onbegin";
pub const ATTRIB_SVG_ONEND_STR: &str = "onend";
pub const ATTRIB_SVG_ONFOCUSIN_STR: &str = "onfocusin";
pub const ATTRIB_SVG_ONFOCUSOUT_STR: &str = "onfocusout";
pub const ATTRIB_SVG_ONREPEAT_STR: &str = "onrepeat";
pub const ATTRIB_SVG_ONZOOM_STR: &str = "onzoom";
pub const ATTRIB_SVG_OPACITY_STR: &str = "opacity";
pub const ATTRIB_SVG_OPERATOR_STR: &str = "operator";
pub const ATTRIB_SVG_ORDER_STR: &str = "order";
pub const ATTRIB_SVG_ORIENT_STR: &str = "orient";
pub const ATTRIB_SVG_ORIENTATION_STR: &str = "orientation";
pub const ATTRIB_SVG_ORIGIN_STR: &str = "origin";
pub const ATTRIB_SVG_OVERFLOW_STR: &str = "overflow";
pub const ATTRIB_SVG_OVERLINE_POSITION_STR: &str = "overline_position";
pub const ATTRIB_SVG_OVERLINE_THICKNESS_STR: &str = "overline_thickness";
pub const ATTRIB_SVG_PANOSE_1_STR: &str = "panose_1";
pub const ATTRIB_SVG_PATH_STR: &str = "path";
pub const ATTRIB_SVG_PATHLENGTH_STR: &str = "pathLength";
pub const ATTRIB_SVG_PATTERNCONTENTUNITS_STR: &str = "patternContentUnits";
pub const ATTRIB_SVG_PATTERNTRANSFORM_STR: &str = "patternTransform";
pub const ATTRIB_SVG_PATTERNUNITS_STR: &str = "patternUnits";
pub const ATTRIB_SVG_POINTER_EVENTS_STR: &str = "pointer_events";
pub const ATTRIB_SVG_POINTS_STR: &str = "points";
pub const ATTRIB_SVG_POINTSATX_STR: &str = "pointsAtX";
pub const ATTRIB_SVG_POINTSATY_STR: &str = "pointsAtY";
pub const ATTRIB_SVG_POINTSATZ_STR: &str = "pointsAtZ";
pub const ATTRIB_SVG_PRESERVEALPHA_STR: &str = "preserveAlpha";
pub const ATTRIB_SVG_PRESERVEASPECTRATIO_STR: &str = "preserveAspectRatio";
pub const ATTRIB_SVG_PRIMITIVEUNITS_STR: &str = "primitiveUnits";
pub const ATTRIB_SVG_R_STR: &str = "r";
pub const ATTRIB_SVG_RADIUS_STR: &str = "radius";
pub const ATTRIB_SVG_REFX_STR: &str = "refX";
pub const ATTRIB_SVG_REFY_STR: &str = "refY";
pub const ATTRIB_SVG_RENDERING_INTENT_STR: &str = "rendering_intent";
pub const ATTRIB_SVG_REPEATCOUNT_STR: &str = "repeatCount";
pub const ATTRIB_SVG_REPEATDUR_STR: &str = "repeatDur";
pub const ATTRIB_SVG_REQUIREDEXTENSIONS_STR: &str = "requiredExtensions";
pub const ATTRIB_SVG_REQUIREDFEATURES_STR: &str = "requiredFeatures";
pub const ATTRIB_SVG_RESTART_STR: &str = "restart";
pub const ATTRIB_SVG_RESULT_STR: &str = "result";
pub const ATTRIB_SVG_ROTATE_STR: &str = "rotate";
pub const ATTRIB_SVG_RX_STR: &str = "rx";
pub const ATTRIB_SVG_RY_STR: &str = "ry";
pub const ATTRIB_SVG_SCALE_STR: &str = "scale";
pub const ATTRIB_SVG_SEED_STR: &str = "seed";
pub const ATTRIB_SVG_SHAPE_RENDERING_STR: &str = "shape_rendering";
pub const ATTRIB_SVG_SLOPE_STR: &str = "slope";
pub const ATTRIB_SVG_SPACING_STR: &str = "spacing";
pub const ATTRIB_SVG_SPECULARCONSTANT_STR: &str = "specularConstant";
pub const ATTRIB_SVG_SPECULAREXPONENT_STR: &str = "specularExponent";
pub const ATTRIB_SVG_SPREADMETHOD_STR: &str = "spreadMethod";
pub const ATTRIB_SVG_STARTOFFSET_STR: &str = "startOffset";
pub const ATTRIB_SVG_STDDEVIATION_STR: &str = "stdDeviation";
pub const ATTRIB_SVG_STEMH_STR: &str = "stemh";
pub const ATTRIB_SVG_STEMV_STR: &str = "stemv";
pub const ATTRIB_SVG_STITCHTILES_STR: &str = "stitchTiles";
pub const ATTRIB_SVG_STOP_COLOR_STR: &str = "stop_color";
pub const ATTRIB_SVG_STOP_OPACITY_STR: &str = "stop_opacity";
pub const ATTRIB_SVG_STRIKETHROUGH_POSITION_STR: &str = "strikethrough_position";
pub const ATTRIB_SVG_STRIKETHROUGH_THICKNESS_STR: &str = "strikethrough_thickness";
pub const ATTRIB_SVG_STROKE_STR: &str = "stroke";
pub const ATTRIB_SVG_STROKE_DASHARRAY_STR: &str = "stroke_dasharray";
pub const ATTRIB_SVG_STROKE_DASHOFFSET_STR: &str = "stroke_dashoffset";
pub const ATTRIB_SVG_STROKE_LINECAP_STR: &str = "stroke_linecap";
pub const ATTRIB_SVG_STROKE_LINEJOIN_STR: &str = "stroke_linejoin";
pub const ATTRIB_SVG_STROKE_MITERLIMIT_STR: &str = "stroke_miterlimit";
pub const ATTRIB_SVG_STROKE_OPACITY_STR: &str = "stroke_opacity";
pub const ATTRIB_SVG_STROKE_WIDTH_STR: &str = "stroke_width";
pub const ATTRIB_SVG_STYLE_STR: &str = "style";
pub const ATTRIB_SVG_SURFACESCALE_STR: &str = "surfaceScale";
pub const ATTRIB_SVG_SYSTEMLANGUAGE_STR: &str = "systemLanguage";
pub const ATTRIB_SVG_TABLEVALUES_STR: &str = "tableValues";
pub const ATTRIB_SVG_TARGET_STR: &str = "target";
pub const ATTRIB_SVG_TARGETX_STR: &str = "targetX";
pub const ATTRIB_SVG_TARGETY_STR: &str = "targetY";
pub const ATTRIB_SVG_TEXTLENGTH_STR: &str = "textLength";
pub const ATTRIB_SVG_TEXT_ANCHOR_STR: &str = "text_anchor";
pub const ATTRIB_SVG_TEXT_DECORATION_STR: &str = "text_decoration";
pub const ATTRIB_SVG_TEXT_RENDERING_STR: &str = "text_rendering";
pub const ATTRIB_SVG_TITLE_STR: &str = "title";
pub const ATTRIB_SVG_TO_STR: &str = "to";
pub const ATTRIB_SVG_TRANSFORM_STR: &str = "transform";
pub const ATTRIB_SVG_TYPE_STR: &str = "type";
pub const ATTRIB_SVG_U1_STR: &str = "u1";
pub const ATTRIB_SVG_U2_STR: &str = "u2";
pub const ATTRIB_SVG_UNDERLINE_POSITION_STR: &str = "underline_position";
pub const ATTRIB_SVG_UNDERLINE_THICKNESS_STR: &str = "underline_thickness";
pub const ATTRIB_SVG_UNICODE_STR: &str = "unicode";
pub const ATTRIB_SVG_UNICODE_BIDI_STR: &str = "unicode_bidi";
pub const ATTRIB_SVG_UNICODE_RANGE_STR: &str = "unicode_range";
pub const ATTRIB_SVG_UNITS_PER_EM_STR: &str = "units_per_em";
pub const ATTRIB_SVG_V_ALPHABETIC_STR: &str = "v_alphabetic";
pub const ATTRIB_SVG_V_HANGING_STR: &str = "v_hanging";
pub const ATTRIB_SVG_V_IDEOGRAPHIC_STR: &str = "v_ideographic";
pub const ATTRIB_SVG_V_MATHEMATICAL_STR: &str = "v_mathematical";
pub const ATTRIB_SVG_VALUES_STR: &str = "values";
pub const ATTRIB_SVG_VERSION_STR: &str = "version";
pub const ATTRIB_SVG_VERT_ADV_Y_STR: &str = "vert_adv_y";
pub const ATTRIB_SVG_VERT_ORIGIN_X_STR: &str = "vert_origin_x";
pub const ATTRIB_SVG_VERT_ORIGIN_Y_STR: &str = "vert_origin_y";
pub const ATTRIB_SVG_VIEWBOX_STR: &str = "viewBox";
pub const ATTRIB_SVG_VIEWTARGET_STR: &str = "viewTarget";
pub const ATTRIB_SVG_VISIBILITY_STR: &str = "visibility";
pub const ATTRIB_SVG_WIDTH_STR: &str = "width";
pub const ATTRIB_SVG_WIDTHS_STR: &str = "widths";
pub const ATTRIB_SVG_WORD_SPACING_STR: &str = "word_spacing";
pub const ATTRIB_SVG_WRITING_MODE_STR: &str = "writing_mode";
pub const ATTRIB_SVG_X_STR: &str = "x";
pub const ATTRIB_SVG_X1_STR: &str = "x1";
pub const ATTRIB_SVG_X2_STR: &str = "x2";
pub const ATTRIB_SVG_XCHANNELSELECTOR_STR: &str = "xChannelSelector";
pub const ATTRIB_SVG_X_HEIGHT_STR: &str = "x_height";
pub const ATTRIB_SVG_Y_STR: &str = "y";
pub const ATTRIB_SVG_Y1_STR: &str = "y1";
pub const ATTRIB_SVG_Y2_STR: &str = "y2";
pub const ATTRIB_SVG_YCHANNELSELECTOR_STR: &str = "yChannelSelector";
pub const ATTRIB_SVG_Z_STR: &str = "z";
pub const ATTRIB_SVG_ZOOMANDPAN_STR: &str = "zoomAndPan";