// This file is generated by ConstMaker, DON'T MODIFY.


enum ELEMENT: UInt8 {
    case SVG_A_ID
    case SVG_ALTGLYPH_ID
    case SVG_ALTGLYPHDEF_ID
    case SVG_ALTGLYPHITEM_ID
    case SVG_ANIMATE_ID
    case SVG_ANIMATECOLOR_ID
    case SVG_ANIMATEMOTION_ID
    case SVG_ANIMATETRANSFORM_ID
    case SVG_CIRCLE_ID
    case SVG_CLIPPATH_ID
    case SVG_COLOR_PROFILE_ID
    case SVG_CURSOR_ID
    case SVG_DEFINITION_SRC_ID
    case SVG_DEFS_ID
    case SVG_DESC_ID
    case SVG_ELLIPSE_ID
    case SVG_FEBLEND_ID
    case SVG_FECOLORMATRIX_ID
    case SVG_FECOMPONENTTRANSFER_ID
    case SVG_FECOMPOSITE_ID
    case SVG_FECONVOLVEMATRIX_ID
    case SVG_FEDIFFUSELIGHTING_ID
    case SVG_FEDISPLACEMENTMAP_ID
    case SVG_FEDISTANTLIGHT_ID
    case SVG_FEFLOOD_ID
    case SVG_FEFUNCA_ID
    case SVG_FEFUNCB_ID
    case SVG_FEFUNCG_ID
    case SVG_FEFUNCR_ID
    case SVG_FEGAUSSIANBLUR_ID
    case SVG_FEIMAGE_ID
    case SVG_FEMERGE_ID
    case SVG_FEMERGENODE_ID
    case SVG_FEMORPHOLOGY_ID
    case SVG_FEOFFSET_ID
    case SVG_FEPOINTLIGHT_ID
    case SVG_FESPECULARLIGHTING_ID
    case SVG_FESPOTLIGHT_ID
    case SVG_FETILE_ID
    case SVG_FETURBULENCE_ID
    case SVG_FILTER_ID
    case SVG_FONT_ID
    case SVG_FONT_FACE_ID
    case SVG_FONT_FACE_FORMAT_ID
    case SVG_FONT_FACE_NAME_ID
    case SVG_FONT_FACE_SRC_ID
    case SVG_FONT_FACE_URI_ID
    case SVG_FOREIGNOBJECT_ID
    case SVG_G_ID
    case SVG_GLYPH_ID
    case SVG_GLYPHREF_ID
    case SVG_HKERN_ID
    case SVG_IMAGE_ID
    case SVG_LINE_ID
    case SVG_LINEARGRADIENT_ID
    case SVG_MARKER_ID
    case SVG_MASK_ID
    case SVG_METADATA_ID
    case SVG_MISSING_GLYPH_ID
    case SVG_MPATH_ID
    case SVG_PATH_ID
    case SVG_PATTERN_ID
    case SVG_POLYGON_ID
    case SVG_POLYLINE_ID
    case SVG_RADIALGRADIENT_ID
    case SVG_RECT_ID
    case SVG_SCRIPT_ID
    case SVG_SET_ID
    case SVG_STOP_ID
    case SVG_STYLE_ID
    case SVG_SVG_ID
    case SVG_SWITCH_ID
    case SVG_SYMBOL_ID
    case SVG_TEXT_ID
    case SVG_TEXTPATH_ID
    case SVG_TITLE_ID
    case SVG_TREF_ID
    case SVG_TSPAN_ID
    case SVG_USE_ID
    case SVG_VIEW_ID
    case SVG_VKERN_ID
}
static let ELEMENT_SVG_A_ID_STR: String = "a"
static let ELEMENT_SVG_ALTGLYPH_ID_STR: String = "altGlyph"
static let ELEMENT_SVG_ALTGLYPHDEF_ID_STR: String = "altGlyphDef"
static let ELEMENT_SVG_ALTGLYPHITEM_ID_STR: String = "altGlyphItem"
static let ELEMENT_SVG_ANIMATE_ID_STR: String = "animate"
static let ELEMENT_SVG_ANIMATECOLOR_ID_STR: String = "animateColor"
static let ELEMENT_SVG_ANIMATEMOTION_ID_STR: String = "animateMotion"
static let ELEMENT_SVG_ANIMATETRANSFORM_ID_STR: String = "animateTransform"
static let ELEMENT_SVG_CIRCLE_ID_STR: String = "circle"
static let ELEMENT_SVG_CLIPPATH_ID_STR: String = "clipPath"
static let ELEMENT_SVG_COLOR_PROFILE_ID_STR: String = "color_profile"
static let ELEMENT_SVG_CURSOR_ID_STR: String = "cursor"
static let ELEMENT_SVG_DEFINITION_SRC_ID_STR: String = "definition_src"
static let ELEMENT_SVG_DEFS_ID_STR: String = "defs"
static let ELEMENT_SVG_DESC_ID_STR: String = "desc"
static let ELEMENT_SVG_ELLIPSE_ID_STR: String = "ellipse"
static let ELEMENT_SVG_FEBLEND_ID_STR: String = "feBlend"
static let ELEMENT_SVG_FECOLORMATRIX_ID_STR: String = "feColorMatrix"
static let ELEMENT_SVG_FECOMPONENTTRANSFER_ID_STR: String = "feComponentTransfer"
static let ELEMENT_SVG_FECOMPOSITE_ID_STR: String = "feComposite"
static let ELEMENT_SVG_FECONVOLVEMATRIX_ID_STR: String = "feConvolveMatrix"
static let ELEMENT_SVG_FEDIFFUSELIGHTING_ID_STR: String = "feDiffuseLighting"
static let ELEMENT_SVG_FEDISPLACEMENTMAP_ID_STR: String = "feDisplacementMap"
static let ELEMENT_SVG_FEDISTANTLIGHT_ID_STR: String = "feDistantLight"
static let ELEMENT_SVG_FEFLOOD_ID_STR: String = "feFlood"
static let ELEMENT_SVG_FEFUNCA_ID_STR: String = "feFuncA"
static let ELEMENT_SVG_FEFUNCB_ID_STR: String = "feFuncB"
static let ELEMENT_SVG_FEFUNCG_ID_STR: String = "feFuncG"
static let ELEMENT_SVG_FEFUNCR_ID_STR: String = "feFuncR"
static let ELEMENT_SVG_FEGAUSSIANBLUR_ID_STR: String = "feGaussianBlur"
static let ELEMENT_SVG_FEIMAGE_ID_STR: String = "feImage"
static let ELEMENT_SVG_FEMERGE_ID_STR: String = "feMerge"
static let ELEMENT_SVG_FEMERGENODE_ID_STR: String = "feMergeNode"
static let ELEMENT_SVG_FEMORPHOLOGY_ID_STR: String = "feMorphology"
static let ELEMENT_SVG_FEOFFSET_ID_STR: String = "feOffset"
static let ELEMENT_SVG_FEPOINTLIGHT_ID_STR: String = "fePointLight"
static let ELEMENT_SVG_FESPECULARLIGHTING_ID_STR: String = "feSpecularLighting"
static let ELEMENT_SVG_FESPOTLIGHT_ID_STR: String = "feSpotLight"
static let ELEMENT_SVG_FETILE_ID_STR: String = "feTile"
static let ELEMENT_SVG_FETURBULENCE_ID_STR: String = "feTurbulence"
static let ELEMENT_SVG_FILTER_ID_STR: String = "filter"
static let ELEMENT_SVG_FONT_ID_STR: String = "font"
static let ELEMENT_SVG_FONT_FACE_ID_STR: String = "font_face"
static let ELEMENT_SVG_FONT_FACE_FORMAT_ID_STR: String = "font_face_format"
static let ELEMENT_SVG_FONT_FACE_NAME_ID_STR: String = "font_face_name"
static let ELEMENT_SVG_FONT_FACE_SRC_ID_STR: String = "font_face_src"
static let ELEMENT_SVG_FONT_FACE_URI_ID_STR: String = "font_face_uri"
static let ELEMENT_SVG_FOREIGNOBJECT_ID_STR: String = "foreignObject"
static let ELEMENT_SVG_G_ID_STR: String = "g"
static let ELEMENT_SVG_GLYPH_ID_STR: String = "glyph"
static let ELEMENT_SVG_GLYPHREF_ID_STR: String = "glyphRef"
static let ELEMENT_SVG_HKERN_ID_STR: String = "hkern"
static let ELEMENT_SVG_IMAGE_ID_STR: String = "image"
static let ELEMENT_SVG_LINE_ID_STR: String = "line"
static let ELEMENT_SVG_LINEARGRADIENT_ID_STR: String = "linearGradient"
static let ELEMENT_SVG_MARKER_ID_STR: String = "marker"
static let ELEMENT_SVG_MASK_ID_STR: String = "mask"
static let ELEMENT_SVG_METADATA_ID_STR: String = "metadata"
static let ELEMENT_SVG_MISSING_GLYPH_ID_STR: String = "missing_glyph"
static let ELEMENT_SVG_MPATH_ID_STR: String = "mpath"
static let ELEMENT_SVG_PATH_ID_STR: String = "path"
static let ELEMENT_SVG_PATTERN_ID_STR: String = "pattern"
static let ELEMENT_SVG_POLYGON_ID_STR: String = "polygon"
static let ELEMENT_SVG_POLYLINE_ID_STR: String = "polyline"
static let ELEMENT_SVG_RADIALGRADIENT_ID_STR: String = "radialGradient"
static let ELEMENT_SVG_RECT_ID_STR: String = "rect"
static let ELEMENT_SVG_SCRIPT_ID_STR: String = "script"
static let ELEMENT_SVG_SET_ID_STR: String = "set"
static let ELEMENT_SVG_STOP_ID_STR: String = "stop"
static let ELEMENT_SVG_STYLE_ID_STR: String = "style"
static let ELEMENT_SVG_SVG_ID_STR: String = "svg"
static let ELEMENT_SVG_SWITCH_ID_STR: String = "switch"
static let ELEMENT_SVG_SYMBOL_ID_STR: String = "symbol"
static let ELEMENT_SVG_TEXT_ID_STR: String = "text"
static let ELEMENT_SVG_TEXTPATH_ID_STR: String = "textPath"
static let ELEMENT_SVG_TITLE_ID_STR: String = "title"
static let ELEMENT_SVG_TREF_ID_STR: String = "tref"
static let ELEMENT_SVG_TSPAN_ID_STR: String = "tspan"
static let ELEMENT_SVG_USE_ID_STR: String = "use"
static let ELEMENT_SVG_VIEW_ID_STR: String = "view"
static let ELEMENT_SVG_VKERN_ID_STR: String = "vkern"

enum ATTRIB: UInt8 {
    case SVG_ACCENT_HEIGHT
    case SVG_ACCUMULATE
    case SVG_ADDITIVE
    case SVG_ALIGNMENT_BASELINE
    case SVG_ALPHABETIC
    case SVG_AMPLITUDE
    case SVG_ANIMATE
    case SVG_ARABIC_FORM
    case SVG_ASCENT
    case SVG_ATTRIBUTENAME
    case SVG_ATTRIBUTETYPE
    case SVG_AZIMUTH
    case SVG_BASEFREQUENCY
    case SVG_BASEPROFILE
    case SVG_BASELINE_SHIFT
    case SVG_BBOX
    case SVG_BEGIN
    case SVG_BIAS
    case SVG_BY
    case SVG_CALCMODE
    case SVG_CAP_HEIGHT
    case SVG_CLIP
    case SVG_CLIPPATHUNITS
    case SVG_CLIP_PATH
    case SVG_CLIP_RULE
    case SVG_COLOR
    case SVG_COLOR_INTERPOLATION
    case SVG_COLOR_INTERPOLATION_FILTERS
    case SVG_COLOR_PROFILE
    case SVG_COLOR_RENDERING
    case SVG_CONTENTSCRIPTTYPE
    case SVG_CONTENTSTYLETYPE
    case SVG_CURSOR
    case SVG_CX
    case SVG_CY
    case SVG_D
    case SVG_DESCENT
    case SVG_DIFFUSECONSTANT
    case SVG_DIRECTION
    case SVG_DISPLAY
    case SVG_DIVISOR
    case SVG_DOMINANT_BASELINE
    case SVG_DUR
    case SVG_DX
    case SVG_DY
    case SVG_EDGEMODE
    case SVG_ELEVATION
    case SVG_ENABLE_BACKGROUND
    case SVG_END
    case SVG_EXPONENT
    case SVG_EXTERNALRESOURCESREQUIRED
    case SVG_FECOLORMATRIX
    case SVG_FECOMPOSITE
    case SVG_FEGAUSSIANBLUR
    case SVG_FEMORPHOLOGY
    case SVG_FETILE
    case SVG_FILL
    case SVG_FILL_OPACITY
    case SVG_FILL_RULE
    case SVG_FILTER
    case SVG_FILTERRES
    case SVG_FILTERUNITS
    case SVG_FLOOD_COLOR
    case SVG_FLOOD_OPACITY
    case SVG_FONT_FAMILY
    case SVG_FONT_SIZE
    case SVG_FONT_SIZE_ADJUST
    case SVG_FONT_STRETCH
    case SVG_FONT_STYLE
    case SVG_FONT_VARIANT
    case SVG_FONT_WEIGHT
    case SVG_FORMAT
    case SVG_FROM
    case SVG_FX
    case SVG_FY
    case SVG_G1
    case SVG_G2
    case SVG_GLYPHREF
    case SVG_GLYPH_NAME
    case SVG_GLYPH_ORIENTATION_HORIZONTAL
    case SVG_GLYPH_ORIENTATION_VERTICAL
    case SVG_GRADIENTTRANSFORM
    case SVG_GRADIENTUNITS
    case SVG_HANGING
    case SVG_HEIGHT
    case SVG_HORIZ_ADV_X
    case SVG_HORIZ_ORIGIN_X
    case SVG_HORIZ_ORIGIN_Y
    case SVG_IDEOGRAPHIC
    case SVG_IMAGE_RENDERING
    case SVG_IN
    case SVG_IN2
    case SVG_INTERCEPT
    case SVG_K
    case SVG_K1
    case SVG_K2
    case SVG_K3
    case SVG_K4
    case SVG_KERNELMATRIX
    case SVG_KERNELUNITLENGTH
    case SVG_KERNING
    case SVG_KEYPOINTS
    case SVG_KEYSPLINES
    case SVG_KEYTIMES
    case SVG_LANG
    case SVG_LENGTHADJUST
    case SVG_LETTER_SPACING
    case SVG_LIGHTING_COLOR
    case SVG_LIMITINGCONEANGLE
    case SVG_LOCAL
    case SVG_MARKERHEIGHT
    case SVG_MARKERUNITS
    case SVG_MARKERWIDTH
    case SVG_MARKER_END
    case SVG_MARKER_MID
    case SVG_MARKER_START
    case SVG_MASK
    case SVG_MASKCONTENTUNITS
    case SVG_MASKUNITS
    case SVG_MATHEMATICAL
    case SVG_MAX
    case SVG_MEDIA
    case SVG_METHOD
    case SVG_MIN
    case SVG_MODE
    case SVG_NAME
    case SVG_NUMOCTAVES
    case SVG_OFFSET
    case SVG_ONACTIVATE
    case SVG_ONBEGIN
    case SVG_ONEND
    case SVG_ONFOCUSIN
    case SVG_ONFOCUSOUT
    case SVG_ONREPEAT
    case SVG_ONZOOM
    case SVG_OPACITY
    case SVG_OPERATOR
    case SVG_ORDER
    case SVG_ORIENT
    case SVG_ORIENTATION
    case SVG_ORIGIN
    case SVG_OVERFLOW
    case SVG_OVERLINE_POSITION
    case SVG_OVERLINE_THICKNESS
    case SVG_PANOSE_1
    case SVG_PATH
    case SVG_PATHLENGTH
    case SVG_PATTERNCONTENTUNITS
    case SVG_PATTERNTRANSFORM
    case SVG_PATTERNUNITS
    case SVG_POINTER_EVENTS
    case SVG_POINTS
    case SVG_POINTSATX
    case SVG_POINTSATY
    case SVG_POINTSATZ
    case SVG_PRESERVEALPHA
    case SVG_PRESERVEASPECTRATIO
    case SVG_PRIMITIVEUNITS
    case SVG_R
    case SVG_RADIUS
    case SVG_REFX
    case SVG_REFY
    case SVG_RENDERING_INTENT
    case SVG_REPEATCOUNT
    case SVG_REPEATDUR
    case SVG_REQUIREDEXTENSIONS
    case SVG_REQUIREDFEATURES
    case SVG_RESTART
    case SVG_RESULT
    case SVG_ROTATE
    case SVG_RX
    case SVG_RY
    case SVG_SCALE
    case SVG_SEED
    case SVG_SHAPE_RENDERING
    case SVG_SLOPE
    case SVG_SPACING
    case SVG_SPECULARCONSTANT
    case SVG_SPECULAREXPONENT
    case SVG_SPREADMETHOD
    case SVG_STARTOFFSET
    case SVG_STDDEVIATION
    case SVG_STEMH
    case SVG_STEMV
    case SVG_STITCHTILES
    case SVG_STOP_COLOR
    case SVG_STOP_OPACITY
    case SVG_STRIKETHROUGH_POSITION
    case SVG_STRIKETHROUGH_THICKNESS
    case SVG_STROKE
    case SVG_STROKE_DASHARRAY
    case SVG_STROKE_DASHOFFSET
    case SVG_STROKE_LINECAP
    case SVG_STROKE_LINEJOIN
    case SVG_STROKE_MITERLIMIT
    case SVG_STROKE_OPACITY
    case SVG_STROKE_WIDTH
    case SVG_STYLE
    case SVG_SURFACESCALE
    case SVG_SYSTEMLANGUAGE
    case SVG_TABLEVALUES
    case SVG_TARGET
    case SVG_TARGETX
    case SVG_TARGETY
    case SVG_TEXTLENGTH
    case SVG_TEXT_ANCHOR
    case SVG_TEXT_DECORATION
    case SVG_TEXT_RENDERING
    case SVG_TITLE
    case SVG_TO
    case SVG_TRANSFORM
    case SVG_TYPE
    case SVG_U1
    case SVG_U2
    case SVG_UNDERLINE_POSITION
    case SVG_UNDERLINE_THICKNESS
    case SVG_UNICODE
    case SVG_UNICODE_BIDI
    case SVG_UNICODE_RANGE
    case SVG_UNITS_PER_EM
    case SVG_V_ALPHABETIC
    case SVG_V_HANGING
    case SVG_V_IDEOGRAPHIC
    case SVG_V_MATHEMATICAL
    case SVG_VALUES
    case SVG_VERSION
    case SVG_VERT_ADV_Y
    case SVG_VERT_ORIGIN_X
    case SVG_VERT_ORIGIN_Y
    case SVG_VIEWBOX
    case SVG_VIEWTARGET
    case SVG_VISIBILITY
    case SVG_WIDTH
    case SVG_WIDTHS
    case SVG_WORD_SPACING
    case SVG_WRITING_MODE
    case SVG_X
    case SVG_X1
    case SVG_X2
    case SVG_XCHANNELSELECTOR
    case SVG_X_HEIGHT
    case SVG_Y
    case SVG_Y1
    case SVG_Y2
    case SVG_YCHANNELSELECTOR
    case SVG_Z
    case SVG_ZOOMANDPAN
}
static let ATTRIB_SVG_ACCENT_HEIGHT_STR: String = "accent_height"
static let ATTRIB_SVG_ACCUMULATE_STR: String = "accumulate"
static let ATTRIB_SVG_ADDITIVE_STR: String = "additive"
static let ATTRIB_SVG_ALIGNMENT_BASELINE_STR: String = "alignment_baseline"
static let ATTRIB_SVG_ALPHABETIC_STR: String = "alphabetic"
static let ATTRIB_SVG_AMPLITUDE_STR: String = "amplitude"
static let ATTRIB_SVG_ANIMATE_STR: String = "animate"
static let ATTRIB_SVG_ARABIC_FORM_STR: String = "arabic_form"
static let ATTRIB_SVG_ASCENT_STR: String = "ascent"
static let ATTRIB_SVG_ATTRIBUTENAME_STR: String = "attributeName"
static let ATTRIB_SVG_ATTRIBUTETYPE_STR: String = "attributeType"
static let ATTRIB_SVG_AZIMUTH_STR: String = "azimuth"
static let ATTRIB_SVG_BASEFREQUENCY_STR: String = "baseFrequency"
static let ATTRIB_SVG_BASEPROFILE_STR: String = "baseProfile"
static let ATTRIB_SVG_BASELINE_SHIFT_STR: String = "baseline_shift"
static let ATTRIB_SVG_BBOX_STR: String = "bbox"
static let ATTRIB_SVG_BEGIN_STR: String = "begin"
static let ATTRIB_SVG_BIAS_STR: String = "bias"
static let ATTRIB_SVG_BY_STR: String = "by"
static let ATTRIB_SVG_CALCMODE_STR: String = "calcMode"
static let ATTRIB_SVG_CAP_HEIGHT_STR: String = "cap_height"
static let ATTRIB_SVG_CLIP_STR: String = "clip"
static let ATTRIB_SVG_CLIPPATHUNITS_STR: String = "clipPathUnits"
static let ATTRIB_SVG_CLIP_PATH_STR: String = "clip_path"
static let ATTRIB_SVG_CLIP_RULE_STR: String = "clip_rule"
static let ATTRIB_SVG_COLOR_STR: String = "color"
static let ATTRIB_SVG_COLOR_INTERPOLATION_STR: String = "color_interpolation"
static let ATTRIB_SVG_COLOR_INTERPOLATION_FILTERS_STR: String = "color_interpolation_filters"
static let ATTRIB_SVG_COLOR_PROFILE_STR: String = "color_profile"
static let ATTRIB_SVG_COLOR_RENDERING_STR: String = "color_rendering"
static let ATTRIB_SVG_CONTENTSCRIPTTYPE_STR: String = "contentScriptType"
static let ATTRIB_SVG_CONTENTSTYLETYPE_STR: String = "contentStyleType"
static let ATTRIB_SVG_CURSOR_STR: String = "cursor"
static let ATTRIB_SVG_CX_STR: String = "cx"
static let ATTRIB_SVG_CY_STR: String = "cy"
static let ATTRIB_SVG_D_STR: String = "d"
static let ATTRIB_SVG_DESCENT_STR: String = "descent"
static let ATTRIB_SVG_DIFFUSECONSTANT_STR: String = "diffuseConstant"
static let ATTRIB_SVG_DIRECTION_STR: String = "direction"
static let ATTRIB_SVG_DISPLAY_STR: String = "display"
static let ATTRIB_SVG_DIVISOR_STR: String = "divisor"
static let ATTRIB_SVG_DOMINANT_BASELINE_STR: String = "dominant_baseline"
static let ATTRIB_SVG_DUR_STR: String = "dur"
static let ATTRIB_SVG_DX_STR: String = "dx"
static let ATTRIB_SVG_DY_STR: String = "dy"
static let ATTRIB_SVG_EDGEMODE_STR: String = "edgeMode"
static let ATTRIB_SVG_ELEVATION_STR: String = "elevation"
static let ATTRIB_SVG_ENABLE_BACKGROUND_STR: String = "enable_background"
static let ATTRIB_SVG_END_STR: String = "end"
static let ATTRIB_SVG_EXPONENT_STR: String = "exponent"
static let ATTRIB_SVG_EXTERNALRESOURCESREQUIRED_STR: String = "externalResourcesRequired"
static let ATTRIB_SVG_FECOLORMATRIX_STR: String = "feColorMatrix"
static let ATTRIB_SVG_FECOMPOSITE_STR: String = "feComposite"
static let ATTRIB_SVG_FEGAUSSIANBLUR_STR: String = "feGaussianBlur"
static let ATTRIB_SVG_FEMORPHOLOGY_STR: String = "feMorphology"
static let ATTRIB_SVG_FETILE_STR: String = "feTile"
static let ATTRIB_SVG_FILL_STR: String = "fill"
static let ATTRIB_SVG_FILL_OPACITY_STR: String = "fill_opacity"
static let ATTRIB_SVG_FILL_RULE_STR: String = "fill_rule"
static let ATTRIB_SVG_FILTER_STR: String = "filter"
static let ATTRIB_SVG_FILTERRES_STR: String = "filterRes"
static let ATTRIB_SVG_FILTERUNITS_STR: String = "filterUnits"
static let ATTRIB_SVG_FLOOD_COLOR_STR: String = "flood_color"
static let ATTRIB_SVG_FLOOD_OPACITY_STR: String = "flood_opacity"
static let ATTRIB_SVG_FONT_FAMILY_STR: String = "font_family"
static let ATTRIB_SVG_FONT_SIZE_STR: String = "font_size"
static let ATTRIB_SVG_FONT_SIZE_ADJUST_STR: String = "font_size_adjust"
static let ATTRIB_SVG_FONT_STRETCH_STR: String = "font_stretch"
static let ATTRIB_SVG_FONT_STYLE_STR: String = "font_style"
static let ATTRIB_SVG_FONT_VARIANT_STR: String = "font_variant"
static let ATTRIB_SVG_FONT_WEIGHT_STR: String = "font_weight"
static let ATTRIB_SVG_FORMAT_STR: String = "format"
static let ATTRIB_SVG_FROM_STR: String = "from"
static let ATTRIB_SVG_FX_STR: String = "fx"
static let ATTRIB_SVG_FY_STR: String = "fy"
static let ATTRIB_SVG_G1_STR: String = "g1"
static let ATTRIB_SVG_G2_STR: String = "g2"
static let ATTRIB_SVG_GLYPHREF_STR: String = "glyphRef"
static let ATTRIB_SVG_GLYPH_NAME_STR: String = "glyph_name"
static let ATTRIB_SVG_GLYPH_ORIENTATION_HORIZONTAL_STR: String = "glyph_orientation_horizontal"
static let ATTRIB_SVG_GLYPH_ORIENTATION_VERTICAL_STR: String = "glyph_orientation_vertical"
static let ATTRIB_SVG_GRADIENTTRANSFORM_STR: String = "gradientTransform"
static let ATTRIB_SVG_GRADIENTUNITS_STR: String = "gradientUnits"
static let ATTRIB_SVG_HANGING_STR: String = "hanging"
static let ATTRIB_SVG_HEIGHT_STR: String = "height"
static let ATTRIB_SVG_HORIZ_ADV_X_STR: String = "horiz_adv_x"
static let ATTRIB_SVG_HORIZ_ORIGIN_X_STR: String = "horiz_origin_x"
static let ATTRIB_SVG_HORIZ_ORIGIN_Y_STR: String = "horiz_origin_y"
static let ATTRIB_SVG_IDEOGRAPHIC_STR: String = "ideographic"
static let ATTRIB_SVG_IMAGE_RENDERING_STR: String = "image_rendering"
static let ATTRIB_SVG_IN_STR: String = "in"
static let ATTRIB_SVG_IN2_STR: String = "in2"
static let ATTRIB_SVG_INTERCEPT_STR: String = "intercept"
static let ATTRIB_SVG_K_STR: String = "k"
static let ATTRIB_SVG_K1_STR: String = "k1"
static let ATTRIB_SVG_K2_STR: String = "k2"
static let ATTRIB_SVG_K3_STR: String = "k3"
static let ATTRIB_SVG_K4_STR: String = "k4"
static let ATTRIB_SVG_KERNELMATRIX_STR: String = "kernelMatrix"
static let ATTRIB_SVG_KERNELUNITLENGTH_STR: String = "kernelUnitLength"
static let ATTRIB_SVG_KERNING_STR: String = "kerning"
static let ATTRIB_SVG_KEYPOINTS_STR: String = "keyPoints"
static let ATTRIB_SVG_KEYSPLINES_STR: String = "keySplines"
static let ATTRIB_SVG_KEYTIMES_STR: String = "keyTimes"
static let ATTRIB_SVG_LANG_STR: String = "lang"
static let ATTRIB_SVG_LENGTHADJUST_STR: String = "lengthAdjust"
static let ATTRIB_SVG_LETTER_SPACING_STR: String = "letter_spacing"
static let ATTRIB_SVG_LIGHTING_COLOR_STR: String = "lighting_color"
static let ATTRIB_SVG_LIMITINGCONEANGLE_STR: String = "limitingConeAngle"
static let ATTRIB_SVG_LOCAL_STR: String = "local"
static let ATTRIB_SVG_MARKERHEIGHT_STR: String = "markerHeight"
static let ATTRIB_SVG_MARKERUNITS_STR: String = "markerUnits"
static let ATTRIB_SVG_MARKERWIDTH_STR: String = "markerWidth"
static let ATTRIB_SVG_MARKER_END_STR: String = "marker_end"
static let ATTRIB_SVG_MARKER_MID_STR: String = "marker_mid"
static let ATTRIB_SVG_MARKER_START_STR: String = "marker_start"
static let ATTRIB_SVG_MASK_STR: String = "mask"
static let ATTRIB_SVG_MASKCONTENTUNITS_STR: String = "maskContentUnits"
static let ATTRIB_SVG_MASKUNITS_STR: String = "maskUnits"
static let ATTRIB_SVG_MATHEMATICAL_STR: String = "mathematical"
static let ATTRIB_SVG_MAX_STR: String = "max"
static let ATTRIB_SVG_MEDIA_STR: String = "media"
static let ATTRIB_SVG_METHOD_STR: String = "method"
static let ATTRIB_SVG_MIN_STR: String = "min"
static let ATTRIB_SVG_MODE_STR: String = "mode"
static let ATTRIB_SVG_NAME_STR: String = "name"
static let ATTRIB_SVG_NUMOCTAVES_STR: String = "numOctaves"
static let ATTRIB_SVG_OFFSET_STR: String = "offset"
static let ATTRIB_SVG_ONACTIVATE_STR: String = "onactivate"
static let ATTRIB_SVG_ONBEGIN_STR: String = "onbegin"
static let ATTRIB_SVG_ONEND_STR: String = "onend"
static let ATTRIB_SVG_ONFOCUSIN_STR: String = "onfocusin"
static let ATTRIB_SVG_ONFOCUSOUT_STR: String = "onfocusout"
static let ATTRIB_SVG_ONREPEAT_STR: String = "onrepeat"
static let ATTRIB_SVG_ONZOOM_STR: String = "onzoom"
static let ATTRIB_SVG_OPACITY_STR: String = "opacity"
static let ATTRIB_SVG_OPERATOR_STR: String = "operator"
static let ATTRIB_SVG_ORDER_STR: String = "order"
static let ATTRIB_SVG_ORIENT_STR: String = "orient"
static let ATTRIB_SVG_ORIENTATION_STR: String = "orientation"
static let ATTRIB_SVG_ORIGIN_STR: String = "origin"
static let ATTRIB_SVG_OVERFLOW_STR: String = "overflow"
static let ATTRIB_SVG_OVERLINE_POSITION_STR: String = "overline_position"
static let ATTRIB_SVG_OVERLINE_THICKNESS_STR: String = "overline_thickness"
static let ATTRIB_SVG_PANOSE_1_STR: String = "panose_1"
static let ATTRIB_SVG_PATH_STR: String = "path"
static let ATTRIB_SVG_PATHLENGTH_STR: String = "pathLength"
static let ATTRIB_SVG_PATTERNCONTENTUNITS_STR: String = "patternContentUnits"
static let ATTRIB_SVG_PATTERNTRANSFORM_STR: String = "patternTransform"
static let ATTRIB_SVG_PATTERNUNITS_STR: String = "patternUnits"
static let ATTRIB_SVG_POINTER_EVENTS_STR: String = "pointer_events"
static let ATTRIB_SVG_POINTS_STR: String = "points"
static let ATTRIB_SVG_POINTSATX_STR: String = "pointsAtX"
static let ATTRIB_SVG_POINTSATY_STR: String = "pointsAtY"
static let ATTRIB_SVG_POINTSATZ_STR: String = "pointsAtZ"
static let ATTRIB_SVG_PRESERVEALPHA_STR: String = "preserveAlpha"
static let ATTRIB_SVG_PRESERVEASPECTRATIO_STR: String = "preserveAspectRatio"
static let ATTRIB_SVG_PRIMITIVEUNITS_STR: String = "primitiveUnits"
static let ATTRIB_SVG_R_STR: String = "r"
static let ATTRIB_SVG_RADIUS_STR: String = "radius"
static let ATTRIB_SVG_REFX_STR: String = "refX"
static let ATTRIB_SVG_REFY_STR: String = "refY"
static let ATTRIB_SVG_RENDERING_INTENT_STR: String = "rendering_intent"
static let ATTRIB_SVG_REPEATCOUNT_STR: String = "repeatCount"
static let ATTRIB_SVG_REPEATDUR_STR: String = "repeatDur"
static let ATTRIB_SVG_REQUIREDEXTENSIONS_STR: String = "requiredExtensions"
static let ATTRIB_SVG_REQUIREDFEATURES_STR: String = "requiredFeatures"
static let ATTRIB_SVG_RESTART_STR: String = "restart"
static let ATTRIB_SVG_RESULT_STR: String = "result"
static let ATTRIB_SVG_ROTATE_STR: String = "rotate"
static let ATTRIB_SVG_RX_STR: String = "rx"
static let ATTRIB_SVG_RY_STR: String = "ry"
static let ATTRIB_SVG_SCALE_STR: String = "scale"
static let ATTRIB_SVG_SEED_STR: String = "seed"
static let ATTRIB_SVG_SHAPE_RENDERING_STR: String = "shape_rendering"
static let ATTRIB_SVG_SLOPE_STR: String = "slope"
static let ATTRIB_SVG_SPACING_STR: String = "spacing"
static let ATTRIB_SVG_SPECULARCONSTANT_STR: String = "specularConstant"
static let ATTRIB_SVG_SPECULAREXPONENT_STR: String = "specularExponent"
static let ATTRIB_SVG_SPREADMETHOD_STR: String = "spreadMethod"
static let ATTRIB_SVG_STARTOFFSET_STR: String = "startOffset"
static let ATTRIB_SVG_STDDEVIATION_STR: String = "stdDeviation"
static let ATTRIB_SVG_STEMH_STR: String = "stemh"
static let ATTRIB_SVG_STEMV_STR: String = "stemv"
static let ATTRIB_SVG_STITCHTILES_STR: String = "stitchTiles"
static let ATTRIB_SVG_STOP_COLOR_STR: String = "stop_color"
static let ATTRIB_SVG_STOP_OPACITY_STR: String = "stop_opacity"
static let ATTRIB_SVG_STRIKETHROUGH_POSITION_STR: String = "strikethrough_position"
static let ATTRIB_SVG_STRIKETHROUGH_THICKNESS_STR: String = "strikethrough_thickness"
static let ATTRIB_SVG_STROKE_STR: String = "stroke"
static let ATTRIB_SVG_STROKE_DASHARRAY_STR: String = "stroke_dasharray"
static let ATTRIB_SVG_STROKE_DASHOFFSET_STR: String = "stroke_dashoffset"
static let ATTRIB_SVG_STROKE_LINECAP_STR: String = "stroke_linecap"
static let ATTRIB_SVG_STROKE_LINEJOIN_STR: String = "stroke_linejoin"
static let ATTRIB_SVG_STROKE_MITERLIMIT_STR: String = "stroke_miterlimit"
static let ATTRIB_SVG_STROKE_OPACITY_STR: String = "stroke_opacity"
static let ATTRIB_SVG_STROKE_WIDTH_STR: String = "stroke_width"
static let ATTRIB_SVG_STYLE_STR: String = "style"
static let ATTRIB_SVG_SURFACESCALE_STR: String = "surfaceScale"
static let ATTRIB_SVG_SYSTEMLANGUAGE_STR: String = "systemLanguage"
static let ATTRIB_SVG_TABLEVALUES_STR: String = "tableValues"
static let ATTRIB_SVG_TARGET_STR: String = "target"
static let ATTRIB_SVG_TARGETX_STR: String = "targetX"
static let ATTRIB_SVG_TARGETY_STR: String = "targetY"
static let ATTRIB_SVG_TEXTLENGTH_STR: String = "textLength"
static let ATTRIB_SVG_TEXT_ANCHOR_STR: String = "text_anchor"
static let ATTRIB_SVG_TEXT_DECORATION_STR: String = "text_decoration"
static let ATTRIB_SVG_TEXT_RENDERING_STR: String = "text_rendering"
static let ATTRIB_SVG_TITLE_STR: String = "title"
static let ATTRIB_SVG_TO_STR: String = "to"
static let ATTRIB_SVG_TRANSFORM_STR: String = "transform"
static let ATTRIB_SVG_TYPE_STR: String = "type"
static let ATTRIB_SVG_U1_STR: String = "u1"
static let ATTRIB_SVG_U2_STR: String = "u2"
static let ATTRIB_SVG_UNDERLINE_POSITION_STR: String = "underline_position"
static let ATTRIB_SVG_UNDERLINE_THICKNESS_STR: String = "underline_thickness"
static let ATTRIB_SVG_UNICODE_STR: String = "unicode"
static let ATTRIB_SVG_UNICODE_BIDI_STR: String = "unicode_bidi"
static let ATTRIB_SVG_UNICODE_RANGE_STR: String = "unicode_range"
static let ATTRIB_SVG_UNITS_PER_EM_STR: String = "units_per_em"
static let ATTRIB_SVG_V_ALPHABETIC_STR: String = "v_alphabetic"
static let ATTRIB_SVG_V_HANGING_STR: String = "v_hanging"
static let ATTRIB_SVG_V_IDEOGRAPHIC_STR: String = "v_ideographic"
static let ATTRIB_SVG_V_MATHEMATICAL_STR: String = "v_mathematical"
static let ATTRIB_SVG_VALUES_STR: String = "values"
static let ATTRIB_SVG_VERSION_STR: String = "version"
static let ATTRIB_SVG_VERT_ADV_Y_STR: String = "vert_adv_y"
static let ATTRIB_SVG_VERT_ORIGIN_X_STR: String = "vert_origin_x"
static let ATTRIB_SVG_VERT_ORIGIN_Y_STR: String = "vert_origin_y"
static let ATTRIB_SVG_VIEWBOX_STR: String = "viewBox"
static let ATTRIB_SVG_VIEWTARGET_STR: String = "viewTarget"
static let ATTRIB_SVG_VISIBILITY_STR: String = "visibility"
static let ATTRIB_SVG_WIDTH_STR: String = "width"
static let ATTRIB_SVG_WIDTHS_STR: String = "widths"
static let ATTRIB_SVG_WORD_SPACING_STR: String = "word_spacing"
static let ATTRIB_SVG_WRITING_MODE_STR: String = "writing_mode"
static let ATTRIB_SVG_X_STR: String = "x"
static let ATTRIB_SVG_X1_STR: String = "x1"
static let ATTRIB_SVG_X2_STR: String = "x2"
static let ATTRIB_SVG_XCHANNELSELECTOR_STR: String = "xChannelSelector"
static let ATTRIB_SVG_X_HEIGHT_STR: String = "x_height"
static let ATTRIB_SVG_Y_STR: String = "y"
static let ATTRIB_SVG_Y1_STR: String = "y1"
static let ATTRIB_SVG_Y2_STR: String = "y2"
static let ATTRIB_SVG_YCHANNELSELECTOR_STR: String = "yChannelSelector"
static let ATTRIB_SVG_Z_STR: String = "z"
static let ATTRIB_SVG_ZOOMANDPAN_STR: String = "zoomAndPan"