// This file is generated by ConstMaker, DON'T MODIFY.

#ifndef CONSTMAKER_GENERATED_SVG_H
#define CONSTMAKER_GENERATED_SVG_H

#include <stdint.h>


typedef NS_ENUM(uint8_t, ELEMENT) {
    SVG_A_ID,
    SVG_ALTGLYPH_ID,
    SVG_ALTGLYPHDEF_ID,
    SVG_ALTGLYPHITEM_ID,
    SVG_ANIMATE_ID,
    SVG_ANIMATECOLOR_ID,
    SVG_ANIMATEMOTION_ID,
    SVG_ANIMATETRANSFORM_ID,
    SVG_CIRCLE_ID,
    SVG_CLIPPATH_ID,
    SVG_COLOR_PROFILE_ID,
    SVG_CURSOR_ID,
    SVG_DEFINITION_SRC_ID,
    SVG_DEFS_ID,
    SVG_DESC_ID,
    SVG_ELLIPSE_ID,
    SVG_FEBLEND_ID,
    SVG_FECOLORMATRIX_ID,
    SVG_FECOMPONENTTRANSFER_ID,
    SVG_FECOMPOSITE_ID,
    SVG_FECONVOLVEMATRIX_ID,
    SVG_FEDIFFUSELIGHTING_ID,
    SVG_FEDISPLACEMENTMAP_ID,
    SVG_FEDISTANTLIGHT_ID,
    SVG_FEFLOOD_ID,
    SVG_FEFUNCA_ID,
    SVG_FEFUNCB_ID,
    SVG_FEFUNCG_ID,
    SVG_FEFUNCR_ID,
    SVG_FEGAUSSIANBLUR_ID,
    SVG_FEIMAGE_ID,
    SVG_FEMERGE_ID,
    SVG_FEMERGENODE_ID,
    SVG_FEMORPHOLOGY_ID,
    SVG_FEOFFSET_ID,
    SVG_FEPOINTLIGHT_ID,
    SVG_FESPECULARLIGHTING_ID,
    SVG_FESPOTLIGHT_ID,
    SVG_FETILE_ID,
    SVG_FETURBULENCE_ID,
    SVG_FILTER_ID,
    SVG_FONT_ID,
    SVG_FONT_FACE_ID,
    SVG_FONT_FACE_FORMAT_ID,
    SVG_FONT_FACE_NAME_ID,
    SVG_FONT_FACE_SRC_ID,
    SVG_FONT_FACE_URI_ID,
    SVG_FOREIGNOBJECT_ID,
    SVG_G_ID,
    SVG_GLYPH_ID,
    SVG_GLYPHREF_ID,
    SVG_HKERN_ID,
    SVG_IMAGE_ID,
    SVG_LINE_ID,
    SVG_LINEARGRADIENT_ID,
    SVG_MARKER_ID,
    SVG_MASK_ID,
    SVG_METADATA_ID,
    SVG_MISSING_GLYPH_ID,
    SVG_MPATH_ID,
    SVG_PATH_ID,
    SVG_PATTERN_ID,
    SVG_POLYGON_ID,
    SVG_POLYLINE_ID,
    SVG_RADIALGRADIENT_ID,
    SVG_RECT_ID,
    SVG_SCRIPT_ID,
    SVG_SET_ID,
    SVG_STOP_ID,
    SVG_STYLE_ID,
    SVG_SVG_ID,
    SVG_SWITCH_ID,
    SVG_SYMBOL_ID,
    SVG_TEXT_ID,
    SVG_TEXTPATH_ID,
    SVG_TITLE_ID,
    SVG_TREF_ID,
    SVG_TSPAN_ID,
    SVG_USE_ID,
    SVG_VIEW_ID,
    SVG_VKERN_ID
};
NSString *const ELEMENT_SVG_A_ID_STR = @"a";
NSString *const ELEMENT_SVG_ALTGLYPH_ID_STR = @"altGlyph";
NSString *const ELEMENT_SVG_ALTGLYPHDEF_ID_STR = @"altGlyphDef";
NSString *const ELEMENT_SVG_ALTGLYPHITEM_ID_STR = @"altGlyphItem";
NSString *const ELEMENT_SVG_ANIMATE_ID_STR = @"animate";
NSString *const ELEMENT_SVG_ANIMATECOLOR_ID_STR = @"animateColor";
NSString *const ELEMENT_SVG_ANIMATEMOTION_ID_STR = @"animateMotion";
NSString *const ELEMENT_SVG_ANIMATETRANSFORM_ID_STR = @"animateTransform";
NSString *const ELEMENT_SVG_CIRCLE_ID_STR = @"circle";
NSString *const ELEMENT_SVG_CLIPPATH_ID_STR = @"clipPath";
NSString *const ELEMENT_SVG_COLOR_PROFILE_ID_STR = @"color_profile";
NSString *const ELEMENT_SVG_CURSOR_ID_STR = @"cursor";
NSString *const ELEMENT_SVG_DEFINITION_SRC_ID_STR = @"definition_src";
NSString *const ELEMENT_SVG_DEFS_ID_STR = @"defs";
NSString *const ELEMENT_SVG_DESC_ID_STR = @"desc";
NSString *const ELEMENT_SVG_ELLIPSE_ID_STR = @"ellipse";
NSString *const ELEMENT_SVG_FEBLEND_ID_STR = @"feBlend";
NSString *const ELEMENT_SVG_FECOLORMATRIX_ID_STR = @"feColorMatrix";
NSString *const ELEMENT_SVG_FECOMPONENTTRANSFER_ID_STR = @"feComponentTransfer";
NSString *const ELEMENT_SVG_FECOMPOSITE_ID_STR = @"feComposite";
NSString *const ELEMENT_SVG_FECONVOLVEMATRIX_ID_STR = @"feConvolveMatrix";
NSString *const ELEMENT_SVG_FEDIFFUSELIGHTING_ID_STR = @"feDiffuseLighting";
NSString *const ELEMENT_SVG_FEDISPLACEMENTMAP_ID_STR = @"feDisplacementMap";
NSString *const ELEMENT_SVG_FEDISTANTLIGHT_ID_STR = @"feDistantLight";
NSString *const ELEMENT_SVG_FEFLOOD_ID_STR = @"feFlood";
NSString *const ELEMENT_SVG_FEFUNCA_ID_STR = @"feFuncA";
NSString *const ELEMENT_SVG_FEFUNCB_ID_STR = @"feFuncB";
NSString *const ELEMENT_SVG_FEFUNCG_ID_STR = @"feFuncG";
NSString *const ELEMENT_SVG_FEFUNCR_ID_STR = @"feFuncR";
NSString *const ELEMENT_SVG_FEGAUSSIANBLUR_ID_STR = @"feGaussianBlur";
NSString *const ELEMENT_SVG_FEIMAGE_ID_STR = @"feImage";
NSString *const ELEMENT_SVG_FEMERGE_ID_STR = @"feMerge";
NSString *const ELEMENT_SVG_FEMERGENODE_ID_STR = @"feMergeNode";
NSString *const ELEMENT_SVG_FEMORPHOLOGY_ID_STR = @"feMorphology";
NSString *const ELEMENT_SVG_FEOFFSET_ID_STR = @"feOffset";
NSString *const ELEMENT_SVG_FEPOINTLIGHT_ID_STR = @"fePointLight";
NSString *const ELEMENT_SVG_FESPECULARLIGHTING_ID_STR = @"feSpecularLighting";
NSString *const ELEMENT_SVG_FESPOTLIGHT_ID_STR = @"feSpotLight";
NSString *const ELEMENT_SVG_FETILE_ID_STR = @"feTile";
NSString *const ELEMENT_SVG_FETURBULENCE_ID_STR = @"feTurbulence";
NSString *const ELEMENT_SVG_FILTER_ID_STR = @"filter";
NSString *const ELEMENT_SVG_FONT_ID_STR = @"font";
NSString *const ELEMENT_SVG_FONT_FACE_ID_STR = @"font_face";
NSString *const ELEMENT_SVG_FONT_FACE_FORMAT_ID_STR = @"font_face_format";
NSString *const ELEMENT_SVG_FONT_FACE_NAME_ID_STR = @"font_face_name";
NSString *const ELEMENT_SVG_FONT_FACE_SRC_ID_STR = @"font_face_src";
NSString *const ELEMENT_SVG_FONT_FACE_URI_ID_STR = @"font_face_uri";
NSString *const ELEMENT_SVG_FOREIGNOBJECT_ID_STR = @"foreignObject";
NSString *const ELEMENT_SVG_G_ID_STR = @"g";
NSString *const ELEMENT_SVG_GLYPH_ID_STR = @"glyph";
NSString *const ELEMENT_SVG_GLYPHREF_ID_STR = @"glyphRef";
NSString *const ELEMENT_SVG_HKERN_ID_STR = @"hkern";
NSString *const ELEMENT_SVG_IMAGE_ID_STR = @"image";
NSString *const ELEMENT_SVG_LINE_ID_STR = @"line";
NSString *const ELEMENT_SVG_LINEARGRADIENT_ID_STR = @"linearGradient";
NSString *const ELEMENT_SVG_MARKER_ID_STR = @"marker";
NSString *const ELEMENT_SVG_MASK_ID_STR = @"mask";
NSString *const ELEMENT_SVG_METADATA_ID_STR = @"metadata";
NSString *const ELEMENT_SVG_MISSING_GLYPH_ID_STR = @"missing_glyph";
NSString *const ELEMENT_SVG_MPATH_ID_STR = @"mpath";
NSString *const ELEMENT_SVG_PATH_ID_STR = @"path";
NSString *const ELEMENT_SVG_PATTERN_ID_STR = @"pattern";
NSString *const ELEMENT_SVG_POLYGON_ID_STR = @"polygon";
NSString *const ELEMENT_SVG_POLYLINE_ID_STR = @"polyline";
NSString *const ELEMENT_SVG_RADIALGRADIENT_ID_STR = @"radialGradient";
NSString *const ELEMENT_SVG_RECT_ID_STR = @"rect";
NSString *const ELEMENT_SVG_SCRIPT_ID_STR = @"script";
NSString *const ELEMENT_SVG_SET_ID_STR = @"set";
NSString *const ELEMENT_SVG_STOP_ID_STR = @"stop";
NSString *const ELEMENT_SVG_STYLE_ID_STR = @"style";
NSString *const ELEMENT_SVG_SVG_ID_STR = @"svg";
NSString *const ELEMENT_SVG_SWITCH_ID_STR = @"switch";
NSString *const ELEMENT_SVG_SYMBOL_ID_STR = @"symbol";
NSString *const ELEMENT_SVG_TEXT_ID_STR = @"text";
NSString *const ELEMENT_SVG_TEXTPATH_ID_STR = @"textPath";
NSString *const ELEMENT_SVG_TITLE_ID_STR = @"title";
NSString *const ELEMENT_SVG_TREF_ID_STR = @"tref";
NSString *const ELEMENT_SVG_TSPAN_ID_STR = @"tspan";
NSString *const ELEMENT_SVG_USE_ID_STR = @"use";
NSString *const ELEMENT_SVG_VIEW_ID_STR = @"view";
NSString *const ELEMENT_SVG_VKERN_ID_STR = @"vkern";

typedef NS_ENUM(uint8_t, ATTRIB) {
    SVG_ACCENT_HEIGHT,
    SVG_ACCUMULATE,
    SVG_ADDITIVE,
    SVG_ALIGNMENT_BASELINE,
    SVG_ALPHABETIC,
    SVG_AMPLITUDE,
    SVG_ANIMATE,
    SVG_ARABIC_FORM,
    SVG_ASCENT,
    SVG_ATTRIBUTENAME,
    SVG_ATTRIBUTETYPE,
    SVG_AZIMUTH,
    SVG_BASEFREQUENCY,
    SVG_BASEPROFILE,
    SVG_BASELINE_SHIFT,
    SVG_BBOX,
    SVG_BEGIN,
    SVG_BIAS,
    SVG_BY,
    SVG_CALCMODE,
    SVG_CAP_HEIGHT,
    SVG_CLIP,
    SVG_CLIPPATHUNITS,
    SVG_CLIP_PATH,
    SVG_CLIP_RULE,
    SVG_COLOR,
    SVG_COLOR_INTERPOLATION,
    SVG_COLOR_INTERPOLATION_FILTERS,
    SVG_COLOR_PROFILE,
    SVG_COLOR_RENDERING,
    SVG_CONTENTSCRIPTTYPE,
    SVG_CONTENTSTYLETYPE,
    SVG_CURSOR,
    SVG_CX,
    SVG_CY,
    SVG_D,
    SVG_DESCENT,
    SVG_DIFFUSECONSTANT,
    SVG_DIRECTION,
    SVG_DISPLAY,
    SVG_DIVISOR,
    SVG_DOMINANT_BASELINE,
    SVG_DUR,
    SVG_DX,
    SVG_DY,
    SVG_EDGEMODE,
    SVG_ELEVATION,
    SVG_ENABLE_BACKGROUND,
    SVG_END,
    SVG_EXPONENT,
    SVG_EXTERNALRESOURCESREQUIRED,
    SVG_FECOLORMATRIX,
    SVG_FECOMPOSITE,
    SVG_FEGAUSSIANBLUR,
    SVG_FEMORPHOLOGY,
    SVG_FETILE,
    SVG_FILL,
    SVG_FILL_OPACITY,
    SVG_FILL_RULE,
    SVG_FILTER,
    SVG_FILTERRES,
    SVG_FILTERUNITS,
    SVG_FLOOD_COLOR,
    SVG_FLOOD_OPACITY,
    SVG_FONT_FAMILY,
    SVG_FONT_SIZE,
    SVG_FONT_SIZE_ADJUST,
    SVG_FONT_STRETCH,
    SVG_FONT_STYLE,
    SVG_FONT_VARIANT,
    SVG_FONT_WEIGHT,
    SVG_FORMAT,
    SVG_FROM,
    SVG_FX,
    SVG_FY,
    SVG_G1,
    SVG_G2,
    SVG_GLYPHREF,
    SVG_GLYPH_NAME,
    SVG_GLYPH_ORIENTATION_HORIZONTAL,
    SVG_GLYPH_ORIENTATION_VERTICAL,
    SVG_GRADIENTTRANSFORM,
    SVG_GRADIENTUNITS,
    SVG_HANGING,
    SVG_HEIGHT,
    SVG_HORIZ_ADV_X,
    SVG_HORIZ_ORIGIN_X,
    SVG_HORIZ_ORIGIN_Y,
    SVG_IDEOGRAPHIC,
    SVG_IMAGE_RENDERING,
    SVG_IN,
    SVG_IN2,
    SVG_INTERCEPT,
    SVG_K,
    SVG_K1,
    SVG_K2,
    SVG_K3,
    SVG_K4,
    SVG_KERNELMATRIX,
    SVG_KERNELUNITLENGTH,
    SVG_KERNING,
    SVG_KEYPOINTS,
    SVG_KEYSPLINES,
    SVG_KEYTIMES,
    SVG_LANG,
    SVG_LENGTHADJUST,
    SVG_LETTER_SPACING,
    SVG_LIGHTING_COLOR,
    SVG_LIMITINGCONEANGLE,
    SVG_LOCAL,
    SVG_MARKERHEIGHT,
    SVG_MARKERUNITS,
    SVG_MARKERWIDTH,
    SVG_MARKER_END,
    SVG_MARKER_MID,
    SVG_MARKER_START,
    SVG_MASK,
    SVG_MASKCONTENTUNITS,
    SVG_MASKUNITS,
    SVG_MATHEMATICAL,
    SVG_MAX,
    SVG_MEDIA,
    SVG_METHOD,
    SVG_MIN,
    SVG_MODE,
    SVG_NAME,
    SVG_NUMOCTAVES,
    SVG_OFFSET,
    SVG_ONACTIVATE,
    SVG_ONBEGIN,
    SVG_ONEND,
    SVG_ONFOCUSIN,
    SVG_ONFOCUSOUT,
    SVG_ONREPEAT,
    SVG_ONZOOM,
    SVG_OPACITY,
    SVG_OPERATOR,
    SVG_ORDER,
    SVG_ORIENT,
    SVG_ORIENTATION,
    SVG_ORIGIN,
    SVG_OVERFLOW,
    SVG_OVERLINE_POSITION,
    SVG_OVERLINE_THICKNESS,
    SVG_PANOSE_1,
    SVG_PATH,
    SVG_PATHLENGTH,
    SVG_PATTERNCONTENTUNITS,
    SVG_PATTERNTRANSFORM,
    SVG_PATTERNUNITS,
    SVG_POINTER_EVENTS,
    SVG_POINTS,
    SVG_POINTSATX,
    SVG_POINTSATY,
    SVG_POINTSATZ,
    SVG_PRESERVEALPHA,
    SVG_PRESERVEASPECTRATIO,
    SVG_PRIMITIVEUNITS,
    SVG_R,
    SVG_RADIUS,
    SVG_REFX,
    SVG_REFY,
    SVG_RENDERING_INTENT,
    SVG_REPEATCOUNT,
    SVG_REPEATDUR,
    SVG_REQUIREDEXTENSIONS,
    SVG_REQUIREDFEATURES,
    SVG_RESTART,
    SVG_RESULT,
    SVG_ROTATE,
    SVG_RX,
    SVG_RY,
    SVG_SCALE,
    SVG_SEED,
    SVG_SHAPE_RENDERING,
    SVG_SLOPE,
    SVG_SPACING,
    SVG_SPECULARCONSTANT,
    SVG_SPECULAREXPONENT,
    SVG_SPREADMETHOD,
    SVG_STARTOFFSET,
    SVG_STDDEVIATION,
    SVG_STEMH,
    SVG_STEMV,
    SVG_STITCHTILES,
    SVG_STOP_COLOR,
    SVG_STOP_OPACITY,
    SVG_STRIKETHROUGH_POSITION,
    SVG_STRIKETHROUGH_THICKNESS,
    SVG_STROKE,
    SVG_STROKE_DASHARRAY,
    SVG_STROKE_DASHOFFSET,
    SVG_STROKE_LINECAP,
    SVG_STROKE_LINEJOIN,
    SVG_STROKE_MITERLIMIT,
    SVG_STROKE_OPACITY,
    SVG_STROKE_WIDTH,
    SVG_STYLE,
    SVG_SURFACESCALE,
    SVG_SYSTEMLANGUAGE,
    SVG_TABLEVALUES,
    SVG_TARGET,
    SVG_TARGETX,
    SVG_TARGETY,
    SVG_TEXTLENGTH,
    SVG_TEXT_ANCHOR,
    SVG_TEXT_DECORATION,
    SVG_TEXT_RENDERING,
    SVG_TITLE,
    SVG_TO,
    SVG_TRANSFORM,
    SVG_TYPE,
    SVG_U1,
    SVG_U2,
    SVG_UNDERLINE_POSITION,
    SVG_UNDERLINE_THICKNESS,
    SVG_UNICODE,
    SVG_UNICODE_BIDI,
    SVG_UNICODE_RANGE,
    SVG_UNITS_PER_EM,
    SVG_V_ALPHABETIC,
    SVG_V_HANGING,
    SVG_V_IDEOGRAPHIC,
    SVG_V_MATHEMATICAL,
    SVG_VALUES,
    SVG_VERSION,
    SVG_VERT_ADV_Y,
    SVG_VERT_ORIGIN_X,
    SVG_VERT_ORIGIN_Y,
    SVG_VIEWBOX,
    SVG_VIEWTARGET,
    SVG_VISIBILITY,
    SVG_WIDTH,
    SVG_WIDTHS,
    SVG_WORD_SPACING,
    SVG_WRITING_MODE,
    SVG_X,
    SVG_X1,
    SVG_X2,
    SVG_XCHANNELSELECTOR,
    SVG_X_HEIGHT,
    SVG_Y,
    SVG_Y1,
    SVG_Y2,
    SVG_YCHANNELSELECTOR,
    SVG_Z,
    SVG_ZOOMANDPAN
};
NSString *const ATTRIB_SVG_ACCENT_HEIGHT_STR = @"accent_height";
NSString *const ATTRIB_SVG_ACCUMULATE_STR = @"accumulate";
NSString *const ATTRIB_SVG_ADDITIVE_STR = @"additive";
NSString *const ATTRIB_SVG_ALIGNMENT_BASELINE_STR = @"alignment_baseline";
NSString *const ATTRIB_SVG_ALPHABETIC_STR = @"alphabetic";
NSString *const ATTRIB_SVG_AMPLITUDE_STR = @"amplitude";
NSString *const ATTRIB_SVG_ANIMATE_STR = @"animate";
NSString *const ATTRIB_SVG_ARABIC_FORM_STR = @"arabic_form";
NSString *const ATTRIB_SVG_ASCENT_STR = @"ascent";
NSString *const ATTRIB_SVG_ATTRIBUTENAME_STR = @"attributeName";
NSString *const ATTRIB_SVG_ATTRIBUTETYPE_STR = @"attributeType";
NSString *const ATTRIB_SVG_AZIMUTH_STR = @"azimuth";
NSString *const ATTRIB_SVG_BASEFREQUENCY_STR = @"baseFrequency";
NSString *const ATTRIB_SVG_BASEPROFILE_STR = @"baseProfile";
NSString *const ATTRIB_SVG_BASELINE_SHIFT_STR = @"baseline_shift";
NSString *const ATTRIB_SVG_BBOX_STR = @"bbox";
NSString *const ATTRIB_SVG_BEGIN_STR = @"begin";
NSString *const ATTRIB_SVG_BIAS_STR = @"bias";
NSString *const ATTRIB_SVG_BY_STR = @"by";
NSString *const ATTRIB_SVG_CALCMODE_STR = @"calcMode";
NSString *const ATTRIB_SVG_CAP_HEIGHT_STR = @"cap_height";
NSString *const ATTRIB_SVG_CLIP_STR = @"clip";
NSString *const ATTRIB_SVG_CLIPPATHUNITS_STR = @"clipPathUnits";
NSString *const ATTRIB_SVG_CLIP_PATH_STR = @"clip_path";
NSString *const ATTRIB_SVG_CLIP_RULE_STR = @"clip_rule";
NSString *const ATTRIB_SVG_COLOR_STR = @"color";
NSString *const ATTRIB_SVG_COLOR_INTERPOLATION_STR = @"color_interpolation";
NSString *const ATTRIB_SVG_COLOR_INTERPOLATION_FILTERS_STR = @"color_interpolation_filters";
NSString *const ATTRIB_SVG_COLOR_PROFILE_STR = @"color_profile";
NSString *const ATTRIB_SVG_COLOR_RENDERING_STR = @"color_rendering";
NSString *const ATTRIB_SVG_CONTENTSCRIPTTYPE_STR = @"contentScriptType";
NSString *const ATTRIB_SVG_CONTENTSTYLETYPE_STR = @"contentStyleType";
NSString *const ATTRIB_SVG_CURSOR_STR = @"cursor";
NSString *const ATTRIB_SVG_CX_STR = @"cx";
NSString *const ATTRIB_SVG_CY_STR = @"cy";
NSString *const ATTRIB_SVG_D_STR = @"d";
NSString *const ATTRIB_SVG_DESCENT_STR = @"descent";
NSString *const ATTRIB_SVG_DIFFUSECONSTANT_STR = @"diffuseConstant";
NSString *const ATTRIB_SVG_DIRECTION_STR = @"direction";
NSString *const ATTRIB_SVG_DISPLAY_STR = @"display";
NSString *const ATTRIB_SVG_DIVISOR_STR = @"divisor";
NSString *const ATTRIB_SVG_DOMINANT_BASELINE_STR = @"dominant_baseline";
NSString *const ATTRIB_SVG_DUR_STR = @"dur";
NSString *const ATTRIB_SVG_DX_STR = @"dx";
NSString *const ATTRIB_SVG_DY_STR = @"dy";
NSString *const ATTRIB_SVG_EDGEMODE_STR = @"edgeMode";
NSString *const ATTRIB_SVG_ELEVATION_STR = @"elevation";
NSString *const ATTRIB_SVG_ENABLE_BACKGROUND_STR = @"enable_background";
NSString *const ATTRIB_SVG_END_STR = @"end";
NSString *const ATTRIB_SVG_EXPONENT_STR = @"exponent";
NSString *const ATTRIB_SVG_EXTERNALRESOURCESREQUIRED_STR = @"externalResourcesRequired";
NSString *const ATTRIB_SVG_FECOLORMATRIX_STR = @"feColorMatrix";
NSString *const ATTRIB_SVG_FECOMPOSITE_STR = @"feComposite";
NSString *const ATTRIB_SVG_FEGAUSSIANBLUR_STR = @"feGaussianBlur";
NSString *const ATTRIB_SVG_FEMORPHOLOGY_STR = @"feMorphology";
NSString *const ATTRIB_SVG_FETILE_STR = @"feTile";
NSString *const ATTRIB_SVG_FILL_STR = @"fill";
NSString *const ATTRIB_SVG_FILL_OPACITY_STR = @"fill_opacity";
NSString *const ATTRIB_SVG_FILL_RULE_STR = @"fill_rule";
NSString *const ATTRIB_SVG_FILTER_STR = @"filter";
NSString *const ATTRIB_SVG_FILTERRES_STR = @"filterRes";
NSString *const ATTRIB_SVG_FILTERUNITS_STR = @"filterUnits";
NSString *const ATTRIB_SVG_FLOOD_COLOR_STR = @"flood_color";
NSString *const ATTRIB_SVG_FLOOD_OPACITY_STR = @"flood_opacity";
NSString *const ATTRIB_SVG_FONT_FAMILY_STR = @"font_family";
NSString *const ATTRIB_SVG_FONT_SIZE_STR = @"font_size";
NSString *const ATTRIB_SVG_FONT_SIZE_ADJUST_STR = @"font_size_adjust";
NSString *const ATTRIB_SVG_FONT_STRETCH_STR = @"font_stretch";
NSString *const ATTRIB_SVG_FONT_STYLE_STR = @"font_style";
NSString *const ATTRIB_SVG_FONT_VARIANT_STR = @"font_variant";
NSString *const ATTRIB_SVG_FONT_WEIGHT_STR = @"font_weight";
NSString *const ATTRIB_SVG_FORMAT_STR = @"format";
NSString *const ATTRIB_SVG_FROM_STR = @"from";
NSString *const ATTRIB_SVG_FX_STR = @"fx";
NSString *const ATTRIB_SVG_FY_STR = @"fy";
NSString *const ATTRIB_SVG_G1_STR = @"g1";
NSString *const ATTRIB_SVG_G2_STR = @"g2";
NSString *const ATTRIB_SVG_GLYPHREF_STR = @"glyphRef";
NSString *const ATTRIB_SVG_GLYPH_NAME_STR = @"glyph_name";
NSString *const ATTRIB_SVG_GLYPH_ORIENTATION_HORIZONTAL_STR = @"glyph_orientation_horizontal";
NSString *const ATTRIB_SVG_GLYPH_ORIENTATION_VERTICAL_STR = @"glyph_orientation_vertical";
NSString *const ATTRIB_SVG_GRADIENTTRANSFORM_STR = @"gradientTransform";
NSString *const ATTRIB_SVG_GRADIENTUNITS_STR = @"gradientUnits";
NSString *const ATTRIB_SVG_HANGING_STR = @"hanging";
NSString *const ATTRIB_SVG_HEIGHT_STR = @"height";
NSString *const ATTRIB_SVG_HORIZ_ADV_X_STR = @"horiz_adv_x";
NSString *const ATTRIB_SVG_HORIZ_ORIGIN_X_STR = @"horiz_origin_x";
NSString *const ATTRIB_SVG_HORIZ_ORIGIN_Y_STR = @"horiz_origin_y";
NSString *const ATTRIB_SVG_IDEOGRAPHIC_STR = @"ideographic";
NSString *const ATTRIB_SVG_IMAGE_RENDERING_STR = @"image_rendering";
NSString *const ATTRIB_SVG_IN_STR = @"in";
NSString *const ATTRIB_SVG_IN2_STR = @"in2";
NSString *const ATTRIB_SVG_INTERCEPT_STR = @"intercept";
NSString *const ATTRIB_SVG_K_STR = @"k";
NSString *const ATTRIB_SVG_K1_STR = @"k1";
NSString *const ATTRIB_SVG_K2_STR = @"k2";
NSString *const ATTRIB_SVG_K3_STR = @"k3";
NSString *const ATTRIB_SVG_K4_STR = @"k4";
NSString *const ATTRIB_SVG_KERNELMATRIX_STR = @"kernelMatrix";
NSString *const ATTRIB_SVG_KERNELUNITLENGTH_STR = @"kernelUnitLength";
NSString *const ATTRIB_SVG_KERNING_STR = @"kerning";
NSString *const ATTRIB_SVG_KEYPOINTS_STR = @"keyPoints";
NSString *const ATTRIB_SVG_KEYSPLINES_STR = @"keySplines";
NSString *const ATTRIB_SVG_KEYTIMES_STR = @"keyTimes";
NSString *const ATTRIB_SVG_LANG_STR = @"lang";
NSString *const ATTRIB_SVG_LENGTHADJUST_STR = @"lengthAdjust";
NSString *const ATTRIB_SVG_LETTER_SPACING_STR = @"letter_spacing";
NSString *const ATTRIB_SVG_LIGHTING_COLOR_STR = @"lighting_color";
NSString *const ATTRIB_SVG_LIMITINGCONEANGLE_STR = @"limitingConeAngle";
NSString *const ATTRIB_SVG_LOCAL_STR = @"local";
NSString *const ATTRIB_SVG_MARKERHEIGHT_STR = @"markerHeight";
NSString *const ATTRIB_SVG_MARKERUNITS_STR = @"markerUnits";
NSString *const ATTRIB_SVG_MARKERWIDTH_STR = @"markerWidth";
NSString *const ATTRIB_SVG_MARKER_END_STR = @"marker_end";
NSString *const ATTRIB_SVG_MARKER_MID_STR = @"marker_mid";
NSString *const ATTRIB_SVG_MARKER_START_STR = @"marker_start";
NSString *const ATTRIB_SVG_MASK_STR = @"mask";
NSString *const ATTRIB_SVG_MASKCONTENTUNITS_STR = @"maskContentUnits";
NSString *const ATTRIB_SVG_MASKUNITS_STR = @"maskUnits";
NSString *const ATTRIB_SVG_MATHEMATICAL_STR = @"mathematical";
NSString *const ATTRIB_SVG_MAX_STR = @"max";
NSString *const ATTRIB_SVG_MEDIA_STR = @"media";
NSString *const ATTRIB_SVG_METHOD_STR = @"method";
NSString *const ATTRIB_SVG_MIN_STR = @"min";
NSString *const ATTRIB_SVG_MODE_STR = @"mode";
NSString *const ATTRIB_SVG_NAME_STR = @"name";
NSString *const ATTRIB_SVG_NUMOCTAVES_STR = @"numOctaves";
NSString *const ATTRIB_SVG_OFFSET_STR = @"offset";
NSString *const ATTRIB_SVG_ONACTIVATE_STR = @"onactivate";
NSString *const ATTRIB_SVG_ONBEGIN_STR = @"onbegin";
NSString *const ATTRIB_SVG_ONEND_STR = @"onend";
NSString *const ATTRIB_SVG_ONFOCUSIN_STR = @"onfocusin";
NSString *const ATTRIB_SVG_ONFOCUSOUT_STR = @"onfocusout";
NSString *const ATTRIB_SVG_ONREPEAT_STR = @"onrepeat";
NSString *const ATTRIB_SVG_ONZOOM_STR = @"onzoom";
NSString *const ATTRIB_SVG_OPACITY_STR = @"opacity";
NSString *const ATTRIB_SVG_OPERATOR_STR = @"operator";
NSString *const ATTRIB_SVG_ORDER_STR = @"order";
NSString *const ATTRIB_SVG_ORIENT_STR = @"orient";
NSString *const ATTRIB_SVG_ORIENTATION_STR = @"orientation";
NSString *const ATTRIB_SVG_ORIGIN_STR = @"origin";
NSString *const ATTRIB_SVG_OVERFLOW_STR = @"overflow";
NSString *const ATTRIB_SVG_OVERLINE_POSITION_STR = @"overline_position";
NSString *const ATTRIB_SVG_OVERLINE_THICKNESS_STR = @"overline_thickness";
NSString *const ATTRIB_SVG_PANOSE_1_STR = @"panose_1";
NSString *const ATTRIB_SVG_PATH_STR = @"path";
NSString *const ATTRIB_SVG_PATHLENGTH_STR = @"pathLength";
NSString *const ATTRIB_SVG_PATTERNCONTENTUNITS_STR = @"patternContentUnits";
NSString *const ATTRIB_SVG_PATTERNTRANSFORM_STR = @"patternTransform";
NSString *const ATTRIB_SVG_PATTERNUNITS_STR = @"patternUnits";
NSString *const ATTRIB_SVG_POINTER_EVENTS_STR = @"pointer_events";
NSString *const ATTRIB_SVG_POINTS_STR = @"points";
NSString *const ATTRIB_SVG_POINTSATX_STR = @"pointsAtX";
NSString *const ATTRIB_SVG_POINTSATY_STR = @"pointsAtY";
NSString *const ATTRIB_SVG_POINTSATZ_STR = @"pointsAtZ";
NSString *const ATTRIB_SVG_PRESERVEALPHA_STR = @"preserveAlpha";
NSString *const ATTRIB_SVG_PRESERVEASPECTRATIO_STR = @"preserveAspectRatio";
NSString *const ATTRIB_SVG_PRIMITIVEUNITS_STR = @"primitiveUnits";
NSString *const ATTRIB_SVG_R_STR = @"r";
NSString *const ATTRIB_SVG_RADIUS_STR = @"radius";
NSString *const ATTRIB_SVG_REFX_STR = @"refX";
NSString *const ATTRIB_SVG_REFY_STR = @"refY";
NSString *const ATTRIB_SVG_RENDERING_INTENT_STR = @"rendering_intent";
NSString *const ATTRIB_SVG_REPEATCOUNT_STR = @"repeatCount";
NSString *const ATTRIB_SVG_REPEATDUR_STR = @"repeatDur";
NSString *const ATTRIB_SVG_REQUIREDEXTENSIONS_STR = @"requiredExtensions";
NSString *const ATTRIB_SVG_REQUIREDFEATURES_STR = @"requiredFeatures";
NSString *const ATTRIB_SVG_RESTART_STR = @"restart";
NSString *const ATTRIB_SVG_RESULT_STR = @"result";
NSString *const ATTRIB_SVG_ROTATE_STR = @"rotate";
NSString *const ATTRIB_SVG_RX_STR = @"rx";
NSString *const ATTRIB_SVG_RY_STR = @"ry";
NSString *const ATTRIB_SVG_SCALE_STR = @"scale";
NSString *const ATTRIB_SVG_SEED_STR = @"seed";
NSString *const ATTRIB_SVG_SHAPE_RENDERING_STR = @"shape_rendering";
NSString *const ATTRIB_SVG_SLOPE_STR = @"slope";
NSString *const ATTRIB_SVG_SPACING_STR = @"spacing";
NSString *const ATTRIB_SVG_SPECULARCONSTANT_STR = @"specularConstant";
NSString *const ATTRIB_SVG_SPECULAREXPONENT_STR = @"specularExponent";
NSString *const ATTRIB_SVG_SPREADMETHOD_STR = @"spreadMethod";
NSString *const ATTRIB_SVG_STARTOFFSET_STR = @"startOffset";
NSString *const ATTRIB_SVG_STDDEVIATION_STR = @"stdDeviation";
NSString *const ATTRIB_SVG_STEMH_STR = @"stemh";
NSString *const ATTRIB_SVG_STEMV_STR = @"stemv";
NSString *const ATTRIB_SVG_STITCHTILES_STR = @"stitchTiles";
NSString *const ATTRIB_SVG_STOP_COLOR_STR = @"stop_color";
NSString *const ATTRIB_SVG_STOP_OPACITY_STR = @"stop_opacity";
NSString *const ATTRIB_SVG_STRIKETHROUGH_POSITION_STR = @"strikethrough_position";
NSString *const ATTRIB_SVG_STRIKETHROUGH_THICKNESS_STR = @"strikethrough_thickness";
NSString *const ATTRIB_SVG_STROKE_STR = @"stroke";
NSString *const ATTRIB_SVG_STROKE_DASHARRAY_STR = @"stroke_dasharray";
NSString *const ATTRIB_SVG_STROKE_DASHOFFSET_STR = @"stroke_dashoffset";
NSString *const ATTRIB_SVG_STROKE_LINECAP_STR = @"stroke_linecap";
NSString *const ATTRIB_SVG_STROKE_LINEJOIN_STR = @"stroke_linejoin";
NSString *const ATTRIB_SVG_STROKE_MITERLIMIT_STR = @"stroke_miterlimit";
NSString *const ATTRIB_SVG_STROKE_OPACITY_STR = @"stroke_opacity";
NSString *const ATTRIB_SVG_STROKE_WIDTH_STR = @"stroke_width";
NSString *const ATTRIB_SVG_STYLE_STR = @"style";
NSString *const ATTRIB_SVG_SURFACESCALE_STR = @"surfaceScale";
NSString *const ATTRIB_SVG_SYSTEMLANGUAGE_STR = @"systemLanguage";
NSString *const ATTRIB_SVG_TABLEVALUES_STR = @"tableValues";
NSString *const ATTRIB_SVG_TARGET_STR = @"target";
NSString *const ATTRIB_SVG_TARGETX_STR = @"targetX";
NSString *const ATTRIB_SVG_TARGETY_STR = @"targetY";
NSString *const ATTRIB_SVG_TEXTLENGTH_STR = @"textLength";
NSString *const ATTRIB_SVG_TEXT_ANCHOR_STR = @"text_anchor";
NSString *const ATTRIB_SVG_TEXT_DECORATION_STR = @"text_decoration";
NSString *const ATTRIB_SVG_TEXT_RENDERING_STR = @"text_rendering";
NSString *const ATTRIB_SVG_TITLE_STR = @"title";
NSString *const ATTRIB_SVG_TO_STR = @"to";
NSString *const ATTRIB_SVG_TRANSFORM_STR = @"transform";
NSString *const ATTRIB_SVG_TYPE_STR = @"type";
NSString *const ATTRIB_SVG_U1_STR = @"u1";
NSString *const ATTRIB_SVG_U2_STR = @"u2";
NSString *const ATTRIB_SVG_UNDERLINE_POSITION_STR = @"underline_position";
NSString *const ATTRIB_SVG_UNDERLINE_THICKNESS_STR = @"underline_thickness";
NSString *const ATTRIB_SVG_UNICODE_STR = @"unicode";
NSString *const ATTRIB_SVG_UNICODE_BIDI_STR = @"unicode_bidi";
NSString *const ATTRIB_SVG_UNICODE_RANGE_STR = @"unicode_range";
NSString *const ATTRIB_SVG_UNITS_PER_EM_STR = @"units_per_em";
NSString *const ATTRIB_SVG_V_ALPHABETIC_STR = @"v_alphabetic";
NSString *const ATTRIB_SVG_V_HANGING_STR = @"v_hanging";
NSString *const ATTRIB_SVG_V_IDEOGRAPHIC_STR = @"v_ideographic";
NSString *const ATTRIB_SVG_V_MATHEMATICAL_STR = @"v_mathematical";
NSString *const ATTRIB_SVG_VALUES_STR = @"values";
NSString *const ATTRIB_SVG_VERSION_STR = @"version";
NSString *const ATTRIB_SVG_VERT_ADV_Y_STR = @"vert_adv_y";
NSString *const ATTRIB_SVG_VERT_ORIGIN_X_STR = @"vert_origin_x";
NSString *const ATTRIB_SVG_VERT_ORIGIN_Y_STR = @"vert_origin_y";
NSString *const ATTRIB_SVG_VIEWBOX_STR = @"viewBox";
NSString *const ATTRIB_SVG_VIEWTARGET_STR = @"viewTarget";
NSString *const ATTRIB_SVG_VISIBILITY_STR = @"visibility";
NSString *const ATTRIB_SVG_WIDTH_STR = @"width";
NSString *const ATTRIB_SVG_WIDTHS_STR = @"widths";
NSString *const ATTRIB_SVG_WORD_SPACING_STR = @"word_spacing";
NSString *const ATTRIB_SVG_WRITING_MODE_STR = @"writing_mode";
NSString *const ATTRIB_SVG_X_STR = @"x";
NSString *const ATTRIB_SVG_X1_STR = @"x1";
NSString *const ATTRIB_SVG_X2_STR = @"x2";
NSString *const ATTRIB_SVG_XCHANNELSELECTOR_STR = @"xChannelSelector";
NSString *const ATTRIB_SVG_X_HEIGHT_STR = @"x_height";
NSString *const ATTRIB_SVG_Y_STR = @"y";
NSString *const ATTRIB_SVG_Y1_STR = @"y1";
NSString *const ATTRIB_SVG_Y2_STR = @"y2";
NSString *const ATTRIB_SVG_YCHANNELSELECTOR_STR = @"yChannelSelector";
NSString *const ATTRIB_SVG_Z_STR = @"z";
NSString *const ATTRIB_SVG_ZOOMANDPAN_STR = @"zoomAndPan";

#endif // CONSTMAKER_GENERATED_SVG_H
