// This file is generated by ConstMaker, DON'T MODIFY.

#ifndef CONSTMAKER_GENERATED_SVG_H
#define CONSTMAKER_GENERATED_SVG_H

#include <stdint.h>


enum class ELEMENT : uint8_t {
    SVG_A_ID,
    SVG_ALTGLYPH_ID,
    SVG_ALTGLYPHDEF_ID,
    SVG_ALTGLYPHITEM_ID,
    SVG_ANIMATE_ID,
    SVG_ANIMATECOLOR_ID,
    SVG_ANIMATEMOTION_ID,
    SVG_ANIMATETRANSFORM_ID,
    SVG_CIRCLE_ID,
    SVG_CLIPPATH_ID,
    SVG_COLOR_PROFILE_ID,
    SVG_CURSOR_ID,
    SVG_DEFINITION_SRC_ID,
    SVG_DEFS_ID,
    SVG_DESC_ID,
    SVG_ELLIPSE_ID,
    SVG_FEBLEND_ID,
    SVG_FECOLORMATRIX_ID,
    SVG_FECOMPONENTTRANSFER_ID,
    SVG_FECOMPOSITE_ID,
    SVG_FECONVOLVEMATRIX_ID,
    SVG_FEDIFFUSELIGHTING_ID,
    SVG_FEDISPLACEMENTMAP_ID,
    SVG_FEDISTANTLIGHT_ID,
    SVG_FEFLOOD_ID,
    SVG_FEFUNCA_ID,
    SVG_FEFUNCB_ID,
    SVG_FEFUNCG_ID,
    SVG_FEFUNCR_ID,
    SVG_FEGAUSSIANBLUR_ID,
    SVG_FEIMAGE_ID,
    SVG_FEMERGE_ID,
    SVG_FEMERGENODE_ID,
    SVG_FEMORPHOLOGY_ID,
    SVG_FEOFFSET_ID,
    SVG_FEPOINTLIGHT_ID,
    SVG_FESPECULARLIGHTING_ID,
    SVG_FESPOTLIGHT_ID,
    SVG_FETILE_ID,
    SVG_FETURBULENCE_ID,
    SVG_FILTER_ID,
    SVG_FONT_ID,
    SVG_FONT_FACE_ID,
    SVG_FONT_FACE_FORMAT_ID,
    SVG_FONT_FACE_NAME_ID,
    SVG_FONT_FACE_SRC_ID,
    SVG_FONT_FACE_URI_ID,
    SVG_FOREIGNOBJECT_ID,
    SVG_G_ID,
    SVG_GLYPH_ID,
    SVG_GLYPHREF_ID,
    SVG_HKERN_ID,
    SVG_IMAGE_ID,
    SVG_LINE_ID,
    SVG_LINEARGRADIENT_ID,
    SVG_MARKER_ID,
    SVG_MASK_ID,
    SVG_METADATA_ID,
    SVG_MISSING_GLYPH_ID,
    SVG_MPATH_ID,
    SVG_PATH_ID,
    SVG_PATTERN_ID,
    SVG_POLYGON_ID,
    SVG_POLYLINE_ID,
    SVG_RADIALGRADIENT_ID,
    SVG_RECT_ID,
    SVG_SCRIPT_ID,
    SVG_SET_ID,
    SVG_STOP_ID,
    SVG_STYLE_ID,
    SVG_SVG_ID,
    SVG_SWITCH_ID,
    SVG_SYMBOL_ID,
    SVG_TEXT_ID,
    SVG_TEXTPATH_ID,
    SVG_TITLE_ID,
    SVG_TREF_ID,
    SVG_TSPAN_ID,
    SVG_USE_ID,
    SVG_VIEW_ID,
    SVG_VKERN_ID,
};
const char* ELEMENT_SVG_A_ID_STR = "a";
const char* ELEMENT_SVG_ALTGLYPH_ID_STR = "altGlyph";
const char* ELEMENT_SVG_ALTGLYPHDEF_ID_STR = "altGlyphDef";
const char* ELEMENT_SVG_ALTGLYPHITEM_ID_STR = "altGlyphItem";
const char* ELEMENT_SVG_ANIMATE_ID_STR = "animate";
const char* ELEMENT_SVG_ANIMATECOLOR_ID_STR = "animateColor";
const char* ELEMENT_SVG_ANIMATEMOTION_ID_STR = "animateMotion";
const char* ELEMENT_SVG_ANIMATETRANSFORM_ID_STR = "animateTransform";
const char* ELEMENT_SVG_CIRCLE_ID_STR = "circle";
const char* ELEMENT_SVG_CLIPPATH_ID_STR = "clipPath";
const char* ELEMENT_SVG_COLOR_PROFILE_ID_STR = "color_profile";
const char* ELEMENT_SVG_CURSOR_ID_STR = "cursor";
const char* ELEMENT_SVG_DEFINITION_SRC_ID_STR = "definition_src";
const char* ELEMENT_SVG_DEFS_ID_STR = "defs";
const char* ELEMENT_SVG_DESC_ID_STR = "desc";
const char* ELEMENT_SVG_ELLIPSE_ID_STR = "ellipse";
const char* ELEMENT_SVG_FEBLEND_ID_STR = "feBlend";
const char* ELEMENT_SVG_FECOLORMATRIX_ID_STR = "feColorMatrix";
const char* ELEMENT_SVG_FECOMPONENTTRANSFER_ID_STR = "feComponentTransfer";
const char* ELEMENT_SVG_FECOMPOSITE_ID_STR = "feComposite";
const char* ELEMENT_SVG_FECONVOLVEMATRIX_ID_STR = "feConvolveMatrix";
const char* ELEMENT_SVG_FEDIFFUSELIGHTING_ID_STR = "feDiffuseLighting";
const char* ELEMENT_SVG_FEDISPLACEMENTMAP_ID_STR = "feDisplacementMap";
const char* ELEMENT_SVG_FEDISTANTLIGHT_ID_STR = "feDistantLight";
const char* ELEMENT_SVG_FEFLOOD_ID_STR = "feFlood";
const char* ELEMENT_SVG_FEFUNCA_ID_STR = "feFuncA";
const char* ELEMENT_SVG_FEFUNCB_ID_STR = "feFuncB";
const char* ELEMENT_SVG_FEFUNCG_ID_STR = "feFuncG";
const char* ELEMENT_SVG_FEFUNCR_ID_STR = "feFuncR";
const char* ELEMENT_SVG_FEGAUSSIANBLUR_ID_STR = "feGaussianBlur";
const char* ELEMENT_SVG_FEIMAGE_ID_STR = "feImage";
const char* ELEMENT_SVG_FEMERGE_ID_STR = "feMerge";
const char* ELEMENT_SVG_FEMERGENODE_ID_STR = "feMergeNode";
const char* ELEMENT_SVG_FEMORPHOLOGY_ID_STR = "feMorphology";
const char* ELEMENT_SVG_FEOFFSET_ID_STR = "feOffset";
const char* ELEMENT_SVG_FEPOINTLIGHT_ID_STR = "fePointLight";
const char* ELEMENT_SVG_FESPECULARLIGHTING_ID_STR = "feSpecularLighting";
const char* ELEMENT_SVG_FESPOTLIGHT_ID_STR = "feSpotLight";
const char* ELEMENT_SVG_FETILE_ID_STR = "feTile";
const char* ELEMENT_SVG_FETURBULENCE_ID_STR = "feTurbulence";
const char* ELEMENT_SVG_FILTER_ID_STR = "filter";
const char* ELEMENT_SVG_FONT_ID_STR = "font";
const char* ELEMENT_SVG_FONT_FACE_ID_STR = "font_face";
const char* ELEMENT_SVG_FONT_FACE_FORMAT_ID_STR = "font_face_format";
const char* ELEMENT_SVG_FONT_FACE_NAME_ID_STR = "font_face_name";
const char* ELEMENT_SVG_FONT_FACE_SRC_ID_STR = "font_face_src";
const char* ELEMENT_SVG_FONT_FACE_URI_ID_STR = "font_face_uri";
const char* ELEMENT_SVG_FOREIGNOBJECT_ID_STR = "foreignObject";
const char* ELEMENT_SVG_G_ID_STR = "g";
const char* ELEMENT_SVG_GLYPH_ID_STR = "glyph";
const char* ELEMENT_SVG_GLYPHREF_ID_STR = "glyphRef";
const char* ELEMENT_SVG_HKERN_ID_STR = "hkern";
const char* ELEMENT_SVG_IMAGE_ID_STR = "image";
const char* ELEMENT_SVG_LINE_ID_STR = "line";
const char* ELEMENT_SVG_LINEARGRADIENT_ID_STR = "linearGradient";
const char* ELEMENT_SVG_MARKER_ID_STR = "marker";
const char* ELEMENT_SVG_MASK_ID_STR = "mask";
const char* ELEMENT_SVG_METADATA_ID_STR = "metadata";
const char* ELEMENT_SVG_MISSING_GLYPH_ID_STR = "missing_glyph";
const char* ELEMENT_SVG_MPATH_ID_STR = "mpath";
const char* ELEMENT_SVG_PATH_ID_STR = "path";
const char* ELEMENT_SVG_PATTERN_ID_STR = "pattern";
const char* ELEMENT_SVG_POLYGON_ID_STR = "polygon";
const char* ELEMENT_SVG_POLYLINE_ID_STR = "polyline";
const char* ELEMENT_SVG_RADIALGRADIENT_ID_STR = "radialGradient";
const char* ELEMENT_SVG_RECT_ID_STR = "rect";
const char* ELEMENT_SVG_SCRIPT_ID_STR = "script";
const char* ELEMENT_SVG_SET_ID_STR = "set";
const char* ELEMENT_SVG_STOP_ID_STR = "stop";
const char* ELEMENT_SVG_STYLE_ID_STR = "style";
const char* ELEMENT_SVG_SVG_ID_STR = "svg";
const char* ELEMENT_SVG_SWITCH_ID_STR = "switch";
const char* ELEMENT_SVG_SYMBOL_ID_STR = "symbol";
const char* ELEMENT_SVG_TEXT_ID_STR = "text";
const char* ELEMENT_SVG_TEXTPATH_ID_STR = "textPath";
const char* ELEMENT_SVG_TITLE_ID_STR = "title";
const char* ELEMENT_SVG_TREF_ID_STR = "tref";
const char* ELEMENT_SVG_TSPAN_ID_STR = "tspan";
const char* ELEMENT_SVG_USE_ID_STR = "use";
const char* ELEMENT_SVG_VIEW_ID_STR = "view";
const char* ELEMENT_SVG_VKERN_ID_STR = "vkern";

enum class ATTRIB : uint8_t {
    SVG_ACCENT_HEIGHT,
    SVG_ACCUMULATE,
    SVG_ADDITIVE,
    SVG_ALIGNMENT_BASELINE,
    SVG_ALPHABETIC,
    SVG_AMPLITUDE,
    SVG_ANIMATE,
    SVG_ARABIC_FORM,
    SVG_ASCENT,
    SVG_ATTRIBUTENAME,
    SVG_ATTRIBUTETYPE,
    SVG_AZIMUTH,
    SVG_BASEFREQUENCY,
    SVG_BASEPROFILE,
    SVG_BASELINE_SHIFT,
    SVG_BBOX,
    SVG_BEGIN,
    SVG_BIAS,
    SVG_BY,
    SVG_CALCMODE,
    SVG_CAP_HEIGHT,
    SVG_CLIP,
    SVG_CLIPPATHUNITS,
    SVG_CLIP_PATH,
    SVG_CLIP_RULE,
    SVG_COLOR,
    SVG_COLOR_INTERPOLATION,
    SVG_COLOR_INTERPOLATION_FILTERS,
    SVG_COLOR_PROFILE,
    SVG_COLOR_RENDERING,
    SVG_CONTENTSCRIPTTYPE,
    SVG_CONTENTSTYLETYPE,
    SVG_CURSOR,
    SVG_CX,
    SVG_CY,
    SVG_D,
    SVG_DESCENT,
    SVG_DIFFUSECONSTANT,
    SVG_DIRECTION,
    SVG_DISPLAY,
    SVG_DIVISOR,
    SVG_DOMINANT_BASELINE,
    SVG_DUR,
    SVG_DX,
    SVG_DY,
    SVG_EDGEMODE,
    SVG_ELEVATION,
    SVG_ENABLE_BACKGROUND,
    SVG_END,
    SVG_EXPONENT,
    SVG_EXTERNALRESOURCESREQUIRED,
    SVG_FECOLORMATRIX,
    SVG_FECOMPOSITE,
    SVG_FEGAUSSIANBLUR,
    SVG_FEMORPHOLOGY,
    SVG_FETILE,
    SVG_FILL,
    SVG_FILL_OPACITY,
    SVG_FILL_RULE,
    SVG_FILTER,
    SVG_FILTERRES,
    SVG_FILTERUNITS,
    SVG_FLOOD_COLOR,
    SVG_FLOOD_OPACITY,
    SVG_FONT_FAMILY,
    SVG_FONT_SIZE,
    SVG_FONT_SIZE_ADJUST,
    SVG_FONT_STRETCH,
    SVG_FONT_STYLE,
    SVG_FONT_VARIANT,
    SVG_FONT_WEIGHT,
    SVG_FORMAT,
    SVG_FROM,
    SVG_FX,
    SVG_FY,
    SVG_G1,
    SVG_G2,
    SVG_GLYPHREF,
    SVG_GLYPH_NAME,
    SVG_GLYPH_ORIENTATION_HORIZONTAL,
    SVG_GLYPH_ORIENTATION_VERTICAL,
    SVG_GRADIENTTRANSFORM,
    SVG_GRADIENTUNITS,
    SVG_HANGING,
    SVG_HEIGHT,
    SVG_HORIZ_ADV_X,
    SVG_HORIZ_ORIGIN_X,
    SVG_HORIZ_ORIGIN_Y,
    SVG_IDEOGRAPHIC,
    SVG_IMAGE_RENDERING,
    SVG_IN,
    SVG_IN2,
    SVG_INTERCEPT,
    SVG_K,
    SVG_K1,
    SVG_K2,
    SVG_K3,
    SVG_K4,
    SVG_KERNELMATRIX,
    SVG_KERNELUNITLENGTH,
    SVG_KERNING,
    SVG_KEYPOINTS,
    SVG_KEYSPLINES,
    SVG_KEYTIMES,
    SVG_LANG,
    SVG_LENGTHADJUST,
    SVG_LETTER_SPACING,
    SVG_LIGHTING_COLOR,
    SVG_LIMITINGCONEANGLE,
    SVG_LOCAL,
    SVG_MARKERHEIGHT,
    SVG_MARKERUNITS,
    SVG_MARKERWIDTH,
    SVG_MARKER_END,
    SVG_MARKER_MID,
    SVG_MARKER_START,
    SVG_MASK,
    SVG_MASKCONTENTUNITS,
    SVG_MASKUNITS,
    SVG_MATHEMATICAL,
    SVG_MAX,
    SVG_MEDIA,
    SVG_METHOD,
    SVG_MIN,
    SVG_MODE,
    SVG_NAME,
    SVG_NUMOCTAVES,
    SVG_OFFSET,
    SVG_ONACTIVATE,
    SVG_ONBEGIN,
    SVG_ONEND,
    SVG_ONFOCUSIN,
    SVG_ONFOCUSOUT,
    SVG_ONREPEAT,
    SVG_ONZOOM,
    SVG_OPACITY,
    SVG_OPERATOR,
    SVG_ORDER,
    SVG_ORIENT,
    SVG_ORIENTATION,
    SVG_ORIGIN,
    SVG_OVERFLOW,
    SVG_OVERLINE_POSITION,
    SVG_OVERLINE_THICKNESS,
    SVG_PANOSE_1,
    SVG_PATH,
    SVG_PATHLENGTH,
    SVG_PATTERNCONTENTUNITS,
    SVG_PATTERNTRANSFORM,
    SVG_PATTERNUNITS,
    SVG_POINTER_EVENTS,
    SVG_POINTS,
    SVG_POINTSATX,
    SVG_POINTSATY,
    SVG_POINTSATZ,
    SVG_PRESERVEALPHA,
    SVG_PRESERVEASPECTRATIO,
    SVG_PRIMITIVEUNITS,
    SVG_R,
    SVG_RADIUS,
    SVG_REFX,
    SVG_REFY,
    SVG_RENDERING_INTENT,
    SVG_REPEATCOUNT,
    SVG_REPEATDUR,
    SVG_REQUIREDEXTENSIONS,
    SVG_REQUIREDFEATURES,
    SVG_RESTART,
    SVG_RESULT,
    SVG_ROTATE,
    SVG_RX,
    SVG_RY,
    SVG_SCALE,
    SVG_SEED,
    SVG_SHAPE_RENDERING,
    SVG_SLOPE,
    SVG_SPACING,
    SVG_SPECULARCONSTANT,
    SVG_SPECULAREXPONENT,
    SVG_SPREADMETHOD,
    SVG_STARTOFFSET,
    SVG_STDDEVIATION,
    SVG_STEMH,
    SVG_STEMV,
    SVG_STITCHTILES,
    SVG_STOP_COLOR,
    SVG_STOP_OPACITY,
    SVG_STRIKETHROUGH_POSITION,
    SVG_STRIKETHROUGH_THICKNESS,
    SVG_STROKE,
    SVG_STROKE_DASHARRAY,
    SVG_STROKE_DASHOFFSET,
    SVG_STROKE_LINECAP,
    SVG_STROKE_LINEJOIN,
    SVG_STROKE_MITERLIMIT,
    SVG_STROKE_OPACITY,
    SVG_STROKE_WIDTH,
    SVG_STYLE,
    SVG_SURFACESCALE,
    SVG_SYSTEMLANGUAGE,
    SVG_TABLEVALUES,
    SVG_TARGET,
    SVG_TARGETX,
    SVG_TARGETY,
    SVG_TEXTLENGTH,
    SVG_TEXT_ANCHOR,
    SVG_TEXT_DECORATION,
    SVG_TEXT_RENDERING,
    SVG_TITLE,
    SVG_TO,
    SVG_TRANSFORM,
    SVG_TYPE,
    SVG_U1,
    SVG_U2,
    SVG_UNDERLINE_POSITION,
    SVG_UNDERLINE_THICKNESS,
    SVG_UNICODE,
    SVG_UNICODE_BIDI,
    SVG_UNICODE_RANGE,
    SVG_UNITS_PER_EM,
    SVG_V_ALPHABETIC,
    SVG_V_HANGING,
    SVG_V_IDEOGRAPHIC,
    SVG_V_MATHEMATICAL,
    SVG_VALUES,
    SVG_VERSION,
    SVG_VERT_ADV_Y,
    SVG_VERT_ORIGIN_X,
    SVG_VERT_ORIGIN_Y,
    SVG_VIEWBOX,
    SVG_VIEWTARGET,
    SVG_VISIBILITY,
    SVG_WIDTH,
    SVG_WIDTHS,
    SVG_WORD_SPACING,
    SVG_WRITING_MODE,
    SVG_X,
    SVG_X1,
    SVG_X2,
    SVG_XCHANNELSELECTOR,
    SVG_X_HEIGHT,
    SVG_Y,
    SVG_Y1,
    SVG_Y2,
    SVG_YCHANNELSELECTOR,
    SVG_Z,
    SVG_ZOOMANDPAN,
};
const char* ATTRIB_SVG_ACCENT_HEIGHT_STR = "accent_height";
const char* ATTRIB_SVG_ACCUMULATE_STR = "accumulate";
const char* ATTRIB_SVG_ADDITIVE_STR = "additive";
const char* ATTRIB_SVG_ALIGNMENT_BASELINE_STR = "alignment_baseline";
const char* ATTRIB_SVG_ALPHABETIC_STR = "alphabetic";
const char* ATTRIB_SVG_AMPLITUDE_STR = "amplitude";
const char* ATTRIB_SVG_ANIMATE_STR = "animate";
const char* ATTRIB_SVG_ARABIC_FORM_STR = "arabic_form";
const char* ATTRIB_SVG_ASCENT_STR = "ascent";
const char* ATTRIB_SVG_ATTRIBUTENAME_STR = "attributeName";
const char* ATTRIB_SVG_ATTRIBUTETYPE_STR = "attributeType";
const char* ATTRIB_SVG_AZIMUTH_STR = "azimuth";
const char* ATTRIB_SVG_BASEFREQUENCY_STR = "baseFrequency";
const char* ATTRIB_SVG_BASEPROFILE_STR = "baseProfile";
const char* ATTRIB_SVG_BASELINE_SHIFT_STR = "baseline_shift";
const char* ATTRIB_SVG_BBOX_STR = "bbox";
const char* ATTRIB_SVG_BEGIN_STR = "begin";
const char* ATTRIB_SVG_BIAS_STR = "bias";
const char* ATTRIB_SVG_BY_STR = "by";
const char* ATTRIB_SVG_CALCMODE_STR = "calcMode";
const char* ATTRIB_SVG_CAP_HEIGHT_STR = "cap_height";
const char* ATTRIB_SVG_CLIP_STR = "clip";
const char* ATTRIB_SVG_CLIPPATHUNITS_STR = "clipPathUnits";
const char* ATTRIB_SVG_CLIP_PATH_STR = "clip_path";
const char* ATTRIB_SVG_CLIP_RULE_STR = "clip_rule";
const char* ATTRIB_SVG_COLOR_STR = "color";
const char* ATTRIB_SVG_COLOR_INTERPOLATION_STR = "color_interpolation";
const char* ATTRIB_SVG_COLOR_INTERPOLATION_FILTERS_STR = "color_interpolation_filters";
const char* ATTRIB_SVG_COLOR_PROFILE_STR = "color_profile";
const char* ATTRIB_SVG_COLOR_RENDERING_STR = "color_rendering";
const char* ATTRIB_SVG_CONTENTSCRIPTTYPE_STR = "contentScriptType";
const char* ATTRIB_SVG_CONTENTSTYLETYPE_STR = "contentStyleType";
const char* ATTRIB_SVG_CURSOR_STR = "cursor";
const char* ATTRIB_SVG_CX_STR = "cx";
const char* ATTRIB_SVG_CY_STR = "cy";
const char* ATTRIB_SVG_D_STR = "d";
const char* ATTRIB_SVG_DESCENT_STR = "descent";
const char* ATTRIB_SVG_DIFFUSECONSTANT_STR = "diffuseConstant";
const char* ATTRIB_SVG_DIRECTION_STR = "direction";
const char* ATTRIB_SVG_DISPLAY_STR = "display";
const char* ATTRIB_SVG_DIVISOR_STR = "divisor";
const char* ATTRIB_SVG_DOMINANT_BASELINE_STR = "dominant_baseline";
const char* ATTRIB_SVG_DUR_STR = "dur";
const char* ATTRIB_SVG_DX_STR = "dx";
const char* ATTRIB_SVG_DY_STR = "dy";
const char* ATTRIB_SVG_EDGEMODE_STR = "edgeMode";
const char* ATTRIB_SVG_ELEVATION_STR = "elevation";
const char* ATTRIB_SVG_ENABLE_BACKGROUND_STR = "enable_background";
const char* ATTRIB_SVG_END_STR = "end";
const char* ATTRIB_SVG_EXPONENT_STR = "exponent";
const char* ATTRIB_SVG_EXTERNALRESOURCESREQUIRED_STR = "externalResourcesRequired";
const char* ATTRIB_SVG_FECOLORMATRIX_STR = "feColorMatrix";
const char* ATTRIB_SVG_FECOMPOSITE_STR = "feComposite";
const char* ATTRIB_SVG_FEGAUSSIANBLUR_STR = "feGaussianBlur";
const char* ATTRIB_SVG_FEMORPHOLOGY_STR = "feMorphology";
const char* ATTRIB_SVG_FETILE_STR = "feTile";
const char* ATTRIB_SVG_FILL_STR = "fill";
const char* ATTRIB_SVG_FILL_OPACITY_STR = "fill_opacity";
const char* ATTRIB_SVG_FILL_RULE_STR = "fill_rule";
const char* ATTRIB_SVG_FILTER_STR = "filter";
const char* ATTRIB_SVG_FILTERRES_STR = "filterRes";
const char* ATTRIB_SVG_FILTERUNITS_STR = "filterUnits";
const char* ATTRIB_SVG_FLOOD_COLOR_STR = "flood_color";
const char* ATTRIB_SVG_FLOOD_OPACITY_STR = "flood_opacity";
const char* ATTRIB_SVG_FONT_FAMILY_STR = "font_family";
const char* ATTRIB_SVG_FONT_SIZE_STR = "font_size";
const char* ATTRIB_SVG_FONT_SIZE_ADJUST_STR = "font_size_adjust";
const char* ATTRIB_SVG_FONT_STRETCH_STR = "font_stretch";
const char* ATTRIB_SVG_FONT_STYLE_STR = "font_style";
const char* ATTRIB_SVG_FONT_VARIANT_STR = "font_variant";
const char* ATTRIB_SVG_FONT_WEIGHT_STR = "font_weight";
const char* ATTRIB_SVG_FORMAT_STR = "format";
const char* ATTRIB_SVG_FROM_STR = "from";
const char* ATTRIB_SVG_FX_STR = "fx";
const char* ATTRIB_SVG_FY_STR = "fy";
const char* ATTRIB_SVG_G1_STR = "g1";
const char* ATTRIB_SVG_G2_STR = "g2";
const char* ATTRIB_SVG_GLYPHREF_STR = "glyphRef";
const char* ATTRIB_SVG_GLYPH_NAME_STR = "glyph_name";
const char* ATTRIB_SVG_GLYPH_ORIENTATION_HORIZONTAL_STR = "glyph_orientation_horizontal";
const char* ATTRIB_SVG_GLYPH_ORIENTATION_VERTICAL_STR = "glyph_orientation_vertical";
const char* ATTRIB_SVG_GRADIENTTRANSFORM_STR = "gradientTransform";
const char* ATTRIB_SVG_GRADIENTUNITS_STR = "gradientUnits";
const char* ATTRIB_SVG_HANGING_STR = "hanging";
const char* ATTRIB_SVG_HEIGHT_STR = "height";
const char* ATTRIB_SVG_HORIZ_ADV_X_STR = "horiz_adv_x";
const char* ATTRIB_SVG_HORIZ_ORIGIN_X_STR = "horiz_origin_x";
const char* ATTRIB_SVG_HORIZ_ORIGIN_Y_STR = "horiz_origin_y";
const char* ATTRIB_SVG_IDEOGRAPHIC_STR = "ideographic";
const char* ATTRIB_SVG_IMAGE_RENDERING_STR = "image_rendering";
const char* ATTRIB_SVG_IN_STR = "in";
const char* ATTRIB_SVG_IN2_STR = "in2";
const char* ATTRIB_SVG_INTERCEPT_STR = "intercept";
const char* ATTRIB_SVG_K_STR = "k";
const char* ATTRIB_SVG_K1_STR = "k1";
const char* ATTRIB_SVG_K2_STR = "k2";
const char* ATTRIB_SVG_K3_STR = "k3";
const char* ATTRIB_SVG_K4_STR = "k4";
const char* ATTRIB_SVG_KERNELMATRIX_STR = "kernelMatrix";
const char* ATTRIB_SVG_KERNELUNITLENGTH_STR = "kernelUnitLength";
const char* ATTRIB_SVG_KERNING_STR = "kerning";
const char* ATTRIB_SVG_KEYPOINTS_STR = "keyPoints";
const char* ATTRIB_SVG_KEYSPLINES_STR = "keySplines";
const char* ATTRIB_SVG_KEYTIMES_STR = "keyTimes";
const char* ATTRIB_SVG_LANG_STR = "lang";
const char* ATTRIB_SVG_LENGTHADJUST_STR = "lengthAdjust";
const char* ATTRIB_SVG_LETTER_SPACING_STR = "letter_spacing";
const char* ATTRIB_SVG_LIGHTING_COLOR_STR = "lighting_color";
const char* ATTRIB_SVG_LIMITINGCONEANGLE_STR = "limitingConeAngle";
const char* ATTRIB_SVG_LOCAL_STR = "local";
const char* ATTRIB_SVG_MARKERHEIGHT_STR = "markerHeight";
const char* ATTRIB_SVG_MARKERUNITS_STR = "markerUnits";
const char* ATTRIB_SVG_MARKERWIDTH_STR = "markerWidth";
const char* ATTRIB_SVG_MARKER_END_STR = "marker_end";
const char* ATTRIB_SVG_MARKER_MID_STR = "marker_mid";
const char* ATTRIB_SVG_MARKER_START_STR = "marker_start";
const char* ATTRIB_SVG_MASK_STR = "mask";
const char* ATTRIB_SVG_MASKCONTENTUNITS_STR = "maskContentUnits";
const char* ATTRIB_SVG_MASKUNITS_STR = "maskUnits";
const char* ATTRIB_SVG_MATHEMATICAL_STR = "mathematical";
const char* ATTRIB_SVG_MAX_STR = "max";
const char* ATTRIB_SVG_MEDIA_STR = "media";
const char* ATTRIB_SVG_METHOD_STR = "method";
const char* ATTRIB_SVG_MIN_STR = "min";
const char* ATTRIB_SVG_MODE_STR = "mode";
const char* ATTRIB_SVG_NAME_STR = "name";
const char* ATTRIB_SVG_NUMOCTAVES_STR = "numOctaves";
const char* ATTRIB_SVG_OFFSET_STR = "offset";
const char* ATTRIB_SVG_ONACTIVATE_STR = "onactivate";
const char* ATTRIB_SVG_ONBEGIN_STR = "onbegin";
const char* ATTRIB_SVG_ONEND_STR = "onend";
const char* ATTRIB_SVG_ONFOCUSIN_STR = "onfocusin";
const char* ATTRIB_SVG_ONFOCUSOUT_STR = "onfocusout";
const char* ATTRIB_SVG_ONREPEAT_STR = "onrepeat";
const char* ATTRIB_SVG_ONZOOM_STR = "onzoom";
const char* ATTRIB_SVG_OPACITY_STR = "opacity";
const char* ATTRIB_SVG_OPERATOR_STR = "operator";
const char* ATTRIB_SVG_ORDER_STR = "order";
const char* ATTRIB_SVG_ORIENT_STR = "orient";
const char* ATTRIB_SVG_ORIENTATION_STR = "orientation";
const char* ATTRIB_SVG_ORIGIN_STR = "origin";
const char* ATTRIB_SVG_OVERFLOW_STR = "overflow";
const char* ATTRIB_SVG_OVERLINE_POSITION_STR = "overline_position";
const char* ATTRIB_SVG_OVERLINE_THICKNESS_STR = "overline_thickness";
const char* ATTRIB_SVG_PANOSE_1_STR = "panose_1";
const char* ATTRIB_SVG_PATH_STR = "path";
const char* ATTRIB_SVG_PATHLENGTH_STR = "pathLength";
const char* ATTRIB_SVG_PATTERNCONTENTUNITS_STR = "patternContentUnits";
const char* ATTRIB_SVG_PATTERNTRANSFORM_STR = "patternTransform";
const char* ATTRIB_SVG_PATTERNUNITS_STR = "patternUnits";
const char* ATTRIB_SVG_POINTER_EVENTS_STR = "pointer_events";
const char* ATTRIB_SVG_POINTS_STR = "points";
const char* ATTRIB_SVG_POINTSATX_STR = "pointsAtX";
const char* ATTRIB_SVG_POINTSATY_STR = "pointsAtY";
const char* ATTRIB_SVG_POINTSATZ_STR = "pointsAtZ";
const char* ATTRIB_SVG_PRESERVEALPHA_STR = "preserveAlpha";
const char* ATTRIB_SVG_PRESERVEASPECTRATIO_STR = "preserveAspectRatio";
const char* ATTRIB_SVG_PRIMITIVEUNITS_STR = "primitiveUnits";
const char* ATTRIB_SVG_R_STR = "r";
const char* ATTRIB_SVG_RADIUS_STR = "radius";
const char* ATTRIB_SVG_REFX_STR = "refX";
const char* ATTRIB_SVG_REFY_STR = "refY";
const char* ATTRIB_SVG_RENDERING_INTENT_STR = "rendering_intent";
const char* ATTRIB_SVG_REPEATCOUNT_STR = "repeatCount";
const char* ATTRIB_SVG_REPEATDUR_STR = "repeatDur";
const char* ATTRIB_SVG_REQUIREDEXTENSIONS_STR = "requiredExtensions";
const char* ATTRIB_SVG_REQUIREDFEATURES_STR = "requiredFeatures";
const char* ATTRIB_SVG_RESTART_STR = "restart";
const char* ATTRIB_SVG_RESULT_STR = "result";
const char* ATTRIB_SVG_ROTATE_STR = "rotate";
const char* ATTRIB_SVG_RX_STR = "rx";
const char* ATTRIB_SVG_RY_STR = "ry";
const char* ATTRIB_SVG_SCALE_STR = "scale";
const char* ATTRIB_SVG_SEED_STR = "seed";
const char* ATTRIB_SVG_SHAPE_RENDERING_STR = "shape_rendering";
const char* ATTRIB_SVG_SLOPE_STR = "slope";
const char* ATTRIB_SVG_SPACING_STR = "spacing";
const char* ATTRIB_SVG_SPECULARCONSTANT_STR = "specularConstant";
const char* ATTRIB_SVG_SPECULAREXPONENT_STR = "specularExponent";
const char* ATTRIB_SVG_SPREADMETHOD_STR = "spreadMethod";
const char* ATTRIB_SVG_STARTOFFSET_STR = "startOffset";
const char* ATTRIB_SVG_STDDEVIATION_STR = "stdDeviation";
const char* ATTRIB_SVG_STEMH_STR = "stemh";
const char* ATTRIB_SVG_STEMV_STR = "stemv";
const char* ATTRIB_SVG_STITCHTILES_STR = "stitchTiles";
const char* ATTRIB_SVG_STOP_COLOR_STR = "stop_color";
const char* ATTRIB_SVG_STOP_OPACITY_STR = "stop_opacity";
const char* ATTRIB_SVG_STRIKETHROUGH_POSITION_STR = "strikethrough_position";
const char* ATTRIB_SVG_STRIKETHROUGH_THICKNESS_STR = "strikethrough_thickness";
const char* ATTRIB_SVG_STROKE_STR = "stroke";
const char* ATTRIB_SVG_STROKE_DASHARRAY_STR = "stroke_dasharray";
const char* ATTRIB_SVG_STROKE_DASHOFFSET_STR = "stroke_dashoffset";
const char* ATTRIB_SVG_STROKE_LINECAP_STR = "stroke_linecap";
const char* ATTRIB_SVG_STROKE_LINEJOIN_STR = "stroke_linejoin";
const char* ATTRIB_SVG_STROKE_MITERLIMIT_STR = "stroke_miterlimit";
const char* ATTRIB_SVG_STROKE_OPACITY_STR = "stroke_opacity";
const char* ATTRIB_SVG_STROKE_WIDTH_STR = "stroke_width";
const char* ATTRIB_SVG_STYLE_STR = "style";
const char* ATTRIB_SVG_SURFACESCALE_STR = "surfaceScale";
const char* ATTRIB_SVG_SYSTEMLANGUAGE_STR = "systemLanguage";
const char* ATTRIB_SVG_TABLEVALUES_STR = "tableValues";
const char* ATTRIB_SVG_TARGET_STR = "target";
const char* ATTRIB_SVG_TARGETX_STR = "targetX";
const char* ATTRIB_SVG_TARGETY_STR = "targetY";
const char* ATTRIB_SVG_TEXTLENGTH_STR = "textLength";
const char* ATTRIB_SVG_TEXT_ANCHOR_STR = "text_anchor";
const char* ATTRIB_SVG_TEXT_DECORATION_STR = "text_decoration";
const char* ATTRIB_SVG_TEXT_RENDERING_STR = "text_rendering";
const char* ATTRIB_SVG_TITLE_STR = "title";
const char* ATTRIB_SVG_TO_STR = "to";
const char* ATTRIB_SVG_TRANSFORM_STR = "transform";
const char* ATTRIB_SVG_TYPE_STR = "type";
const char* ATTRIB_SVG_U1_STR = "u1";
const char* ATTRIB_SVG_U2_STR = "u2";
const char* ATTRIB_SVG_UNDERLINE_POSITION_STR = "underline_position";
const char* ATTRIB_SVG_UNDERLINE_THICKNESS_STR = "underline_thickness";
const char* ATTRIB_SVG_UNICODE_STR = "unicode";
const char* ATTRIB_SVG_UNICODE_BIDI_STR = "unicode_bidi";
const char* ATTRIB_SVG_UNICODE_RANGE_STR = "unicode_range";
const char* ATTRIB_SVG_UNITS_PER_EM_STR = "units_per_em";
const char* ATTRIB_SVG_V_ALPHABETIC_STR = "v_alphabetic";
const char* ATTRIB_SVG_V_HANGING_STR = "v_hanging";
const char* ATTRIB_SVG_V_IDEOGRAPHIC_STR = "v_ideographic";
const char* ATTRIB_SVG_V_MATHEMATICAL_STR = "v_mathematical";
const char* ATTRIB_SVG_VALUES_STR = "values";
const char* ATTRIB_SVG_VERSION_STR = "version";
const char* ATTRIB_SVG_VERT_ADV_Y_STR = "vert_adv_y";
const char* ATTRIB_SVG_VERT_ORIGIN_X_STR = "vert_origin_x";
const char* ATTRIB_SVG_VERT_ORIGIN_Y_STR = "vert_origin_y";
const char* ATTRIB_SVG_VIEWBOX_STR = "viewBox";
const char* ATTRIB_SVG_VIEWTARGET_STR = "viewTarget";
const char* ATTRIB_SVG_VISIBILITY_STR = "visibility";
const char* ATTRIB_SVG_WIDTH_STR = "width";
const char* ATTRIB_SVG_WIDTHS_STR = "widths";
const char* ATTRIB_SVG_WORD_SPACING_STR = "word_spacing";
const char* ATTRIB_SVG_WRITING_MODE_STR = "writing_mode";
const char* ATTRIB_SVG_X_STR = "x";
const char* ATTRIB_SVG_X1_STR = "x1";
const char* ATTRIB_SVG_X2_STR = "x2";
const char* ATTRIB_SVG_XCHANNELSELECTOR_STR = "xChannelSelector";
const char* ATTRIB_SVG_X_HEIGHT_STR = "x_height";
const char* ATTRIB_SVG_Y_STR = "y";
const char* ATTRIB_SVG_Y1_STR = "y1";
const char* ATTRIB_SVG_Y2_STR = "y2";
const char* ATTRIB_SVG_YCHANNELSELECTOR_STR = "yChannelSelector";
const char* ATTRIB_SVG_Z_STR = "z";
const char* ATTRIB_SVG_ZOOMANDPAN_STR = "zoomAndPan";

#endif // CONSTMAKER_GENERATED_SVG_H
