// This file is generated by ConstMaker, DON'T MODIFY.

#ifndef CONSTMAKER_GENERATED_HTML_H
#define CONSTMAKER_GENERATED_HTML_H

#include <stdint.h>


typedef NS_ENUM(uint8_t, ELEMENT) {
    HTML_A_ID,
    HTML_ABBR_ID,
    HTML_ACRONYM_ID,
    HTML_ADDRESS_ID,
    HTML_APPLET_ID,
    HTML_AREA_ID,
    HTML_AUDIO_ID,
    HTML_B_ID,
    HTML_BASE_ID,
    HTML_BASEFONT_ID,
    HTML_BDO_ID,
    HTML_BIG_ID,
    HTML_BLOCKQUOTE_ID,
    HTML_BODY_ID,
    HTML_BR_ID,
    HTML_BUTTON_ID,
    HTML_CANVAS_ID,
    HTML_CAPTION_ID,
    HTML_CENTER_ID,
    HTML_CITE_ID,
    HTML_CODE_ID,
    HTML_COL_ID,
    HTML_COLGROUP_ID,
    HTML_COMMENT_ID,
    HTML_DD_ID,
    HTML_DEL_ID,
    HTML_DFN_ID,
    HTML_DIR_ID,
    HTML_DIV_ID,
    HTML_DL_ID,
    HTML_DT_ID,
    HTML_EM_ID,
    HTML_EMBED_ID,
    HTML_FIELDSET_ID,
    HTML_FONT_ID,
    HTML_FORM_ID,
    HTML_FRAME_ID,
    HTML_FRAMESET_ID,
    HTML_H1_ID,
    HTML_H2_ID,
    HTML_H3_ID,
    HTML_H4_ID,
    HTML_H5_ID,
    HTML_H6_ID,
    HTML_HEAD_ID,
    HTML_HR_ID,
    HTML_HTML_ID,
    HTML_I_ID,
    HTML_IFRAME_ID,
    HTML_ILAYER_ID,
    HTML_IMAGE_ID,
    HTML_IMG_ID,
    HTML_INPUT_ID,
    HTML_INS_ID,
    HTML_ISINDEX_ID,
    HTML_KBD_ID,
    HTML_KEYGEN_ID,
    HTML_LABEL_ID,
    HTML_LAYER_ID,
    HTML_LEGEND_ID,
    HTML_LI_ID,
    HTML_LINK_ID,
    HTML_LISTING_ID,
    HTML_MAP_ID,
    HTML_MARQUEE_ID,
    HTML_MENU_ID,
    HTML_META_ID,
    HTML_NOBR_ID,
    HTML_NOEMBED_ID,
    HTML_NOFRAMES_ID,
    HTML_NOLAYER_ID,
    HTML_NOSCRIPT_ID,
    HTML_OBJECT_ID,
    HTML_OL_ID,
    HTML_OPTGROUP_ID,
    HTML_OPTION_ID,
    HTML_P_ID,
    HTML_PARAM_ID,
    HTML_PLAINTEXT_ID,
    HTML_PRE_ID,
    HTML_Q_ID,
    HTML_S_ID,
    HTML_SAMP_ID,
    HTML_SCRIPT_ID,
    HTML_SELECT_ID,
    HTML_SMALL_ID,
    HTML_SOURCE_ID,
    HTML_SPAN_ID,
    HTML_STRIKE_ID,
    HTML_STRONG_ID,
    HTML_STYLE_ID,
    HTML_SUB_ID,
    HTML_SUP_ID,
    HTML_TABLE_ID,
    HTML_TBODY_ID,
    HTML_TD_ID,
    HTML_TEXT_ID,
    HTML_TEXTAREA_ID,
    HTML_TFOOT_ID,
    HTML_TH_ID,
    HTML_THEAD_ID,
    HTML_TITLE_ID,
    HTML_TR_ID,
    HTML_TT_ID,
    HTML_U_ID,
    HTML_UL_ID,
    HTML_VAR_ID,
    HTML_VIDEO_ID,
    HTML_WBR_ID,
    HTML_XMP_ID
};
NSString *const ELEMENT_HTML_A_ID_STR = @"a";
NSString *const ELEMENT_HTML_ABBR_ID_STR = @"abbr";
NSString *const ELEMENT_HTML_ACRONYM_ID_STR = @"acronym";
NSString *const ELEMENT_HTML_ADDRESS_ID_STR = @"address";
NSString *const ELEMENT_HTML_APPLET_ID_STR = @"applet";
NSString *const ELEMENT_HTML_AREA_ID_STR = @"area";
NSString *const ELEMENT_HTML_AUDIO_ID_STR = @"audio";
NSString *const ELEMENT_HTML_B_ID_STR = @"b";
NSString *const ELEMENT_HTML_BASE_ID_STR = @"base";
NSString *const ELEMENT_HTML_BASEFONT_ID_STR = @"basefont";
NSString *const ELEMENT_HTML_BDO_ID_STR = @"bdo";
NSString *const ELEMENT_HTML_BIG_ID_STR = @"big";
NSString *const ELEMENT_HTML_BLOCKQUOTE_ID_STR = @"blockquote";
NSString *const ELEMENT_HTML_BODY_ID_STR = @"body";
NSString *const ELEMENT_HTML_BR_ID_STR = @"br";
NSString *const ELEMENT_HTML_BUTTON_ID_STR = @"button";
NSString *const ELEMENT_HTML_CANVAS_ID_STR = @"canvas";
NSString *const ELEMENT_HTML_CAPTION_ID_STR = @"caption";
NSString *const ELEMENT_HTML_CENTER_ID_STR = @"center";
NSString *const ELEMENT_HTML_CITE_ID_STR = @"cite";
NSString *const ELEMENT_HTML_CODE_ID_STR = @"code";
NSString *const ELEMENT_HTML_COL_ID_STR = @"col";
NSString *const ELEMENT_HTML_COLGROUP_ID_STR = @"colgroup";
NSString *const ELEMENT_HTML_COMMENT_ID_STR = @"comment";
NSString *const ELEMENT_HTML_DD_ID_STR = @"dd";
NSString *const ELEMENT_HTML_DEL_ID_STR = @"del";
NSString *const ELEMENT_HTML_DFN_ID_STR = @"dfn";
NSString *const ELEMENT_HTML_DIR_ID_STR = @"dir";
NSString *const ELEMENT_HTML_DIV_ID_STR = @"div";
NSString *const ELEMENT_HTML_DL_ID_STR = @"dl";
NSString *const ELEMENT_HTML_DT_ID_STR = @"dt";
NSString *const ELEMENT_HTML_EM_ID_STR = @"em";
NSString *const ELEMENT_HTML_EMBED_ID_STR = @"embed";
NSString *const ELEMENT_HTML_FIELDSET_ID_STR = @"fieldset";
NSString *const ELEMENT_HTML_FONT_ID_STR = @"font";
NSString *const ELEMENT_HTML_FORM_ID_STR = @"form";
NSString *const ELEMENT_HTML_FRAME_ID_STR = @"frame";
NSString *const ELEMENT_HTML_FRAMESET_ID_STR = @"frameset";
NSString *const ELEMENT_HTML_H1_ID_STR = @"h1";
NSString *const ELEMENT_HTML_H2_ID_STR = @"h2";
NSString *const ELEMENT_HTML_H3_ID_STR = @"h3";
NSString *const ELEMENT_HTML_H4_ID_STR = @"h4";
NSString *const ELEMENT_HTML_H5_ID_STR = @"h5";
NSString *const ELEMENT_HTML_H6_ID_STR = @"h6";
NSString *const ELEMENT_HTML_HEAD_ID_STR = @"head";
NSString *const ELEMENT_HTML_HR_ID_STR = @"hr";
NSString *const ELEMENT_HTML_HTML_ID_STR = @"html";
NSString *const ELEMENT_HTML_I_ID_STR = @"i";
NSString *const ELEMENT_HTML_IFRAME_ID_STR = @"iframe";
NSString *const ELEMENT_HTML_ILAYER_ID_STR = @"ilayer";
NSString *const ELEMENT_HTML_IMAGE_ID_STR = @"image";
NSString *const ELEMENT_HTML_IMG_ID_STR = @"img";
NSString *const ELEMENT_HTML_INPUT_ID_STR = @"input";
NSString *const ELEMENT_HTML_INS_ID_STR = @"ins";
NSString *const ELEMENT_HTML_ISINDEX_ID_STR = @"isindex";
NSString *const ELEMENT_HTML_KBD_ID_STR = @"kbd";
NSString *const ELEMENT_HTML_KEYGEN_ID_STR = @"keygen";
NSString *const ELEMENT_HTML_LABEL_ID_STR = @"label";
NSString *const ELEMENT_HTML_LAYER_ID_STR = @"layer";
NSString *const ELEMENT_HTML_LEGEND_ID_STR = @"legend";
NSString *const ELEMENT_HTML_LI_ID_STR = @"li";
NSString *const ELEMENT_HTML_LINK_ID_STR = @"link";
NSString *const ELEMENT_HTML_LISTING_ID_STR = @"listing";
NSString *const ELEMENT_HTML_MAP_ID_STR = @"map";
NSString *const ELEMENT_HTML_MARQUEE_ID_STR = @"marquee";
NSString *const ELEMENT_HTML_MENU_ID_STR = @"menu";
NSString *const ELEMENT_HTML_META_ID_STR = @"meta";
NSString *const ELEMENT_HTML_NOBR_ID_STR = @"nobr";
NSString *const ELEMENT_HTML_NOEMBED_ID_STR = @"noembed";
NSString *const ELEMENT_HTML_NOFRAMES_ID_STR = @"noframes";
NSString *const ELEMENT_HTML_NOLAYER_ID_STR = @"nolayer";
NSString *const ELEMENT_HTML_NOSCRIPT_ID_STR = @"noscript";
NSString *const ELEMENT_HTML_OBJECT_ID_STR = @"object";
NSString *const ELEMENT_HTML_OL_ID_STR = @"ol";
NSString *const ELEMENT_HTML_OPTGROUP_ID_STR = @"optgroup";
NSString *const ELEMENT_HTML_OPTION_ID_STR = @"option";
NSString *const ELEMENT_HTML_P_ID_STR = @"p";
NSString *const ELEMENT_HTML_PARAM_ID_STR = @"param";
NSString *const ELEMENT_HTML_PLAINTEXT_ID_STR = @"plaintext";
NSString *const ELEMENT_HTML_PRE_ID_STR = @"pre";
NSString *const ELEMENT_HTML_Q_ID_STR = @"q";
NSString *const ELEMENT_HTML_S_ID_STR = @"s";
NSString *const ELEMENT_HTML_SAMP_ID_STR = @"samp";
NSString *const ELEMENT_HTML_SCRIPT_ID_STR = @"script";
NSString *const ELEMENT_HTML_SELECT_ID_STR = @"select";
NSString *const ELEMENT_HTML_SMALL_ID_STR = @"small";
NSString *const ELEMENT_HTML_SOURCE_ID_STR = @"source";
NSString *const ELEMENT_HTML_SPAN_ID_STR = @"span";
NSString *const ELEMENT_HTML_STRIKE_ID_STR = @"strike";
NSString *const ELEMENT_HTML_STRONG_ID_STR = @"strong";
NSString *const ELEMENT_HTML_STYLE_ID_STR = @"style";
NSString *const ELEMENT_HTML_SUB_ID_STR = @"sub";
NSString *const ELEMENT_HTML_SUP_ID_STR = @"sup";
NSString *const ELEMENT_HTML_TABLE_ID_STR = @"table";
NSString *const ELEMENT_HTML_TBODY_ID_STR = @"tbody";
NSString *const ELEMENT_HTML_TD_ID_STR = @"td";
NSString *const ELEMENT_HTML_TEXT_ID_STR = @"text";
NSString *const ELEMENT_HTML_TEXTAREA_ID_STR = @"textarea";
NSString *const ELEMENT_HTML_TFOOT_ID_STR = @"tfoot";
NSString *const ELEMENT_HTML_TH_ID_STR = @"th";
NSString *const ELEMENT_HTML_THEAD_ID_STR = @"thead";
NSString *const ELEMENT_HTML_TITLE_ID_STR = @"title";
NSString *const ELEMENT_HTML_TR_ID_STR = @"tr";
NSString *const ELEMENT_HTML_TT_ID_STR = @"tt";
NSString *const ELEMENT_HTML_U_ID_STR = @"u";
NSString *const ELEMENT_HTML_UL_ID_STR = @"ul";
NSString *const ELEMENT_HTML_VAR_ID_STR = @"var";
NSString *const ELEMENT_HTML_VIDEO_ID_STR = @"video";
NSString *const ELEMENT_HTML_WBR_ID_STR = @"wbr";
NSString *const ELEMENT_HTML_XMP_ID_STR = @"xmp";

typedef NS_ENUM(uint8_t, ATTRIB) {
    HTML_ABBR,
    HTML_ACCEPT,
    HTML_ACCEPT_CHARSET,
    HTML_ACCESSKEY,
    HTML_ACTION,
    HTML_ALIGN,
    HTML_ALINK,
    HTML_ALT,
    HTML_ARCHIVE,
    HTML_AUTOCOMPLETE,
    HTML_AUTOPLAY,
    HTML_AXIS,
    HTML_BACKGROUND,
    HTML_BEHAVIOR,
    HTML_BGCOLOR,
    HTML_BGPROPERTIES,
    HTML_BORDER,
    HTML_BORDERCOLOR,
    HTML_CELLPADDING,
    HTML_CELLSPACING,
    HTML_CHALLENGE,
    HTML_CHAR,
    HTML_CHAROFF,
    HTML_CHARSET,
    HTML_CHECKED,
    HTML_CITE,
    HTML_CLASS,
    HTML_CLASSID,
    HTML_CLEAR,
    HTML_CODE,
    HTML_CODEBASE,
    HTML_CODETYPE,
    HTML_COLOR,
    HTML_COLS,
    HTML_COLSPAN,
    HTML_COMPACT,
    HTML_CONTENT,
    HTML_CONTENTEDITABLE,
    HTML_CONTROLS,
    HTML_COORDS,
    HTML_DATA,
    HTML_DATETIME,
    HTML_DECLARE,
    HTML_DEFER,
    HTML_DIR,
    HTML_DIRECTION,
    HTML_DISABLED,
    HTML_ENCTYPE,
    HTML_FACE,
    HTML_FOR,
    HTML_FRAME,
    HTML_FRAMEBORDER,
    HTML_HEADERS,
    HTML_HEIGHT,
    HTML_HIDDEN,
    HTML_HREF,
    HTML_HREFLANG,
    HTML_HSPACE,
    HTML_HTML,
    HTML_HTTP_EQUIV,
    HTML_ID,
    HTML_ISMAP,
    HTML_LABEL,
    HTML_LANG,
    HTML_LANGUAGE,
    HTML_LEFT,
    HTML_LEFTMARGIN,
    HTML_LINK,
    HTML_LONGDESC,
    HTML_LOOP,
    HTML_MARGINHEIGHT,
    HTML_MARGINWIDTH,
    HTML_MAXLENGTH,
    HTML_MEDIA,
    HTML_METHOD,
    HTML_MULTIPLE,
    HTML_NAME,
    HTML_NOHREF,
    HTML_NORESIZE,
    HTML_NOSAVE,
    HTML_NOSHADE,
    HTML_NOWRAP,
    HTML_OBJECT,
    HTML_ONABORT,
    HTML_ONBLUR,
    HTML_ONCHANGE,
    HTML_ONCLICK,
    HTML_ONDBLCLICK,
    HTML_ONERROR,
    HTML_ONFOCUS,
    HTML_ONHASHCHANGE,
    HTML_ONKEYDOWN,
    HTML_ONKEYPRESS,
    HTML_ONKEYUP,
    HTML_ONLOAD,
    HTML_ONMESSAGE,
    HTML_ONMOUSEDOWN,
    HTML_ONMOUSEMOVE,
    HTML_ONMOUSEOUT,
    HTML_ONMOUSEOVER,
    HTML_ONMOUSEUP,
    HTML_ONRESET,
    HTML_ONRESIZE,
    HTML_ONSCROLL,
    HTML_ONSELECT,
    HTML_ONSUBMIT,
    HTML_ONUNLOAD,
    HTML_OVERSRC,
    HTML_PAGEX,
    HTML_PAGEY,
    HTML_PLACEHOLDER,
    HTML_PLAIN,
    HTML_PLUGINPAGE,
    HTML_PLUGINSPAGE,
    HTML_PLUGINURL,
    HTML_POSTER,
    HTML_PROFILE,
    HTML_PROMPT,
    HTML_READONLY,
    HTML_REL,
    HTML_REV,
    HTML_ROWS,
    HTML_ROWSPAN,
    HTML_RULES,
    HTML_SCHEME,
    HTML_SCOPE,
    HTML_SCROLLAMOUNT,
    HTML_SCROLLDELAY,
    HTML_SCROLLING,
    HTML_SELECTED,
    HTML_SHAPE,
    HTML_SIZE,
    HTML_SPAN,
    HTML_SRC,
    HTML_STANDBY,
    HTML_START,
    HTML_STYLE,
    HTML_SUMMARY,
    HTML_TABINDEX,
    HTML_TARGET,
    HTML_TEXT,
    HTML_TITLE,
    HTML_TOP,
    HTML_TOPMARGIN,
    HTML_TRUESPEED,
    HTML_TYPE,
    HTML_UNKNOWN,
    HTML_USEMAP,
    HTML_VALIGN,
    HTML_VALUE,
    HTML_VALUETYPE,
    HTML_VERSION,
    HTML_VISIBILITY,
    HTML_VLINK,
    HTML_VSPACE,
    HTML_WIDTH,
    HTML_WRAP,
    HTML_XMLNS,
    HTML_Z_INDEX
};
NSString *const ATTRIB_HTML_ABBR_STR = @"abbr";
NSString *const ATTRIB_HTML_ACCEPT_STR = @"accept";
NSString *const ATTRIB_HTML_ACCEPT_CHARSET_STR = @"accept_charset";
NSString *const ATTRIB_HTML_ACCESSKEY_STR = @"accesskey";
NSString *const ATTRIB_HTML_ACTION_STR = @"action";
NSString *const ATTRIB_HTML_ALIGN_STR = @"align";
NSString *const ATTRIB_HTML_ALINK_STR = @"alink";
NSString *const ATTRIB_HTML_ALT_STR = @"alt";
NSString *const ATTRIB_HTML_ARCHIVE_STR = @"archive";
NSString *const ATTRIB_HTML_AUTOCOMPLETE_STR = @"autocomplete";
NSString *const ATTRIB_HTML_AUTOPLAY_STR = @"autoplay";
NSString *const ATTRIB_HTML_AXIS_STR = @"axis";
NSString *const ATTRIB_HTML_BACKGROUND_STR = @"background";
NSString *const ATTRIB_HTML_BEHAVIOR_STR = @"behavior";
NSString *const ATTRIB_HTML_BGCOLOR_STR = @"bgcolor";
NSString *const ATTRIB_HTML_BGPROPERTIES_STR = @"bgproperties";
NSString *const ATTRIB_HTML_BORDER_STR = @"border";
NSString *const ATTRIB_HTML_BORDERCOLOR_STR = @"bordercolor";
NSString *const ATTRIB_HTML_CELLPADDING_STR = @"cellpadding";
NSString *const ATTRIB_HTML_CELLSPACING_STR = @"cellspacing";
NSString *const ATTRIB_HTML_CHALLENGE_STR = @"challenge";
NSString *const ATTRIB_HTML_CHAR_STR = @"char";
NSString *const ATTRIB_HTML_CHAROFF_STR = @"charoff";
NSString *const ATTRIB_HTML_CHARSET_STR = @"charset";
NSString *const ATTRIB_HTML_CHECKED_STR = @"checked";
NSString *const ATTRIB_HTML_CITE_STR = @"cite";
NSString *const ATTRIB_HTML_CLASS_STR = @"class";
NSString *const ATTRIB_HTML_CLASSID_STR = @"classid";
NSString *const ATTRIB_HTML_CLEAR_STR = @"clear";
NSString *const ATTRIB_HTML_CODE_STR = @"code";
NSString *const ATTRIB_HTML_CODEBASE_STR = @"codebase";
NSString *const ATTRIB_HTML_CODETYPE_STR = @"codetype";
NSString *const ATTRIB_HTML_COLOR_STR = @"color";
NSString *const ATTRIB_HTML_COLS_STR = @"cols";
NSString *const ATTRIB_HTML_COLSPAN_STR = @"colspan";
NSString *const ATTRIB_HTML_COMPACT_STR = @"compact";
NSString *const ATTRIB_HTML_CONTENT_STR = @"content";
NSString *const ATTRIB_HTML_CONTENTEDITABLE_STR = @"contenteditable";
NSString *const ATTRIB_HTML_CONTROLS_STR = @"controls";
NSString *const ATTRIB_HTML_COORDS_STR = @"coords";
NSString *const ATTRIB_HTML_DATA_STR = @"data";
NSString *const ATTRIB_HTML_DATETIME_STR = @"datetime";
NSString *const ATTRIB_HTML_DECLARE_STR = @"declare";
NSString *const ATTRIB_HTML_DEFER_STR = @"defer";
NSString *const ATTRIB_HTML_DIR_STR = @"dir";
NSString *const ATTRIB_HTML_DIRECTION_STR = @"direction";
NSString *const ATTRIB_HTML_DISABLED_STR = @"disabled";
NSString *const ATTRIB_HTML_ENCTYPE_STR = @"enctype";
NSString *const ATTRIB_HTML_FACE_STR = @"face";
NSString *const ATTRIB_HTML_FOR_STR = @"for";
NSString *const ATTRIB_HTML_FRAME_STR = @"frame";
NSString *const ATTRIB_HTML_FRAMEBORDER_STR = @"frameborder";
NSString *const ATTRIB_HTML_HEADERS_STR = @"headers";
NSString *const ATTRIB_HTML_HEIGHT_STR = @"height";
NSString *const ATTRIB_HTML_HIDDEN_STR = @"hidden";
NSString *const ATTRIB_HTML_HREF_STR = @"href";
NSString *const ATTRIB_HTML_HREFLANG_STR = @"hreflang";
NSString *const ATTRIB_HTML_HSPACE_STR = @"hspace";
NSString *const ATTRIB_HTML_HTML_STR = @"html";
NSString *const ATTRIB_HTML_HTTP_EQUIV_STR = @"http_equiv";
NSString *const ATTRIB_HTML_ID_STR = @"id";
NSString *const ATTRIB_HTML_ISMAP_STR = @"ismap";
NSString *const ATTRIB_HTML_LABEL_STR = @"label";
NSString *const ATTRIB_HTML_LANG_STR = @"lang";
NSString *const ATTRIB_HTML_LANGUAGE_STR = @"language";
NSString *const ATTRIB_HTML_LEFT_STR = @"left";
NSString *const ATTRIB_HTML_LEFTMARGIN_STR = @"leftmargin";
NSString *const ATTRIB_HTML_LINK_STR = @"link";
NSString *const ATTRIB_HTML_LONGDESC_STR = @"longdesc";
NSString *const ATTRIB_HTML_LOOP_STR = @"loop";
NSString *const ATTRIB_HTML_MARGINHEIGHT_STR = @"marginheight";
NSString *const ATTRIB_HTML_MARGINWIDTH_STR = @"marginwidth";
NSString *const ATTRIB_HTML_MAXLENGTH_STR = @"maxlength";
NSString *const ATTRIB_HTML_MEDIA_STR = @"media";
NSString *const ATTRIB_HTML_METHOD_STR = @"method";
NSString *const ATTRIB_HTML_MULTIPLE_STR = @"multiple";
NSString *const ATTRIB_HTML_NAME_STR = @"name";
NSString *const ATTRIB_HTML_NOHREF_STR = @"nohref";
NSString *const ATTRIB_HTML_NORESIZE_STR = @"noresize";
NSString *const ATTRIB_HTML_NOSAVE_STR = @"nosave";
NSString *const ATTRIB_HTML_NOSHADE_STR = @"noshade";
NSString *const ATTRIB_HTML_NOWRAP_STR = @"nowrap";
NSString *const ATTRIB_HTML_OBJECT_STR = @"object";
NSString *const ATTRIB_HTML_ONABORT_STR = @"onabort";
NSString *const ATTRIB_HTML_ONBLUR_STR = @"onblur";
NSString *const ATTRIB_HTML_ONCHANGE_STR = @"onchange";
NSString *const ATTRIB_HTML_ONCLICK_STR = @"onclick";
NSString *const ATTRIB_HTML_ONDBLCLICK_STR = @"ondblclick";
NSString *const ATTRIB_HTML_ONERROR_STR = @"onerror";
NSString *const ATTRIB_HTML_ONFOCUS_STR = @"onfocus";
NSString *const ATTRIB_HTML_ONHASHCHANGE_STR = @"onhashchange";
NSString *const ATTRIB_HTML_ONKEYDOWN_STR = @"onkeydown";
NSString *const ATTRIB_HTML_ONKEYPRESS_STR = @"onkeypress";
NSString *const ATTRIB_HTML_ONKEYUP_STR = @"onkeyup";
NSString *const ATTRIB_HTML_ONLOAD_STR = @"onload";
NSString *const ATTRIB_HTML_ONMESSAGE_STR = @"onmessage";
NSString *const ATTRIB_HTML_ONMOUSEDOWN_STR = @"onmousedown";
NSString *const ATTRIB_HTML_ONMOUSEMOVE_STR = @"onmousemove";
NSString *const ATTRIB_HTML_ONMOUSEOUT_STR = @"onmouseout";
NSString *const ATTRIB_HTML_ONMOUSEOVER_STR = @"onmouseover";
NSString *const ATTRIB_HTML_ONMOUSEUP_STR = @"onmouseup";
NSString *const ATTRIB_HTML_ONRESET_STR = @"onreset";
NSString *const ATTRIB_HTML_ONRESIZE_STR = @"onresize";
NSString *const ATTRIB_HTML_ONSCROLL_STR = @"onscroll";
NSString *const ATTRIB_HTML_ONSELECT_STR = @"onselect";
NSString *const ATTRIB_HTML_ONSUBMIT_STR = @"onsubmit";
NSString *const ATTRIB_HTML_ONUNLOAD_STR = @"onunload";
NSString *const ATTRIB_HTML_OVERSRC_STR = @"oversrc";
NSString *const ATTRIB_HTML_PAGEX_STR = @"pagex";
NSString *const ATTRIB_HTML_PAGEY_STR = @"pagey";
NSString *const ATTRIB_HTML_PLACEHOLDER_STR = @"placeholder";
NSString *const ATTRIB_HTML_PLAIN_STR = @"plain";
NSString *const ATTRIB_HTML_PLUGINPAGE_STR = @"pluginpage";
NSString *const ATTRIB_HTML_PLUGINSPAGE_STR = @"pluginspage";
NSString *const ATTRIB_HTML_PLUGINURL_STR = @"pluginurl";
NSString *const ATTRIB_HTML_POSTER_STR = @"poster";
NSString *const ATTRIB_HTML_PROFILE_STR = @"profile";
NSString *const ATTRIB_HTML_PROMPT_STR = @"prompt";
NSString *const ATTRIB_HTML_READONLY_STR = @"readonly";
NSString *const ATTRIB_HTML_REL_STR = @"rel";
NSString *const ATTRIB_HTML_REV_STR = @"rev";
NSString *const ATTRIB_HTML_ROWS_STR = @"rows";
NSString *const ATTRIB_HTML_ROWSPAN_STR = @"rowspan";
NSString *const ATTRIB_HTML_RULES_STR = @"rules";
NSString *const ATTRIB_HTML_SCHEME_STR = @"scheme";
NSString *const ATTRIB_HTML_SCOPE_STR = @"scope";
NSString *const ATTRIB_HTML_SCROLLAMOUNT_STR = @"scrollamount";
NSString *const ATTRIB_HTML_SCROLLDELAY_STR = @"scrolldelay";
NSString *const ATTRIB_HTML_SCROLLING_STR = @"scrolling";
NSString *const ATTRIB_HTML_SELECTED_STR = @"selected";
NSString *const ATTRIB_HTML_SHAPE_STR = @"shape";
NSString *const ATTRIB_HTML_SIZE_STR = @"size";
NSString *const ATTRIB_HTML_SPAN_STR = @"span";
NSString *const ATTRIB_HTML_SRC_STR = @"src";
NSString *const ATTRIB_HTML_STANDBY_STR = @"standby";
NSString *const ATTRIB_HTML_START_STR = @"start";
NSString *const ATTRIB_HTML_STYLE_STR = @"style";
NSString *const ATTRIB_HTML_SUMMARY_STR = @"summary";
NSString *const ATTRIB_HTML_TABINDEX_STR = @"tabindex";
NSString *const ATTRIB_HTML_TARGET_STR = @"target";
NSString *const ATTRIB_HTML_TEXT_STR = @"text";
NSString *const ATTRIB_HTML_TITLE_STR = @"title";
NSString *const ATTRIB_HTML_TOP_STR = @"top";
NSString *const ATTRIB_HTML_TOPMARGIN_STR = @"topmargin";
NSString *const ATTRIB_HTML_TRUESPEED_STR = @"truespeed";
NSString *const ATTRIB_HTML_TYPE_STR = @"type";
NSString *const ATTRIB_HTML_UNKNOWN_STR = @"unknown";
NSString *const ATTRIB_HTML_USEMAP_STR = @"usemap";
NSString *const ATTRIB_HTML_VALIGN_STR = @"valign";
NSString *const ATTRIB_HTML_VALUE_STR = @"value";
NSString *const ATTRIB_HTML_VALUETYPE_STR = @"valuetype";
NSString *const ATTRIB_HTML_VERSION_STR = @"version";
NSString *const ATTRIB_HTML_VISIBILITY_STR = @"visibility";
NSString *const ATTRIB_HTML_VLINK_STR = @"vlink";
NSString *const ATTRIB_HTML_VSPACE_STR = @"vspace";
NSString *const ATTRIB_HTML_WIDTH_STR = @"width";
NSString *const ATTRIB_HTML_WRAP_STR = @"wrap";
NSString *const ATTRIB_HTML_XMLNS_STR = @"xmlns";
NSString *const ATTRIB_HTML_Z_INDEX_STR = @"z_index";

#endif // CONSTMAKER_GENERATED_HTML_H
