// This file is generated by ConstMaker, DON'T MODIFY.

QtObject {
    id: html


    enum ELEMENT {
        HTML_A_ID,
        HTML_ABBR_ID,
        HTML_ACRONYM_ID,
        HTML_ADDRESS_ID,
        HTML_APPLET_ID,
        HTML_AREA_ID,
        HTML_AUDIO_ID,
        HTML_B_ID,
        HTML_BASE_ID,
        HTML_BASEFONT_ID,
        HTML_BDO_ID,
        HTML_BIG_ID,
        HTML_BLOCKQUOTE_ID,
        HTML_BODY_ID,
        HTML_BR_ID,
        HTML_BUTTON_ID,
        HTML_CANVAS_ID,
        HTML_CAPTION_ID,
        HTML_CENTER_ID,
        HTML_CITE_ID,
        HTML_CODE_ID,
        HTML_COL_ID,
        HTML_COLGROUP_ID,
        HTML_COMMENT_ID,
        HTML_DD_ID,
        HTML_DEL_ID,
        HTML_DFN_ID,
        HTML_DIR_ID,
        HTML_DIV_ID,
        HTML_DL_ID,
        HTML_DT_ID,
        HTML_EM_ID,
        HTML_EMBED_ID,
        HTML_FIELDSET_ID,
        HTML_FONT_ID,
        HTML_FORM_ID,
        HTML_FRAME_ID,
        HTML_FRAMESET_ID,
        HTML_H1_ID,
        HTML_H2_ID,
        HTML_H3_ID,
        HTML_H4_ID,
        HTML_H5_ID,
        HTML_H6_ID,
        HTML_HEAD_ID,
        HTML_HR_ID,
        HTML_HTML_ID,
        HTML_I_ID,
        HTML_IFRAME_ID,
        HTML_ILAYER_ID,
        HTML_IMAGE_ID,
        HTML_IMG_ID,
        HTML_INPUT_ID,
        HTML_INS_ID,
        HTML_ISINDEX_ID,
        HTML_KBD_ID,
        HTML_KEYGEN_ID,
        HTML_LABEL_ID,
        HTML_LAYER_ID,
        HTML_LEGEND_ID,
        HTML_LI_ID,
        HTML_LINK_ID,
        HTML_LISTING_ID,
        HTML_MAP_ID,
        HTML_MARQUEE_ID,
        HTML_MENU_ID,
        HTML_META_ID,
        HTML_NOBR_ID,
        HTML_NOEMBED_ID,
        HTML_NOFRAMES_ID,
        HTML_NOLAYER_ID,
        HTML_NOSCRIPT_ID,
        HTML_OBJECT_ID,
        HTML_OL_ID,
        HTML_OPTGROUP_ID,
        HTML_OPTION_ID,
        HTML_P_ID,
        HTML_PARAM_ID,
        HTML_PLAINTEXT_ID,
        HTML_PRE_ID,
        HTML_Q_ID,
        HTML_S_ID,
        HTML_SAMP_ID,
        HTML_SCRIPT_ID,
        HTML_SELECT_ID,
        HTML_SMALL_ID,
        HTML_SOURCE_ID,
        HTML_SPAN_ID,
        HTML_STRIKE_ID,
        HTML_STRONG_ID,
        HTML_STYLE_ID,
        HTML_SUB_ID,
        HTML_SUP_ID,
        HTML_TABLE_ID,
        HTML_TBODY_ID,
        HTML_TD_ID,
        HTML_TEXT_ID,
        HTML_TEXTAREA_ID,
        HTML_TFOOT_ID,
        HTML_TH_ID,
        HTML_THEAD_ID,
        HTML_TITLE_ID,
        HTML_TR_ID,
        HTML_TT_ID,
        HTML_U_ID,
        HTML_UL_ID,
        HTML_VAR_ID,
        HTML_VIDEO_ID,
        HTML_WBR_ID,
        HTML_XMP_ID
    }
    property string ELEMENT_HTML_A_ID_STR: "a"
    property string ELEMENT_HTML_ABBR_ID_STR: "abbr"
    property string ELEMENT_HTML_ACRONYM_ID_STR: "acronym"
    property string ELEMENT_HTML_ADDRESS_ID_STR: "address"
    property string ELEMENT_HTML_APPLET_ID_STR: "applet"
    property string ELEMENT_HTML_AREA_ID_STR: "area"
    property string ELEMENT_HTML_AUDIO_ID_STR: "audio"
    property string ELEMENT_HTML_B_ID_STR: "b"
    property string ELEMENT_HTML_BASE_ID_STR: "base"
    property string ELEMENT_HTML_BASEFONT_ID_STR: "basefont"
    property string ELEMENT_HTML_BDO_ID_STR: "bdo"
    property string ELEMENT_HTML_BIG_ID_STR: "big"
    property string ELEMENT_HTML_BLOCKQUOTE_ID_STR: "blockquote"
    property string ELEMENT_HTML_BODY_ID_STR: "body"
    property string ELEMENT_HTML_BR_ID_STR: "br"
    property string ELEMENT_HTML_BUTTON_ID_STR: "button"
    property string ELEMENT_HTML_CANVAS_ID_STR: "canvas"
    property string ELEMENT_HTML_CAPTION_ID_STR: "caption"
    property string ELEMENT_HTML_CENTER_ID_STR: "center"
    property string ELEMENT_HTML_CITE_ID_STR: "cite"
    property string ELEMENT_HTML_CODE_ID_STR: "code"
    property string ELEMENT_HTML_COL_ID_STR: "col"
    property string ELEMENT_HTML_COLGROUP_ID_STR: "colgroup"
    property string ELEMENT_HTML_COMMENT_ID_STR: "comment"
    property string ELEMENT_HTML_DD_ID_STR: "dd"
    property string ELEMENT_HTML_DEL_ID_STR: "del"
    property string ELEMENT_HTML_DFN_ID_STR: "dfn"
    property string ELEMENT_HTML_DIR_ID_STR: "dir"
    property string ELEMENT_HTML_DIV_ID_STR: "div"
    property string ELEMENT_HTML_DL_ID_STR: "dl"
    property string ELEMENT_HTML_DT_ID_STR: "dt"
    property string ELEMENT_HTML_EM_ID_STR: "em"
    property string ELEMENT_HTML_EMBED_ID_STR: "embed"
    property string ELEMENT_HTML_FIELDSET_ID_STR: "fieldset"
    property string ELEMENT_HTML_FONT_ID_STR: "font"
    property string ELEMENT_HTML_FORM_ID_STR: "form"
    property string ELEMENT_HTML_FRAME_ID_STR: "frame"
    property string ELEMENT_HTML_FRAMESET_ID_STR: "frameset"
    property string ELEMENT_HTML_H1_ID_STR: "h1"
    property string ELEMENT_HTML_H2_ID_STR: "h2"
    property string ELEMENT_HTML_H3_ID_STR: "h3"
    property string ELEMENT_HTML_H4_ID_STR: "h4"
    property string ELEMENT_HTML_H5_ID_STR: "h5"
    property string ELEMENT_HTML_H6_ID_STR: "h6"
    property string ELEMENT_HTML_HEAD_ID_STR: "head"
    property string ELEMENT_HTML_HR_ID_STR: "hr"
    property string ELEMENT_HTML_HTML_ID_STR: "html"
    property string ELEMENT_HTML_I_ID_STR: "i"
    property string ELEMENT_HTML_IFRAME_ID_STR: "iframe"
    property string ELEMENT_HTML_ILAYER_ID_STR: "ilayer"
    property string ELEMENT_HTML_IMAGE_ID_STR: "image"
    property string ELEMENT_HTML_IMG_ID_STR: "img"
    property string ELEMENT_HTML_INPUT_ID_STR: "input"
    property string ELEMENT_HTML_INS_ID_STR: "ins"
    property string ELEMENT_HTML_ISINDEX_ID_STR: "isindex"
    property string ELEMENT_HTML_KBD_ID_STR: "kbd"
    property string ELEMENT_HTML_KEYGEN_ID_STR: "keygen"
    property string ELEMENT_HTML_LABEL_ID_STR: "label"
    property string ELEMENT_HTML_LAYER_ID_STR: "layer"
    property string ELEMENT_HTML_LEGEND_ID_STR: "legend"
    property string ELEMENT_HTML_LI_ID_STR: "li"
    property string ELEMENT_HTML_LINK_ID_STR: "link"
    property string ELEMENT_HTML_LISTING_ID_STR: "listing"
    property string ELEMENT_HTML_MAP_ID_STR: "map"
    property string ELEMENT_HTML_MARQUEE_ID_STR: "marquee"
    property string ELEMENT_HTML_MENU_ID_STR: "menu"
    property string ELEMENT_HTML_META_ID_STR: "meta"
    property string ELEMENT_HTML_NOBR_ID_STR: "nobr"
    property string ELEMENT_HTML_NOEMBED_ID_STR: "noembed"
    property string ELEMENT_HTML_NOFRAMES_ID_STR: "noframes"
    property string ELEMENT_HTML_NOLAYER_ID_STR: "nolayer"
    property string ELEMENT_HTML_NOSCRIPT_ID_STR: "noscript"
    property string ELEMENT_HTML_OBJECT_ID_STR: "object"
    property string ELEMENT_HTML_OL_ID_STR: "ol"
    property string ELEMENT_HTML_OPTGROUP_ID_STR: "optgroup"
    property string ELEMENT_HTML_OPTION_ID_STR: "option"
    property string ELEMENT_HTML_P_ID_STR: "p"
    property string ELEMENT_HTML_PARAM_ID_STR: "param"
    property string ELEMENT_HTML_PLAINTEXT_ID_STR: "plaintext"
    property string ELEMENT_HTML_PRE_ID_STR: "pre"
    property string ELEMENT_HTML_Q_ID_STR: "q"
    property string ELEMENT_HTML_S_ID_STR: "s"
    property string ELEMENT_HTML_SAMP_ID_STR: "samp"
    property string ELEMENT_HTML_SCRIPT_ID_STR: "script"
    property string ELEMENT_HTML_SELECT_ID_STR: "select"
    property string ELEMENT_HTML_SMALL_ID_STR: "small"
    property string ELEMENT_HTML_SOURCE_ID_STR: "source"
    property string ELEMENT_HTML_SPAN_ID_STR: "span"
    property string ELEMENT_HTML_STRIKE_ID_STR: "strike"
    property string ELEMENT_HTML_STRONG_ID_STR: "strong"
    property string ELEMENT_HTML_STYLE_ID_STR: "style"
    property string ELEMENT_HTML_SUB_ID_STR: "sub"
    property string ELEMENT_HTML_SUP_ID_STR: "sup"
    property string ELEMENT_HTML_TABLE_ID_STR: "table"
    property string ELEMENT_HTML_TBODY_ID_STR: "tbody"
    property string ELEMENT_HTML_TD_ID_STR: "td"
    property string ELEMENT_HTML_TEXT_ID_STR: "text"
    property string ELEMENT_HTML_TEXTAREA_ID_STR: "textarea"
    property string ELEMENT_HTML_TFOOT_ID_STR: "tfoot"
    property string ELEMENT_HTML_TH_ID_STR: "th"
    property string ELEMENT_HTML_THEAD_ID_STR: "thead"
    property string ELEMENT_HTML_TITLE_ID_STR: "title"
    property string ELEMENT_HTML_TR_ID_STR: "tr"
    property string ELEMENT_HTML_TT_ID_STR: "tt"
    property string ELEMENT_HTML_U_ID_STR: "u"
    property string ELEMENT_HTML_UL_ID_STR: "ul"
    property string ELEMENT_HTML_VAR_ID_STR: "var"
    property string ELEMENT_HTML_VIDEO_ID_STR: "video"
    property string ELEMENT_HTML_WBR_ID_STR: "wbr"
    property string ELEMENT_HTML_XMP_ID_STR: "xmp"

    enum ATTRIB {
        HTML_ABBR,
        HTML_ACCEPT,
        HTML_ACCEPT_CHARSET,
        HTML_ACCESSKEY,
        HTML_ACTION,
        HTML_ALIGN,
        HTML_ALINK,
        HTML_ALT,
        HTML_ARCHIVE,
        HTML_AUTOCOMPLETE,
        HTML_AUTOPLAY,
        HTML_AXIS,
        HTML_BACKGROUND,
        HTML_BEHAVIOR,
        HTML_BGCOLOR,
        HTML_BGPROPERTIES,
        HTML_BORDER,
        HTML_BORDERCOLOR,
        HTML_CELLPADDING,
        HTML_CELLSPACING,
        HTML_CHALLENGE,
        HTML_CHAR,
        HTML_CHAROFF,
        HTML_CHARSET,
        HTML_CHECKED,
        HTML_CITE,
        HTML_CLASS,
        HTML_CLASSID,
        HTML_CLEAR,
        HTML_CODE,
        HTML_CODEBASE,
        HTML_CODETYPE,
        HTML_COLOR,
        HTML_COLS,
        HTML_COLSPAN,
        HTML_COMPACT,
        HTML_CONTENT,
        HTML_CONTENTEDITABLE,
        HTML_CONTROLS,
        HTML_COORDS,
        HTML_DATA,
        HTML_DATETIME,
        HTML_DECLARE,
        HTML_DEFER,
        HTML_DIR,
        HTML_DIRECTION,
        HTML_DISABLED,
        HTML_ENCTYPE,
        HTML_FACE,
        HTML_FOR,
        HTML_FRAME,
        HTML_FRAMEBORDER,
        HTML_HEADERS,
        HTML_HEIGHT,
        HTML_HIDDEN,
        HTML_HREF,
        HTML_HREFLANG,
        HTML_HSPACE,
        HTML_HTML,
        HTML_HTTP_EQUIV,
        HTML_ID,
        HTML_ISMAP,
        HTML_LABEL,
        HTML_LANG,
        HTML_LANGUAGE,
        HTML_LEFT,
        HTML_LEFTMARGIN,
        HTML_LINK,
        HTML_LONGDESC,
        HTML_LOOP,
        HTML_MARGINHEIGHT,
        HTML_MARGINWIDTH,
        HTML_MAXLENGTH,
        HTML_MEDIA,
        HTML_METHOD,
        HTML_MULTIPLE,
        HTML_NAME,
        HTML_NOHREF,
        HTML_NORESIZE,
        HTML_NOSAVE,
        HTML_NOSHADE,
        HTML_NOWRAP,
        HTML_OBJECT,
        HTML_ONABORT,
        HTML_ONBLUR,
        HTML_ONCHANGE,
        HTML_ONCLICK,
        HTML_ONDBLCLICK,
        HTML_ONERROR,
        HTML_ONFOCUS,
        HTML_ONHASHCHANGE,
        HTML_ONKEYDOWN,
        HTML_ONKEYPRESS,
        HTML_ONKEYUP,
        HTML_ONLOAD,
        HTML_ONMESSAGE,
        HTML_ONMOUSEDOWN,
        HTML_ONMOUSEMOVE,
        HTML_ONMOUSEOUT,
        HTML_ONMOUSEOVER,
        HTML_ONMOUSEUP,
        HTML_ONRESET,
        HTML_ONRESIZE,
        HTML_ONSCROLL,
        HTML_ONSELECT,
        HTML_ONSUBMIT,
        HTML_ONUNLOAD,
        HTML_OVERSRC,
        HTML_PAGEX,
        HTML_PAGEY,
        HTML_PLACEHOLDER,
        HTML_PLAIN,
        HTML_PLUGINPAGE,
        HTML_PLUGINSPAGE,
        HTML_PLUGINURL,
        HTML_POSTER,
        HTML_PROFILE,
        HTML_PROMPT,
        HTML_READONLY,
        HTML_REL,
        HTML_REV,
        HTML_ROWS,
        HTML_ROWSPAN,
        HTML_RULES,
        HTML_SCHEME,
        HTML_SCOPE,
        HTML_SCROLLAMOUNT,
        HTML_SCROLLDELAY,
        HTML_SCROLLING,
        HTML_SELECTED,
        HTML_SHAPE,
        HTML_SIZE,
        HTML_SPAN,
        HTML_SRC,
        HTML_STANDBY,
        HTML_START,
        HTML_STYLE,
        HTML_SUMMARY,
        HTML_TABINDEX,
        HTML_TARGET,
        HTML_TEXT,
        HTML_TITLE,
        HTML_TOP,
        HTML_TOPMARGIN,
        HTML_TRUESPEED,
        HTML_TYPE,
        HTML_UNKNOWN,
        HTML_USEMAP,
        HTML_VALIGN,
        HTML_VALUE,
        HTML_VALUETYPE,
        HTML_VERSION,
        HTML_VISIBILITY,
        HTML_VLINK,
        HTML_VSPACE,
        HTML_WIDTH,
        HTML_WRAP,
        HTML_XMLNS,
        HTML_Z_INDEX
    }
    property string ATTRIB_HTML_ABBR_STR: "abbr"
    property string ATTRIB_HTML_ACCEPT_STR: "accept"
    property string ATTRIB_HTML_ACCEPT_CHARSET_STR: "accept_charset"
    property string ATTRIB_HTML_ACCESSKEY_STR: "accesskey"
    property string ATTRIB_HTML_ACTION_STR: "action"
    property string ATTRIB_HTML_ALIGN_STR: "align"
    property string ATTRIB_HTML_ALINK_STR: "alink"
    property string ATTRIB_HTML_ALT_STR: "alt"
    property string ATTRIB_HTML_ARCHIVE_STR: "archive"
    property string ATTRIB_HTML_AUTOCOMPLETE_STR: "autocomplete"
    property string ATTRIB_HTML_AUTOPLAY_STR: "autoplay"
    property string ATTRIB_HTML_AXIS_STR: "axis"
    property string ATTRIB_HTML_BACKGROUND_STR: "background"
    property string ATTRIB_HTML_BEHAVIOR_STR: "behavior"
    property string ATTRIB_HTML_BGCOLOR_STR: "bgcolor"
    property string ATTRIB_HTML_BGPROPERTIES_STR: "bgproperties"
    property string ATTRIB_HTML_BORDER_STR: "border"
    property string ATTRIB_HTML_BORDERCOLOR_STR: "bordercolor"
    property string ATTRIB_HTML_CELLPADDING_STR: "cellpadding"
    property string ATTRIB_HTML_CELLSPACING_STR: "cellspacing"
    property string ATTRIB_HTML_CHALLENGE_STR: "challenge"
    property string ATTRIB_HTML_CHAR_STR: "char"
    property string ATTRIB_HTML_CHAROFF_STR: "charoff"
    property string ATTRIB_HTML_CHARSET_STR: "charset"
    property string ATTRIB_HTML_CHECKED_STR: "checked"
    property string ATTRIB_HTML_CITE_STR: "cite"
    property string ATTRIB_HTML_CLASS_STR: "class"
    property string ATTRIB_HTML_CLASSID_STR: "classid"
    property string ATTRIB_HTML_CLEAR_STR: "clear"
    property string ATTRIB_HTML_CODE_STR: "code"
    property string ATTRIB_HTML_CODEBASE_STR: "codebase"
    property string ATTRIB_HTML_CODETYPE_STR: "codetype"
    property string ATTRIB_HTML_COLOR_STR: "color"
    property string ATTRIB_HTML_COLS_STR: "cols"
    property string ATTRIB_HTML_COLSPAN_STR: "colspan"
    property string ATTRIB_HTML_COMPACT_STR: "compact"
    property string ATTRIB_HTML_CONTENT_STR: "content"
    property string ATTRIB_HTML_CONTENTEDITABLE_STR: "contenteditable"
    property string ATTRIB_HTML_CONTROLS_STR: "controls"
    property string ATTRIB_HTML_COORDS_STR: "coords"
    property string ATTRIB_HTML_DATA_STR: "data"
    property string ATTRIB_HTML_DATETIME_STR: "datetime"
    property string ATTRIB_HTML_DECLARE_STR: "declare"
    property string ATTRIB_HTML_DEFER_STR: "defer"
    property string ATTRIB_HTML_DIR_STR: "dir"
    property string ATTRIB_HTML_DIRECTION_STR: "direction"
    property string ATTRIB_HTML_DISABLED_STR: "disabled"
    property string ATTRIB_HTML_ENCTYPE_STR: "enctype"
    property string ATTRIB_HTML_FACE_STR: "face"
    property string ATTRIB_HTML_FOR_STR: "for"
    property string ATTRIB_HTML_FRAME_STR: "frame"
    property string ATTRIB_HTML_FRAMEBORDER_STR: "frameborder"
    property string ATTRIB_HTML_HEADERS_STR: "headers"
    property string ATTRIB_HTML_HEIGHT_STR: "height"
    property string ATTRIB_HTML_HIDDEN_STR: "hidden"
    property string ATTRIB_HTML_HREF_STR: "href"
    property string ATTRIB_HTML_HREFLANG_STR: "hreflang"
    property string ATTRIB_HTML_HSPACE_STR: "hspace"
    property string ATTRIB_HTML_HTML_STR: "html"
    property string ATTRIB_HTML_HTTP_EQUIV_STR: "http_equiv"
    property string ATTRIB_HTML_ID_STR: "id"
    property string ATTRIB_HTML_ISMAP_STR: "ismap"
    property string ATTRIB_HTML_LABEL_STR: "label"
    property string ATTRIB_HTML_LANG_STR: "lang"
    property string ATTRIB_HTML_LANGUAGE_STR: "language"
    property string ATTRIB_HTML_LEFT_STR: "left"
    property string ATTRIB_HTML_LEFTMARGIN_STR: "leftmargin"
    property string ATTRIB_HTML_LINK_STR: "link"
    property string ATTRIB_HTML_LONGDESC_STR: "longdesc"
    property string ATTRIB_HTML_LOOP_STR: "loop"
    property string ATTRIB_HTML_MARGINHEIGHT_STR: "marginheight"
    property string ATTRIB_HTML_MARGINWIDTH_STR: "marginwidth"
    property string ATTRIB_HTML_MAXLENGTH_STR: "maxlength"
    property string ATTRIB_HTML_MEDIA_STR: "media"
    property string ATTRIB_HTML_METHOD_STR: "method"
    property string ATTRIB_HTML_MULTIPLE_STR: "multiple"
    property string ATTRIB_HTML_NAME_STR: "name"
    property string ATTRIB_HTML_NOHREF_STR: "nohref"
    property string ATTRIB_HTML_NORESIZE_STR: "noresize"
    property string ATTRIB_HTML_NOSAVE_STR: "nosave"
    property string ATTRIB_HTML_NOSHADE_STR: "noshade"
    property string ATTRIB_HTML_NOWRAP_STR: "nowrap"
    property string ATTRIB_HTML_OBJECT_STR: "object"
    property string ATTRIB_HTML_ONABORT_STR: "onabort"
    property string ATTRIB_HTML_ONBLUR_STR: "onblur"
    property string ATTRIB_HTML_ONCHANGE_STR: "onchange"
    property string ATTRIB_HTML_ONCLICK_STR: "onclick"
    property string ATTRIB_HTML_ONDBLCLICK_STR: "ondblclick"
    property string ATTRIB_HTML_ONERROR_STR: "onerror"
    property string ATTRIB_HTML_ONFOCUS_STR: "onfocus"
    property string ATTRIB_HTML_ONHASHCHANGE_STR: "onhashchange"
    property string ATTRIB_HTML_ONKEYDOWN_STR: "onkeydown"
    property string ATTRIB_HTML_ONKEYPRESS_STR: "onkeypress"
    property string ATTRIB_HTML_ONKEYUP_STR: "onkeyup"
    property string ATTRIB_HTML_ONLOAD_STR: "onload"
    property string ATTRIB_HTML_ONMESSAGE_STR: "onmessage"
    property string ATTRIB_HTML_ONMOUSEDOWN_STR: "onmousedown"
    property string ATTRIB_HTML_ONMOUSEMOVE_STR: "onmousemove"
    property string ATTRIB_HTML_ONMOUSEOUT_STR: "onmouseout"
    property string ATTRIB_HTML_ONMOUSEOVER_STR: "onmouseover"
    property string ATTRIB_HTML_ONMOUSEUP_STR: "onmouseup"
    property string ATTRIB_HTML_ONRESET_STR: "onreset"
    property string ATTRIB_HTML_ONRESIZE_STR: "onresize"
    property string ATTRIB_HTML_ONSCROLL_STR: "onscroll"
    property string ATTRIB_HTML_ONSELECT_STR: "onselect"
    property string ATTRIB_HTML_ONSUBMIT_STR: "onsubmit"
    property string ATTRIB_HTML_ONUNLOAD_STR: "onunload"
    property string ATTRIB_HTML_OVERSRC_STR: "oversrc"
    property string ATTRIB_HTML_PAGEX_STR: "pagex"
    property string ATTRIB_HTML_PAGEY_STR: "pagey"
    property string ATTRIB_HTML_PLACEHOLDER_STR: "placeholder"
    property string ATTRIB_HTML_PLAIN_STR: "plain"
    property string ATTRIB_HTML_PLUGINPAGE_STR: "pluginpage"
    property string ATTRIB_HTML_PLUGINSPAGE_STR: "pluginspage"
    property string ATTRIB_HTML_PLUGINURL_STR: "pluginurl"
    property string ATTRIB_HTML_POSTER_STR: "poster"
    property string ATTRIB_HTML_PROFILE_STR: "profile"
    property string ATTRIB_HTML_PROMPT_STR: "prompt"
    property string ATTRIB_HTML_READONLY_STR: "readonly"
    property string ATTRIB_HTML_REL_STR: "rel"
    property string ATTRIB_HTML_REV_STR: "rev"
    property string ATTRIB_HTML_ROWS_STR: "rows"
    property string ATTRIB_HTML_ROWSPAN_STR: "rowspan"
    property string ATTRIB_HTML_RULES_STR: "rules"
    property string ATTRIB_HTML_SCHEME_STR: "scheme"
    property string ATTRIB_HTML_SCOPE_STR: "scope"
    property string ATTRIB_HTML_SCROLLAMOUNT_STR: "scrollamount"
    property string ATTRIB_HTML_SCROLLDELAY_STR: "scrolldelay"
    property string ATTRIB_HTML_SCROLLING_STR: "scrolling"
    property string ATTRIB_HTML_SELECTED_STR: "selected"
    property string ATTRIB_HTML_SHAPE_STR: "shape"
    property string ATTRIB_HTML_SIZE_STR: "size"
    property string ATTRIB_HTML_SPAN_STR: "span"
    property string ATTRIB_HTML_SRC_STR: "src"
    property string ATTRIB_HTML_STANDBY_STR: "standby"
    property string ATTRIB_HTML_START_STR: "start"
    property string ATTRIB_HTML_STYLE_STR: "style"
    property string ATTRIB_HTML_SUMMARY_STR: "summary"
    property string ATTRIB_HTML_TABINDEX_STR: "tabindex"
    property string ATTRIB_HTML_TARGET_STR: "target"
    property string ATTRIB_HTML_TEXT_STR: "text"
    property string ATTRIB_HTML_TITLE_STR: "title"
    property string ATTRIB_HTML_TOP_STR: "top"
    property string ATTRIB_HTML_TOPMARGIN_STR: "topmargin"
    property string ATTRIB_HTML_TRUESPEED_STR: "truespeed"
    property string ATTRIB_HTML_TYPE_STR: "type"
    property string ATTRIB_HTML_UNKNOWN_STR: "unknown"
    property string ATTRIB_HTML_USEMAP_STR: "usemap"
    property string ATTRIB_HTML_VALIGN_STR: "valign"
    property string ATTRIB_HTML_VALUE_STR: "value"
    property string ATTRIB_HTML_VALUETYPE_STR: "valuetype"
    property string ATTRIB_HTML_VERSION_STR: "version"
    property string ATTRIB_HTML_VISIBILITY_STR: "visibility"
    property string ATTRIB_HTML_VLINK_STR: "vlink"
    property string ATTRIB_HTML_VSPACE_STR: "vspace"
    property string ATTRIB_HTML_WIDTH_STR: "width"
    property string ATTRIB_HTML_WRAP_STR: "wrap"
    property string ATTRIB_HTML_XMLNS_STR: "xmlns"
    property string ATTRIB_HTML_Z_INDEX_STR: "z_index"
}