(* This file is generated by ConstMaker, DON'T MODIFY. *)


type ELEMENT = (
    HTML_A_ID,
    HTML_ABBR_ID,
    HTML_ACRONYM_ID,
    HTML_ADDRESS_ID,
    HTML_APPLET_ID,
    HTML_AREA_ID,
    HTML_AUDIO_ID,
    HTML_B_ID,
    HTML_BASE_ID,
    HTML_BASEFONT_ID,
    HTML_BDO_ID,
    HTML_BIG_ID,
    HTML_BLOCKQUOTE_ID,
    HTML_BODY_ID,
    HTML_BR_ID,
    HTML_BUTTON_ID,
    HTML_CANVAS_ID,
    HTML_CAPTION_ID,
    HTML_CENTER_ID,
    HTML_CITE_ID,
    HTML_CODE_ID,
    HTML_COL_ID,
    HTML_COLGROUP_ID,
    HTML_COMMENT_ID,
    HTML_DD_ID,
    HTML_DEL_ID,
    HTML_DFN_ID,
    HTML_DIR_ID,
    HTML_DIV_ID,
    HTML_DL_ID,
    HTML_DT_ID,
    HTML_EM_ID,
    HTML_EMBED_ID,
    HTML_FIELDSET_ID,
    HTML_FONT_ID,
    HTML_FORM_ID,
    HTML_FRAME_ID,
    HTML_FRAMESET_ID,
    HTML_H1_ID,
    HTML_H2_ID,
    HTML_H3_ID,
    HTML_H4_ID,
    HTML_H5_ID,
    HTML_H6_ID,
    HTML_HEAD_ID,
    HTML_HR_ID,
    HTML_HTML_ID,
    HTML_I_ID,
    HTML_IFRAME_ID,
    HTML_ILAYER_ID,
    HTML_IMAGE_ID,
    HTML_IMG_ID,
    HTML_INPUT_ID,
    HTML_INS_ID,
    HTML_ISINDEX_ID,
    HTML_KBD_ID,
    HTML_KEYGEN_ID,
    HTML_LABEL_ID,
    HTML_LAYER_ID,
    HTML_LEGEND_ID,
    HTML_LI_ID,
    HTML_LINK_ID,
    HTML_LISTING_ID,
    HTML_MAP_ID,
    HTML_MARQUEE_ID,
    HTML_MENU_ID,
    HTML_META_ID,
    HTML_NOBR_ID,
    HTML_NOEMBED_ID,
    HTML_NOFRAMES_ID,
    HTML_NOLAYER_ID,
    HTML_NOSCRIPT_ID,
    HTML_OBJECT_ID,
    HTML_OL_ID,
    HTML_OPTGROUP_ID,
    HTML_OPTION_ID,
    HTML_P_ID,
    HTML_PARAM_ID,
    HTML_PLAINTEXT_ID,
    HTML_PRE_ID,
    HTML_Q_ID,
    HTML_S_ID,
    HTML_SAMP_ID,
    HTML_SCRIPT_ID,
    HTML_SELECT_ID,
    HTML_SMALL_ID,
    HTML_SOURCE_ID,
    HTML_SPAN_ID,
    HTML_STRIKE_ID,
    HTML_STRONG_ID,
    HTML_STYLE_ID,
    HTML_SUB_ID,
    HTML_SUP_ID,
    HTML_TABLE_ID,
    HTML_TBODY_ID,
    HTML_TD_ID,
    HTML_TEXT_ID,
    HTML_TEXTAREA_ID,
    HTML_TFOOT_ID,
    HTML_TH_ID,
    HTML_THEAD_ID,
    HTML_TITLE_ID,
    HTML_TR_ID,
    HTML_TT_ID,
    HTML_U_ID,
    HTML_UL_ID,
    HTML_VAR_ID,
    HTML_VIDEO_ID,
    HTML_WBR_ID,
    HTML_XMP_ID
);
const ELEMENT_HTML_A_ID_STR: String = "a";
const ELEMENT_HTML_ABBR_ID_STR: String = "abbr";
const ELEMENT_HTML_ACRONYM_ID_STR: String = "acronym";
const ELEMENT_HTML_ADDRESS_ID_STR: String = "address";
const ELEMENT_HTML_APPLET_ID_STR: String = "applet";
const ELEMENT_HTML_AREA_ID_STR: String = "area";
const ELEMENT_HTML_AUDIO_ID_STR: String = "audio";
const ELEMENT_HTML_B_ID_STR: String = "b";
const ELEMENT_HTML_BASE_ID_STR: String = "base";
const ELEMENT_HTML_BASEFONT_ID_STR: String = "basefont";
const ELEMENT_HTML_BDO_ID_STR: String = "bdo";
const ELEMENT_HTML_BIG_ID_STR: String = "big";
const ELEMENT_HTML_BLOCKQUOTE_ID_STR: String = "blockquote";
const ELEMENT_HTML_BODY_ID_STR: String = "body";
const ELEMENT_HTML_BR_ID_STR: String = "br";
const ELEMENT_HTML_BUTTON_ID_STR: String = "button";
const ELEMENT_HTML_CANVAS_ID_STR: String = "canvas";
const ELEMENT_HTML_CAPTION_ID_STR: String = "caption";
const ELEMENT_HTML_CENTER_ID_STR: String = "center";
const ELEMENT_HTML_CITE_ID_STR: String = "cite";
const ELEMENT_HTML_CODE_ID_STR: String = "code";
const ELEMENT_HTML_COL_ID_STR: String = "col";
const ELEMENT_HTML_COLGROUP_ID_STR: String = "colgroup";
const ELEMENT_HTML_COMMENT_ID_STR: String = "comment";
const ELEMENT_HTML_DD_ID_STR: String = "dd";
const ELEMENT_HTML_DEL_ID_STR: String = "del";
const ELEMENT_HTML_DFN_ID_STR: String = "dfn";
const ELEMENT_HTML_DIR_ID_STR: String = "dir";
const ELEMENT_HTML_DIV_ID_STR: String = "div";
const ELEMENT_HTML_DL_ID_STR: String = "dl";
const ELEMENT_HTML_DT_ID_STR: String = "dt";
const ELEMENT_HTML_EM_ID_STR: String = "em";
const ELEMENT_HTML_EMBED_ID_STR: String = "embed";
const ELEMENT_HTML_FIELDSET_ID_STR: String = "fieldset";
const ELEMENT_HTML_FONT_ID_STR: String = "font";
const ELEMENT_HTML_FORM_ID_STR: String = "form";
const ELEMENT_HTML_FRAME_ID_STR: String = "frame";
const ELEMENT_HTML_FRAMESET_ID_STR: String = "frameset";
const ELEMENT_HTML_H1_ID_STR: String = "h1";
const ELEMENT_HTML_H2_ID_STR: String = "h2";
const ELEMENT_HTML_H3_ID_STR: String = "h3";
const ELEMENT_HTML_H4_ID_STR: String = "h4";
const ELEMENT_HTML_H5_ID_STR: String = "h5";
const ELEMENT_HTML_H6_ID_STR: String = "h6";
const ELEMENT_HTML_HEAD_ID_STR: String = "head";
const ELEMENT_HTML_HR_ID_STR: String = "hr";
const ELEMENT_HTML_HTML_ID_STR: String = "html";
const ELEMENT_HTML_I_ID_STR: String = "i";
const ELEMENT_HTML_IFRAME_ID_STR: String = "iframe";
const ELEMENT_HTML_ILAYER_ID_STR: String = "ilayer";
const ELEMENT_HTML_IMAGE_ID_STR: String = "image";
const ELEMENT_HTML_IMG_ID_STR: String = "img";
const ELEMENT_HTML_INPUT_ID_STR: String = "input";
const ELEMENT_HTML_INS_ID_STR: String = "ins";
const ELEMENT_HTML_ISINDEX_ID_STR: String = "isindex";
const ELEMENT_HTML_KBD_ID_STR: String = "kbd";
const ELEMENT_HTML_KEYGEN_ID_STR: String = "keygen";
const ELEMENT_HTML_LABEL_ID_STR: String = "label";
const ELEMENT_HTML_LAYER_ID_STR: String = "layer";
const ELEMENT_HTML_LEGEND_ID_STR: String = "legend";
const ELEMENT_HTML_LI_ID_STR: String = "li";
const ELEMENT_HTML_LINK_ID_STR: String = "link";
const ELEMENT_HTML_LISTING_ID_STR: String = "listing";
const ELEMENT_HTML_MAP_ID_STR: String = "map";
const ELEMENT_HTML_MARQUEE_ID_STR: String = "marquee";
const ELEMENT_HTML_MENU_ID_STR: String = "menu";
const ELEMENT_HTML_META_ID_STR: String = "meta";
const ELEMENT_HTML_NOBR_ID_STR: String = "nobr";
const ELEMENT_HTML_NOEMBED_ID_STR: String = "noembed";
const ELEMENT_HTML_NOFRAMES_ID_STR: String = "noframes";
const ELEMENT_HTML_NOLAYER_ID_STR: String = "nolayer";
const ELEMENT_HTML_NOSCRIPT_ID_STR: String = "noscript";
const ELEMENT_HTML_OBJECT_ID_STR: String = "object";
const ELEMENT_HTML_OL_ID_STR: String = "ol";
const ELEMENT_HTML_OPTGROUP_ID_STR: String = "optgroup";
const ELEMENT_HTML_OPTION_ID_STR: String = "option";
const ELEMENT_HTML_P_ID_STR: String = "p";
const ELEMENT_HTML_PARAM_ID_STR: String = "param";
const ELEMENT_HTML_PLAINTEXT_ID_STR: String = "plaintext";
const ELEMENT_HTML_PRE_ID_STR: String = "pre";
const ELEMENT_HTML_Q_ID_STR: String = "q";
const ELEMENT_HTML_S_ID_STR: String = "s";
const ELEMENT_HTML_SAMP_ID_STR: String = "samp";
const ELEMENT_HTML_SCRIPT_ID_STR: String = "script";
const ELEMENT_HTML_SELECT_ID_STR: String = "select";
const ELEMENT_HTML_SMALL_ID_STR: String = "small";
const ELEMENT_HTML_SOURCE_ID_STR: String = "source";
const ELEMENT_HTML_SPAN_ID_STR: String = "span";
const ELEMENT_HTML_STRIKE_ID_STR: String = "strike";
const ELEMENT_HTML_STRONG_ID_STR: String = "strong";
const ELEMENT_HTML_STYLE_ID_STR: String = "style";
const ELEMENT_HTML_SUB_ID_STR: String = "sub";
const ELEMENT_HTML_SUP_ID_STR: String = "sup";
const ELEMENT_HTML_TABLE_ID_STR: String = "table";
const ELEMENT_HTML_TBODY_ID_STR: String = "tbody";
const ELEMENT_HTML_TD_ID_STR: String = "td";
const ELEMENT_HTML_TEXT_ID_STR: String = "text";
const ELEMENT_HTML_TEXTAREA_ID_STR: String = "textarea";
const ELEMENT_HTML_TFOOT_ID_STR: String = "tfoot";
const ELEMENT_HTML_TH_ID_STR: String = "th";
const ELEMENT_HTML_THEAD_ID_STR: String = "thead";
const ELEMENT_HTML_TITLE_ID_STR: String = "title";
const ELEMENT_HTML_TR_ID_STR: String = "tr";
const ELEMENT_HTML_TT_ID_STR: String = "tt";
const ELEMENT_HTML_U_ID_STR: String = "u";
const ELEMENT_HTML_UL_ID_STR: String = "ul";
const ELEMENT_HTML_VAR_ID_STR: String = "var";
const ELEMENT_HTML_VIDEO_ID_STR: String = "video";
const ELEMENT_HTML_WBR_ID_STR: String = "wbr";
const ELEMENT_HTML_XMP_ID_STR: String = "xmp";

type ATTRIB = (
    HTML_ABBR,
    HTML_ACCEPT,
    HTML_ACCEPT_CHARSET,
    HTML_ACCESSKEY,
    HTML_ACTION,
    HTML_ALIGN,
    HTML_ALINK,
    HTML_ALT,
    HTML_ARCHIVE,
    HTML_AUTOCOMPLETE,
    HTML_AUTOPLAY,
    HTML_AXIS,
    HTML_BACKGROUND,
    HTML_BEHAVIOR,
    HTML_BGCOLOR,
    HTML_BGPROPERTIES,
    HTML_BORDER,
    HTML_BORDERCOLOR,
    HTML_CELLPADDING,
    HTML_CELLSPACING,
    HTML_CHALLENGE,
    HTML_CHAR,
    HTML_CHAROFF,
    HTML_CHARSET,
    HTML_CHECKED,
    HTML_CITE,
    HTML_CLASS,
    HTML_CLASSID,
    HTML_CLEAR,
    HTML_CODE,
    HTML_CODEBASE,
    HTML_CODETYPE,
    HTML_COLOR,
    HTML_COLS,
    HTML_COLSPAN,
    HTML_COMPACT,
    HTML_CONTENT,
    HTML_CONTENTEDITABLE,
    HTML_CONTROLS,
    HTML_COORDS,
    HTML_DATA,
    HTML_DATETIME,
    HTML_DECLARE,
    HTML_DEFER,
    HTML_DIR,
    HTML_DIRECTION,
    HTML_DISABLED,
    HTML_ENCTYPE,
    HTML_FACE,
    HTML_FOR,
    HTML_FRAME,
    HTML_FRAMEBORDER,
    HTML_HEADERS,
    HTML_HEIGHT,
    HTML_HIDDEN,
    HTML_HREF,
    HTML_HREFLANG,
    HTML_HSPACE,
    HTML_HTML,
    HTML_HTTP_EQUIV,
    HTML_ID,
    HTML_ISMAP,
    HTML_LABEL,
    HTML_LANG,
    HTML_LANGUAGE,
    HTML_LEFT,
    HTML_LEFTMARGIN,
    HTML_LINK,
    HTML_LONGDESC,
    HTML_LOOP,
    HTML_MARGINHEIGHT,
    HTML_MARGINWIDTH,
    HTML_MAXLENGTH,
    HTML_MEDIA,
    HTML_METHOD,
    HTML_MULTIPLE,
    HTML_NAME,
    HTML_NOHREF,
    HTML_NORESIZE,
    HTML_NOSAVE,
    HTML_NOSHADE,
    HTML_NOWRAP,
    HTML_OBJECT,
    HTML_ONABORT,
    HTML_ONBLUR,
    HTML_ONCHANGE,
    HTML_ONCLICK,
    HTML_ONDBLCLICK,
    HTML_ONERROR,
    HTML_ONFOCUS,
    HTML_ONHASHCHANGE,
    HTML_ONKEYDOWN,
    HTML_ONKEYPRESS,
    HTML_ONKEYUP,
    HTML_ONLOAD,
    HTML_ONMESSAGE,
    HTML_ONMOUSEDOWN,
    HTML_ONMOUSEMOVE,
    HTML_ONMOUSEOUT,
    HTML_ONMOUSEOVER,
    HTML_ONMOUSEUP,
    HTML_ONRESET,
    HTML_ONRESIZE,
    HTML_ONSCROLL,
    HTML_ONSELECT,
    HTML_ONSUBMIT,
    HTML_ONUNLOAD,
    HTML_OVERSRC,
    HTML_PAGEX,
    HTML_PAGEY,
    HTML_PLACEHOLDER,
    HTML_PLAIN,
    HTML_PLUGINPAGE,
    HTML_PLUGINSPAGE,
    HTML_PLUGINURL,
    HTML_POSTER,
    HTML_PROFILE,
    HTML_PROMPT,
    HTML_READONLY,
    HTML_REL,
    HTML_REV,
    HTML_ROWS,
    HTML_ROWSPAN,
    HTML_RULES,
    HTML_SCHEME,
    HTML_SCOPE,
    HTML_SCROLLAMOUNT,
    HTML_SCROLLDELAY,
    HTML_SCROLLING,
    HTML_SELECTED,
    HTML_SHAPE,
    HTML_SIZE,
    HTML_SPAN,
    HTML_SRC,
    HTML_STANDBY,
    HTML_START,
    HTML_STYLE,
    HTML_SUMMARY,
    HTML_TABINDEX,
    HTML_TARGET,
    HTML_TEXT,
    HTML_TITLE,
    HTML_TOP,
    HTML_TOPMARGIN,
    HTML_TRUESPEED,
    HTML_TYPE,
    HTML_UNKNOWN,
    HTML_USEMAP,
    HTML_VALIGN,
    HTML_VALUE,
    HTML_VALUETYPE,
    HTML_VERSION,
    HTML_VISIBILITY,
    HTML_VLINK,
    HTML_VSPACE,
    HTML_WIDTH,
    HTML_WRAP,
    HTML_XMLNS,
    HTML_Z_INDEX
);
const ATTRIB_HTML_ABBR_STR: String = "abbr";
const ATTRIB_HTML_ACCEPT_STR: String = "accept";
const ATTRIB_HTML_ACCEPT_CHARSET_STR: String = "accept_charset";
const ATTRIB_HTML_ACCESSKEY_STR: String = "accesskey";
const ATTRIB_HTML_ACTION_STR: String = "action";
const ATTRIB_HTML_ALIGN_STR: String = "align";
const ATTRIB_HTML_ALINK_STR: String = "alink";
const ATTRIB_HTML_ALT_STR: String = "alt";
const ATTRIB_HTML_ARCHIVE_STR: String = "archive";
const ATTRIB_HTML_AUTOCOMPLETE_STR: String = "autocomplete";
const ATTRIB_HTML_AUTOPLAY_STR: String = "autoplay";
const ATTRIB_HTML_AXIS_STR: String = "axis";
const ATTRIB_HTML_BACKGROUND_STR: String = "background";
const ATTRIB_HTML_BEHAVIOR_STR: String = "behavior";
const ATTRIB_HTML_BGCOLOR_STR: String = "bgcolor";
const ATTRIB_HTML_BGPROPERTIES_STR: String = "bgproperties";
const ATTRIB_HTML_BORDER_STR: String = "border";
const ATTRIB_HTML_BORDERCOLOR_STR: String = "bordercolor";
const ATTRIB_HTML_CELLPADDING_STR: String = "cellpadding";
const ATTRIB_HTML_CELLSPACING_STR: String = "cellspacing";
const ATTRIB_HTML_CHALLENGE_STR: String = "challenge";
const ATTRIB_HTML_CHAR_STR: String = "char";
const ATTRIB_HTML_CHAROFF_STR: String = "charoff";
const ATTRIB_HTML_CHARSET_STR: String = "charset";
const ATTRIB_HTML_CHECKED_STR: String = "checked";
const ATTRIB_HTML_CITE_STR: String = "cite";
const ATTRIB_HTML_CLASS_STR: String = "class";
const ATTRIB_HTML_CLASSID_STR: String = "classid";
const ATTRIB_HTML_CLEAR_STR: String = "clear";
const ATTRIB_HTML_CODE_STR: String = "code";
const ATTRIB_HTML_CODEBASE_STR: String = "codebase";
const ATTRIB_HTML_CODETYPE_STR: String = "codetype";
const ATTRIB_HTML_COLOR_STR: String = "color";
const ATTRIB_HTML_COLS_STR: String = "cols";
const ATTRIB_HTML_COLSPAN_STR: String = "colspan";
const ATTRIB_HTML_COMPACT_STR: String = "compact";
const ATTRIB_HTML_CONTENT_STR: String = "content";
const ATTRIB_HTML_CONTENTEDITABLE_STR: String = "contenteditable";
const ATTRIB_HTML_CONTROLS_STR: String = "controls";
const ATTRIB_HTML_COORDS_STR: String = "coords";
const ATTRIB_HTML_DATA_STR: String = "data";
const ATTRIB_HTML_DATETIME_STR: String = "datetime";
const ATTRIB_HTML_DECLARE_STR: String = "declare";
const ATTRIB_HTML_DEFER_STR: String = "defer";
const ATTRIB_HTML_DIR_STR: String = "dir";
const ATTRIB_HTML_DIRECTION_STR: String = "direction";
const ATTRIB_HTML_DISABLED_STR: String = "disabled";
const ATTRIB_HTML_ENCTYPE_STR: String = "enctype";
const ATTRIB_HTML_FACE_STR: String = "face";
const ATTRIB_HTML_FOR_STR: String = "for";
const ATTRIB_HTML_FRAME_STR: String = "frame";
const ATTRIB_HTML_FRAMEBORDER_STR: String = "frameborder";
const ATTRIB_HTML_HEADERS_STR: String = "headers";
const ATTRIB_HTML_HEIGHT_STR: String = "height";
const ATTRIB_HTML_HIDDEN_STR: String = "hidden";
const ATTRIB_HTML_HREF_STR: String = "href";
const ATTRIB_HTML_HREFLANG_STR: String = "hreflang";
const ATTRIB_HTML_HSPACE_STR: String = "hspace";
const ATTRIB_HTML_HTML_STR: String = "html";
const ATTRIB_HTML_HTTP_EQUIV_STR: String = "http_equiv";
const ATTRIB_HTML_ID_STR: String = "id";
const ATTRIB_HTML_ISMAP_STR: String = "ismap";
const ATTRIB_HTML_LABEL_STR: String = "label";
const ATTRIB_HTML_LANG_STR: String = "lang";
const ATTRIB_HTML_LANGUAGE_STR: String = "language";
const ATTRIB_HTML_LEFT_STR: String = "left";
const ATTRIB_HTML_LEFTMARGIN_STR: String = "leftmargin";
const ATTRIB_HTML_LINK_STR: String = "link";
const ATTRIB_HTML_LONGDESC_STR: String = "longdesc";
const ATTRIB_HTML_LOOP_STR: String = "loop";
const ATTRIB_HTML_MARGINHEIGHT_STR: String = "marginheight";
const ATTRIB_HTML_MARGINWIDTH_STR: String = "marginwidth";
const ATTRIB_HTML_MAXLENGTH_STR: String = "maxlength";
const ATTRIB_HTML_MEDIA_STR: String = "media";
const ATTRIB_HTML_METHOD_STR: String = "method";
const ATTRIB_HTML_MULTIPLE_STR: String = "multiple";
const ATTRIB_HTML_NAME_STR: String = "name";
const ATTRIB_HTML_NOHREF_STR: String = "nohref";
const ATTRIB_HTML_NORESIZE_STR: String = "noresize";
const ATTRIB_HTML_NOSAVE_STR: String = "nosave";
const ATTRIB_HTML_NOSHADE_STR: String = "noshade";
const ATTRIB_HTML_NOWRAP_STR: String = "nowrap";
const ATTRIB_HTML_OBJECT_STR: String = "object";
const ATTRIB_HTML_ONABORT_STR: String = "onabort";
const ATTRIB_HTML_ONBLUR_STR: String = "onblur";
const ATTRIB_HTML_ONCHANGE_STR: String = "onchange";
const ATTRIB_HTML_ONCLICK_STR: String = "onclick";
const ATTRIB_HTML_ONDBLCLICK_STR: String = "ondblclick";
const ATTRIB_HTML_ONERROR_STR: String = "onerror";
const ATTRIB_HTML_ONFOCUS_STR: String = "onfocus";
const ATTRIB_HTML_ONHASHCHANGE_STR: String = "onhashchange";
const ATTRIB_HTML_ONKEYDOWN_STR: String = "onkeydown";
const ATTRIB_HTML_ONKEYPRESS_STR: String = "onkeypress";
const ATTRIB_HTML_ONKEYUP_STR: String = "onkeyup";
const ATTRIB_HTML_ONLOAD_STR: String = "onload";
const ATTRIB_HTML_ONMESSAGE_STR: String = "onmessage";
const ATTRIB_HTML_ONMOUSEDOWN_STR: String = "onmousedown";
const ATTRIB_HTML_ONMOUSEMOVE_STR: String = "onmousemove";
const ATTRIB_HTML_ONMOUSEOUT_STR: String = "onmouseout";
const ATTRIB_HTML_ONMOUSEOVER_STR: String = "onmouseover";
const ATTRIB_HTML_ONMOUSEUP_STR: String = "onmouseup";
const ATTRIB_HTML_ONRESET_STR: String = "onreset";
const ATTRIB_HTML_ONRESIZE_STR: String = "onresize";
const ATTRIB_HTML_ONSCROLL_STR: String = "onscroll";
const ATTRIB_HTML_ONSELECT_STR: String = "onselect";
const ATTRIB_HTML_ONSUBMIT_STR: String = "onsubmit";
const ATTRIB_HTML_ONUNLOAD_STR: String = "onunload";
const ATTRIB_HTML_OVERSRC_STR: String = "oversrc";
const ATTRIB_HTML_PAGEX_STR: String = "pagex";
const ATTRIB_HTML_PAGEY_STR: String = "pagey";
const ATTRIB_HTML_PLACEHOLDER_STR: String = "placeholder";
const ATTRIB_HTML_PLAIN_STR: String = "plain";
const ATTRIB_HTML_PLUGINPAGE_STR: String = "pluginpage";
const ATTRIB_HTML_PLUGINSPAGE_STR: String = "pluginspage";
const ATTRIB_HTML_PLUGINURL_STR: String = "pluginurl";
const ATTRIB_HTML_POSTER_STR: String = "poster";
const ATTRIB_HTML_PROFILE_STR: String = "profile";
const ATTRIB_HTML_PROMPT_STR: String = "prompt";
const ATTRIB_HTML_READONLY_STR: String = "readonly";
const ATTRIB_HTML_REL_STR: String = "rel";
const ATTRIB_HTML_REV_STR: String = "rev";
const ATTRIB_HTML_ROWS_STR: String = "rows";
const ATTRIB_HTML_ROWSPAN_STR: String = "rowspan";
const ATTRIB_HTML_RULES_STR: String = "rules";
const ATTRIB_HTML_SCHEME_STR: String = "scheme";
const ATTRIB_HTML_SCOPE_STR: String = "scope";
const ATTRIB_HTML_SCROLLAMOUNT_STR: String = "scrollamount";
const ATTRIB_HTML_SCROLLDELAY_STR: String = "scrolldelay";
const ATTRIB_HTML_SCROLLING_STR: String = "scrolling";
const ATTRIB_HTML_SELECTED_STR: String = "selected";
const ATTRIB_HTML_SHAPE_STR: String = "shape";
const ATTRIB_HTML_SIZE_STR: String = "size";
const ATTRIB_HTML_SPAN_STR: String = "span";
const ATTRIB_HTML_SRC_STR: String = "src";
const ATTRIB_HTML_STANDBY_STR: String = "standby";
const ATTRIB_HTML_START_STR: String = "start";
const ATTRIB_HTML_STYLE_STR: String = "style";
const ATTRIB_HTML_SUMMARY_STR: String = "summary";
const ATTRIB_HTML_TABINDEX_STR: String = "tabindex";
const ATTRIB_HTML_TARGET_STR: String = "target";
const ATTRIB_HTML_TEXT_STR: String = "text";
const ATTRIB_HTML_TITLE_STR: String = "title";
const ATTRIB_HTML_TOP_STR: String = "top";
const ATTRIB_HTML_TOPMARGIN_STR: String = "topmargin";
const ATTRIB_HTML_TRUESPEED_STR: String = "truespeed";
const ATTRIB_HTML_TYPE_STR: String = "type";
const ATTRIB_HTML_UNKNOWN_STR: String = "unknown";
const ATTRIB_HTML_USEMAP_STR: String = "usemap";
const ATTRIB_HTML_VALIGN_STR: String = "valign";
const ATTRIB_HTML_VALUE_STR: String = "value";
const ATTRIB_HTML_VALUETYPE_STR: String = "valuetype";
const ATTRIB_HTML_VERSION_STR: String = "version";
const ATTRIB_HTML_VISIBILITY_STR: String = "visibility";
const ATTRIB_HTML_VLINK_STR: String = "vlink";
const ATTRIB_HTML_VSPACE_STR: String = "vspace";
const ATTRIB_HTML_WIDTH_STR: String = "width";
const ATTRIB_HTML_WRAP_STR: String = "wrap";
const ATTRIB_HTML_XMLNS_STR: String = "xmlns";
const ATTRIB_HTML_Z_INDEX_STR: String = "z_index";