// This file is generated by ConstMaker, DON'T MODIFY.

QtObject {
    id: html


    enum ELEMENT {
        HTML_A_ID,
        HTML_ABBR_ID,
        HTML_ACRONYM_ID,
        HTML_ADDRESS_ID,
        HTML_APPLET_ID,
        HTML_AREA_ID,
        HTML_AUDIO_ID,
        HTML_B_ID,
        HTML_BASE_ID,
        HTML_BASEFONT_ID,
        HTML_BDO_ID,
        HTML_BIG_ID,
        HTML_BLOCKQUOTE_ID,
        HTML_BODY_ID,
        HTML_BR_ID,
        HTML_BUTTON_ID,
        HTML_CANVAS_ID,
        HTML_CAPTION_ID,
        HTML_CENTER_ID,
        HTML_CITE_ID,
        HTML_CODE_ID,
        HTML_COL_ID,
        HTML_COLGROUP_ID,
        HTML_COMMENT_ID,
        HTML_DD_ID,
        HTML_DEL_ID,
        HTML_DFN_ID,
        HTML_DIR_ID,
        HTML_DIV_ID,
        HTML_DL_ID,
        HTML_DT_ID,
        HTML_EM_ID,
        HTML_EMBED_ID,
        HTML_FIELDSET_ID,
        HTML_FONT_ID,
        HTML_FORM_ID,
        HTML_FRAME_ID,
        HTML_FRAMESET_ID,
        HTML_H1_ID,
        HTML_H2_ID,
        HTML_H3_ID,
        HTML_H4_ID,
        HTML_H5_ID,
        HTML_H6_ID,
        HTML_HEAD_ID,
        HTML_HR_ID,
        HTML_HTML_ID,
        HTML_I_ID,
        HTML_IFRAME_ID,
        HTML_ILAYER_ID,
        HTML_IMAGE_ID,
        HTML_IMG_ID,
        HTML_INPUT_ID,
        HTML_INS_ID,
        HTML_ISINDEX_ID,
        HTML_KBD_ID,
        HTML_KEYGEN_ID,
        HTML_LABEL_ID,
        HTML_LAYER_ID,
        HTML_LEGEND_ID,
        HTML_LI_ID,
        HTML_LINK_ID,
        HTML_LISTING_ID,
        HTML_MAP_ID,
        HTML_MARQUEE_ID,
        HTML_MENU_ID,
        HTML_META_ID,
        HTML_NOBR_ID,
        HTML_NOEMBED_ID,
        HTML_NOFRAMES_ID,
        HTML_NOLAYER_ID,
        HTML_NOSCRIPT_ID,
        HTML_OBJECT_ID,
        HTML_OL_ID,
        HTML_OPTGROUP_ID,
        HTML_OPTION_ID,
        HTML_P_ID,
        HTML_PARAM_ID,
        HTML_PLAINTEXT_ID,
        HTML_PRE_ID,
        HTML_Q_ID,
        HTML_S_ID,
        HTML_SAMP_ID,
        HTML_SCRIPT_ID,
        HTML_SELECT_ID,
        HTML_SMALL_ID,
        HTML_SOURCE_ID,
        HTML_SPAN_ID,
        HTML_STRIKE_ID,
        HTML_STRONG_ID,
        HTML_STYLE_ID,
        HTML_SUB_ID,
        HTML_SUP_ID,
        HTML_TABLE_ID,
        HTML_TBODY_ID,
        HTML_TD_ID,
        HTML_TEXT_ID,
        HTML_TEXTAREA_ID,
        HTML_TFOOT_ID,
        HTML_TH_ID,
        HTML_THEAD_ID,
        HTML_TITLE_ID,
        HTML_TR_ID,
        HTML_TT_ID,
        HTML_U_ID,
        HTML_UL_ID,
        HTML_VAR_ID,
        HTML_VIDEO_ID,
        HTML_WBR_ID,
        HTML_XMP_ID
    }
    property string ELEMENT_HTML_A_ID_STR: "HTML_A_ID"
    property string ELEMENT_HTML_ABBR_ID_STR: "HTML_ABBR_ID"
    property string ELEMENT_HTML_ACRONYM_ID_STR: "HTML_ACRONYM_ID"
    property string ELEMENT_HTML_ADDRESS_ID_STR: "HTML_ADDRESS_ID"
    property string ELEMENT_HTML_APPLET_ID_STR: "HTML_APPLET_ID"
    property string ELEMENT_HTML_AREA_ID_STR: "HTML_AREA_ID"
    property string ELEMENT_HTML_AUDIO_ID_STR: "HTML_AUDIO_ID"
    property string ELEMENT_HTML_B_ID_STR: "HTML_B_ID"
    property string ELEMENT_HTML_BASE_ID_STR: "HTML_BASE_ID"
    property string ELEMENT_HTML_BASEFONT_ID_STR: "HTML_BASEFONT_ID"
    property string ELEMENT_HTML_BDO_ID_STR: "HTML_BDO_ID"
    property string ELEMENT_HTML_BIG_ID_STR: "HTML_BIG_ID"
    property string ELEMENT_HTML_BLOCKQUOTE_ID_STR: "HTML_BLOCKQUOTE_ID"
    property string ELEMENT_HTML_BODY_ID_STR: "HTML_BODY_ID"
    property string ELEMENT_HTML_BR_ID_STR: "HTML_BR_ID"
    property string ELEMENT_HTML_BUTTON_ID_STR: "HTML_BUTTON_ID"
    property string ELEMENT_HTML_CANVAS_ID_STR: "HTML_CANVAS_ID"
    property string ELEMENT_HTML_CAPTION_ID_STR: "HTML_CAPTION_ID"
    property string ELEMENT_HTML_CENTER_ID_STR: "HTML_CENTER_ID"
    property string ELEMENT_HTML_CITE_ID_STR: "HTML_CITE_ID"
    property string ELEMENT_HTML_CODE_ID_STR: "HTML_CODE_ID"
    property string ELEMENT_HTML_COL_ID_STR: "HTML_COL_ID"
    property string ELEMENT_HTML_COLGROUP_ID_STR: "HTML_COLGROUP_ID"
    property string ELEMENT_HTML_COMMENT_ID_STR: "HTML_COMMENT_ID"
    property string ELEMENT_HTML_DD_ID_STR: "HTML_DD_ID"
    property string ELEMENT_HTML_DEL_ID_STR: "HTML_DEL_ID"
    property string ELEMENT_HTML_DFN_ID_STR: "HTML_DFN_ID"
    property string ELEMENT_HTML_DIR_ID_STR: "HTML_DIR_ID"
    property string ELEMENT_HTML_DIV_ID_STR: "HTML_DIV_ID"
    property string ELEMENT_HTML_DL_ID_STR: "HTML_DL_ID"
    property string ELEMENT_HTML_DT_ID_STR: "HTML_DT_ID"
    property string ELEMENT_HTML_EM_ID_STR: "HTML_EM_ID"
    property string ELEMENT_HTML_EMBED_ID_STR: "HTML_EMBED_ID"
    property string ELEMENT_HTML_FIELDSET_ID_STR: "HTML_FIELDSET_ID"
    property string ELEMENT_HTML_FONT_ID_STR: "HTML_FONT_ID"
    property string ELEMENT_HTML_FORM_ID_STR: "HTML_FORM_ID"
    property string ELEMENT_HTML_FRAME_ID_STR: "HTML_FRAME_ID"
    property string ELEMENT_HTML_FRAMESET_ID_STR: "HTML_FRAMESET_ID"
    property string ELEMENT_HTML_H1_ID_STR: "HTML_H1_ID"
    property string ELEMENT_HTML_H2_ID_STR: "HTML_H2_ID"
    property string ELEMENT_HTML_H3_ID_STR: "HTML_H3_ID"
    property string ELEMENT_HTML_H4_ID_STR: "HTML_H4_ID"
    property string ELEMENT_HTML_H5_ID_STR: "HTML_H5_ID"
    property string ELEMENT_HTML_H6_ID_STR: "HTML_H6_ID"
    property string ELEMENT_HTML_HEAD_ID_STR: "HTML_HEAD_ID"
    property string ELEMENT_HTML_HR_ID_STR: "HTML_HR_ID"
    property string ELEMENT_HTML_HTML_ID_STR: "HTML_HTML_ID"
    property string ELEMENT_HTML_I_ID_STR: "HTML_I_ID"
    property string ELEMENT_HTML_IFRAME_ID_STR: "HTML_IFRAME_ID"
    property string ELEMENT_HTML_ILAYER_ID_STR: "HTML_ILAYER_ID"
    property string ELEMENT_HTML_IMAGE_ID_STR: "HTML_IMAGE_ID"
    property string ELEMENT_HTML_IMG_ID_STR: "HTML_IMG_ID"
    property string ELEMENT_HTML_INPUT_ID_STR: "HTML_INPUT_ID"
    property string ELEMENT_HTML_INS_ID_STR: "HTML_INS_ID"
    property string ELEMENT_HTML_ISINDEX_ID_STR: "HTML_ISINDEX_ID"
    property string ELEMENT_HTML_KBD_ID_STR: "HTML_KBD_ID"
    property string ELEMENT_HTML_KEYGEN_ID_STR: "HTML_KEYGEN_ID"
    property string ELEMENT_HTML_LABEL_ID_STR: "HTML_LABEL_ID"
    property string ELEMENT_HTML_LAYER_ID_STR: "HTML_LAYER_ID"
    property string ELEMENT_HTML_LEGEND_ID_STR: "HTML_LEGEND_ID"
    property string ELEMENT_HTML_LI_ID_STR: "HTML_LI_ID"
    property string ELEMENT_HTML_LINK_ID_STR: "HTML_LINK_ID"
    property string ELEMENT_HTML_LISTING_ID_STR: "HTML_LISTING_ID"
    property string ELEMENT_HTML_MAP_ID_STR: "HTML_MAP_ID"
    property string ELEMENT_HTML_MARQUEE_ID_STR: "HTML_MARQUEE_ID"
    property string ELEMENT_HTML_MENU_ID_STR: "HTML_MENU_ID"
    property string ELEMENT_HTML_META_ID_STR: "HTML_META_ID"
    property string ELEMENT_HTML_NOBR_ID_STR: "HTML_NOBR_ID"
    property string ELEMENT_HTML_NOEMBED_ID_STR: "HTML_NOEMBED_ID"
    property string ELEMENT_HTML_NOFRAMES_ID_STR: "HTML_NOFRAMES_ID"
    property string ELEMENT_HTML_NOLAYER_ID_STR: "HTML_NOLAYER_ID"
    property string ELEMENT_HTML_NOSCRIPT_ID_STR: "HTML_NOSCRIPT_ID"
    property string ELEMENT_HTML_OBJECT_ID_STR: "HTML_OBJECT_ID"
    property string ELEMENT_HTML_OL_ID_STR: "HTML_OL_ID"
    property string ELEMENT_HTML_OPTGROUP_ID_STR: "HTML_OPTGROUP_ID"
    property string ELEMENT_HTML_OPTION_ID_STR: "HTML_OPTION_ID"
    property string ELEMENT_HTML_P_ID_STR: "HTML_P_ID"
    property string ELEMENT_HTML_PARAM_ID_STR: "HTML_PARAM_ID"
    property string ELEMENT_HTML_PLAINTEXT_ID_STR: "HTML_PLAINTEXT_ID"
    property string ELEMENT_HTML_PRE_ID_STR: "HTML_PRE_ID"
    property string ELEMENT_HTML_Q_ID_STR: "HTML_Q_ID"
    property string ELEMENT_HTML_S_ID_STR: "HTML_S_ID"
    property string ELEMENT_HTML_SAMP_ID_STR: "HTML_SAMP_ID"
    property string ELEMENT_HTML_SCRIPT_ID_STR: "HTML_SCRIPT_ID"
    property string ELEMENT_HTML_SELECT_ID_STR: "HTML_SELECT_ID"
    property string ELEMENT_HTML_SMALL_ID_STR: "HTML_SMALL_ID"
    property string ELEMENT_HTML_SOURCE_ID_STR: "HTML_SOURCE_ID"
    property string ELEMENT_HTML_SPAN_ID_STR: "HTML_SPAN_ID"
    property string ELEMENT_HTML_STRIKE_ID_STR: "HTML_STRIKE_ID"
    property string ELEMENT_HTML_STRONG_ID_STR: "HTML_STRONG_ID"
    property string ELEMENT_HTML_STYLE_ID_STR: "HTML_STYLE_ID"
    property string ELEMENT_HTML_SUB_ID_STR: "HTML_SUB_ID"
    property string ELEMENT_HTML_SUP_ID_STR: "HTML_SUP_ID"
    property string ELEMENT_HTML_TABLE_ID_STR: "HTML_TABLE_ID"
    property string ELEMENT_HTML_TBODY_ID_STR: "HTML_TBODY_ID"
    property string ELEMENT_HTML_TD_ID_STR: "HTML_TD_ID"
    property string ELEMENT_HTML_TEXT_ID_STR: "HTML_TEXT_ID"
    property string ELEMENT_HTML_TEXTAREA_ID_STR: "HTML_TEXTAREA_ID"
    property string ELEMENT_HTML_TFOOT_ID_STR: "HTML_TFOOT_ID"
    property string ELEMENT_HTML_TH_ID_STR: "HTML_TH_ID"
    property string ELEMENT_HTML_THEAD_ID_STR: "HTML_THEAD_ID"
    property string ELEMENT_HTML_TITLE_ID_STR: "HTML_TITLE_ID"
    property string ELEMENT_HTML_TR_ID_STR: "HTML_TR_ID"
    property string ELEMENT_HTML_TT_ID_STR: "HTML_TT_ID"
    property string ELEMENT_HTML_U_ID_STR: "HTML_U_ID"
    property string ELEMENT_HTML_UL_ID_STR: "HTML_UL_ID"
    property string ELEMENT_HTML_VAR_ID_STR: "HTML_VAR_ID"
    property string ELEMENT_HTML_VIDEO_ID_STR: "HTML_VIDEO_ID"
    property string ELEMENT_HTML_WBR_ID_STR: "HTML_WBR_ID"
    property string ELEMENT_HTML_XMP_ID_STR: "HTML_XMP_ID"

    enum ATTRIB {
        HTML_ABBR,
        HTML_ACCEPT,
        HTML_ACCEPT_CHARSET,
        HTML_ACCESSKEY,
        HTML_ACTION,
        HTML_ALIGN,
        HTML_ALINK,
        HTML_ALT,
        HTML_ARCHIVE,
        HTML_AUTOCOMPLETE,
        HTML_AUTOPLAY,
        HTML_AXIS,
        HTML_BACKGROUND,
        HTML_BEHAVIOR,
        HTML_BGCOLOR,
        HTML_BGPROPERTIES,
        HTML_BORDER,
        HTML_BORDERCOLOR,
        HTML_CELLPADDING,
        HTML_CELLSPACING,
        HTML_CHALLENGE,
        HTML_CHAR,
        HTML_CHAROFF,
        HTML_CHARSET,
        HTML_CHECKED,
        HTML_CITE,
        HTML_CLASS,
        HTML_CLASSID,
        HTML_CLEAR,
        HTML_CODE,
        HTML_CODEBASE,
        HTML_CODETYPE,
        HTML_COLOR,
        HTML_COLS,
        HTML_COLSPAN,
        HTML_COMPACT,
        HTML_CONTENT,
        HTML_CONTENTEDITABLE,
        HTML_CONTROLS,
        HTML_COORDS,
        HTML_DATA,
        HTML_DATETIME,
        HTML_DECLARE,
        HTML_DEFER,
        HTML_DIR,
        HTML_DIRECTION,
        HTML_DISABLED,
        HTML_ENCTYPE,
        HTML_FACE,
        HTML_FOR,
        HTML_FRAME,
        HTML_FRAMEBORDER,
        HTML_HEADERS,
        HTML_HEIGHT,
        HTML_HIDDEN,
        HTML_HREF,
        HTML_HREFLANG,
        HTML_HSPACE,
        HTML_HTML,
        HTML_HTTP_EQUIV,
        HTML_ID,
        HTML_ISMAP,
        HTML_LABEL,
        HTML_LANG,
        HTML_LANGUAGE,
        HTML_LEFT,
        HTML_LEFTMARGIN,
        HTML_LINK,
        HTML_LONGDESC,
        HTML_LOOP,
        HTML_MARGINHEIGHT,
        HTML_MARGINWIDTH,
        HTML_MAXLENGTH,
        HTML_MEDIA,
        HTML_METHOD,
        HTML_MULTIPLE,
        HTML_NAME,
        HTML_NOHREF,
        HTML_NORESIZE,
        HTML_NOSAVE,
        HTML_NOSHADE,
        HTML_NOWRAP,
        HTML_OBJECT,
        HTML_ONABORT,
        HTML_ONBLUR,
        HTML_ONCHANGE,
        HTML_ONCLICK,
        HTML_ONDBLCLICK,
        HTML_ONERROR,
        HTML_ONFOCUS,
        HTML_ONHASHCHANGE,
        HTML_ONKEYDOWN,
        HTML_ONKEYPRESS,
        HTML_ONKEYUP,
        HTML_ONLOAD,
        HTML_ONMESSAGE,
        HTML_ONMOUSEDOWN,
        HTML_ONMOUSEMOVE,
        HTML_ONMOUSEOUT,
        HTML_ONMOUSEOVER,
        HTML_ONMOUSEUP,
        HTML_ONRESET,
        HTML_ONRESIZE,
        HTML_ONSCROLL,
        HTML_ONSELECT,
        HTML_ONSUBMIT,
        HTML_ONUNLOAD,
        HTML_OVERSRC,
        HTML_PAGEX,
        HTML_PAGEY,
        HTML_PLACEHOLDER,
        HTML_PLAIN,
        HTML_PLUGINPAGE,
        HTML_PLUGINSPAGE,
        HTML_PLUGINURL,
        HTML_POSTER,
        HTML_PROFILE,
        HTML_PROMPT,
        HTML_READONLY,
        HTML_REL,
        HTML_REV,
        HTML_ROWS,
        HTML_ROWSPAN,
        HTML_RULES,
        HTML_SCHEME,
        HTML_SCOPE,
        HTML_SCROLLAMOUNT,
        HTML_SCROLLDELAY,
        HTML_SCROLLING,
        HTML_SELECTED,
        HTML_SHAPE,
        HTML_SIZE,
        HTML_SPAN,
        HTML_SRC,
        HTML_STANDBY,
        HTML_START,
        HTML_STYLE,
        HTML_SUMMARY,
        HTML_TABINDEX,
        HTML_TARGET,
        HTML_TEXT,
        HTML_TITLE,
        HTML_TOP,
        HTML_TOPMARGIN,
        HTML_TRUESPEED,
        HTML_TYPE,
        HTML_UNKNOWN,
        HTML_USEMAP,
        HTML_VALIGN,
        HTML_VALUE,
        HTML_VALUETYPE,
        HTML_VERSION,
        HTML_VISIBILITY,
        HTML_VLINK,
        HTML_VSPACE,
        HTML_WIDTH,
        HTML_WRAP,
        HTML_XMLNS,
        HTML_Z_INDEX
    }
    property string ATTRIB_HTML_ABBR_STR: "HTML_ABBR"
    property string ATTRIB_HTML_ACCEPT_STR: "HTML_ACCEPT"
    property string ATTRIB_HTML_ACCEPT_CHARSET_STR: "HTML_ACCEPT_CHARSET"
    property string ATTRIB_HTML_ACCESSKEY_STR: "HTML_ACCESSKEY"
    property string ATTRIB_HTML_ACTION_STR: "HTML_ACTION"
    property string ATTRIB_HTML_ALIGN_STR: "HTML_ALIGN"
    property string ATTRIB_HTML_ALINK_STR: "HTML_ALINK"
    property string ATTRIB_HTML_ALT_STR: "HTML_ALT"
    property string ATTRIB_HTML_ARCHIVE_STR: "HTML_ARCHIVE"
    property string ATTRIB_HTML_AUTOCOMPLETE_STR: "HTML_AUTOCOMPLETE"
    property string ATTRIB_HTML_AUTOPLAY_STR: "HTML_AUTOPLAY"
    property string ATTRIB_HTML_AXIS_STR: "HTML_AXIS"
    property string ATTRIB_HTML_BACKGROUND_STR: "HTML_BACKGROUND"
    property string ATTRIB_HTML_BEHAVIOR_STR: "HTML_BEHAVIOR"
    property string ATTRIB_HTML_BGCOLOR_STR: "HTML_BGCOLOR"
    property string ATTRIB_HTML_BGPROPERTIES_STR: "HTML_BGPROPERTIES"
    property string ATTRIB_HTML_BORDER_STR: "HTML_BORDER"
    property string ATTRIB_HTML_BORDERCOLOR_STR: "HTML_BORDERCOLOR"
    property string ATTRIB_HTML_CELLPADDING_STR: "HTML_CELLPADDING"
    property string ATTRIB_HTML_CELLSPACING_STR: "HTML_CELLSPACING"
    property string ATTRIB_HTML_CHALLENGE_STR: "HTML_CHALLENGE"
    property string ATTRIB_HTML_CHAR_STR: "HTML_CHAR"
    property string ATTRIB_HTML_CHAROFF_STR: "HTML_CHAROFF"
    property string ATTRIB_HTML_CHARSET_STR: "HTML_CHARSET"
    property string ATTRIB_HTML_CHECKED_STR: "HTML_CHECKED"
    property string ATTRIB_HTML_CITE_STR: "HTML_CITE"
    property string ATTRIB_HTML_CLASS_STR: "HTML_CLASS"
    property string ATTRIB_HTML_CLASSID_STR: "HTML_CLASSID"
    property string ATTRIB_HTML_CLEAR_STR: "HTML_CLEAR"
    property string ATTRIB_HTML_CODE_STR: "HTML_CODE"
    property string ATTRIB_HTML_CODEBASE_STR: "HTML_CODEBASE"
    property string ATTRIB_HTML_CODETYPE_STR: "HTML_CODETYPE"
    property string ATTRIB_HTML_COLOR_STR: "HTML_COLOR"
    property string ATTRIB_HTML_COLS_STR: "HTML_COLS"
    property string ATTRIB_HTML_COLSPAN_STR: "HTML_COLSPAN"
    property string ATTRIB_HTML_COMPACT_STR: "HTML_COMPACT"
    property string ATTRIB_HTML_CONTENT_STR: "HTML_CONTENT"
    property string ATTRIB_HTML_CONTENTEDITABLE_STR: "HTML_CONTENTEDITABLE"
    property string ATTRIB_HTML_CONTROLS_STR: "HTML_CONTROLS"
    property string ATTRIB_HTML_COORDS_STR: "HTML_COORDS"
    property string ATTRIB_HTML_DATA_STR: "HTML_DATA"
    property string ATTRIB_HTML_DATETIME_STR: "HTML_DATETIME"
    property string ATTRIB_HTML_DECLARE_STR: "HTML_DECLARE"
    property string ATTRIB_HTML_DEFER_STR: "HTML_DEFER"
    property string ATTRIB_HTML_DIR_STR: "HTML_DIR"
    property string ATTRIB_HTML_DIRECTION_STR: "HTML_DIRECTION"
    property string ATTRIB_HTML_DISABLED_STR: "HTML_DISABLED"
    property string ATTRIB_HTML_ENCTYPE_STR: "HTML_ENCTYPE"
    property string ATTRIB_HTML_FACE_STR: "HTML_FACE"
    property string ATTRIB_HTML_FOR_STR: "HTML_FOR"
    property string ATTRIB_HTML_FRAME_STR: "HTML_FRAME"
    property string ATTRIB_HTML_FRAMEBORDER_STR: "HTML_FRAMEBORDER"
    property string ATTRIB_HTML_HEADERS_STR: "HTML_HEADERS"
    property string ATTRIB_HTML_HEIGHT_STR: "HTML_HEIGHT"
    property string ATTRIB_HTML_HIDDEN_STR: "HTML_HIDDEN"
    property string ATTRIB_HTML_HREF_STR: "HTML_HREF"
    property string ATTRIB_HTML_HREFLANG_STR: "HTML_HREFLANG"
    property string ATTRIB_HTML_HSPACE_STR: "HTML_HSPACE"
    property string ATTRIB_HTML_HTML_STR: "HTML_HTML"
    property string ATTRIB_HTML_HTTP_EQUIV_STR: "HTML_HTTP_EQUIV"
    property string ATTRIB_HTML_ID_STR: "HTML_ID"
    property string ATTRIB_HTML_ISMAP_STR: "HTML_ISMAP"
    property string ATTRIB_HTML_LABEL_STR: "HTML_LABEL"
    property string ATTRIB_HTML_LANG_STR: "HTML_LANG"
    property string ATTRIB_HTML_LANGUAGE_STR: "HTML_LANGUAGE"
    property string ATTRIB_HTML_LEFT_STR: "HTML_LEFT"
    property string ATTRIB_HTML_LEFTMARGIN_STR: "HTML_LEFTMARGIN"
    property string ATTRIB_HTML_LINK_STR: "HTML_LINK"
    property string ATTRIB_HTML_LONGDESC_STR: "HTML_LONGDESC"
    property string ATTRIB_HTML_LOOP_STR: "HTML_LOOP"
    property string ATTRIB_HTML_MARGINHEIGHT_STR: "HTML_MARGINHEIGHT"
    property string ATTRIB_HTML_MARGINWIDTH_STR: "HTML_MARGINWIDTH"
    property string ATTRIB_HTML_MAXLENGTH_STR: "HTML_MAXLENGTH"
    property string ATTRIB_HTML_MEDIA_STR: "HTML_MEDIA"
    property string ATTRIB_HTML_METHOD_STR: "HTML_METHOD"
    property string ATTRIB_HTML_MULTIPLE_STR: "HTML_MULTIPLE"
    property string ATTRIB_HTML_NAME_STR: "HTML_NAME"
    property string ATTRIB_HTML_NOHREF_STR: "HTML_NOHREF"
    property string ATTRIB_HTML_NORESIZE_STR: "HTML_NORESIZE"
    property string ATTRIB_HTML_NOSAVE_STR: "HTML_NOSAVE"
    property string ATTRIB_HTML_NOSHADE_STR: "HTML_NOSHADE"
    property string ATTRIB_HTML_NOWRAP_STR: "HTML_NOWRAP"
    property string ATTRIB_HTML_OBJECT_STR: "HTML_OBJECT"
    property string ATTRIB_HTML_ONABORT_STR: "HTML_ONABORT"
    property string ATTRIB_HTML_ONBLUR_STR: "HTML_ONBLUR"
    property string ATTRIB_HTML_ONCHANGE_STR: "HTML_ONCHANGE"
    property string ATTRIB_HTML_ONCLICK_STR: "HTML_ONCLICK"
    property string ATTRIB_HTML_ONDBLCLICK_STR: "HTML_ONDBLCLICK"
    property string ATTRIB_HTML_ONERROR_STR: "HTML_ONERROR"
    property string ATTRIB_HTML_ONFOCUS_STR: "HTML_ONFOCUS"
    property string ATTRIB_HTML_ONHASHCHANGE_STR: "HTML_ONHASHCHANGE"
    property string ATTRIB_HTML_ONKEYDOWN_STR: "HTML_ONKEYDOWN"
    property string ATTRIB_HTML_ONKEYPRESS_STR: "HTML_ONKEYPRESS"
    property string ATTRIB_HTML_ONKEYUP_STR: "HTML_ONKEYUP"
    property string ATTRIB_HTML_ONLOAD_STR: "HTML_ONLOAD"
    property string ATTRIB_HTML_ONMESSAGE_STR: "HTML_ONMESSAGE"
    property string ATTRIB_HTML_ONMOUSEDOWN_STR: "HTML_ONMOUSEDOWN"
    property string ATTRIB_HTML_ONMOUSEMOVE_STR: "HTML_ONMOUSEMOVE"
    property string ATTRIB_HTML_ONMOUSEOUT_STR: "HTML_ONMOUSEOUT"
    property string ATTRIB_HTML_ONMOUSEOVER_STR: "HTML_ONMOUSEOVER"
    property string ATTRIB_HTML_ONMOUSEUP_STR: "HTML_ONMOUSEUP"
    property string ATTRIB_HTML_ONRESET_STR: "HTML_ONRESET"
    property string ATTRIB_HTML_ONRESIZE_STR: "HTML_ONRESIZE"
    property string ATTRIB_HTML_ONSCROLL_STR: "HTML_ONSCROLL"
    property string ATTRIB_HTML_ONSELECT_STR: "HTML_ONSELECT"
    property string ATTRIB_HTML_ONSUBMIT_STR: "HTML_ONSUBMIT"
    property string ATTRIB_HTML_ONUNLOAD_STR: "HTML_ONUNLOAD"
    property string ATTRIB_HTML_OVERSRC_STR: "HTML_OVERSRC"
    property string ATTRIB_HTML_PAGEX_STR: "HTML_PAGEX"
    property string ATTRIB_HTML_PAGEY_STR: "HTML_PAGEY"
    property string ATTRIB_HTML_PLACEHOLDER_STR: "HTML_PLACEHOLDER"
    property string ATTRIB_HTML_PLAIN_STR: "HTML_PLAIN"
    property string ATTRIB_HTML_PLUGINPAGE_STR: "HTML_PLUGINPAGE"
    property string ATTRIB_HTML_PLUGINSPAGE_STR: "HTML_PLUGINSPAGE"
    property string ATTRIB_HTML_PLUGINURL_STR: "HTML_PLUGINURL"
    property string ATTRIB_HTML_POSTER_STR: "HTML_POSTER"
    property string ATTRIB_HTML_PROFILE_STR: "HTML_PROFILE"
    property string ATTRIB_HTML_PROMPT_STR: "HTML_PROMPT"
    property string ATTRIB_HTML_READONLY_STR: "HTML_READONLY"
    property string ATTRIB_HTML_REL_STR: "HTML_REL"
    property string ATTRIB_HTML_REV_STR: "HTML_REV"
    property string ATTRIB_HTML_ROWS_STR: "HTML_ROWS"
    property string ATTRIB_HTML_ROWSPAN_STR: "HTML_ROWSPAN"
    property string ATTRIB_HTML_RULES_STR: "HTML_RULES"
    property string ATTRIB_HTML_SCHEME_STR: "HTML_SCHEME"
    property string ATTRIB_HTML_SCOPE_STR: "HTML_SCOPE"
    property string ATTRIB_HTML_SCROLLAMOUNT_STR: "HTML_SCROLLAMOUNT"
    property string ATTRIB_HTML_SCROLLDELAY_STR: "HTML_SCROLLDELAY"
    property string ATTRIB_HTML_SCROLLING_STR: "HTML_SCROLLING"
    property string ATTRIB_HTML_SELECTED_STR: "HTML_SELECTED"
    property string ATTRIB_HTML_SHAPE_STR: "HTML_SHAPE"
    property string ATTRIB_HTML_SIZE_STR: "HTML_SIZE"
    property string ATTRIB_HTML_SPAN_STR: "HTML_SPAN"
    property string ATTRIB_HTML_SRC_STR: "HTML_SRC"
    property string ATTRIB_HTML_STANDBY_STR: "HTML_STANDBY"
    property string ATTRIB_HTML_START_STR: "HTML_START"
    property string ATTRIB_HTML_STYLE_STR: "HTML_STYLE"
    property string ATTRIB_HTML_SUMMARY_STR: "HTML_SUMMARY"
    property string ATTRIB_HTML_TABINDEX_STR: "HTML_TABINDEX"
    property string ATTRIB_HTML_TARGET_STR: "HTML_TARGET"
    property string ATTRIB_HTML_TEXT_STR: "HTML_TEXT"
    property string ATTRIB_HTML_TITLE_STR: "HTML_TITLE"
    property string ATTRIB_HTML_TOP_STR: "HTML_TOP"
    property string ATTRIB_HTML_TOPMARGIN_STR: "HTML_TOPMARGIN"
    property string ATTRIB_HTML_TRUESPEED_STR: "HTML_TRUESPEED"
    property string ATTRIB_HTML_TYPE_STR: "HTML_TYPE"
    property string ATTRIB_HTML_UNKNOWN_STR: "HTML_UNKNOWN"
    property string ATTRIB_HTML_USEMAP_STR: "HTML_USEMAP"
    property string ATTRIB_HTML_VALIGN_STR: "HTML_VALIGN"
    property string ATTRIB_HTML_VALUE_STR: "HTML_VALUE"
    property string ATTRIB_HTML_VALUETYPE_STR: "HTML_VALUETYPE"
    property string ATTRIB_HTML_VERSION_STR: "HTML_VERSION"
    property string ATTRIB_HTML_VISIBILITY_STR: "HTML_VISIBILITY"
    property string ATTRIB_HTML_VLINK_STR: "HTML_VLINK"
    property string ATTRIB_HTML_VSPACE_STR: "HTML_VSPACE"
    property string ATTRIB_HTML_WIDTH_STR: "HTML_WIDTH"
    property string ATTRIB_HTML_WRAP_STR: "HTML_WRAP"
    property string ATTRIB_HTML_XMLNS_STR: "HTML_XMLNS"
    property string ATTRIB_HTML_Z_INDEX_STR: "HTML_Z_INDEX"
}