// This file is generated by ConstMaker, DON'T MODIFY.

interface html {

    enum ELEMENT {
        HTML_A_ID,
        HTML_ABBR_ID,
        HTML_ACRONYM_ID,
        HTML_ADDRESS_ID,
        HTML_APPLET_ID,
        HTML_AREA_ID,
        HTML_AUDIO_ID,
        HTML_B_ID,
        HTML_BASE_ID,
        HTML_BASEFONT_ID,
        HTML_BDO_ID,
        HTML_BIG_ID,
        HTML_BLOCKQUOTE_ID,
        HTML_BODY_ID,
        HTML_BR_ID,
        HTML_BUTTON_ID,
        HTML_CANVAS_ID,
        HTML_CAPTION_ID,
        HTML_CENTER_ID,
        HTML_CITE_ID,
        HTML_CODE_ID,
        HTML_COL_ID,
        HTML_COLGROUP_ID,
        HTML_COMMENT_ID,
        HTML_DD_ID,
        HTML_DEL_ID,
        HTML_DFN_ID,
        HTML_DIR_ID,
        HTML_DIV_ID,
        HTML_DL_ID,
        HTML_DT_ID,
        HTML_EM_ID,
        HTML_EMBED_ID,
        HTML_FIELDSET_ID,
        HTML_FONT_ID,
        HTML_FORM_ID,
        HTML_FRAME_ID,
        HTML_FRAMESET_ID,
        HTML_H1_ID,
        HTML_H2_ID,
        HTML_H3_ID,
        HTML_H4_ID,
        HTML_H5_ID,
        HTML_H6_ID,
        HTML_HEAD_ID,
        HTML_HR_ID,
        HTML_HTML_ID,
        HTML_I_ID,
        HTML_IFRAME_ID,
        HTML_ILAYER_ID,
        HTML_IMAGE_ID,
        HTML_IMG_ID,
        HTML_INPUT_ID,
        HTML_INS_ID,
        HTML_ISINDEX_ID,
        HTML_KBD_ID,
        HTML_KEYGEN_ID,
        HTML_LABEL_ID,
        HTML_LAYER_ID,
        HTML_LEGEND_ID,
        HTML_LI_ID,
        HTML_LINK_ID,
        HTML_LISTING_ID,
        HTML_MAP_ID,
        HTML_MARQUEE_ID,
        HTML_MENU_ID,
        HTML_META_ID,
        HTML_NOBR_ID,
        HTML_NOEMBED_ID,
        HTML_NOFRAMES_ID,
        HTML_NOLAYER_ID,
        HTML_NOSCRIPT_ID,
        HTML_OBJECT_ID,
        HTML_OL_ID,
        HTML_OPTGROUP_ID,
        HTML_OPTION_ID,
        HTML_P_ID,
        HTML_PARAM_ID,
        HTML_PLAINTEXT_ID,
        HTML_PRE_ID,
        HTML_Q_ID,
        HTML_S_ID,
        HTML_SAMP_ID,
        HTML_SCRIPT_ID,
        HTML_SELECT_ID,
        HTML_SMALL_ID,
        HTML_SOURCE_ID,
        HTML_SPAN_ID,
        HTML_STRIKE_ID,
        HTML_STRONG_ID,
        HTML_STYLE_ID,
        HTML_SUB_ID,
        HTML_SUP_ID,
        HTML_TABLE_ID,
        HTML_TBODY_ID,
        HTML_TD_ID,
        HTML_TEXT_ID,
        HTML_TEXTAREA_ID,
        HTML_TFOOT_ID,
        HTML_TH_ID,
        HTML_THEAD_ID,
        HTML_TITLE_ID,
        HTML_TR_ID,
        HTML_TT_ID,
        HTML_U_ID,
        HTML_UL_ID,
        HTML_VAR_ID,
        HTML_VIDEO_ID,
        HTML_WBR_ID,
        HTML_XMP_ID
    }
    public static final String ELEMENT_HTML_A_ID_STR = "HTML_A_ID";
    public static final String ELEMENT_HTML_ABBR_ID_STR = "HTML_ABBR_ID";
    public static final String ELEMENT_HTML_ACRONYM_ID_STR = "HTML_ACRONYM_ID";
    public static final String ELEMENT_HTML_ADDRESS_ID_STR = "HTML_ADDRESS_ID";
    public static final String ELEMENT_HTML_APPLET_ID_STR = "HTML_APPLET_ID";
    public static final String ELEMENT_HTML_AREA_ID_STR = "HTML_AREA_ID";
    public static final String ELEMENT_HTML_AUDIO_ID_STR = "HTML_AUDIO_ID";
    public static final String ELEMENT_HTML_B_ID_STR = "HTML_B_ID";
    public static final String ELEMENT_HTML_BASE_ID_STR = "HTML_BASE_ID";
    public static final String ELEMENT_HTML_BASEFONT_ID_STR = "HTML_BASEFONT_ID";
    public static final String ELEMENT_HTML_BDO_ID_STR = "HTML_BDO_ID";
    public static final String ELEMENT_HTML_BIG_ID_STR = "HTML_BIG_ID";
    public static final String ELEMENT_HTML_BLOCKQUOTE_ID_STR = "HTML_BLOCKQUOTE_ID";
    public static final String ELEMENT_HTML_BODY_ID_STR = "HTML_BODY_ID";
    public static final String ELEMENT_HTML_BR_ID_STR = "HTML_BR_ID";
    public static final String ELEMENT_HTML_BUTTON_ID_STR = "HTML_BUTTON_ID";
    public static final String ELEMENT_HTML_CANVAS_ID_STR = "HTML_CANVAS_ID";
    public static final String ELEMENT_HTML_CAPTION_ID_STR = "HTML_CAPTION_ID";
    public static final String ELEMENT_HTML_CENTER_ID_STR = "HTML_CENTER_ID";
    public static final String ELEMENT_HTML_CITE_ID_STR = "HTML_CITE_ID";
    public static final String ELEMENT_HTML_CODE_ID_STR = "HTML_CODE_ID";
    public static final String ELEMENT_HTML_COL_ID_STR = "HTML_COL_ID";
    public static final String ELEMENT_HTML_COLGROUP_ID_STR = "HTML_COLGROUP_ID";
    public static final String ELEMENT_HTML_COMMENT_ID_STR = "HTML_COMMENT_ID";
    public static final String ELEMENT_HTML_DD_ID_STR = "HTML_DD_ID";
    public static final String ELEMENT_HTML_DEL_ID_STR = "HTML_DEL_ID";
    public static final String ELEMENT_HTML_DFN_ID_STR = "HTML_DFN_ID";
    public static final String ELEMENT_HTML_DIR_ID_STR = "HTML_DIR_ID";
    public static final String ELEMENT_HTML_DIV_ID_STR = "HTML_DIV_ID";
    public static final String ELEMENT_HTML_DL_ID_STR = "HTML_DL_ID";
    public static final String ELEMENT_HTML_DT_ID_STR = "HTML_DT_ID";
    public static final String ELEMENT_HTML_EM_ID_STR = "HTML_EM_ID";
    public static final String ELEMENT_HTML_EMBED_ID_STR = "HTML_EMBED_ID";
    public static final String ELEMENT_HTML_FIELDSET_ID_STR = "HTML_FIELDSET_ID";
    public static final String ELEMENT_HTML_FONT_ID_STR = "HTML_FONT_ID";
    public static final String ELEMENT_HTML_FORM_ID_STR = "HTML_FORM_ID";
    public static final String ELEMENT_HTML_FRAME_ID_STR = "HTML_FRAME_ID";
    public static final String ELEMENT_HTML_FRAMESET_ID_STR = "HTML_FRAMESET_ID";
    public static final String ELEMENT_HTML_H1_ID_STR = "HTML_H1_ID";
    public static final String ELEMENT_HTML_H2_ID_STR = "HTML_H2_ID";
    public static final String ELEMENT_HTML_H3_ID_STR = "HTML_H3_ID";
    public static final String ELEMENT_HTML_H4_ID_STR = "HTML_H4_ID";
    public static final String ELEMENT_HTML_H5_ID_STR = "HTML_H5_ID";
    public static final String ELEMENT_HTML_H6_ID_STR = "HTML_H6_ID";
    public static final String ELEMENT_HTML_HEAD_ID_STR = "HTML_HEAD_ID";
    public static final String ELEMENT_HTML_HR_ID_STR = "HTML_HR_ID";
    public static final String ELEMENT_HTML_HTML_ID_STR = "HTML_HTML_ID";
    public static final String ELEMENT_HTML_I_ID_STR = "HTML_I_ID";
    public static final String ELEMENT_HTML_IFRAME_ID_STR = "HTML_IFRAME_ID";
    public static final String ELEMENT_HTML_ILAYER_ID_STR = "HTML_ILAYER_ID";
    public static final String ELEMENT_HTML_IMAGE_ID_STR = "HTML_IMAGE_ID";
    public static final String ELEMENT_HTML_IMG_ID_STR = "HTML_IMG_ID";
    public static final String ELEMENT_HTML_INPUT_ID_STR = "HTML_INPUT_ID";
    public static final String ELEMENT_HTML_INS_ID_STR = "HTML_INS_ID";
    public static final String ELEMENT_HTML_ISINDEX_ID_STR = "HTML_ISINDEX_ID";
    public static final String ELEMENT_HTML_KBD_ID_STR = "HTML_KBD_ID";
    public static final String ELEMENT_HTML_KEYGEN_ID_STR = "HTML_KEYGEN_ID";
    public static final String ELEMENT_HTML_LABEL_ID_STR = "HTML_LABEL_ID";
    public static final String ELEMENT_HTML_LAYER_ID_STR = "HTML_LAYER_ID";
    public static final String ELEMENT_HTML_LEGEND_ID_STR = "HTML_LEGEND_ID";
    public static final String ELEMENT_HTML_LI_ID_STR = "HTML_LI_ID";
    public static final String ELEMENT_HTML_LINK_ID_STR = "HTML_LINK_ID";
    public static final String ELEMENT_HTML_LISTING_ID_STR = "HTML_LISTING_ID";
    public static final String ELEMENT_HTML_MAP_ID_STR = "HTML_MAP_ID";
    public static final String ELEMENT_HTML_MARQUEE_ID_STR = "HTML_MARQUEE_ID";
    public static final String ELEMENT_HTML_MENU_ID_STR = "HTML_MENU_ID";
    public static final String ELEMENT_HTML_META_ID_STR = "HTML_META_ID";
    public static final String ELEMENT_HTML_NOBR_ID_STR = "HTML_NOBR_ID";
    public static final String ELEMENT_HTML_NOEMBED_ID_STR = "HTML_NOEMBED_ID";
    public static final String ELEMENT_HTML_NOFRAMES_ID_STR = "HTML_NOFRAMES_ID";
    public static final String ELEMENT_HTML_NOLAYER_ID_STR = "HTML_NOLAYER_ID";
    public static final String ELEMENT_HTML_NOSCRIPT_ID_STR = "HTML_NOSCRIPT_ID";
    public static final String ELEMENT_HTML_OBJECT_ID_STR = "HTML_OBJECT_ID";
    public static final String ELEMENT_HTML_OL_ID_STR = "HTML_OL_ID";
    public static final String ELEMENT_HTML_OPTGROUP_ID_STR = "HTML_OPTGROUP_ID";
    public static final String ELEMENT_HTML_OPTION_ID_STR = "HTML_OPTION_ID";
    public static final String ELEMENT_HTML_P_ID_STR = "HTML_P_ID";
    public static final String ELEMENT_HTML_PARAM_ID_STR = "HTML_PARAM_ID";
    public static final String ELEMENT_HTML_PLAINTEXT_ID_STR = "HTML_PLAINTEXT_ID";
    public static final String ELEMENT_HTML_PRE_ID_STR = "HTML_PRE_ID";
    public static final String ELEMENT_HTML_Q_ID_STR = "HTML_Q_ID";
    public static final String ELEMENT_HTML_S_ID_STR = "HTML_S_ID";
    public static final String ELEMENT_HTML_SAMP_ID_STR = "HTML_SAMP_ID";
    public static final String ELEMENT_HTML_SCRIPT_ID_STR = "HTML_SCRIPT_ID";
    public static final String ELEMENT_HTML_SELECT_ID_STR = "HTML_SELECT_ID";
    public static final String ELEMENT_HTML_SMALL_ID_STR = "HTML_SMALL_ID";
    public static final String ELEMENT_HTML_SOURCE_ID_STR = "HTML_SOURCE_ID";
    public static final String ELEMENT_HTML_SPAN_ID_STR = "HTML_SPAN_ID";
    public static final String ELEMENT_HTML_STRIKE_ID_STR = "HTML_STRIKE_ID";
    public static final String ELEMENT_HTML_STRONG_ID_STR = "HTML_STRONG_ID";
    public static final String ELEMENT_HTML_STYLE_ID_STR = "HTML_STYLE_ID";
    public static final String ELEMENT_HTML_SUB_ID_STR = "HTML_SUB_ID";
    public static final String ELEMENT_HTML_SUP_ID_STR = "HTML_SUP_ID";
    public static final String ELEMENT_HTML_TABLE_ID_STR = "HTML_TABLE_ID";
    public static final String ELEMENT_HTML_TBODY_ID_STR = "HTML_TBODY_ID";
    public static final String ELEMENT_HTML_TD_ID_STR = "HTML_TD_ID";
    public static final String ELEMENT_HTML_TEXT_ID_STR = "HTML_TEXT_ID";
    public static final String ELEMENT_HTML_TEXTAREA_ID_STR = "HTML_TEXTAREA_ID";
    public static final String ELEMENT_HTML_TFOOT_ID_STR = "HTML_TFOOT_ID";
    public static final String ELEMENT_HTML_TH_ID_STR = "HTML_TH_ID";
    public static final String ELEMENT_HTML_THEAD_ID_STR = "HTML_THEAD_ID";
    public static final String ELEMENT_HTML_TITLE_ID_STR = "HTML_TITLE_ID";
    public static final String ELEMENT_HTML_TR_ID_STR = "HTML_TR_ID";
    public static final String ELEMENT_HTML_TT_ID_STR = "HTML_TT_ID";
    public static final String ELEMENT_HTML_U_ID_STR = "HTML_U_ID";
    public static final String ELEMENT_HTML_UL_ID_STR = "HTML_UL_ID";
    public static final String ELEMENT_HTML_VAR_ID_STR = "HTML_VAR_ID";
    public static final String ELEMENT_HTML_VIDEO_ID_STR = "HTML_VIDEO_ID";
    public static final String ELEMENT_HTML_WBR_ID_STR = "HTML_WBR_ID";
    public static final String ELEMENT_HTML_XMP_ID_STR = "HTML_XMP_ID";

    enum ATTRIB {
        HTML_ABBR,
        HTML_ACCEPT,
        HTML_ACCEPT_CHARSET,
        HTML_ACCESSKEY,
        HTML_ACTION,
        HTML_ALIGN,
        HTML_ALINK,
        HTML_ALT,
        HTML_ARCHIVE,
        HTML_AUTOCOMPLETE,
        HTML_AUTOPLAY,
        HTML_AXIS,
        HTML_BACKGROUND,
        HTML_BEHAVIOR,
        HTML_BGCOLOR,
        HTML_BGPROPERTIES,
        HTML_BORDER,
        HTML_BORDERCOLOR,
        HTML_CELLPADDING,
        HTML_CELLSPACING,
        HTML_CHALLENGE,
        HTML_CHAR,
        HTML_CHAROFF,
        HTML_CHARSET,
        HTML_CHECKED,
        HTML_CITE,
        HTML_CLASS,
        HTML_CLASSID,
        HTML_CLEAR,
        HTML_CODE,
        HTML_CODEBASE,
        HTML_CODETYPE,
        HTML_COLOR,
        HTML_COLS,
        HTML_COLSPAN,
        HTML_COMPACT,
        HTML_CONTENT,
        HTML_CONTENTEDITABLE,
        HTML_CONTROLS,
        HTML_COORDS,
        HTML_DATA,
        HTML_DATETIME,
        HTML_DECLARE,
        HTML_DEFER,
        HTML_DIR,
        HTML_DIRECTION,
        HTML_DISABLED,
        HTML_ENCTYPE,
        HTML_FACE,
        HTML_FOR,
        HTML_FRAME,
        HTML_FRAMEBORDER,
        HTML_HEADERS,
        HTML_HEIGHT,
        HTML_HIDDEN,
        HTML_HREF,
        HTML_HREFLANG,
        HTML_HSPACE,
        HTML_HTML,
        HTML_HTTP_EQUIV,
        HTML_ID,
        HTML_ISMAP,
        HTML_LABEL,
        HTML_LANG,
        HTML_LANGUAGE,
        HTML_LEFT,
        HTML_LEFTMARGIN,
        HTML_LINK,
        HTML_LONGDESC,
        HTML_LOOP,
        HTML_MARGINHEIGHT,
        HTML_MARGINWIDTH,
        HTML_MAXLENGTH,
        HTML_MEDIA,
        HTML_METHOD,
        HTML_MULTIPLE,
        HTML_NAME,
        HTML_NOHREF,
        HTML_NORESIZE,
        HTML_NOSAVE,
        HTML_NOSHADE,
        HTML_NOWRAP,
        HTML_OBJECT,
        HTML_ONABORT,
        HTML_ONBLUR,
        HTML_ONCHANGE,
        HTML_ONCLICK,
        HTML_ONDBLCLICK,
        HTML_ONERROR,
        HTML_ONFOCUS,
        HTML_ONHASHCHANGE,
        HTML_ONKEYDOWN,
        HTML_ONKEYPRESS,
        HTML_ONKEYUP,
        HTML_ONLOAD,
        HTML_ONMESSAGE,
        HTML_ONMOUSEDOWN,
        HTML_ONMOUSEMOVE,
        HTML_ONMOUSEOUT,
        HTML_ONMOUSEOVER,
        HTML_ONMOUSEUP,
        HTML_ONRESET,
        HTML_ONRESIZE,
        HTML_ONSCROLL,
        HTML_ONSELECT,
        HTML_ONSUBMIT,
        HTML_ONUNLOAD,
        HTML_OVERSRC,
        HTML_PAGEX,
        HTML_PAGEY,
        HTML_PLACEHOLDER,
        HTML_PLAIN,
        HTML_PLUGINPAGE,
        HTML_PLUGINSPAGE,
        HTML_PLUGINURL,
        HTML_POSTER,
        HTML_PROFILE,
        HTML_PROMPT,
        HTML_READONLY,
        HTML_REL,
        HTML_REV,
        HTML_ROWS,
        HTML_ROWSPAN,
        HTML_RULES,
        HTML_SCHEME,
        HTML_SCOPE,
        HTML_SCROLLAMOUNT,
        HTML_SCROLLDELAY,
        HTML_SCROLLING,
        HTML_SELECTED,
        HTML_SHAPE,
        HTML_SIZE,
        HTML_SPAN,
        HTML_SRC,
        HTML_STANDBY,
        HTML_START,
        HTML_STYLE,
        HTML_SUMMARY,
        HTML_TABINDEX,
        HTML_TARGET,
        HTML_TEXT,
        HTML_TITLE,
        HTML_TOP,
        HTML_TOPMARGIN,
        HTML_TRUESPEED,
        HTML_TYPE,
        HTML_UNKNOWN,
        HTML_USEMAP,
        HTML_VALIGN,
        HTML_VALUE,
        HTML_VALUETYPE,
        HTML_VERSION,
        HTML_VISIBILITY,
        HTML_VLINK,
        HTML_VSPACE,
        HTML_WIDTH,
        HTML_WRAP,
        HTML_XMLNS,
        HTML_Z_INDEX
    }
    public static final String ATTRIB_HTML_ABBR_STR = "HTML_ABBR";
    public static final String ATTRIB_HTML_ACCEPT_STR = "HTML_ACCEPT";
    public static final String ATTRIB_HTML_ACCEPT_CHARSET_STR = "HTML_ACCEPT_CHARSET";
    public static final String ATTRIB_HTML_ACCESSKEY_STR = "HTML_ACCESSKEY";
    public static final String ATTRIB_HTML_ACTION_STR = "HTML_ACTION";
    public static final String ATTRIB_HTML_ALIGN_STR = "HTML_ALIGN";
    public static final String ATTRIB_HTML_ALINK_STR = "HTML_ALINK";
    public static final String ATTRIB_HTML_ALT_STR = "HTML_ALT";
    public static final String ATTRIB_HTML_ARCHIVE_STR = "HTML_ARCHIVE";
    public static final String ATTRIB_HTML_AUTOCOMPLETE_STR = "HTML_AUTOCOMPLETE";
    public static final String ATTRIB_HTML_AUTOPLAY_STR = "HTML_AUTOPLAY";
    public static final String ATTRIB_HTML_AXIS_STR = "HTML_AXIS";
    public static final String ATTRIB_HTML_BACKGROUND_STR = "HTML_BACKGROUND";
    public static final String ATTRIB_HTML_BEHAVIOR_STR = "HTML_BEHAVIOR";
    public static final String ATTRIB_HTML_BGCOLOR_STR = "HTML_BGCOLOR";
    public static final String ATTRIB_HTML_BGPROPERTIES_STR = "HTML_BGPROPERTIES";
    public static final String ATTRIB_HTML_BORDER_STR = "HTML_BORDER";
    public static final String ATTRIB_HTML_BORDERCOLOR_STR = "HTML_BORDERCOLOR";
    public static final String ATTRIB_HTML_CELLPADDING_STR = "HTML_CELLPADDING";
    public static final String ATTRIB_HTML_CELLSPACING_STR = "HTML_CELLSPACING";
    public static final String ATTRIB_HTML_CHALLENGE_STR = "HTML_CHALLENGE";
    public static final String ATTRIB_HTML_CHAR_STR = "HTML_CHAR";
    public static final String ATTRIB_HTML_CHAROFF_STR = "HTML_CHAROFF";
    public static final String ATTRIB_HTML_CHARSET_STR = "HTML_CHARSET";
    public static final String ATTRIB_HTML_CHECKED_STR = "HTML_CHECKED";
    public static final String ATTRIB_HTML_CITE_STR = "HTML_CITE";
    public static final String ATTRIB_HTML_CLASS_STR = "HTML_CLASS";
    public static final String ATTRIB_HTML_CLASSID_STR = "HTML_CLASSID";
    public static final String ATTRIB_HTML_CLEAR_STR = "HTML_CLEAR";
    public static final String ATTRIB_HTML_CODE_STR = "HTML_CODE";
    public static final String ATTRIB_HTML_CODEBASE_STR = "HTML_CODEBASE";
    public static final String ATTRIB_HTML_CODETYPE_STR = "HTML_CODETYPE";
    public static final String ATTRIB_HTML_COLOR_STR = "HTML_COLOR";
    public static final String ATTRIB_HTML_COLS_STR = "HTML_COLS";
    public static final String ATTRIB_HTML_COLSPAN_STR = "HTML_COLSPAN";
    public static final String ATTRIB_HTML_COMPACT_STR = "HTML_COMPACT";
    public static final String ATTRIB_HTML_CONTENT_STR = "HTML_CONTENT";
    public static final String ATTRIB_HTML_CONTENTEDITABLE_STR = "HTML_CONTENTEDITABLE";
    public static final String ATTRIB_HTML_CONTROLS_STR = "HTML_CONTROLS";
    public static final String ATTRIB_HTML_COORDS_STR = "HTML_COORDS";
    public static final String ATTRIB_HTML_DATA_STR = "HTML_DATA";
    public static final String ATTRIB_HTML_DATETIME_STR = "HTML_DATETIME";
    public static final String ATTRIB_HTML_DECLARE_STR = "HTML_DECLARE";
    public static final String ATTRIB_HTML_DEFER_STR = "HTML_DEFER";
    public static final String ATTRIB_HTML_DIR_STR = "HTML_DIR";
    public static final String ATTRIB_HTML_DIRECTION_STR = "HTML_DIRECTION";
    public static final String ATTRIB_HTML_DISABLED_STR = "HTML_DISABLED";
    public static final String ATTRIB_HTML_ENCTYPE_STR = "HTML_ENCTYPE";
    public static final String ATTRIB_HTML_FACE_STR = "HTML_FACE";
    public static final String ATTRIB_HTML_FOR_STR = "HTML_FOR";
    public static final String ATTRIB_HTML_FRAME_STR = "HTML_FRAME";
    public static final String ATTRIB_HTML_FRAMEBORDER_STR = "HTML_FRAMEBORDER";
    public static final String ATTRIB_HTML_HEADERS_STR = "HTML_HEADERS";
    public static final String ATTRIB_HTML_HEIGHT_STR = "HTML_HEIGHT";
    public static final String ATTRIB_HTML_HIDDEN_STR = "HTML_HIDDEN";
    public static final String ATTRIB_HTML_HREF_STR = "HTML_HREF";
    public static final String ATTRIB_HTML_HREFLANG_STR = "HTML_HREFLANG";
    public static final String ATTRIB_HTML_HSPACE_STR = "HTML_HSPACE";
    public static final String ATTRIB_HTML_HTML_STR = "HTML_HTML";
    public static final String ATTRIB_HTML_HTTP_EQUIV_STR = "HTML_HTTP_EQUIV";
    public static final String ATTRIB_HTML_ID_STR = "HTML_ID";
    public static final String ATTRIB_HTML_ISMAP_STR = "HTML_ISMAP";
    public static final String ATTRIB_HTML_LABEL_STR = "HTML_LABEL";
    public static final String ATTRIB_HTML_LANG_STR = "HTML_LANG";
    public static final String ATTRIB_HTML_LANGUAGE_STR = "HTML_LANGUAGE";
    public static final String ATTRIB_HTML_LEFT_STR = "HTML_LEFT";
    public static final String ATTRIB_HTML_LEFTMARGIN_STR = "HTML_LEFTMARGIN";
    public static final String ATTRIB_HTML_LINK_STR = "HTML_LINK";
    public static final String ATTRIB_HTML_LONGDESC_STR = "HTML_LONGDESC";
    public static final String ATTRIB_HTML_LOOP_STR = "HTML_LOOP";
    public static final String ATTRIB_HTML_MARGINHEIGHT_STR = "HTML_MARGINHEIGHT";
    public static final String ATTRIB_HTML_MARGINWIDTH_STR = "HTML_MARGINWIDTH";
    public static final String ATTRIB_HTML_MAXLENGTH_STR = "HTML_MAXLENGTH";
    public static final String ATTRIB_HTML_MEDIA_STR = "HTML_MEDIA";
    public static final String ATTRIB_HTML_METHOD_STR = "HTML_METHOD";
    public static final String ATTRIB_HTML_MULTIPLE_STR = "HTML_MULTIPLE";
    public static final String ATTRIB_HTML_NAME_STR = "HTML_NAME";
    public static final String ATTRIB_HTML_NOHREF_STR = "HTML_NOHREF";
    public static final String ATTRIB_HTML_NORESIZE_STR = "HTML_NORESIZE";
    public static final String ATTRIB_HTML_NOSAVE_STR = "HTML_NOSAVE";
    public static final String ATTRIB_HTML_NOSHADE_STR = "HTML_NOSHADE";
    public static final String ATTRIB_HTML_NOWRAP_STR = "HTML_NOWRAP";
    public static final String ATTRIB_HTML_OBJECT_STR = "HTML_OBJECT";
    public static final String ATTRIB_HTML_ONABORT_STR = "HTML_ONABORT";
    public static final String ATTRIB_HTML_ONBLUR_STR = "HTML_ONBLUR";
    public static final String ATTRIB_HTML_ONCHANGE_STR = "HTML_ONCHANGE";
    public static final String ATTRIB_HTML_ONCLICK_STR = "HTML_ONCLICK";
    public static final String ATTRIB_HTML_ONDBLCLICK_STR = "HTML_ONDBLCLICK";
    public static final String ATTRIB_HTML_ONERROR_STR = "HTML_ONERROR";
    public static final String ATTRIB_HTML_ONFOCUS_STR = "HTML_ONFOCUS";
    public static final String ATTRIB_HTML_ONHASHCHANGE_STR = "HTML_ONHASHCHANGE";
    public static final String ATTRIB_HTML_ONKEYDOWN_STR = "HTML_ONKEYDOWN";
    public static final String ATTRIB_HTML_ONKEYPRESS_STR = "HTML_ONKEYPRESS";
    public static final String ATTRIB_HTML_ONKEYUP_STR = "HTML_ONKEYUP";
    public static final String ATTRIB_HTML_ONLOAD_STR = "HTML_ONLOAD";
    public static final String ATTRIB_HTML_ONMESSAGE_STR = "HTML_ONMESSAGE";
    public static final String ATTRIB_HTML_ONMOUSEDOWN_STR = "HTML_ONMOUSEDOWN";
    public static final String ATTRIB_HTML_ONMOUSEMOVE_STR = "HTML_ONMOUSEMOVE";
    public static final String ATTRIB_HTML_ONMOUSEOUT_STR = "HTML_ONMOUSEOUT";
    public static final String ATTRIB_HTML_ONMOUSEOVER_STR = "HTML_ONMOUSEOVER";
    public static final String ATTRIB_HTML_ONMOUSEUP_STR = "HTML_ONMOUSEUP";
    public static final String ATTRIB_HTML_ONRESET_STR = "HTML_ONRESET";
    public static final String ATTRIB_HTML_ONRESIZE_STR = "HTML_ONRESIZE";
    public static final String ATTRIB_HTML_ONSCROLL_STR = "HTML_ONSCROLL";
    public static final String ATTRIB_HTML_ONSELECT_STR = "HTML_ONSELECT";
    public static final String ATTRIB_HTML_ONSUBMIT_STR = "HTML_ONSUBMIT";
    public static final String ATTRIB_HTML_ONUNLOAD_STR = "HTML_ONUNLOAD";
    public static final String ATTRIB_HTML_OVERSRC_STR = "HTML_OVERSRC";
    public static final String ATTRIB_HTML_PAGEX_STR = "HTML_PAGEX";
    public static final String ATTRIB_HTML_PAGEY_STR = "HTML_PAGEY";
    public static final String ATTRIB_HTML_PLACEHOLDER_STR = "HTML_PLACEHOLDER";
    public static final String ATTRIB_HTML_PLAIN_STR = "HTML_PLAIN";
    public static final String ATTRIB_HTML_PLUGINPAGE_STR = "HTML_PLUGINPAGE";
    public static final String ATTRIB_HTML_PLUGINSPAGE_STR = "HTML_PLUGINSPAGE";
    public static final String ATTRIB_HTML_PLUGINURL_STR = "HTML_PLUGINURL";
    public static final String ATTRIB_HTML_POSTER_STR = "HTML_POSTER";
    public static final String ATTRIB_HTML_PROFILE_STR = "HTML_PROFILE";
    public static final String ATTRIB_HTML_PROMPT_STR = "HTML_PROMPT";
    public static final String ATTRIB_HTML_READONLY_STR = "HTML_READONLY";
    public static final String ATTRIB_HTML_REL_STR = "HTML_REL";
    public static final String ATTRIB_HTML_REV_STR = "HTML_REV";
    public static final String ATTRIB_HTML_ROWS_STR = "HTML_ROWS";
    public static final String ATTRIB_HTML_ROWSPAN_STR = "HTML_ROWSPAN";
    public static final String ATTRIB_HTML_RULES_STR = "HTML_RULES";
    public static final String ATTRIB_HTML_SCHEME_STR = "HTML_SCHEME";
    public static final String ATTRIB_HTML_SCOPE_STR = "HTML_SCOPE";
    public static final String ATTRIB_HTML_SCROLLAMOUNT_STR = "HTML_SCROLLAMOUNT";
    public static final String ATTRIB_HTML_SCROLLDELAY_STR = "HTML_SCROLLDELAY";
    public static final String ATTRIB_HTML_SCROLLING_STR = "HTML_SCROLLING";
    public static final String ATTRIB_HTML_SELECTED_STR = "HTML_SELECTED";
    public static final String ATTRIB_HTML_SHAPE_STR = "HTML_SHAPE";
    public static final String ATTRIB_HTML_SIZE_STR = "HTML_SIZE";
    public static final String ATTRIB_HTML_SPAN_STR = "HTML_SPAN";
    public static final String ATTRIB_HTML_SRC_STR = "HTML_SRC";
    public static final String ATTRIB_HTML_STANDBY_STR = "HTML_STANDBY";
    public static final String ATTRIB_HTML_START_STR = "HTML_START";
    public static final String ATTRIB_HTML_STYLE_STR = "HTML_STYLE";
    public static final String ATTRIB_HTML_SUMMARY_STR = "HTML_SUMMARY";
    public static final String ATTRIB_HTML_TABINDEX_STR = "HTML_TABINDEX";
    public static final String ATTRIB_HTML_TARGET_STR = "HTML_TARGET";
    public static final String ATTRIB_HTML_TEXT_STR = "HTML_TEXT";
    public static final String ATTRIB_HTML_TITLE_STR = "HTML_TITLE";
    public static final String ATTRIB_HTML_TOP_STR = "HTML_TOP";
    public static final String ATTRIB_HTML_TOPMARGIN_STR = "HTML_TOPMARGIN";
    public static final String ATTRIB_HTML_TRUESPEED_STR = "HTML_TRUESPEED";
    public static final String ATTRIB_HTML_TYPE_STR = "HTML_TYPE";
    public static final String ATTRIB_HTML_UNKNOWN_STR = "HTML_UNKNOWN";
    public static final String ATTRIB_HTML_USEMAP_STR = "HTML_USEMAP";
    public static final String ATTRIB_HTML_VALIGN_STR = "HTML_VALIGN";
    public static final String ATTRIB_HTML_VALUE_STR = "HTML_VALUE";
    public static final String ATTRIB_HTML_VALUETYPE_STR = "HTML_VALUETYPE";
    public static final String ATTRIB_HTML_VERSION_STR = "HTML_VERSION";
    public static final String ATTRIB_HTML_VISIBILITY_STR = "HTML_VISIBILITY";
    public static final String ATTRIB_HTML_VLINK_STR = "HTML_VLINK";
    public static final String ATTRIB_HTML_VSPACE_STR = "HTML_VSPACE";
    public static final String ATTRIB_HTML_WIDTH_STR = "HTML_WIDTH";
    public static final String ATTRIB_HTML_WRAP_STR = "HTML_WRAP";
    public static final String ATTRIB_HTML_XMLNS_STR = "HTML_XMLNS";
    public static final String ATTRIB_HTML_Z_INDEX_STR = "HTML_Z_INDEX";
}